### ISSUE TITLE
Add translations for Nuvola user interface

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#10]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Make it possible to translate texts in Nuvola Player interface with community-provided translations.

## Details from reporter

Nuvola Player 3 currently doesn't contain translations.
- [ ] Mark translatable strings in Vala files
- [ ] Create translation template from the marked strings
- [x] Find on-line service for translations.
  - ~~Launchpad?~~
  - ~~Weblate?~~
  - Zanata! - project typr "po dir"
- [ ] Integrate translations to Nuvola Player.
- [ ] Implement translations in web app scripts.
- [ITS Tool Documentation](http://itstool.org/documentation/) - for HTML/XML files
- https://wordpress.stackexchange.com/questions/27144/localizing-text-from-xml-files
- nuvola-runtime/app.pot
- nuvola-runtime/welcome-xml.pot
- nuvola-app-deezer/integrate-js.pot ← integrate.js
- nuvola-app-deezer/changelog-md.pot ← changelog.xml ← changelog.md

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.
