### ISSUE TITLE
Enable Headerbar in Pantheon/Freya

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#108]
Feedback from a patron running Nuvola Player in ElementaryOS Freya:

> The toolbar is annoying. I would really like having a combined title+toolbar like the other GNOME apps do use nowadays.

**Comment by theblacklion** [comment]
Actually Freya is using header bars wherever possible, too. So it should work fine.

**Comment by fenryxo** [comment]
@theblacklion, could you post output of a command  `xprop -id $(xprop -root _NET_SUPPORTING_WM_CHECK | cut -d\# -f2)` to an issue tiliado/diorite#2?

**Comment by fenryxo** [comment]
With tiliado/diorite#2 fixed, it is now easy to add support for Freya, but I need information I requested in my previous comment. I might install Freya in August/September to get this information on my own though.

**Comment by tcitworld** [comment]
@fenryxo This is what I've got : 

```
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x100000b
_MUTTER_VERSION(UTF8_STRING) = "3.12.2"
_GNOME_WM_KEYBINDINGS(UTF8_STRING) = "Mutter"
_NET_WM_NAME(UTF8_STRING) = "Mutter(Gala)"
```

**Comment by theblacklion** [comment]
@fenryxo Same here:
```
$ xprop -id $(xprop -root _NET_SUPPORTING_WM_CHECK | cut -d\# -f2)
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x120000b
_MUTTER_VERSION(UTF8_STRING) = "3.12.2"
_GNOME_WM_KEYBINDINGS(UTF8_STRING) = "Mutter"
_NET_WM_NAME(UTF8_STRING) = "Mutter(Gala)"
```

**Comment by fenryxo** [comment]
Thanks, @tcitworld  and @theblacklion.

**Comment by fenryxo** [comment]
Fixed in git master & 0.1.x branches of Diorite library. Will be included in the next update of package repository. Thanks for your assistence :+1:

**Comment by theblacklion** [comment]
Nice :)

**Comment by fenryxo** [comment]
@theblacklion, could you post here a screenshot of Nuvola Player with client side decorations? I want to be sure it works as expected. Thanks :-)

**Comment by leafymind** [comment]
![bildschirmfoto vom 2015-07-21 08 51 21](https://cloud.githubusercontent.com/assets/2802675/8794644/b181802e-2f85-11e5-8576-c0319a604531.png)

The dark theme could be a bit darker :grinning:

**Comment by fenryxo** [comment]
> The dark theme could be a bit darker

Hello @leafymind. Could you [create a new ticket for it in Diorite bug tracker](https://github.com/tiliado/diorite/issues/new)?

**Comment by theblacklion** [comment]
@fenryxo The bright theme looks nice :)

![bildschirmfoto vom 2015-09-11 13 46 33](https://cloud.githubusercontent.com/assets/687189/9814092/938860b8-588b-11e5-8229-694c9ae5ca86.png)
