### ISSUE TITLE
Add support for downloads

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#11]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Nuvola Player 2 supported file downloads (see screenshot below). It would be great to have this feature in Nuvola Player 3 too.

## Details from the reporter

_Old user interface_
![downloads](https://cloud.githubusercontent.com/assets/853706/4975888/5ee51196-68de-11e4-9db2-73a0a3bbefa4.png)

Tasks:
- [ ] Port downloads backend from Nuvola Player 2
- [ ] Create new GUI (using Gtk.ListBox)

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
