### ISSUE TITLE
Google Play Music fails to stream from radio (All Access),  but uploaded songs do work

### ISSUE THREAD

**Issue by pszi1ard** [tiliado/nuvolaplayer#124]
Issue
-------
Google Play Music fails to stream from radio (All Access), but uploaded songs do work. This bug is not specific to Nuvola Player (see an article [Google Play Music All Access Web App Is Not Working In Firefox, Internet Explorer, Or Safari On Desktops](http://www.androidpolice.com/2015/07/11/google-play-music-all-access-web-app-is-not-working-in-firefox-internet-explorer-or-safari-on-desktops/)) and has to be fixed by Google.

Original Report
--------------------

The last update of the nuvolaplayer3 package (nuvolaplayer3:amd64 3.0.0~201506090713.0d482d6-0+1~trusty -> 3.0.0~201507061356.c86a837-0+3~trusty) seems to have broken the Google Play plugin. I keep getting the following message after it skips a few tracks first:
"Can't reach Google Play
Reload the page and try again."

Of course, I did verified that the same tracks do play in Chrome.

OS: Ubuntu 14.04 x86_64
Desktop: Unity

**Comment by chelog** [comment]
+1 here.

OS: Elemetary (based on Ubuntu 14.04 x86_64)
Desktop: Pantheon

**Comment by hackel** [comment]
For me, it's working fine for regular songs I've uploaded, but if I try to play one of the new radio stations, I get the "Can't reach Google Play" error.  (Works fine in Chrome)
Here's the error:
```
WebEngine.vala:507: Navigation, current window: uri = https://imasdk.googleapis.com/js/core/bridge3.101.3_en.html#goog_407976747, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
CONSOLE ERROR Blocked a frame with origin "https://imasdk.googleapis.com" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
```
nuvolaplayer3-google-play-music 5.3-1~vivid
nuvolaplayer3 3.0.0~201507061356.c86a837-0+3~vivid

**Comment by fenryxo** [comment]
Hi @pszi1ard, @chelog and @hackel. Could you post a complete debugging output from terminal? See [the Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

 @hackel, what do you exactly mean by "one of the new radio stations"?

**Comment by pszi1ard** [comment]
Here's the debug output :
http:// pastebin.com / PNYY91Ff

**Comment by hackel** [comment]
@fenryxo Google recently added (or perhaps they just made them ad-supported?) radio stations like Pandora, found in the action bar under "Browse stations."  The excerpt I posted above was the terminal output when I click on a station to play.

**Comment by fenryxo** [comment]
Thanks, @hackel. Did these new radio stations replace All Access subscription or is it an extra offer?

**Comment by jamgregory** [comment]
@fenryxo - I think it's an extra offer - I can't see anything else that's different with my All Access subscription.

If it helps at all, I'm trying to play music from my playlist, and it appears that the track issues mostly occur on tracks that have an associated YouTube video. The debug log doesn't indicate any issue when playing though (happy to provide if you need it).

**Comment by scaine** [comment]
This doesn't appear to be specific to Nuvola either. I get the same error trying to run Google Play Music in Firefox 39 (Ubuntu 14.04, 64-bit). The service works fine in Chrome.

I've tried switching the service to NOT use HTML5, but it still doesn't work in Firefox, nor Nuvola. I'm having to use Chrome at the moment.

If Google keep messing about with this service, I'm going to have to ditch them!

**Comment by lidel** [comment]
It may be related to this:
http://www.androidpolice.com/2015/07/11/google-play-music-all-access-web-app-is-not-working-in-firefox-internet-explorer-or-safari-on-desktops/

**Comment by fenryxo** [comment]
Thanks for your comments, @jamgregory, @scaine and @lidel.

>  I think it's an extra offer - I can't see anything else that's different with my All Access subscription.

OK, it seems to be like All Access streaming technically, but with ads for users without All Access subscription.

> I've tried switching the service to NOT use HTML5

HTML5 setting actually makes sense only in Chrome as other browsers don't support all technologies required by Google Play Music to play without Flash.

> This doesn't appear to be specific to Nuvola either. I get the same error trying to run Google Play Music in Firefox 39 (Ubuntu 14.04, 64-bit). The service works fine in Chrome.

> It may be related to this:
[Google Play Music All Access Web App Is Not Working In Firefox, Internet Explorer, Or Safari On Desktops](http://www.androidpolice.com/2015/07/11/google-play-music-all-access-web-app-is-not-working-in-firefox-internet-explorer-or-safari-on-desktops/)

Indeed. It looks like a bug in Google Play Music, possibly related to a recent security update of Adobe Flash. The issue also occur in WebKit-based Radiant player (kbhomes/radiant-player-mac#342).

I'm keeping this issue open for a while to prevent duplicates. However, I don't think I can do anything with this bug. It's in Google's hands. Personally, I would consider to look for alternatives, because Google Play Music keeps breaking too often.

**Comment by scaine** [comment]
I've ditched them now - sick of the constant breakages (this is the third time I've had issues with their service). I'll get Spotify on the go nearer my cut-off date for Google Play Music.

**Comment by lidel** [comment]
FYI it seems to be fixed now.

**Comment by jck** [comment]
It's resumed working in firefox, but still broken in nuvola for me.

**Comment by pszi1ard** [comment]
Seems to be working fine for me again.

**Comment by fenryxo** [comment]
Does anyone still have this issue?

**Comment by jck** [comment]
I still have this issue on Arch.

**Comment by fenryxo** [comment]
@jck, do you have up-to-date Adobe Flash plugin?

**Comment by jck** [comment]
Yes, I have version 11.2.202.491

**Comment by sigsergv** [comment]
In my case google play service doesn't work at all. Sometimes it loads some parts but won't play anything. And in most cases just doesn't load anything, empty white or blue screen.

It prints this output, I hope it will help:

```
[Worker:DEBUG    Nuvola] main.vala:232: Page 1 created for (null)
[Worker:DEBUG    Nuvola] jsapi.vala:519: Nuvola.log: 'Fixed webcomponents: https://raw.githubusercontent.com/tiliado/nuvola-app-google-play/16627e12bf115fcaa97f4abc581382c2251f0e76/webcomponents.js'
[Worker:DEBUG    Nuvola] main.vala:141: Window object cleared: https://play.google.com/music/listen, 0xae902e50, 0x9568608, 0xa94ffa64
https://play.google.com/music/listenJS ERROR: Refused to get unsafe header "Location"
JS ERROR: Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
https://ssl.gstatic.com/play/music/fe/aaebde07a1270d4f408220f0088f8e2f/listen_extended_d5d41cbe37133fce94c32acca2b8435c21125ddb__ru.js:3414:235JS ERROR: CustomError: Error in protected function: undefined is not an object (evaluating 'a.toString=b')
https://ssl.gstatic.com/play/music/fe/aaebde07a1270d4f408220f0088f8e2f/listen_extended_d5d41cbe37133fce94c32acca2b8435c21125ddb__ru.js:3414:235JS ERROR: CustomError: Error in protected function: undefined is not an object (evaluating 'a.toString=b')
```

**Comment by fenryxo** [comment]
Hello @sigsergv. Please [create a new bug report](https://github.com/tiliado/nuvolaplayer/issues/new) for your issue.

**Comment by MaikoID** [comment]
Same here ubuntu 14.04 x64. Works on FF though

**Comment by jck** [comment]
If all you only use google play music, this is a decent alternative: https://github.com/twolfson/google-music-electron

It is built on github's electron, and supports HTML5 audio.

**Comment by fenryxo** [comment]
Could anybody try to purge cache (see command bellow) and check whether it makes any better?

`rm -rf ~/.local/share/nuvolaplayer3/apps_data/google_play_music ~/.cache/nuvolaplayer3/apps_data/google_play_music ~/.adobe/Flash_Player ~/.macromedia/Flash_Player`

**Comment by MaikoID** [comment]
I tried to to do that @fenryxo but without success. How google music is the only music streaming service that I currently  use I will give the @jck suggestion a shot. However I will keep an eye in this thread, continue with the good work.

**Comment by jscinoz** [comment]
I was encountering this same issue, on Gentoo. Not sure exactly what fixed it, but I did a pull (my local clone was a few days behind) & rebuilt Nuvola, as well as updated to Flash 11.2.202.508, and all streaming with GPM now works correctly on my machine.

@jck: Is the aforementioned version of Flash available in your distro?

**Comment by fenryxo** [comment]
@jscinoz It's probably the updated Flash that fixed this issue for you. It actually isn't an issue in Nuvola Player at all, but a kind of WebKitGTK + Flash plugin + Google Play Music compatibility issue caused by recent security fixes in Adobe Flash.

**Comment by fenryxo** [comment]
Does anyone still experience this issue with Flash plugin updated to 11.2.202.508?

**Comment by jck** [comment]
I'm still having this issue with Flashplugin 11.2.202.508. I deleted the dirs you mentioned and rebuilt nuvola.

**Comment by fenryxo** [comment]
@jck Could you post debugging output as described in [the Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) after your rebuild Nuvola Player?

@MaikoID, could you also post debugging output?

There might be something in common as you are only users who are still affected by this bug. Moreover, all users that reported similar issue with Radiant player are no longer affected too (kbhomes/radiant-player-mac#342).

**Comment by MaikoID** [comment]
Hey guys, good news, I've tried to reinstall without using the tiliado-repositories applications and it's working now. 

The tiliado-repo is giving a strange error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tiliadoweb/installer.py", line 85, in on_sign_in_clicked
    self.switch_to_repositories()
  File "/usr/lib/python3/dist-packages/tiliadoweb/installer.py", line 139, in switch_to_repositories
    self.repositories_page.set_repositories([repo for repo in self.api.repositories if repo["active"]])
  File "/usr/lib/python3/dist-packages/tiliadoweb/api.py", line 77, in repositories
    return self.make_request("repository/repositories/")
  File "/usr/lib/python3/dist-packages/tiliadoweb/api.py", line 64, in make_request
    response = urlopen(request)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1223, in connect
    super().connect()
  File "/usr/lib/python3.4/http/client.py", line 837, in connect
    self._tunnel()
  File "/usr/lib/python3.4/http/client.py", line 815, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''

So I've used the ppa instead.

**Comment by fenryxo** [comment]
> So I've used the ppa instead.

Which PPA? If you use [Tiliado repository for Nuvola Player](https://tiliado.eu/nuvolaplayer/repository/), it doesn't matter whether you add it manually or with the Tiliado Repository installer. You always get the same Nuvola Player packages.

**Comment by sigsergv** [comment]
Here is my debug log https://gist.github.com/sigsergv/c43933c2eb882247f072

**Comment by MaikoID** [comment]
Yes I know, but the error stopped once I reinstalled the player directly from the ppa: deb https://tiliado.eu/nuvolaplayer/repository/deb/ trusty stable

**Comment by fenryxo** [comment]
I'm closing this issue as I haven't received a debugging output that I requested a month ago (on August 26). If anyone is still affected by this issue and is willing to collaborate, feel free to submit the debug output and reopen this issue.
