### ISSUE TITLE
Add lyrics fetching

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#13]
:heart: One Nuvola Patron is interested in this task.

Nuvola Player 2 has lyrics fetching feature (see screenshot bellow). It would be great to have it in Nuvola Player 3 too.

Five users have voted for this feature in Trello board:
*  Adrian garcia (adriangcia)
* Camilo Sampedro (camilosampedro)
* Geoffrey (geoffrey57)
* Jan Polášek (janpolasek)
* Mark Rich (markrich1)

![lyrics](https://cloud.githubusercontent.com/assets/853706/4977266/f1e0161a-68e5-11e4-8b2c-88eb803776e3.png)

**Comment by fenryxo** [comment]
Work in progress in [branch lyrics](https://github.com/tiliado/nuvolaplayer/tree/lyrics).

**Comment by fenryxo** [comment]
Fixed in both master & 3.0.x branches. Will be available with the next rebuild of packages.

**Comment by fenryxo** [comment]
Follow up:  Add overlay lyrics widget #137

**Comment by seemsindie** [comment]
How do you turn on the sidebar or see the lyrics?

**Comment by fenryxo** [comment]
Hello @seemsindie. See https://tiliado.github.io/nuvolaplayer/documentation/3.0/explore.html#lyrics-fetching

**Comment by seemsindie** [comment]
@fenryxo Thanks
