### ISSUE TITLE
Crash after "Failed to open BO for returned DRI2 buffer"

### ISSUE THREAD

**Issue by rosshadden** [tiliado/nuvolaplayer#131]
In the Google Play app, after a couple minutes of playing music, I receive the following error and subsequent crash:

```
Failed to open BO for returned DRI2 buffer (2876x1472, dri2 back buffer, named 4).
This is likely a bug in the X Server that will lead to a crash soon.
[Runner:WARNING  Nuvola] AppRunnerController.vala:649: Communication failed: Failed to connect to socket '/tmp/libdiorite.nuvolaplayer3.google_play_music.webworker(ross)'. Connection refused
[Runner:WARNING  Nuvola] AppRunnerController.vala:649: Communication failed: Failed to connect to socket '/tmp/libdiorite.nuvolaplayer3.google_play_music.webworker(ross)'. Connection refused
[Runner:WARNING  Nuvola] AppRunnerController.vala:669: Communication failed: Failed to connect to socket '/tmp/libdiorite.nuvolaplayer3.google_play_music.webworker(ross)'. Connection refused
```

I created this issue on the main `nuvolaplayer` project because most of the core functionality is service-agnostic, but it is of course possible that it only crashes is Google Play Music.

> Edit:  This issue was originally about the scrobbling plugin crashing the app, but I just discovered that the crash has nothing to do with scrobbling, as the plugin is now disabled.

**Comment by fenryxo** [comment]
Hello. Thanks for taking the time to report this issue. I'll take a look at it in [August 2015](https://github.com/tiliado/nuvolaplayer.project/issues/5) as [funds for July 2015](https://tiliado.eu/nuvolaplayer/funding/tasks/201507/) have been already almost spent. Thanks for your understanding.

**Comment by fenryxo** [comment]
Hello. I'm sorry, but I cannot do anything with this issue as it seems to be an issue of a graphic driver. I'm closing this ticket for this reason. You can try to [set your driver to use SNA AccelMethod](https://bugs.freedesktop.org/show_bug.cgi?id=84372#c7).

**Comment by rosshadden** [comment]
I can try what you suggested, but I don't think it has anything to do with graphics drivers.

This issue is present both on one computer with NVIDIA drivers, and one with Intel, which has an integrated card.  Also the symptoms in the issue you linked don't seem to apply, as `nuvolaplayer` crashes regardless of which displays are being used for outputs.

**Comment by fenryxo** [comment]
> I don't think it has anything to do with graphics drivers.

Error "Failed to open BO for returned DRI2 buffer" is certainly related to graphics drivers.

**Comment by fenryxo** [comment]
I could help you to push this issue upstream, but you have to provide at least basic information about your system as described in [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines).
