### ISSUE TITLE
Pebble Watch App to control Nuvola Player over Wi-Fi

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#133]
I have borrowed Pebble Watch from a friend of mine. It might be interesting to create a Pebble Watch App to control Nuvola Player over Wi-Fi.

Depends on: #19

**Comment by petRUShka** [comment]
It would be great! I'm waiting for such app!

**Comment by fenryxo** [comment]
**Development has started in my private repository.** The first screenshot is shown below. Due to [insufficient funding of the Nuvola Player project](https://tiliado.eu/nuvolaplayer/funding/), I work on this feature for free. As a consequence, the watch app will not be provided for free initially and the source code will be released when the app pays for its development. Nuvola Patrons will probably receive a discount code (up to 100%).

**Tentative schedule:**

* Alpha version (free): Autumn 2016, compatible with Nuvola Player 3.1.x Rolling Releases
* Beta version (paid): Spring 2017, compatible with Nuvola Player 3.3.x Rolling Releases
* Stable version (paid): December 2017, compatible with Nuvola Player 3.4.x Stable Releases

![nuvolactl](https://cloud.githubusercontent.com/assets/853706/16357881/2bb98966-3b03-11e6-9d1a-c1283451beb3.png)

**Comment by fenryxo** [comment]
[Pebble watchapp has been released](https://tiliado.github.io/nuvolaplayer/documentation/3.1/explore.html#nuvola-controller-pebble-watchapp).

![connecting](https://cloud.githubusercontent.com/assets/853706/19863258/d53922cc-9f93-11e6-970e-164115cf3538.png) ![deezer_paused_alone](https://cloud.githubusercontent.com/assets/853706/19863268/e0782430-9f93-11e6-8faa-349e8082efc7.png) ![google_play_music_playing_three_dots](https://cloud.githubusercontent.com/assets/853706/19863277/e6df7be8-9f93-11e6-8af3-cf2b228e5e06.png) ![app_selector_prev_track](https://cloud.githubusercontent.com/assets/853706/19863282/edef4936-9f93-11e6-883d-130d620e48b5.png)
