### ISSUE TITLE
Add overlay lyrics widget

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#137]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add option to show lyrics in a semi-transparent overlay widget over the webpage.

## Details from reporter

It could be combined with synchronized lyrics #453.

**Comment by fenryxo** [comment]
* [The MusixMatch Desktop Lyrics App Is Available for Linux](https://www.omgubuntu.co.uk/2017/08/musixmatch-desktop-app-on-linux?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+d0od+(OMG!+Ubuntu!)) - it provides synchronized lyrics
* [Rock On: Deepin Music is Now Available as a Snap App on Ubuntu](https://www.omgubuntu.co.uk/2017/03/rock-deepin-music-now-available-snap-app) - it also has synchronized lyrics
* https://github.com/linuxdeepin/deepin-music/blob/master/music-player/view/lyricwidget.cpp

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
