### ISSUE TITLE
Warn when PulseAudio flat-volumes feature is enabled

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#138]
PulseAudio flat-volumes feature is broken by design and causes many issues, e.g.:
- tiliado/nuvolaplayer#84
- tiliado/nuvola-app-rdio#2
- tiliado/nuvola-app-spotify#6

Nuvola Player should warn user when this feature is enabled, because they usually actually don't want to have flat volumes.
##

**Comment by fenryxo** [comment]
Related: [Epiphany sets sound volume to 100%](https://bugzilla.gnome.org/show_bug.cgi?id=675217)
