### ISSUE TITLE
Add network proxy settings

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#14]
Nuvola Player uses system network proxy settings out of the box. However, Nuvola Player 2 allowed user to set custom proxy settings (see screenshot bellow). It would be great to have this feature in Nuvola Player 3 too.

![preferences-network](https://cloud.githubusercontent.com/assets/853706/4977448/7f31a5f0-68e7-11e4-97f7-077d3196c9bf.png)

**Comment by bartlibert** [comment]
I was just wondering, is this issue only about adding the settings interface, or is this also for tracking the issue "Nuvola Player 3 does not work at all behind a proxy"?

**Comment by fenryxo** [comment]
Nuvola Player 3 is powered by WebKit2gtk library that should use system
proxy settings, so proxy support should work out of the box. I use Nuvola
Player 3 behind HTTP proxy every day. This ticket is about providing a way
how to use different proxy settings per service.

**Comment by bartlibert** [comment]
Thanks for the info . I was under the impression it did not work, because Nuvola Player 2 was working on my system and 3 wasn't, but I just realized I have custom proxy settings in version 2. When I change my system proxy settings to those custom settings, Nuvola Player 3 does work (but some other things on my system don't). So eagerly awaiting this fix now :)

**Comment by fenryxo** [comment]
I've updated description of the issue to be more precise and added tag patron to increase priority.

**Comment by fenryxo** [comment]
It seems there is no [API to set proxy settings in WebKit2Gtk](https://bugs.webkit.org/show_bug.cgi?id=128674).

**Comment by fenryxo** [comment]
After reading many lines of code of WeKit2Gtk network stack, libsoup proxy handling and glib-networking module, I've found a hack how to disable [the default proxy resolver](https://git.gnome.org/browse/glib-networking/tree/proxy/gnome/gproxyresolvergnome.c)  that uses system proxy settings.

```
Environment.unset_variable("GNOME_DESKTOP_SESSION_ID");
Environment.unset_variable("DESKTOP_SESSION");
```

**Comment by bartlibert** [comment]
Thanks for the quick response and investigation work on this, great job!

**Comment by fenryxo** [comment]
Nuvola Player can now apply proxy settings from configuration file, e.g. `~/.config/nuvolaplayer3/apps_data/rdio/config.json`:
```
{
  "webview" : {
    "proxy" : {
      "type" : "http",
      "host": "proxy.vscht.cz",
      "port" : 3128
    }
  }
}
```
Proxy settings dialog will follow.

**Comment by bartlibert** [comment]
I've tested the json proxy configuration for google play and it works perfectly, great job!

**Comment by fenryxo** [comment]
Hi @bartlibert. I've just uploaded packages with network proxy settings in Nuvola Player Preferences dialog. Could you check it out? Thanks!

**Comment by bartlibert** [comment]
Hi, this all seems to work as expected. Great job! 
Only thing I have not tested is the SOCKS proxy, as I don't have access to one.

**Comment by fenryxo** [comment]
Great :-)
