### ISSUE TITLE
Set default player window width from metadata.json

### ISSUE THREAD

**Issue by cermakjn** [tiliado/nuvolaplayer#141]
Default window with is not enough for 1 (maybe more) music service, eg. youradio.cz.

  - Add optional "width" parameter in metadata.json file, which will be set default player to specify width.

**Comment by fenryxo** [comment]
Thanks for your idea ;-)

* Set window width to `min(screen_width - 100, meta.window_width || default_width)`.
* Set window height to `min(screen_height - 100, meta.window_height || default_height)`.

**Comment by fenryxo** [comment]
Changes landed in git master & 3.0.x branches. Will be available with the next rebuild of packages. More info at 7b508cc. Thanks for your idea.
