### ISSUE TITLE
Add adblock functionality

### ISSUE THREAD

**Issue by petRUShka** [tiliado/nuvolaplayer#146]
Some services full of advertising. And it is quite convenient to add some [adblock functionality](https://en.wikipedia.org/wiki/Ad_blocking) to Nuvolaplayer. May be as plugin.

**Comment by fenryxo** [comment]
Hello. Thanks for your idea. However, I fully respect advertisement as a valid monetization method and I don't want to cause any financial harm to music streaming services. If you don't like ads, you should choose a service that offers an ad-free premium account or a service that doesn't use ads at all.

**Comment by str** [comment]
@petRUShka I had the same idea. I found [Deezer Shortcut] ( https://chrome.google.com/webstore/detail/deezer-shortcut/paccflbfblppaoidibhflahkogodngie?hl=en) to have a great adbock for Deezer.

Reading the source code made it very easy to find how to block Deezer's adds, even the audio ads

```js
    //block ads
    webview.request.onBeforeRequest.addListener(
        function (details) {
            return {
                cancel: true
            };
        }, {
            urls: ["*://*.googleadservices.com/*", "*://*.googlesyndication.com/*", "*://*.smartadserver.com/*"]
        }, ["blocking"]);
``` 

Of course that would not work in Nuvola, but it's a start. I'm going to read more about how to integrate it in nuvola.
