### ISSUE TITLE
Extra notification at the end of a song

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#156]
Feedback from @tcitworld:

> I had noticed gnome notifications displaying at the beginning and at the end of the song.

Notifications are shown when track or playback status changes to update playback actions (e.g. buttons in GNOME lock screen). The problem is probably that playback stops at the end of a song to buffer the next song and this causes extra notification.
##

**Comment by tcitworld** [comment]
Can't be sure this is still happening. Will provide exact feedback in the upcoming weeks.

**Comment by fenryxo** [comment]
No feedback has been provided, closing.
