### ISSUE TITLE
Thumbs-up thumbs-down commands should not toggle

### ISSUE THREAD

**Issue by KruyKaze** [tiliado/nuvolaplayer#157]
When we run these commands remotely, we cannot actually see if the song has already been thumbed up/down.
So can we have these commands not toggle the state and just keep the song thumbed up if it already is for example?
Thank you!

**Comment by fenryxo** [comment]
Hello. Thanks for taking the time to report this issue.

> So can we have these commands not toggle the state and just keep the song thumbed up if it already is for example?

This would be inconsistent with behaviour of  the web interface. Thumbs up/down actions are toggle actions in the web UI, so they mus be toggle actions in all Nuvola Player interfaces.

> When we run these commands remotely, we cannot actually see if the song has already been thumbed up/down.

Supposing you mean command line usage by "run these commands remotely", you can use commands `nuvolaplayer3ctl action-state thumbs-up` and `nuvolaplayer3ctl action-state thumbs-down` to get state of the action. Is this helpful?

**Comment by fenryxo** [comment]
Alternatively, it will be possible to use `nuvolaplayer3ctl action thumbs-up true` to always toggle thumbs up on. Commit tiliado/diorite@d9d654b will be available with the next rebuild of packages. Is this helpful?

**Comment by KruyKaze** [comment]
Yes that would be perfect. Will it work for "thumbs-down true " as well ?

**Comment by fenryxo** [comment]
> Will it work for "thumbs-down true " as well ?

It will work for all toggle actions including thumbs-down.

**Comment by KruyKaze** [comment]
Excellent. I will now be able to use voice commands to thumb up/down
without worrying about undoing previous actions.
This is great thanks

**Comment by KruyKaze** [comment]
I have built diorite-git with your latest modification but nuvolaplayer3ctl
action thumbs-up truestill toggles.

Thanks.

**Comment by fenryxo** [comment]
> I have built diorite-git with your latest modification but nuvolaplayer3ctl action thumbs-up truestill toggles.

Have you also rebuilt Nuvola Player? Could you provide a debugging output from terminal when you type commands `nuvolaplayer3ctl action thumbs-up` and `nuvolaplayer3ctl action thumbs-up true` (two times each) in a new terminal window/tab? See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by KruyKaze** [comment]
No I didn't think I needed to rebuild nuvola player. That's probably why. I
guess I'll wait until it's updated in arch aur.
Thanks

**Comment by KruyKaze** [comment]
I finally rebuilt nuvola and the commands still toggle. Here's the terminal
output: http://pastebin.com/RfPe6Lxz
Thank you

**Comment by KruyKaze** [comment]
and here's the debug output : http://pastebin.com/hsBh2ZAT

**Comment by fenryxo** [comment]
That's interesting. Could you post output of following commands?

1. Find PATH of dioritegtk-0.1.vapi: `locate dioritegtk-0.1.vapi`
2. Check activate method signature: `grep -n "public override void activate" PATH`

**Comment by KruyKaze** [comment]
grep -n "public override void activate"
/usr/share/vala/vapi/dioritegtk-0.1.vapi gives me nothing

**Comment by fenryxo** [comment]
> grep -n "public override void activate" /usr/share/vala/vapi/dioritegtk-0.1.vapi gives me nothing

It seems you don't have installed the latest commit of Diorite library then.

**Comment by KruyKaze** [comment]
I installed nuvola from the aur. Then a couple of weeks ago when I
submitted this ticket I installed diorite from github. Then last night I
installed nuvola from github. Should I uninstall then install from git both
packages?
Thanks

**Comment by KruyKaze** [comment]
I uninstalled both nuvola and diorite and reinstalled from AUR .And that
fixed the problem.
Thank you.
