### ISSUE TITLE
Upgraded SoundCloud to Nuvola 3

### ISSUE THREAD

**Issue by kixam** [tiliado/nuvolaplayer#161]
Hi,

FYI, I needed it so I upgraded [old SoundCloud plugin](https://github.com/ipf/nuvola-soundcloud) to make it work under Nuvola 3

[check it out](https://github.com/kixam/nuvola-soundcloud) please

**Comment by kixam** [comment]
hum, sorry, I did not notice #30 ... I should have checked before posting... please merge or close this issue

**Comment by fenryxo** [comment]
Hello @kixam. Please consult your script with @SteVwonder at #30 to reach an agreement about which Soundcloud script will be the official one. Thanks!

**Comment by kixam** [comment]
Hi,

I do not bring anything new compared to @SteVwonder 's, except maybe I scan song artist/title permanently when he scans it only while playing, but he has anteriority, so I see no reason for my script to become the official one.

Maybe I will fork his script if I need some tweaking, but for the time being I am fine as it is.

**Comment by SteVwonder** [comment]
@kixam, i haven't forked the existing soundcloud plugin yet to make my modifications.  So if you provide any benefits over the existing one, then I am very interesting in using/including your code.

**Comment by kixam** [comment]
well, originally when I found about #30, I did not intend to implement more functionalities, but as a matter of fact, I do now:
* as opposed to @AltarBeastiful 's, I scan for artist, title and cover art whether the track is playing or not
* I fill in the album track field
* I implemented extra buttons "Like" and "Shuffle"

There are limitations from SoundCloud I could not solve any more than @AltarBeastiful could:
* track title is filled with title and/or artist. Indeed, in SoundCloud, there is one field for both. Sometimes artist appears twice, sometimes it does not appear at all; sometimes it comes first, sometimes last... cannot be helped, very difficult to parse accurately, so I just do not.
* artist is filled with playlist owner. It can be the track artist, or just another SoundCloud user
* album is filled with playlist name
* eventually Nuvola will freeze and you will have to restart it. I cannot find what's wrong from the logs, and so far I did not have any luck in wild guesses.

**Comment by SteVwonder** [comment]
I agree that the metadata (artist, track, album) on Soundcloud is very difficult to parse.  I doubt that the parsing will be of much use for scrobbling to Last.fm, but it is nice to have for local viewing and local notifications.

@AltarBeastiful had a very good idea in building off of web-scrobbler.  They have done a lot of work already on parsing common patterns found in Soundcloud track titles (extracting artist, album, etc).  I haven't tried it out yet, but it would be interesting to see how well their code performs. https://github.com/david-sabata/web-scrobbler/blob/master/connectors/v2/soundcloud.js

As far as crashes, I will pull your repo and use it.  If it crashes, I will try and investigate as well.

**Comment by kixam** [comment]
hi @SteVwonder ,

thanks for the link to the filtering function. I integrated it in my code.

**Comment by kixam** [comment]
regarding the freeze, sometimes I get this just before:

[Runner:WARNING  Nuvola] AppRunnerController.vala:620: Communication failed: Failed to read from socket.

**Comment by SteVwonder** [comment]
Sweet!  I think at this point, we should move this discussion away from this issue.  It has been closed for a while.  Do you want to resubmit your fork for review by @fenryxo?

Once that gets merged into the main nuvola-soundcloud repo, we can open an issue there for the freezes.

**Comment by kixam** [comment]
hi @SteVwonder ,

> Do you want to resubmit your fork for review by @fenryxo?

I think he said to get your agreement ;)

> I think at this point, we should move this discussion away from this issue.

let's discuss this at #30
