### ISSUE TITLE
The player window doesn't follow the dark theme preference

### ISSUE THREAD

**Issue by MartijnBraam** [tiliado/nuvolaplayer#163]
The "main" window of nuvola (where you select the streaming service) does use the dark theme on my laptop but the player window (with google play in it) uses the light theme and ignores the dark theme preference.

I'm using arch linux x64 with the latest version of GTK3 and gnome shell. The nuvolaplayer version is 2e9d673c37403d917ee06fe5876fa4b533cfe3d5

![screenshot from 2015-09-21 11-18-03](https://cloud.githubusercontent.com/assets/6928199/9988632/7ffe7ef0-6052-11e5-82b3-013476831180.png)

![screenshot from 2015-09-21 11-18-19](https://cloud.githubusercontent.com/assets/6928199/9988633/845320e6-6052-11e5-8e7f-9f80e15bb685.png)

**Comment by fenryxo** [comment]
Hello @MartijnBraam. Have you set "Prefer dark theme" in Web App Preferences (App Menu → Preferences → tab General)?

**Comment by MartijnBraam** [comment]
Ok that fixes that. But why doesn't it follow my system preferences (Global dark theme)? It seems like that should at least by default follow the system theme.

**Comment by fenryxo** [comment]
> But why doesn't it follow my system preferences (Global dark theme)?

There is a really simple explanation for that: I wasn't aware of the global dark theme preference settings, so assumed the light theme was always default unless it is overridden by an application. This is obviously wrong and needs to be fixed.

**Comment by fenryxo** [comment]
Fixed in git master & 3.0.x branches. Will be available with the next rebuilt of packages. Thanks for your bug report.
