### ISSUE TITLE
Some missing information in Ubuntu package metadata

### ISSUE THREAD

**Issue by skyghis** [tiliado/nuvolaplayer#165]
The integration scripts package informations on Ubuntu contains some missing/invalid informations 
* License
* Homepage

E.g.: 

`$ apt-cache show nuvolaplayer3-google-play-music`
> Package: nuvolaplayer3-google-play-music
> Version: 5.6-1~vivid
> License: unknown
> Vendor: fenryxo@charmeleon
> Architecture: amd64
> Maintainer: Jiří Janoušek <janousek.jiri@gmail.com>
> Installed-Size: 312
> Depends: nuvolaplayer3 (>= 3)
> Homepage: http://example.com/no-uri-given
> Priority: optional
> [...]

It would be nice to fix it on all integrations scripts

**Comment by fenryxo** [comment]
Hello. Thanks for taking the time to report this issue. I will probably take a look at it after 3.0.0 release as the packages work fine and metadata are not so important for now.

Actions:

* [ ] Add license field to metadata.json and use it for License field in package metadata
* [ ] Set Homepage to repository URL
* [ ] Set Vendor to Tiliado

**Comment by fenryxo** [comment]
The Homepage and Vendor fields have been fixed. The build script also supports the license field of `metadata.json`, but web app scripts must be updated first to provide such a field.

**Comment by fenryxo** [comment]
Hello @skyghis. I'm closing this ticket in favour of #242, which track the status of the license field in all scripts. Thanks for your bug report.
