### ISSUE TITLE
Create packages for Fedora 23

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#167]
There are **internal builds** of packages for Fedora 23 ([Final Release](https://fedoraproject.org/wiki/Schedule) October 27th), which are available for Tiliado developers Nuvola Patrons (it's necessary to enter Tiliado account credentials in Tiliado repository installer to get access to these builds). **Public builds** will be available when all issues are solved.

Results of [installation in Fedora 23](http://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html#fedora):

* [x] Installation of Nuvola Player 3 & Diorite
    * [x] Installation of tiliado-repositories RPM package fails with GNOME Software Center. It is necessary to install it via commandline `dnf install ...` Future workaround: tiliado/tiliado-repositories#3
    * [x] Installation of tiliado-repositories RPM package works from command line: `dnf install ...`
    * [x] Tiliado Repository Installer installs Nuvola Player 3 successfully.
* [x] Installation of GStreamer plugins
    * [ ] `yum localinstall --nogpgcheck ...` => change to `dnf install --nogpgcheck ...`
    * [x]  `yum install gstreamer1-{libav,plugins-{good,ugly,bad-free}}` => `Error: Error downloading packages: Cannot download x264-libs-0.142-12.20141221git6a301b6.fc22.x86_64.rpm: All mirrors were tried`
* [x] Instalation of Adobe Flash plugin - no problems
* [x] Deezer plays

**Comment by fenryxo** [comment]
Internal builds available, needs testing in virtualbox.

**Comment by fenryxo** [comment]
Found many issues: Installation of tiliado-repositories RPM package fails with GNOME Software Center. Installation of GStreamer plugins fails with Cannot download x264-libs-0.142-12.20141221git6a301b6.fc22.x86_64.rpm.

Hi @Tar-Dingens. Do you playn to upgrade to Fedora 23 soon?

**Comment by fenryxo** [comment]
Postponed to November.

**Comment by Tar-Dingens** [comment]
Yes, I do plan to upgrade soon.

**Comment by fenryxo** [comment]
Great. Builds for Fedora 23 are not public yet as there are some unresolved issues. You will have to enter your Tiliado account credentials in the Repository installer to get access to the packages. If you find an issue that is not included in this thread, report it here ;-)

**Comment by fenryxo** [comment]
It's obvious. Fedora doesn't like me. Reinstalling... :-(

![fedora_23_crashes](https://cloud.githubusercontent.com/assets/853706/11319793/a714f10c-9083-11e5-97d9-3a810e738b0c.png)

**Comment by fenryxo** [comment]
Reinstall didn't help. I had to upgrade VirtualBox to 5.10.

**Comment by fenryxo** [comment]
* Installation of Tiliado Repositories Installer RPM package via Software centre works :+1: 
  * We should switch to `dnf` as soon we drop Fedora 21 => tiliado/tiliado-repositories#5; tiliado/nuvolaplayer#182

    ```
    + ['yum', 'install', '-y', 'nuvolaplayer3']
    Yum command has been deprecated, redirecting to '/usr/bin/dnf install -y nuvolaplayer3'.
    See 'man dnf' and 'man yum2dnf' for more information.
    To transfer transaction metadata from yum to DNF, run:
    'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'
    ```

  * Flash plugin installs fine :+1: 
  * Installation of GStreamer plugins also works :+1:
  * GNOME 3.18 lost notifications with playback actions :-1:

Todo:
* Build stable packages
* Replace `yum` → `dnf` in documentation

**Comment by fenryxo** [comment]
* Done: Build stable packages
* Done: Replace `yum` → `dnf` in documentation
* TODO: Proxy settings: tiliado/tiliado-repositories#4

**Comment by fenryxo** [comment]
Done: Proxy settings: tiliado/tiliado-repositories#4
