### ISSUE TITLE
Last.fm scrobbling is not working behind a proxy

### ISSUE THREAD

**Issue by inulinux12** [tiliado/nuvolaplayer#168]
Hi.

I am using Nuvola from an HTTP proxy with authentication in Ubuntu 14.04. However when I try to connect with last.fm I get the following error:

![screenshot from 2015-09-30 18 56 15](https://cloud.githubusercontent.com/assets/1887477/10209815/0d5475c6-67a5-11e5-9902-eb42aa8ed465.png)

In console I get
`[Runner:WARNING  Nuvola] ScrobblerSettings.vala:169: Failed to get auth URL: Empty response from the server.`

Although I have set the "proxy preferences" in the Preferences window I still get the same result.

**Comment by fenryxo** [comment]
Hello. Nuvola Player proxy settings currently apply only to web pages. The rest of Nuvola Player network communication including Last.fm scrobbling uses system proxy settings. This is obviously wrong and should be fixed. Does Last.fm scrobbling work if you set your system proxy settings to the same values as you have set in Nuvola Player and restart Nuvola Player?

**Comment by fenryxo** [comment]
Fixed in git master & 3.0.x branches. Will be available with the next rebuilt of packages. Thanks for your bug report.
