### ISSUE TITLE
MPRIS and Media keys no longer work properly in GNOME

### ISSUE THREAD

**Issue by fastcat** [tiliado/nuvolaplayer#174]
This used to work properly, but something in either the nuvolaplayer3 or gnome updates in the last week or two (I use Debian Testing and generally update on Mondays) broke this.  I'm currently using `3.0.0~201510101914.d95d0c6-0+1~jessie`.

I don't know if this is service specific, I only use google play music.  Everything highlighted as broken below was working until recently.

The MPRIS interface is visible as "existing" to gnome, but the status is wrong:
* When no playlist/queue has been loaded, the MPRIS interface shows no content loaded, and has the prev, next, and play buttons all enabled
* When a playlist is loaded and playing, the prev and next buttons are *disabled* and the Play button still shows (instead of a pause button)
* Clicking the MPRIS play button in this state is equivalent to clicking the "I'm feeling lucky"
* The same problem happens if playback has been paused from within nuvola itself
* The MPRIS interface never shows the information on the currently playing song (though the notification popups do)

The media keys handling is similarly broken (maybe this goes through MPRIS too?):
* Next and Prev hotkeys *do* work properly
* The Play and Pause hotkeys both exhibit the same problematic behavior as the MPRIS play button

If I run nuvolaplayer from a terminal, I see:
* `file:///usr/share/nuvolaplayer3/js/main.js:350:16: CONSOLE LOG JS API: Action activated: play` when I click the MPRIS play button or press the play hotkey
* `... Action activated: toggle-play` when I press the pause hotkey

**Comment by fastcat** [comment]
Addendum: nuvolaplayer's own tray menu reflects the improper status of the various buttons too

**Comment by fenryxo** [comment]
Hi @fastcat. Do you have installed the latest version of Google Play Music script (5.8)?

**Comment by fastcat** [comment]
Aah, it looks like that update was released just after I last installed updates, and now that I've installed it, the problem is fixed!

**Comment by fenryxo** [comment]
Great :-)
