### ISSUE TITLE
Can't build nuvola from source

### ISSUE THREAD

**Issue by KruyKaze** [tiliado/nuvolaplayer#176]
I get this error : 
http://pastebin.com/6tW7H1qi
Let me know if you need further info.
Thanks

**Comment by KruyKaze** [comment]
Solved! I have re-installed diorite from aur may times to try to fix this.
Then decided to install diorite from github . That errored out . Then I installed it from aur again and that somehow allowed me to install nuvolaplayer-git successfully.
I'm still confused about why that worked.

**Comment by fenryxo** [comment]
Hi @KruyKaze. Git builds of Nuvola Player always require the latest Git build of Diorite library. Regarding your attempts to install Diorite library from AUR - I have no idea what's happening as I have practically zero experience with AUR. I suggest asking the maintainer of the AUR package for explanation.

> Then decided to install diorite from github. That errored out.

The error message and build log might be helpful for understanding the issue.
