### ISSUE TITLE
nuvolaplayer3ctl track-info ...  seems to get stuck

### ISSUE THREAD

**Issue by emacsomancer** [tiliado/nuvolaplayer#177]
If I start nuvolaplayer3 and start playing something, then the commandline "nuvolaplayer3ctl track-info [all|artist...]" correctly spits out the current info. But if I change the playing track, "nuvolaplayer3ctl track-info [all|artist...]" still returns the info for the first thing I played. This doesn't seem to change unless I completely shut down and restart nuvolaplayer3.

**Comment by fenryxo** [comment]
Hello @emacsomancer. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Your Linux distribution & version.
* Version of Nuvola Player.
* Which streaming service you use and its version.

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by emacsomancer** [comment]
OS: x86_64 Arch Linux - 03.11.2015 up-to-date - 
Nuvola Player: 2015.10.17.e585544-1 (nuvolaplayer-git in AUR repo)
Service: Google Play Music (whatever version they're on)

**Comment by fenryxo** [comment]
> Which streaming service you use and its version.
>> Service: Google Play Music (whatever version they're on)

I mean version of the Google Play Music integration script, e.g. from Menu → About.

**Comment by emacsomancer** [comment]
Version 5.7

**Comment by fenryxo** [comment]
Could you upgrade to version 5.8 and check whether the issue persists?

**Comment by emacsomancer** [comment]
Seem to be working on v 5.8. (Also the State values seemed to be fixed
too). Thanks.
