### ISSUE TITLE
Nuvola Player crashes in Wayland session after gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed

### ISSUE THREAD

**Issue by jjardon** [tiliado/nuvolaplayer#181]
**This issue has been fixed in the [master](https://github.com/tiliado/nuvolaplayer) & [3.0.x](https://github.com/tiliado/nuvolaplayer/tree/3.0.x) GIT branches. Thanks for your bug report.**

At first, this fix will be available with the next rebuilt of packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html). Later, the fix will be also included in the next bug-fix release of the [Nuvola Player 3.0 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html). To get informed when Nuvola Player 3.0.4 Stable Release is released, follow Nuvola Player on [Facebook](https://www.facebook.com/nuvolaplayer), [Google+](https://plus.google.com/110794636546911932554) or [Twitter](https://twitter.com/NuvolaPlayer), or subscribe to the Nuvola Player Newsletter: [weekly](http://eepurl.com/bLbm5H) or [monthly](http://eepurl.com/bLbtM1).

**Update:** This issue has been fixed in the [Nuvola Player 3.0.4 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html) (September 17th, 2016).

---

**Original report:**

$ nuvolaplayer3
[Master:CRITICAL   Gdk] gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed
[Master:CRITICAL   Gdk] Application will not function properly.
Segmentation fault (core dumped)

**Comment by fenryxo** [comment]
Hello. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Your linux distribution and version.
* You desktop environment and its version.
* Debugging output from terminal up to the crash.

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by jjardon** [comment]
Hi, sorry I missed that info:

Im using GNOME in Arch Loinux

My nuvola version is the one in AUR: https://aur.archlinux.org/packages/nuvolaplayer-git/, so what it was in the git repo 3 days ago
$ nuvolaplayer3 --version
Nuvola Player 3 Beta 3.0.0
Revision fuzzy

$ nuvolaplayer3 --debug
[Master:DEBUG      Gtk] Connecting to session manager
[Master:CRITICAL   Gdk] gdk_window_get_display: assertion 'GDK_IS_WINDOW (window)' failed
[Master:CRITICAL   Gdk] Application will not function properly.
Segmentation fault (core dumped)

I think the problem nuvolaplayer3 assume is in a X11 session, and its missing some checks; it runs without problems is I specify the backend:

$ GDK_BACKEND=x11 nuvolaplayer3 --debug
[Master:CRITICAL GLib-GObject] g_object_ref: assertion 'G_IS_OBJECT (object)' failed
[Master:CRITICAL GLib-GObject] Application will not function properly.
[Master:DEBUG      Gtk] Connecting to session manager
[Master:DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: gnome shell 3.18.2, CSD on
[Master:DEBUG    Nuvola] config.vala:174: Json Error: Failed to open file '/home/jjardon/.config/nuvolaplayer3/master/config.json': No such file or directory
[Master:WARNING  Nuvola] WebAppRegistry.vala:165: Unable to load web app from /usr/share/nuvolaplayer3/web_apps/template: /usr/share/nuvolaplayer3/web_apps/template/metadata.json is not a file
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.8
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.1
[Master:WARNING  DioriteGtk] Icons.vala:40: Failed to load icon 'nuvolaplayer3': Icon 'nuvolaplayer3' not present in theme Adwaita
[Master:WARNING  Nuvola] WebAppListWindow.vala:52: Unable to load application icon.
[Master:DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager

**Comment by fenryxo** [comment]
Thanks for your log. Due to limited resources, Nuvola Player fails to keep up with modern technologies such as Wayland. Wayland support might be a good release goal for Nuvola Player 3.1, whose development will start in February 2016.

**Comment by excieve** [comment]
FYI: this is still happening (Fedora 24). Wayland support in Gnome is pretty good by now and likely to be the default for Fedora 25. Workaround mentioned by @jjardon helps though.

**Comment by fenryxo** [comment]
Hi @excieve. Could you [provide a backtrace](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#get-backtrace)?

**Comment by fenryxo** [comment]
Since there are at least three features that don't work under Wayland (see #240) and no easy way to port them to Wayland (at least for me), I'm going to set the `GDK_BACKEND=x11` environment variable in Nuvola processes to always use X11 or XWayland and avoid crashing.

**Comment by fenryxo** [comment]
**This issue has been fixed in the [master](https://github.com/tiliado/nuvolaplayer) & [3.0.x](https://github.com/tiliado/nuvolaplayer/tree/3.0.x) GIT branches. Thanks for your bug report.**

At first, this fix will be available with the next rebuilt of packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html). Later, the fix will be also included in the next bug-fix release of the [Nuvola Player 3.0 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html). To get informed when Nuvola Player 3.0.4 Stable Release is released, follow Nuvola Player on [Facebook](https://www.facebook.com/nuvolaplayer), [Google+](https://plus.google.com/110794636546911932554) or [Twitter](https://twitter.com/NuvolaPlayer), or subscribe to the Nuvola Player Newsletter: [weekly](http://eepurl.com/bLbm5H) or [monthly](http://eepurl.com/bLbtM1).

**Comment by fenryxo** [comment]
**Update:** This issue has been fixed in the [Nuvola Player 3.0.4 Stable Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html) (September 17th, 2016).
