### ISSUE TITLE
Nuvola Player resets icon at update [$15]

### ISSUE THREAD

**Issue by jGleitz** [tiliado/nuvolaplayer#184]
I use a custom icon theme that ships an icon for Google Play Music. To make Nuvola better fit into my desktop theme, I adapted the used icon in `nuvolaplayer3-google-play-music.desktop` as such:

```
[…]
# Icon=/usr/share/nuvolaplayer3/web_apps/google_play_music/icon.png
Icon=google-music
[…]
```

Now whenever nuvola player updates (which fortunately happens quite often :+1:) this change is overwritten.

I’d love to be able to specifiy the icon I’m using myself and think that nuvola player should not override an existing launcher.

I only tested this with the Google Play Music integration.

I’m running 
```
Nuvola Player 3 Beta 3.0.0+201511141626.f558c94
Revision f558c94983c2d0fdba25c17927286202959fbcf5
```
on Ubuntu 15.10.

I think the issue is present since Nuvola Player 3 was introduced.

**Comment by fenryxo** [comment]
Hello. Thanks for taking time to report this issue. Does it help if you mark the desktop file read-only (`chmod a-w`) after adapting it?

**Comment by jGleitz** [comment]
> Does it help if you mark the desktop file read-only (`chmod a-w`) after adapting it

Oh, never thought of that, sorry! Is there any way to “simulate” an update to check?

**Comment by fenryxo** [comment]
The desktop file is currently re-generated at every start-up of a particular web app.

**Comment by jGleitz** [comment]
Thanks for clarifying. Removing write permissions fixes the issue. Sorry for not thinking about it!

**Comment by fenryxo** [comment]
> Sorry for not thinking about it!

No problem. I think not mentioning this option is actually a bug in Nuvola Player documentation, which needs to be fixed.

**Comment by fenryxo** [comment]
A section about desktop launchers and a way to preserve your custom launchers have been added to [the documentation](https://tiliado.github.io/nuvolaplayer/documentation/3.0/explore.html#explore-unity).
