### ISSUE TITLE
No MediaKey Control for Spotify WebApp

### ISSUE THREAD

**Issue by erichlf** [tiliado/nuvolaplayer#185]
Nuvola Player 3 Beta 3.0.0+201511141626.f558c94
Ubuntu 14.04

When trying to control nuvolaplayer3-spotify from dbus with either playerctl or nuvolplayer3ctl nothing happens. However, google-play-music works fine. My guess is that the spotify web-app api has changed.

**Comment by fenryxo** [comment]
Hello @erichlf. Thanks for taking the time to report your issue. I'm notifying the maintainer of Spotify script.

@thenyeguy, could you take a look at this issue?

**Comment by erichlf** [comment]
I don't completely understand the spotify-app code (it is too simple and appears to be missing things, to me anyway). But If it does what I think then I believe the following lines from 
https://play.spotify.edgekey.net/apps/player/4.2.0/main.js
might help:

``` 
  var playBtn = new PlayPauseButton('play-pause', logger, adBreak);
  var nextBtn = new nextBackButtons.NextButton('next', eventManager, logger, adBreak);
  var backBtn = new nextBackButtons.BackButton('previous', eventManager, logger, adBreak);
```
and
```
      var handleMiniPlayerMessage = function (msg) {
        switch (msg.miniplayer) {
        case 'staterequest':
          postMiniPlayerState();
          break;
        case 'playpause':
          playBtn.toggle();
          break;
        case 'next':
          nextBtn.playerNext();
          break;
        case 'back':
          backBtn.playerBack();
          break;
        case 'shuffle':
          shuffleBtn.toggle();
          break;
        case 'repeat':
          repeatBtn.toggle();
          break;
        case 'star':
          starUnstar();
          break;
        case 'seek':
          player.seek(msg.target);
          break;
        case 'volume':
          player.setVolume(msg.target);
          break;
        case 'openuri':
          models.application.openURI(msg.target);
          break;
        default:
          break;
        }
      };
```

**Comment by erichlf** [comment]
Weird! Just started listening again and decided to click play-pause and it works again. I didn't update anything, so it appears that it was an internal spotify issue. This should be closed then.

**Comment by fenryxo** [comment]
Glad to hear the issue has gone. Feel free to reopen this ticket If it appears again. Thanks for your bug report.

**Comment by erichlf** [comment]
This problem seems to come and go, but I can't seem to figure out what causes it. Restarting nuvolaplayer doesn't fix the problem, so...

**Comment by thenyeguy** [comment]
Do you use Chrome with an extension for using media keys? Chrome has a bad habit of capturing them and never letting go.

**Comment by erichlf** [comment]
No, I use firefox, but also, I use i3wm so technically there isn't support
for media keys in the standard way. I use playerctl and a keybinding (I
have tried nuvolaplayer3ctl directly too) to use media keys. However, the
media keys work in the google-play-music app just fine, while they aren't
working in the spotify app. It is quite strange.

Erich L Foster

**Comment by erichlf** [comment]
Okay, a reboot gets things back. Logging out and back in didn't solve the issue. Weird!

**Comment by fenryxo** [comment]
> I use i3wm so technically there isn't support for media keys in the standard way

Nuvola Player can actually bind media keys like XF86AudioPlay directly unless they have been already grabbed by another app.

> I use playerctl and a keybinding

There may be a conflict between your keybinding and Nuvola Player's media keys grabbing. Could you post a debugging output? See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.
