### ISSUE TITLE
Code review: Hello Play

### ISSUE THREAD

**Issue by thepisu** [tiliado/nuvolaplayer#190]
Hi, I have developed a service integration for Hello Play (https://www.hellosound.it), a new Italian music cloud service created by Hello Bank - BNL, an Italian bank, and powered by Universal Music Group.

The integration is very simple, as this service does not provide thumbs up / down feature or other things.

This is the push to Nuvola Player issue:
https://github.com/thepisu/nuvola-app-helloplay/issues/1

**Comment by fenryxo** [comment]
Hello @thepisu, I will look at it after stable release of NP 3.0.

**Comment by thepisu** [comment]
Hello @fenryxo , I found that Hello Play can be used after trial period only subscribing a bank account with Hello Bank, so I think that few people will be really interested in this service. For this reason, I would like to retire my code review request, and instead publishing the DEB package (and GitHub repository link) on my website.

**Comment by thepisu** [comment]
Link to published article (in Italian): 
https://jaub.wordpress.com/2016/01/09/nuvola-player-3-e-hello-play/

Link to Ubuntu/Debian package: 
http://www.stefanobagnatica.it/dl/nuvolaplayer/nuvolaplayer3-helloplay_1.0-1.deb

**Comment by fenryxo** [comment]
Ok, closing.
