### ISSUE TITLE
nuvolaplayer3 should recommend libwebkit2gtk-4.0-37-gtk2

### ISSUE THREAD

**Issue by fastcat** [tiliado/nuvolaplayer#191]
Recent Debian packagings of webkit have moved support for Flash (and other GTK+2 based plugins) into a separate package that is not installed by default.

Since many of the services supported by nuvolaplayer need flash, nuvolaplayer should probably recommend this package.  Even better would be to have the individual services that need it do so :)

```
webkit2gtk (2.10.4+dfsg1-1) unstable; urgency=medium

  Since webkit2gtk 2.10.4, support for GTK+2-based plugins (Adobe
  Flash, Google Talk/Hangouts) has been moved to a separate package
  called libwebkit2gtk-4.0-37-gtk2.

  This removes the GTK+ 2 dependency from the main libwebkit2gtk package
  and makes it much smaller, so if you don't want to use any of those
  plugins you don't need to install this new package.

 -- Alberto Garcia <berto@igalia.com>  Thu, 12 Nov 2015 20:40:18 +0200
```

**Comment by fenryxo** [comment]
Hello @fastcat. Thanks for reporting this issue. I've just updated packaging for Sid & Stretch and rebuilt packages for Sid. Packages for Stretch will be rebuilt later this week. Do you use Sid or Stretch? If Sid, could you upgrade Nuvola Player and then check whether an attempt to uninstall libwebkit2gtk-4.0-37-gtk2 would lead to the uninstallation of Nuvola Player package? I don't have Sid/Stretch machine around. Thanks!

**Comment by fastcat** [comment]
I use stretch/sid, yes.  Which repo section / version has these new packages?  I'm happy to confirm concretely, but I can say from experience that uninstalling a recommended package does not trigger removal of the recommending package ... that's part of the point of the distinction between Depends vs. Recommends or Suggests.

**Comment by fenryxo** [comment]
> Which repo section / version has these new packages?

Both stable/beta & devel.

> I can say from experience that uninstalling a recommended package does not trigger removal of the recommending package

It's currently a hard depencency as most of the streaming services require Flash. This may be later fine-tuned as part of #158.

**Comment by fastcat** [comment]
> could you upgrade Nuvola Player and then check whether an attempt to uninstall libwebkit2gtk-4.0-37-gtk2 would lead to the uninstallation of Nuvola Player package?

Confirmed

**Comment by fenryxo** [comment]
Thanks.
