### ISSUE TITLE
Gear menu missing options in Arch Budgie Desktop

### ISSUE THREAD

**Issue by marek287** [tiliado/nuvolaplayer#193]
In Ubuntu I have more options to select.
![image](https://cloud.githubusercontent.com/assets/9947650/12066803/66e1999a-aff6-11e5-8024-64942e563af2.png)
In Arch Budgie Desktop I have only these options:
![image](https://cloud.githubusercontent.com/assets/9947650/12066789/4dc8d9fa-aff6-11e5-8571-d3850944b50c.png)

**Comment by fenryxo** [comment]
Hello @marek287. Thanks for reporting your issue. Does Budgie Desktop have appmenu like GNOME?

![AppMenu in GNOME](https://tiliado.github.io/nuvolaplayer/documentation/images/3.0/gnome/gnome_grooveshark_appmenu_preferences.png)

**Comment by marek287** [comment]
Ok, my feeling was right. It's budgie issue. I have only this options.
![image](https://cloud.githubusercontent.com/assets/9947650/12067501/5630e9c2-b003-11e5-93fb-3c8770dd9c95.png)

**Comment by fenryxo** [comment]
It is possible to add a workaround. I need a line from debugging output (`nuvolaplayer3 -D`) similar to `Master: [DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: gnome shell 3.14.4, CSD 1, appmenu 1, menubar 0` using the latest git master version of Diorite library I've just pushed to GitHub. I believe it's the package `diorite-git` in Arch Linux.

**Comment by marek287** [comment]
Master: [DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: mutter(budgie) (null), CSD 0, appmenu 1, menubar 0

Is it that you want?

**Comment by fenryxo** [comment]
Yes, thanks. It is indeed a bug in Budgie, because it falsely claims to support appmenu. Does Budgie support client side decorations? I could enable them.

**Comment by ikeydoherty** [comment]
Hey, no we don't falsely claim anything.

We don't yet override the XSettings to enforce AppMenu presence in the titlebar.
Solus currently uses a patch to achieve this in gnome-settings-daemon, but it will be enforced directly in Budgie soon.

There is no "claiming", it's a GTK assumption.

The following needs to be overriden in XSettings:

````
Gtk/ShellShowsAppMenu : 0
Gtk/DecorationLayout: menu:minimize,maximize,close
```

**Comment by fenryxo** [comment]
Fair enough. Fixed in diorite's git master branch.

**Comment by ikeydoherty** [comment]
^ You don't need to put a workaround in, I was gonna get it done in Budgie! Thanks though.

Ok as soon as I implement this in Budgie, should I just open a new issue for you to revert this?

**Comment by fenryxo** [comment]
Yes, please, as soon as your fix lands to your next stable release.

**Comment by marek287** [comment]
Thanx @ikeydoherty @fenryxo. 
I have now double options:
![image](https://cloud.githubusercontent.com/assets/9947650/12068050/e28b7702-b00d-11e5-85e0-538664039c0e.png)

![image](https://cloud.githubusercontent.com/assets/9947650/12068061/0be57c74-b00e-11e5-9888-37c13acfbbe6.png)

**Comment by fenryxo** [comment]
> I have now double options:

Reticketed as tiliado/diorite#4
