### ISSUE TITLE
Thumbs-up thumbs-down icons don't change color

### ISSUE THREAD

**Issue by KruyKaze** [tiliado/nuvolaplayer#194]
Nuvola 3.0 / Google music 5.11
Let me know if you need extra info thanks.
![screenshot from 2016-01-02 03-56-43](https://cloud.githubusercontent.com/assets/70369/12074265/50d3b7c6-b106-11e5-81e4-590ca0e3dfdb.png)

**Comment by fenryxo** [comment]
Hello @KruyKaze. Thanks for your report. It seems to be a bug in Google Play Music code, because it also happens in Firefox, but not in Chrome.

**Comment by fenryxo** [comment]
Hello. Does this issue still happen with the latest WebKitGTK+ library?

**Comment by KruyKaze** [comment]
I believe it's been resolved lately

**Comment by fenryxo** [comment]
Great :-)
