### ISSUE TITLE
Rename icon.svg in nuvolaplayer and web app scripts to support Numix icon theme

### ISSUE THREAD

**Issue by rishadafc** [tiliado/nuvolaplayer#195]
With reference to [this issue](https://github.com/numixproject/numix-icon-theme-circle/issues/1576), would it be possible to rename the icons to allow the Numix developers to support Nuvola in their icon theme? 

I don't know if this affects other icon themes, but it would be really nice to have this fixed. This is the only app I have that isn't changing icons to adapt to the icon theme I choose.

I would be happy to provide a pull request if this isn't a difficult/complicated task.

**Comment by fenryxo** [comment]
Hello. Nuvola Player already supports icon themes that contain icon names `nuvolaplayer3_APP_ID`. See https://github.com/tiliado/nuvolaplayer/issues/78#issuecomment-167314230 for details.
