### ISSUE TITLE
Nuvola not recognizing Flash installation Fedora 23

### ISSUE THREAD

**Issue by aia832003** [tiliado/nuvolaplayer#199]
I having the issue that despite Flash being installed, and up to date, Nuvola doesn't recognize the plugin when using Google Play.

**Comment by fenryxo** [comment]
Hello @aia832003 . Thanks for taking the time to report your issue. I need more information to investigate it further:

* Debugging output from terminal as described in [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines).
* How did you install the Flash plugin? Have you followed [Flash installation instructions](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html#fedora-flash)?

**Comment by aia832003** [comment]
Nuvola Player 3 3.0.0
Revision 53b1d03843d1987c3510401da8959384fa25670e

[09:17 andrew ~]$ nuvolaplayer3 --debug
Master: [DEBUG      Gtk] Connecting to session manager
Master: [DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: gnome shell 3.18.2, CSD on
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.11
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.0
Master: [WARNING  Nuvola] WebAppRegistry.vala:165: Unable to load web app from /usr/share/nuvolaplayer3/web_apps/template: /usr/share/nuvolaplayer3/web_apps/template/metadata.json is not a file
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.1
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_8tracks 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_amazon_cloud_player 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_bandcamp 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_deezer 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_google_play_music 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_jango 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_kexp 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_logitech_media_server 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_mixcloud 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_plex 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_spotify 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_test 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_tunein 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_yandex_music 48 not found.
Master: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager


I installed through RPM Fusion repos as well as the official Flash page view the Nuvola link.

**Comment by aia832003** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/11007827/12395137/926cd322-bdc5-11e5-98c5-96061732dfec.png)

**Comment by fenryxo** [comment]
The debugging output seems to be incomplete. Could you post a new debugging output up to the point when Google Play Music page is fully loaded? Also, could you post a screenshot of the Format support dialog? Thanks.

**Comment by aia832003** [comment]
[09:37 andrew ~]$ nuvolaplayer3 --debug
Master: [DEBUG      Gtk] Connecting to session manager
Master: [DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: gnome shell 3.18.2, CSD on
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.11
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.0
Master: [WARNING  Nuvola] WebAppRegistry.vala:165: Unable to load web app from /usr/share/nuvolaplayer3/web_apps/template: /usr/share/nuvolaplayer3/web_apps/template/metadata.json is not a file
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.1
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_8tracks 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_amazon_cloud_player 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_bandcamp 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_deezer 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_google_play_music 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_jango 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_kexp 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_logitech_media_server 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_mixcloud 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_plex 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_spotify 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_test 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_tunein 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_yandex_music 48 not found.
Master: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.11
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.0
Master: [WARNING  Nuvola] WebAppRegistry.vala:165: Unable to load web app from /usr/share/nuvolaplayer3/web_apps/template: /usr/share/nuvolaplayer3/web_apps/template/metadata.json is not a file
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.1
Master: [INFO     Nuvola] WebAppRegistry.vala:89: Using web app Google Play Music, version 5.11, data dir /usr/share/nuvolaplayer3/web_apps/google_play_music
Master: [DEBUG    Nuvola] MasterController.vala:463: Launch app runner for 'google_play_music': /usr/lib64/nuvolaplayer3/apprunner -D -a /usr/share/nuvolaplayer3/web_apps/google_play_music 
Runner: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_google_play_music 1024 not found.
Runner: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_google_play_music 1024 not found.
Runner: [DEBUG      Gtk] Connecting to session manager
Runner: [DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: gnome shell 3.18.2, CSD on
Runner: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
Master: [DEBUG    Nuvola] MasterController.vala:287: Connected to runner server for 'google_play_music'.
Runner: [DEBUG    Nuvola] Connection.vala:132: Network Proxy: system settings
Runner: [DEBUG    Nuvola] WebEngine.vala:66: Nuvola WebKit Extension directory: /usr/lib64/nuvolaplayer3
Runner: [WARNING  GLib-GObject] g_object_set_property: construct property "local-storage-directory" for object 'WebKitWebContext' can't be set after construction
Runner: [DEBUG    Nuvola] Notifications.vala:175: Notifications: persistence true, actions true, icons false
Master: [DEBUG    Nuvola] MediaKeys.vala:99: GNOME settings daemon appeared: org.gnome.SettingsDaemon, :1.11
Runner: [DEBUG    Nuvola] MPRISProvider.vala:73: Bus acquired: org.mpris.MediaPlayer2.NuvolaAppGooglePlayMusic, registering objects
Runner: [DEBUG    Nuvola] MPRISProvider.vala:90: Bus name acquired: org.mpris.MediaPlayer2.NuvolaAppGooglePlayMusic
Runner: Error loading module '/usr/lib64/nuvolaplayer3/libflashplayer.so': /usr/lib64/nuvolaplayer3/libflashplayer.so: cannot open shared object file: Permission denied
Worker: [DEBUG    Nuvola] WebExtension.vala:237: Page 1 created for (null)
Runner: [DEBUG    Nuvola] WebEngine.vala:464: Navigation, current window: uri = https://play.google.com/music/listen#/now, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Trying to play /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from NULL to READY.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from READY to PAUSED.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from PAUSED to PLAYING.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: End of stream for file /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Evince Browser Plugin (enabled, not flash) at /usr/lib64/mozilla/plugins/libevbrowserplugin.so: The <a href="http://wiki.gnome.org/Apps/Evince/">Evince</a> 3.18.2 plugin handles documents inside the browser window.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Gnome Shell Integration (enabled, not flash) at /usr/lib64/mozilla/plugins/libgnome-shell-browser-plugin.so: This plugin provides integration with Gnome Shell for live extension enabling and disabling. It can be used only by extensions.gnome.org
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: IcedTea-Web Plugin (using IcedTea-Web 1.6.1 (fedora-4.fc23-x86_64)) (enabled, not flash) at /usr/lib64/mozilla/plugins/libjavaplugin.so: The <a href="http://icedtea.classpath.org/wiki/IcedTea-Web">IcedTea-Web Plugin</a> executes Java applets.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebRunner: Plugin: iTunes Application Detector (enabled, not flash) at /usr/lib64/mozilla/plugins/librhythmbox-itms-detection-plugin.so: This plug-in detects the presence of iTunes when opening iTunes Store URLs in a web page with Firefox.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: PackageKit (enabled, not flash) at /usr/lib64/mozilla/plugins/packagekit-plugin.so: Plugin for Installing Applications (new)
Runner: [WARNING  Nuvola] FormatSupportCheck.vala:152: No Flash plugin has been found.
Worker: [DEBUG    Nuvola] WebExtension.vala:140: Window object cleared: https://play.google.com/music/listen#/now, 0x558e8ff7f070, 0x558e8ff0a520, 0x7fce8553b740
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] WebAppWindow.vala:170: Sidebar position: 890
Runner: [DEBUG    Nuvola] WebEngine.vala:464: Navigation, current window: uri = https://fls.doubleclick.net/activityi;src=2542116;type=andro238;cat=googl515;ord=1;num=2820594389922.917?, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: https://play-music.gstatic.com/fe/42a7c09036df78db5b649e8467b14d66/webcomponents-lite.min.js:11:17074: CONSOLE ERROR Refused to get unsafe header "Location"
Runner: [DEBUG    Nuvola] WebEngine.vala:464: Navigation, current window: uri = https://2542116.fls.doubleclick.net/activityi;src=2542116;type=andro238;cat=googl515;ord=1;num=2820594389922.917, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [INFO     Nuvola] AppRunnerController.vala:236: Logged in as  ()
Runner: https://www.googleadservices.com/pagead/conversion.js:16:111: CONSOLE ERROR Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
Runner: https://www.googleadservices.com/pagead/conversion.js:16:172: CONSOLE ERROR Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
Runner: https://www.googleadservices.com/pagead/conversion.js:13:240: CONSOLE ERROR Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-pause
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-stop
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-play
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-go-previous
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-go-next
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: [DEBUG    Nuvola] WebEngine.vala:464: Navigation, current window: uri = https://accounts.google.com/o/oauth2/postmessageRelay?parent=https%3A%2F%2Fplay.google.com#rpctoken=523621218&forcesecure=1, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebEngine.vala:464: Navigation, current window: uri = https://0.client-channel.google.com/client-channel/client?cfg=%7B%222%22%3A%22music%22%2C%228%22%3Afalse%2C%2213%22%3Afalse%7D&ctype=music&xpc=%7B%22cn%22%3A%22ehnNQF7Kfn%22%2C%22tp%22%3Anull%2C%22osh%22%3Anull%2C%22ppu%22%3A%22https%3A%2F%2Fplay.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2F0.client-channel.google.com%2Frobots.txt%22%7D, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebEngine.vala:464: Navigation, current window: uri = https://clients4.google.com/invalidation/lcs/client?xpc=%7B%22cn%22%3A%22p3rbRbpKoP%22%2C%22tp%22%3Anull%2C%22osh%22%3Anull%2C%22ppu%22%3A%22https%3A%2F%2Fplay.google.com%2Frobots.txt%22%2C%22lpu%22%3A%22https%3A%2F%2Fclients4.google.com%2Frobots.txt%22%7D, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebEngine.vala:464: Navigation, current window: uri = https://play.google.com/music/services/streamingloadalltracks?u=0&xt=CjUKATASMEFNLVdiWGhPdHdSZ05qMEZRM0pEOV9hV0xxNVFoNVd2YWc6MTQ1MzEzMTQ3NDk1Mw%3D%3D&json=%7B%22tier%22%3A2%2C%22requestCause%22%3A1%2C%22requestType%22%3A1%2C%22sessionId%22%3A%22i8ase9myrr6m%22%7D&format=jsarray, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] WebEngine.vala:464: Navigation, current window: uri = https://plus.google.com/u/0/_/notifications/frame?sourceid=166&hl=en&origin=https%3A%2F%2Fplay.google.com&uc=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.031mdWrIyGE.O%2Fm%3D__features__%2Fam%3DAAQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo9LVH8q4HIB6ymfgTF00d12dbkTeA#pid=166&rpctoken=115861002&_methods=onError%2ConInfo%2ChideNotificationWidget%2CpostSharedMessage%2Creauth%2CsetNotificationWidgetHeight%2CsetNotificationWidgetSize%2CswitchTo%2CnavigateTo%2CsetNotificationText%2CsetNotificationAnimation%2CgetNotificationText%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart&id=I1_1453131480986&parent=https%3A%2F%2Fplay.google.com&pfname=, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-play
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location

**Comment by aia832003** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/11007827/12395466/67ee8d78-bdc7-11e5-9abb-5c23f9dc2a3c.png)

**Comment by fenryxo** [comment]
> `Runner: Error loading module '/usr/lib64/nuvolaplayer3/libflashplayer.so': /usr/lib64/nuvolaplayer3/libflashplayer.so: cannot open shared object file: Permission denied`

Flash plugin seems to have been installed into an unusual location and with wrong permissions. Could you try fixing the permissions?

>* `Evince Browser Plugin (enabled, not flash) at /usr/lib64/mozilla/plugins/libevbrowserplugin.so: The Evince 3.18.2 plugin handles documents inside the browser window. `
>* `Gnome Shell Integration (enabled, not flash) at /usr/lib64/mozilla/plugins/libgnome-shell-browser-plugin.so: This plugin provides integration with Gnome Shell for live extension enabling and disabling. It can be used only by extensions.gnome.org `
>* `IcedTea-Web Plugin (using IcedTea-Web 1.6.1 (fedora-4.fc23-x86_64)) (enabled, not flash) at /usr/lib64/mozilla/plugins/libjavaplugin.so: The IcedTea-Web Plugin executes Java applets. `
>* `iTunes Application Detector (enabled, not flash) at /usr/lib64/mozilla/plugins/librhythmbox-itms-detection-plugin.so: This plug-in detects the presence of iTunes when opening iTunes Store URLs in a web page with Firefox. `
>* `PackageKit (enabled, not flash) at /usr/lib64/mozilla/plugins/packagekit-plugin.so: Plugin for Installing Applications (new)`

There are several other plugins in the standard location, but none of them is Flash. If I recall correctly, the installation according to [Flash installation instructions](https://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html#fedora-flash) puts Flash plugin into the "/usr/lib64/mozilla/plugins" directory. What went wrong?

**Comment by aia832003** [comment]
I looked in the Mozilla lib64 folder and did not find the service there. The other locations were placed there in my poor attempt to self remedy the problem. lol

I will move the file and change permissions and report back.

**Comment by aia832003** [comment]
Ok. Was able to reconcile doing the following:

1) Download 64bit Redhat file from https://www.rpmfind.net/linux/rpm2html/search.php?query=libflashplayer.so()(64bit)
2) Seems the deprecation of non-Chrome flash on Linux places this in /usr/lib64/flash-plugin
3) Move libflashplayer.so from /usr/lib64/flash-plugin to /usr/lib64/mozilla/plugins
4) Success!

**Comment by fenryxo** [comment]
Glad to hear it works. However, I'd strongly recommend to use the Adobe's Flash repository in order to receive security updates
