### ISSUE TITLE
Support webkit2gtk-4.0 API (Fedora 21, Arch Linux)

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvolaplayer#2]
:heart: [Two Nuvola Patrons](https://tiliado.eu/accounts/group/3/) is interested in this issue (note 22).

The release 2.6 of WebKit2Gtk (the second generation of the WebKit library with GTK+ user interface) [introduced ABI break](http://blogs.igalia.com/carlosgc/2014/08/01/webkitgtk-2-5-1-good-bye-webkit1/) and changed ABI version from `webkit2gtk-3.0` (supported by Nuvola Player)  to `webkit2gtk-4.0` (not yet supported by Nuvola Player).

This is usually fine, because both the old and the new libraries can be installed together and don't interfere with each other. Therefore, *sane distributions* offer packages for both versions for a transition period and developers are granted enough time to upgrade their applications to add support for the new ABI. Unfortunately, some *bleeding edge distributions* like Arch Linux and Fedora 21 don't care about backward compatibility and happily introduce new incompatible version without keeping older version around. :-(

Original report
------------------

i get the message "webkit2gtk-3.0' >= 2.2 not found" although webkit2gtk3 is installed.

[root@fc21 tmp]# rpm -qa |grep webkitgtk3
webkitgtk3-2.4.7-1.fc21.x86_64
webkitgtk3-devel-2.4.7-1.fc21.x86_64

[martin@fc21 SPECS]$ rpmbuild -ba nuvolaplayer-3.0.0.spec

Ausführung(%prep): /bin/sh -e /var/tmp/rpm-tmp.o3AKNG
+ umask 022
+ cd /home/martin/rpmbuild/BUILD
+ cd /home/martin/rpmbuild/BUILD
+ rm -rf nuvolaplayer-3.0.0
+ /usr/bin/bzip2 -dc /home/martin/rpmbuild/SOURCES/nuvolaplayer-3.0.0.tar.bz2
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd nuvolaplayer-3.0.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Ausführung(%build): /bin/sh -e /var/tmp/rpm-tmp.Yajqps
+ umask 022
+ cd /home/martin/rpmbuild/BUILD
+ cd nuvolaplayer-3.0.0
+ export RSVG=/usr/bin/rsvg-convert
+ RSVG=/usr/bin/rsvg-convert
+ waf configure --prefix=/usr --libdir=/usr/lib64
fatal: Not a git repository (or any of the parent directories): .git
Setting top to : /home/martin/rpmbuild/BUILD/nuvolaplayer-3.0.0
Setting out to : /home/martin/rpmbuild/BUILD/nuvolaplayer-3.0.0/build
Revision id : fuzzy_id
Target platform : LINUX
Install prefix : /usr
Checking for 'c_bgxlc' (c compiler) : not found
Checking for 'gcc' (c compiler) : /usr/bin/gcc
Checking for program pkg-config : /usr/bin/pkg-config
Checking for 'gobject-2.0' : yes
Checking for 'gthread-2.0' : yes
Checking for program valac-0.8 : not found
Checking for program valac : /usr/bin/valac
Checking for valac version >= (0, 8, 0) : (0, 26, 1)
Checking for program valac-0.22 : /usr/bin/valac
Checking for valac-0.22 version >= (0, 22, 1) : (0, 26, 1)
Compiler optimizations : ON
Checking for 'glib-2.0' >= 2.32 : yes
Checking for 'gio-2.0' >= 2.32 : yes
Checking for 'gtk+-3.0' >= 3.4 : yes
Checking for 'gdk-3.0' >= 3.4 : yes
Checking for 'gdk-x11-3.0' >= 3.4 : yes
Checking for 'x11' >= 0.5 : yes
Checking for 'gthread-2.0' >= 2.32 : yes
Checking for 'dioriteglib-0.1' >= 0.1 : yes
Checking for 'dioritegtk-0.1' >= 0.1 : yes
Checking for 'json-glib-1.0' >= 0.7 : yes
Checking for 'libarchive' >= 3.1 : yes
Checking for 'webkit2gtk-3.0' >= 2.2 : not found
The configuration failed
(complete log in /home/martin/rpmbuild/BUILD/nuvolaplayer-3.0.0/build/config.log)
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.Yajqps (%build)

**Comment by fenryxo** [comment]
Nuvola Player should now work correctly with webkit2gtk-4.0

**Comment by mpdeimos** [comment]
Thanks! I can confirm this works on Arch Linux.

Is there a way to install flash player just for Nuvola Player? I'm not very keen on installing it system-wide unless I could use Pepper Flash ;)

**Comment by fenryxo** [comment]
> Is there a way to install flash player just for Nuvola Player?

You can try to install flash plugin to a special directory and set MOZ_PLUGIN_PATH environment variable.

$ MOZ_PLUGIN_PATH=/opt/myflash nuvolaplayer3

**Comment by rosshadden** [comment]
@mpdeimos Did you figure out a way to install an isolated flash instance?  I don't want to install flash, either.  Unless, as you said, it's Pepper Flash, which is already installed for Chrome.

**Comment by fenryxo** [comment]
@mpdeimos @rosshadden You can also try out [Fresh Player plugin](http://www.webupd8.org/2014/05/install-fresh-player-plugin-in-ubuntu.html) + Pepper Flash plugin.

**Comment by mpdeimos** [comment]
I haven't played with this yet. If I've time during the weekend I'll let you know.

**Comment by rosshadden** [comment]
Thanks @fenryxo. That works.
