### ISSUE TITLE
Enormous memory usage in Arch Linux

### ISSUE THREAD

**Issue by KruyKaze** [tiliado/nuvolaplayer#200]
I noticed that Nuvola's memory usage keeps groiwing over time and the pc locks up after a few days.
I was thinking about a cron job that would restart it every day but is there a way to automate shuffling the library? I can't find the command for that.
Thanks!

**Comment by fenryxo** [comment]
Hello @KruyKaze. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Version of Nuvola Player.
* Your system and its version.
* What memory usage do you experience?

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details

**Comment by KruyKaze** [comment]
* I am using Nuvola Player 3 beta on Arch. I got it from the AUR : https://aur.archlinux.org/packages/nuvolaplayer-git
* I am using Arch (64bit) so there's no OS version.
* As for the actual memory usage I don't have the exact number but it locks up my system with 8Gb of ram and no other applications are open. I will have to wait until next time it locks up to tell you in detail.

Thank you!

**Comment by petRUShka** [comment]
I confirm that behavior. After 24 hours (even of inactivity) it start to freeze and to slow down whole system. Only way to fix it is to close nuvola.

Arch linux 64 bit, nuvola stable 3.0.0

**Comment by fenryxo** [comment]
Thanks for your feedback. I need more information:

* Which streaming services do you use?
* Did this issue always occur or has it appeared just recently, e.g. after a system update?
* Could post outpu of following command?

```
top -n 1 -p `pidof nuvolaplayer3` -p `pidof apprunner` -p `pidof WebKitWebProcess` -p `pidof WebKitPluginProcess2`
```

**Comment by Celti** [comment]
Memory usage for me with nuvolaplayer-git and Google Play Music on Arch 64-bit is high but doesn't crash the system, maxing out at around 2.2GB total.

````
 4051 celti     20   0  828.4m  55.4m   0.0  0.3   0:00.62 S nuvolaplayer3
 4065 celti     20   0 3206.9m 105.0m   0.0  0.7   5:59.68 S  `- nuvolaplayer3-g
 4094 celti     20   0 5084.7m 1.284g   0.0  8.2  72:38.69 S WebKitWebProces
 4196 celti     20   0 3508.9m 732.2m   0.0  4.6  63:21.68 S WebKitPluginPro
````

**Comment by fenryxo** [comment]
It might be an issue in WebKitGtk. Is such a high memory usage also reproducible in Epiphany (GNOME Web) browser?

**Comment by Celti** [comment]
Memory usage between the two is comparable at startup; Epiphany's seems to rise at slightly a higher rate than NuvolaPlayer's does.

**Comment by fenryxo** [comment]
It is necessary to report the issue upstream. However, I don't have any virtual machine with the same WebKitGTK version as in Arch Linux to reproduce the issue. Could you go to the [WebKitGTK+ website](http://webkitgtk.org/) and report the bug via the link *File a bug* in the right sidebar?

**Comment by fenryxo** [comment]
This may be related: [What's new in the WebKitGTK+ 2.10.8 release?](https://lists.webkit.org/pipermail/webkit-gtk/2016-March/002646.html)
  - Limit the number of tiles according to the visible area. This was causing a huge memory
    consumption with some websites.
  - ...

**Comment by KruyKaze** [comment]
I just received this update : 
webkit2gtk             2.10.7-1   -> 2.10.8-1
Is that the same thing?

**Comment by fenryxo** [comment]
> webkit2gtk 2.10.7-1 -> 2.10.8-1. Is that the same thing?

Yes, it is.

**Comment by fenryxo** [comment]
> webkit2gtk 2.10.7-1 -> 2.10.8-1

Does it make any difference?

**Comment by KruyKaze** [comment]
After 18 days webkit was using 20% of my memory.
I reloaded now and it's using 5% and climbed up to 5.5% within a couple of minutes.
We'll see how big it will get in the next few days.
Thanks

**Comment by fenryxo** [comment]
Unfortunately, it's going to break again in WebKitGTK 2.10.9 (and  2.12.0). I recommend not upgrading for now.

> What's new in the WebKitGTK+ 2.10.9 release?  - Revert the patch to limit the number of tiles according to the visible area introduced in 2.10.8, because it caused rendering issues in several popular websites.

From the upstream bug [[GTK] Limit the number of tiles according to the visible area](https://bugs.webkit.org/show_bug.cgi?id=126122):

> I'm not longer able to reproduce this problem if I force AC [Accelerated Compositing] mode to be off. The usage of RAM don't grows out of normal. [...]

A work-around may be to [disable accelerated compositing](https://bugs.webkit.org/show_bug.cgi?id=154147) with `WEBKIT_DISABLE_COMPOSITING_MODE` environment variable in WebKitGTK 2.12.0.

**Comment by KruyKaze** [comment]
I don't know if this is still an issue but if I upgrade now , will I have high mem usage or will nuvola stop working?

**Comment by fenryxo** [comment]
The high memory usage will probably be back if you upgrade to WebKitGtk 2.10.9 or 2.12.0.

**Comment by KruyKaze** [comment]
But nuvola won't stop working?

**Comment by fenryxo** [comment]
Hopefully not.

**Comment by fenryxo** [comment]
Hello everybody, any update on this issue or may I close it?

**Comment by Celti** [comment]
Been running for two days solid on my machine, memory usage hasn't climbed above 1.5GB, a full half of that being the WebKitPluginProcess (using libfreshplayer and Pepper Flash). I suspect HTML5 would solve everyone's problems for this issue.

**Comment by fenryxo** [comment]
>  I suspect HTML5 would solve everyone's problems for this issue.

HTML5 Audio in Google Play Music works in Nuvola Player 3.1 in Ubuntu 14.04, 15.10 and 16.04, Debian Jessie and Fedora 23 with my account without All Access subscription. I'm going to check also Ubuntu 15.04, Fedora 22 and Arch Linux later. Subscribe to the issue #91 if you would like to be informed about details.

I'm closing this ticket as an upstream issue that seems to have been resolved
