### ISSUE TITLE
Compiling with libappindicator is broken

### ISSUE THREAD

**Issue by susnux** [tiliado/nuvolaplayer#201]
Using the 3.0.0 release compiling with: --with-appindicator does not work.
It crashes with the following error.

System: openSUSE Leap 42.1 64bit

    [  104s] Loaded package `/usr/share/vala/vapi/appindicator3-0.1.vapi'
    [  104s] Compilation failed: 1 error(s), 3 warning(s)
    [  104s] /home/abuild/rpmbuild/BUILD/nuvolaplayer-3.0.0/src/nuvolakit-runner/webkit/WebEngine.vala:457.13-457.28: warning: WebKit.NavigationPolicyDecision.request has been deprecated since 2.6
    [  104s] /home/abuild/rpmbuild/BUILD/nuvolaplayer-3.0.0/src/nuvolakit-runner/webkit/WebEngine.vala:463.14-463.37: warning: WebKit.NavigationPolicyDecision.navigation_type has been deprecated since 2.6
    [  104s] /home/abuild/rpmbuild/BUILD/nuvolaplayer-3.0.0/src/nuvolakit-runner/components/trayicon/TrayIcon.vala:69.4-69.23: error: The name `path_name' does not exist in the context of `Nuvola.AppRunnerController'
    [  104s] 			controller.path_name, controller.icon, AppIndicator.IndicatorCategory.APPLICATION_STATUS);
    [  104s] 			^^^^^^^^^^^^^^^^^^^^
    [  104s] /home/abuild/rpmbuild/BUILD/nuvolaplayer-3.0.0/src/nuvolakit-runner/gui/WelcomeWindow.vala:148.13-148.28: warning: WebKit.NavigationPolicyDecision.request has been deprecated since 2.6
    [  104s] Waf: Leaving directory `/home/abuild/rpmbuild/BUILD/nuvolaplayer-3.0.0/build'
    [  104s] Build failed
    [  104s]  -&gt; task in 'nuvolaplayer3-runner' failed (exit status 1): 
    [  104s] 	{task 70367006702544: valac AppRunnerController.vala,MasterController.vala,ActionsBinding.vala,Binding.vala,Bindings.vala,LauncherBinding.vala,MediaKeysBinding.vala,MediaPlayerBinding.vala,MenuBarBinding.vala,NotificationBinding.vala,NotificationsBinding.vala,Component.vala,ComponentsManager.vala,WebApp.vala,WebAppRegistry.vala,WebAppStorage.vala,WebAppWindow.vala,WebWorker.vala,FormatSupport.vala,FormatSupportCheck.vala,FormatSupportDialog.vala,AboutDialog.vala,NetworkSettings.vala,PreferencesDialog.vala,Sidebar.vala,WelcomeWindow.vala,ActionsInterface.vala,MediaKeysInterface.vala,MenuBarInterface.vala,NotificationInterface.vala,NotificationsInterface.vala,AppRunner.vala,LauncherModel.vala,MediaPlayerModel.vala,Connection.vala,Desktop.vala,TiliadoAccount.vala,TiliadoAccountForm.vala,TiliadoApi.vala,AppCategoriesView.vala,WebAppListFilter.vala,WebAppListModel.vala,WebAppListView.vala,WebAppListWindow.vala,WebEngine.vala,WebView.vala,WebWindow.vala,ActionsHelper.vala,DeveloperComponent.vala,DeveloperSidebar.vala,ActionsKeyBinder.vala,ActionsKeyBinderClient.vala,ActionsKeyBinderServer.vala,GlobalActionsKeyBinder.vala,GlobalKeyBinder.vala,GlobalKeyBindings.vala,KeybindingsSettings.vala,XKeyGrabber.vala,AZLyricsFetcher.vala,LyricsComponent.vala,LyricsFetcher.vala,LyricsFetcherCache.vala,LyricsProvider.vala,LyricsSidebar.vala,MediaKeyClient.vala,MediaKeyServer.vala,MediaKeys.vala,MediaPlayer.vala,Menubar.vala,MPRISApplication.vala,MPRISComponent.vala,MPRISPlayer.vala,MPRISProvider.vala,Notifications.vala,NotificationsComponent.vala,AudioScrobbler.vala,AudioScrobblerComponent.vala,LastfmCompatibleScrobbler.vala,LastfmScrobbler.vala,ScrobblerSettings.vala,TrayIcon.vala,TrayIconComponent.vala,UnityLaucher.vala,UnityLauncherComponent.vala -&gt; nuvolaplayer3-runner.h,nuvolaplayer3-runner.vapi,nuvolaplayer3-runner.deps,AppRunnerController.c,MasterController.c,ActionsBinding.c,Binding.c,Bindings.c,LauncherBinding.c,MediaKeysBinding.c,MediaPlayerBinding.c,MenuBarBinding.c,NotificationBinding.c,NotificationsBinding.c,Component.c,ComponentsManager.c,WebApp.c,WebAppRegistry.c,WebAppStorage.c,WebAppWindow.c,WebWorker.c,FormatSupport.c,FormatSupportCheck.c,FormatSupportDialog.c,AboutDialog.c,NetworkSettings.c,PreferencesDialog.c,Sidebar.c,WelcomeWindow.c,ActionsInterface.c,MediaKeysInterface.c,MenuBarInterface.c,NotificationInterface.c,NotificationsInterface.c,AppRunner.c,LauncherModel.c,MediaPlayerModel.c,Connection.c,Desktop.c,TiliadoAccount.c,TiliadoAccountForm.c,TiliadoApi.c,AppCategoriesView.c,WebAppListFilter.c,WebAppListModel.c,WebAppListView.c,WebAppListWindow.c,WebEngine.c,WebView.c,WebWindow.c,ActionsHelper.c,DeveloperComponent.c,DeveloperSidebar.c,ActionsKeyBinder.c,ActionsKeyBinderClient.c,ActionsKeyBinderServer.c,GlobalActionsKeyBinder.c,GlobalKeyBinder.c,GlobalKeyBindings.c,KeybindingsSettings.c,XKeyGrabber.c,AZLyricsFetcher.c,LyricsComponent.c,LyricsFetcher.c,LyricsFetcherCache.c,LyricsProvider.c,LyricsSidebar.c,MediaKeyClient.c,MediaKeyServer.c,MediaKeys.c,MediaPlayer.c,Menubar.c,MPRISApplication.c,MPRISComponent.c,MPRISPlayer.c,MPRISProvider.c,Notifications.c,NotificationsComponent.c,AudioScrobbler.c,AudioScrobblerComponent.c,LastfmCompatibleScrobbler.c,LastfmScrobbler.c,ScrobblerSettings.c,TrayIcon.c,TrayIconComponent.c,UnityLaucher.c,UnityLauncherComponent.c}
    [  104s] ''

**Comment by fenryxo** [comment]
Hello @susnux. Thanks for reporting this issue. The AppIndicator integration is currently unmaintained, but may be reintroduced in the future (tiliado/nuvolaplayer#45). I've removed the `--with-appindicator` option for now.

Changes landed in the git *master* & *3.0.x* branches of [Nuvola Player](https://github.com/tiliado/nuvolaplayer). The fix will be released in **Nuvola Player 3.0.1** (Nuvola Player 3.0 Stable Releases) and a next rebuild of **Nuvola Player 3.1.x** (Nuvola Player 3.1 Rolling Releases). To get informed when Nuvola Player 3.0.1 is released,

  * follow Nuvola Player on [Facebook](https://www.facebook.com/nuvolaplayer),
    [Google+](https://plus.google.com/110794636546911932554) or
    [Twitter](https://twitter.com/NuvolaPlayer).
  * subscribe to the Nuvola Player Newsletter: [weekly](http://eepurl.com/bLbm5H)
    or [monthly](http://eepurl.com/bLbtM1).

**Comment by susnux** [comment]
Ok thank you for the answer.
