### ISSUE TITLE
Not connecting to Spotify

### ISSUE THREAD

**Issue by bloema7** [tiliado/nuvolaplayer#211]
The Spotify app loads but it doesn't connect and ends up hanging, while still loading and loading and loading...

**Comment by fenryxo** [comment]
Hello @bloema7. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Your distribution, architecture and version.
* Version of Nuvola Player.
* Debugging output from terminal as described

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by bloema7** [comment]
Hi there,

I am running the latest version of Ubuntu 15.10.. Version of player is 3.0

On Mon, Mar 7, 2016 at 6:08 PM, Jiří Janoušek <notifications@github.com>
wrote:

> Hello @bloema7 <https://github.com/bloema7>. Thanks for taking the time
> to report your issue. I need more information to investigate it further:
>
>    - Your distribution, architecture and version.
>    - Version of Nuvola Player.
>    - Debugging output from terminal as described
>
> See Bug Reporting Guidelines
> <https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines>
> for details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiliado/nuvolaplayer/issues/211#issuecomment-193189812>
> .
>



-- 
Kind Regards

Will Bloem

**Comment by bloema7** [comment]
Hi there,

I am running the latest version of Ubuntu 15.10.. Version of player is 3.0

(sorry hit the sent button) Thanks for the great player..I reinstalled it
and works again for me ..

Thanks

Will

On Mon, Mar 7, 2016 at 6:08 PM, Jiří Janoušek <notifications@github.com>
wrote:

> Hello @bloema7 <https://github.com/bloema7>. Thanks for taking the time
> to report your issue. I need more information to investigate it further:
>
>    - Your distribution, architecture and version.
>    - Version of Nuvola Player.
>    - Debugging output from terminal as described
>
> See Bug Reporting Guidelines
> <https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines>
> for details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiliado/nuvolaplayer/issues/211#issuecomment-193189812>
> .
>



-- 
Kind Regards

Will Bloem

**Comment by fenryxo** [comment]
> I reinstalled it and works again for me ..

OK, I'm closing this issue then. Happy listening :-)
