### ISSUE TITLE
Tiliado Repositories unable to Download on Nuvola Side /Ubuntu 15.10 wily/ pi2 B

### ISSUE THREAD

**Issue by Nikocs** [tiliado/nuvolaplayer#220]
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
Raspberry pi2 B

+ ['/usr/bin/tiliado-repositories', '-d', 'ubuntu', '-r', 'wily', '-v', 'stable', '-p', 'nuvolaplayer', '-i', 'nuvolaplayer3', '--server', 'tiliado.eu', '--protocol', 'https']
+ ['apt-get', 'remove', '-y', 'nuvolaplayer3']
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
E: Paket nuvolaplayer3 kann nicht gefunden werden.
Command '['apt-get', 'remove', '-y', 'nuvolaplayer3']' returned non-zero exit status 100
+ ['apt-key', 'adv', '--keyserver', 'hkp://keyserver.ubuntu.com:80', '--recv-keys', '40554B8FA5FE6F6A']
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.2iTdZNctyk --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/flexiondotorg_ubuntu_minecraft.gpg --keyring /etc/apt/trusted.gpg.d/pipelight_ubuntu_stable.gpg --keyring /etc/apt/trusted.gpg.d/ubuntu-pi-flavour-makers_ubuntu_ppa.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 40554B8FA5FE6F6A
gpg: requesting key A5FE6F6A from hkp server keyserver.ubuntu.com
gpg: key A5FE6F6A: "Jiří Janoušek <janousek.jiri@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ [makedirs '/etc/apt/sources.list.d']
+ [write '/etc/apt/sources.list.d/tiliado-nuvolaplayer.list']
deb https://tiliado.eu/nuvolaplayer/repository/deb/ wily stable # nuvolaplayer (stable)

+ ['apt-get', 'update']
OK   http://ports.ubuntu.com wily InRelease
OK   http://ports.ubuntu.com wily-updates InRelease
OK   http://ppa.launchpad.net wily InRelease
OK   http://ppa.launchpad.net wily InRelease
OK   http://ports.ubuntu.com wily-security InRelease
...
OK   https://tiliado.eu wily InRelease
...
OK   http://ports.ubuntu.com wily/universe Translation-de
OK   http://ports.ubuntu.com wily/universe Translation-en
W: Fehlschlag beim Holen von https://tiliado.eu/nuvolaplayer/repository/deb/dists/wily/InRelease  Erwarteter Eintrag »stable/binary-armhf/Packages« konnte in Release-Datei nicht gefunden werden (falscher Eintrag in sources.list oder missgebildete Datei).

E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

Warning: Database update command failed, probably because of broken repositories in your APT sources lists. Error code:
+ ['apt-get', 'install', '-y', 'nuvolaplayer3']
Paketlisten werden gelesen...
Abhängigkeitsbaum wird aufgebaut....
Statusinformationen werden eingelesen....
E: Paket nuvolaplayer3 kann nicht gefunden werden.
Subprocess Error: Command '['apt-get', 'install', '-y', 'nuvolaplayer3']' returned non-zero exit status 100
+ [Return code = 4]

Thanks for any answer

**Comment by fenryxo** [comment]
Hello @Nikocs. I'm sorry but Nuvola Player repository provides packages only for i386 and amd64 architectures, not for armhf. Tiliado Repositories Installer should show a warning - I've created a ticket for that (tiliado/tiliado-repositories#8).
