### ISSUE TITLE
Code review: Google Keep integration

### ISSUE THREAD

**Issue by fastcat** [tiliado/nuvolaplayer#222]
fastcat/nuvola-app-google-keep#1

I've made basic changes to the google calendar app integration to become a google keep integration.
##

**Comment by fastcat** [comment]
I've noticed an issue while testing this, which I presume applies equally to the calendar integration on which I based it -- despite not being a "media" app, it is registering for the global media hotkeys from the gnome environment, which means that if I launch this app after I launch my normal media app, keep will eat the media hotkeys.  Looking into how I might fix this...

**Comment by fenryxo** [comment]
Hello @fastcat. Could you [create a bug report](https://github.com/tiliado/nuvolaplayer/issues/new) for me to look at the global media hotkeys issue. Thanks.

**Comment by fastcat** [comment]
Submitted #230 for the global hotkeys issue

**Comment by fenryxo** [comment]
Thanks @fastcat. I'll go through the code review after #230 is fixed. Is it ok?

**Comment by fastcat** [comment]
Sure, no problem
