### ISSUE TITLE
Flash Player not found in Fedora 23

### ISSUE THREAD

**Issue by jla1** [tiliado/nuvolaplayer#223]
Nuvola 3.0.1 018a1322200541ee7c37 doesn't find Flash Player in Fedora 23 with Cinnamon DE. I followed the instructions and "locate flash-plugin" shows:                       
/usr/lib64/flash-plugin
/usr/lib64/flash-plugin/LICENSE
/usr/lib64/flash-plugin/README
/usr/lib64/flash-plugin/homecleanup
/usr/lib64/flash-plugin/libflashplayer.so
/usr/lib64/flash-plugin/setup
/usr/share/doc/flash-plugin-11.2.202.616
/usr/share/doc/flash-plugin-11.2.202.616/LGPL.txt
/usr/share/doc/flash-plugin-11.2.202.616/notice.txt
/usr/share/doc/flash-plugin-11.2.202.616/readme.txt

**Comment by fenryxo** [comment]
Hello @jla1. Thanks for taking the time to report your issue. I need more information to investigate it further though. 

* Which instructions have you followed?
* Could you attach a debugging output from a terminal with any streaming service that requires the flash plugin?

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by jla1** [comment]
The ones here: http://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html#fedora

Debugging output: http://pastebin.com/ww0Huxhm

**Comment by fenryxo** [comment]
Thanks for the log. The following line looks suspicious as it didn't definitely occur last time I tested NP in Fedora 23. I'll try to find out what has changed since then.

`Runner: Failed to launch /usr/libexec/webkit2gtk-4.0/WebKitPluginProcess2: Failed to execute child process "/usr/libexec/webkit2gtk-4.0/WebKitPluginProcess2" (No such file or directory)`

**Comment by fenryxo** [comment]
Could you try to install the `webkitgtk4-plugin-process-gtk2` package?

**Comment by jla1** [comment]
Yup, that did it. Works now. Thanks.

**Comment by fenryxo** [comment]
Great. I'll update package dependencies to include also that package.

**Comment by fenryxo** [comment]
Fixed in Nuvola Player 3.0.2 Stable Release and in Nuvola Player 3.1 Rolling Releases.
