### ISSUE TITLE
Blank page on startup of Google Play Music

### ISSUE THREAD

**Issue by alekstar** [tiliado/nuvolaplayer#228]
On Ubuntu 16.04, Google Play Music 5.12, Nuvola Player 3.0.1. It often appears a blank page (nothing is showing) on startup of Google Play Music. Nothing is happening and nothing is loading. Pushing the "Home" and "Refresh" buttons does not help. This bug is floating (it means, that it repeats not every time).

This is how the window of Google Play Music looks:
![google play music issue](https://cloud.githubusercontent.com/assets/4435537/15136503/d3f26c12-168a-11e6-8430-97fde2cc3ec9.png)

**Comment by alekstar** [comment]
On a 10th time of pushing "Refresh" button and "Home" button the Google Play Music becomes to loading in that window.

**Comment by fenryxo** [comment]
> Google Play Music 5.12, Nuvola Player 3.0.1

Hello. These versions are old. Please upgrade to 5.13 and 3.0.2. Feel free to reopen this ticket if the issue still persists after the upgrade.
