### ISSUE TITLE
Non-media apps eat global media hotkeys

### ISSUE THREAD

**Issue by fastcat** [tiliado/nuvolaplayer#230]
Non-media app instances of nuvolaplayer still "eat" global hotkeys.

Prerequisites / Setup
- Prepare a media app instance of nuvolaplayer (I used Google Music)
- Prepare a non-media app instance of nuvolaplayer (I tried both the distributed Google Calendar and my Google Keep fork of that) -- note that it implements the basic `Nuvola.$WebApp`, there is no `Nuvola.MediaPlayer`
- Have a third window for some other app handy (I used Gnome Terminal)

Test process:
1. Launch both nuvolaplayer apps
2. Focus the media nuvolaplayer app, then focus the non-nuvolaplayer app
3. Try a global media hotkey -- it works
4. Focus the non-media nuvolaplayer app, then focus the non-nuvolaplayer app
5. Try a global media hotkey -- it doesn't work

**Comment by fenryxo** [comment]
Hello. The MediaPlayer and MediaKeys components are currently automatically loaded and activated and each Nuvola app claims to be a media player as a result. This should be changed as follows:

1. Load a particular component if it is enabled in preferences (e.g. notifications) or always enabled (media player), but don't activate it
2. Activate a particular component only if requested by a script (e.g. when `Nuvola.MediaPlayer` object is created)

**Comment by fenryxo** [comment]
Components now have two states
1. Enabled (true/false): If true, a component is loaded and can be activated later. This state corresponds to an on/off switch in the Preferences dialog.
2. Active (true/false): If true, a component is allowed to do its job. Components are activated upon load by default but mpris, lyrics, mediakeys and scrobbler are activated only after MediaPlayer instance is created by an web app script.

**Comment by fenryxo** [comment]
**This issue has been fixed in the [master branch](https://github.com/tiliado/nuvolaplayer) and will be available with the next rebuilding of  packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html). Thanks for making Nuvola Player better by filing bug reports.**
