### ISSUE TITLE
Problem with Flash in Nuvola Player 3.0.2 on Ubuntu 16.04

### ISSUE THREAD

**Issue by progressor2009** [tiliado/nuvolaplayer#231]
I have a program Nuvola Player problems
My OS: 
Ubuntu-Mate 16.04 x64
Nuvola Player Stable 3.0.2

Original player Google Play Music in firefox works fine:
[screen](http://storage5.static.itmages.com/i/16/0518/h_1463562207_1344386_7975397e62.png)

But, unfortunately, Nuvola player does not work:
"No Flash plugins have been found."
[screen](http://storage9.static.itmages.com/i/16/0518/h_1463562275_2693930_c072cc65d4.png)

**Comment by fenryxo** [comment]
Hello. Thanks for taking the time to report your issue. I need more information to investigate it further:

* Debugging output from terminal.
* The output of a command `ls -l /usr/lib/mozilla/plugins`.

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by progressor2009** [comment]
[ls -l /usr/lib/mozilla/plugins](http://storage9.static.itmages.com/i/16/0518/h_1463566305_2439041_4c79b264ce.png)

**Comment by fenryxo** [comment]
Please post both outputs as text not as images. Also, the debugging output seems to be incomplete.

**Comment by progressor2009** [comment]
> gordeev@book-gordeev:~$ ls -l /usr/lib/mozilla/plugins
итого 8
lrwxrwxrwx 1 root root 37 май 15 13:18 flashplugin-alternative.so -> /etc/alternatives/mozilla-flashplugin
lrwxrwxrwx 1 root root 39 май 13 17:36 libjavaplugin.so -> /etc/alternatives/mozilla-javaplugin.so
gordeev@book-gordeev:~$ 


run nuvolaplayer3

> gordeev@book-gordeev:~$ nuvolaplayer3
Master: [WARNING    Gtk] Theme parsing error: gtk-main.css:69:33: Failed to import: Произошла ошибка при открытии файла: No such file or directory


then run google play music

> Runner: [WARNING    Gtk] Theme parsing error: gtk-main.css:69:33: Failed to import: Произошла ошибка при открытии файла: Нет такого файла или каталога
Runner: [WARNING    Gtk] Theme parsing error: gtk-main.css:69:33: Failed to import: Произошла ошибка при открытии файла: Нет такого файла или каталога
Runner: [WARNING  GLib-GObject] g_object_set_property: construct property "local-storage-directory" for object 'WebKitWebContext' can't be set after construction
Runner: 
(WebKitWebProcess:7323): Gtk-WARNING **: Theme parsing error: gtk-main.css:69:33: Failed to import: Произошла ошибка при открытии файла: Нет такого файла или каталога
Worker: [DEBUG    Nuvola] WebExtension.vala:242: Page 1 created for (null)
Worker: [DEBUG    Nuvola] WebExtension.vala:192: Waiting until initialized
Runner: [WARNING  Nuvola] FormatSupportCheck.vala:152: No Flash plugin has been found.
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Worker: [DEBUG    Nuvola] WebExtension.vala:136: Window object cleared for 'https://get.adobe.com/ru/flashplayer/'
Worker: [DEBUG    Nuvola] WebExtension.vala:144: Init frame: https://get.adobe.com/ru/flashplayer/, 0x7ff3a000ac70, 0x55fdddb70ba0, 0x7ff3c020f740
Runner: https://wwwimages2.adobe.com/downloadcenter/js/live/polarbear.js:36:21: CONSOLE LOG  value=Flash_Player_11.2_for_other_Linux_(.tar.gz)_64-bit

**Comment by fenryxo** [comment]
Oh, I haven't noticed that you forgot to add `--debug` flag  (as specified in  [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)) to get a complete debugging output. Could you post a complete debugging output by running `nuvolaplayer3 --debug`?

**Comment by progressor2009** [comment]
Ok.
start nuvolaplayer

> nuvolaplayer3 --debug
Master: [WARNING    Gtk] Theme parsing error: gtk-main.css:69:33: Failed to import: Произошла ошибка при открытии файла: No such file or directory
Master: [DEBUG      Gtk] Connecting to session manager
Master: [DEBUG    DioriteGtk] DesktopShell.vala:96: Shell: metacity (marco) (null), CSD 0, appmenu 0, menubar 0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.13
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Groove at /usr/share/nuvolaplayer3/web_apps/groove, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SoundCloud at /usr/share/nuvolaplayer3/web_apps/soundcloud, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_8tracks 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_amazon_cloud_player 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_bandcamp 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_deezer 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_jango 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_kexp 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_logitech_media_server 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_mixcloud 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_plex 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_spotify 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_test 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_tunein 48 not found.
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_yandex_music 48 not found.
Master: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager

and run Google Play Music

> Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.13
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Groove at /usr/share/nuvolaplayer3/web_apps/groove, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SoundCloud at /usr/share/nuvolaplayer3/web_apps/soundcloud, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.0
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.1
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [INFO     Nuvola] WebAppRegistry.vala:89: Using web app Google Play Music, version 5.13, data dir /usr/share/nuvolaplayer3/web_apps/google_play_music
Master: [DEBUG    Nuvola] MasterController.vala:463: Launch app runner for 'google_play_music': /usr/lib/nuvolaplayer3/apprunner -D -a /usr/share/nuvolaplayer3/web_apps/google_play_music 
Runner: [WARNING    Gtk] Theme parsing error: gtk-main.css:69:33: Failed to import: Произошла ошибка при открытии файла: Нет такого файла или каталога
Runner: [DEBUG      Gtk] Connecting to session manager
Runner: [DEBUG    DioriteGtk] DesktopShell.vala:96: Shell: metacity (marco) (null), CSD 0, appmenu 0, menubar 0
Runner: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
Master: [DEBUG    Nuvola] MasterController.vala:287: Connected to runner server for 'google_play_music'.
Runner: [WARNING    Gtk] Theme parsing error: gtk-main.css:69:33: Failed to import: Произошла ошибка при открытии файла: Нет такого файла или каталога
Runner: [DEBUG    Nuvola] Connection.vala:132: Network Proxy: system settings
Runner: [DEBUG    Nuvola] WebEngine.vala:69: Nuvola WebKit Extension directory: /usr/lib/nuvolaplayer3
Runner: [WARNING  GLib-GObject] g_object_set_property: construct property "local-storage-directory" for object 'WebKitWebContext' can't be set after construction
Runner: 
(WebKitWebProcess:6160): Gtk-WARNING **: Theme parsing error: gtk-main.css:69:33: Failed to import: Произошла ошибка при открытии файла: Нет такого файла или каталога
Runner: [DEBUG    Nuvola] Notifications.vala:175: Notifications: persistence false, actions true, icons false
Master: [DEBUG    Nuvola] MediaKeys.vala:130: GNOME settings daemon vanished: org.gnome.SettingsDaemon
Runner: [DEBUG    Nuvola] MPRISProvider.vala:73: Bus acquired: org.mpris.MediaPlayer2.NuvolaAppGooglePlayMusic, registering objects
Runner: [DEBUG    Nuvola] MPRISProvider.vala:90: Bus name acquired: org.mpris.MediaPlayer2.NuvolaAppGooglePlayMusic
Worker: [DEBUG    Nuvola] WebExtension.vala:242: Page 1 created for (null)
Runner: [DEBUG    Nuvola] WebEngine.vala:467: Navigation, current window: uri = https://get.adobe.com/ru/flashplayer/, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
Worker: [DEBUG    Nuvola] WebExtension.vala:192: Waiting until initialized
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Trying to play /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from NULL to READY.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from READY to PAUSED.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from PAUSED to PLAYING.
Runner: [DEBUG    Nuvola] FormatSupport.vala:103: End of stream for file /usr/share/nuvolaplayer3/audio/audiotest.mp3.
Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Java(TM) Plug-in 10.80.2 (enabled, not flash) at /usr/lib/mozilla/plugins/libjavaplugin.so: Next Generation Java Plug-in 10.80.2 for Mozilla browsers
Runner: [WARNING  Nuvola] FormatSupportCheck.vala:152: No Flash plugin has been found.
Runner: [DEBUG    Nuvola] WebAppWindow.vala:170: Sidebar position: 934
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5c1f40
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5c2d40
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5c3200
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5fd840
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5a5280
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5c2e00
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5c3240
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5c2ca0
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5a5280
Runner: [DEBUG     Json] Copying immutable JsonNode 0x55ecdb5fd840
Runner: [INFO     Nuvola] AppRunnerController.vala:236: Logged in as  ()
Worker: [DEBUG    Nuvola] WebExtension.vala:136: Window object cleared for 'https://get.adobe.com/ru/flashplayer/'
Worker: [DEBUG    Nuvola] WebExtension.vala:144: Init frame: https://get.adobe.com/ru/flashplayer/, 0x562ef601b500, 0x562ef5e65460, 0x7fce7e4c3740
Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
Runner: https://wwwimages2.adobe.com/downloadcenter/js/live/polarbear.js:36:21: CONSOLE LOG  value=Flash_Player_11.2_for_other_Linux_(.tar.gz)_64-bit
Runner: [DEBUG    Nuvola] WebEngine.vala:467: Navigation, current window: uri = https://get3.adobe.com/util/pal/read/, result = false, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER

**Comment by fenryxo** [comment]
It looks as if the `libwebkit2gtk-4.0-37-gtk2` package wasn't installed. Could you install it and try again?

**Comment by progressor2009** [comment]
Thank you. It really helped.

**Comment by fenryxo** [comment]
Great. I'll update package dependencies to avoid this problem in the future #232.
