### ISSUE TITLE
Fedora 23 : Failed to synchronize cache for repo 'tiliado-nuvolaplayer'

### ISSUE THREAD

**Issue by didli** [tiliado/nuvolaplayer#234]
I get this message each time I'm trying to update nuvolaplayer repo for Fedora 23. Maybe the repo might miss repodata/repomd.xml files ? (not sure about this, just guessing).

**Comment by fenryxo** [comment]
Hello @didli. Thanks for taking the time to report this issue. I need more information to investigate it further.

* Which repository do you use? 3.0 Stable Releases or 3.1 Rolling Releases?
* How have you installed the repository? Manually or using Tiliado Repository Installer?
* Where exactly is the error message shown?

**Comment by didli** [comment]
I followed the instructions here : http://tiliado.github.io/nuvolaplayer/documentation/3.0/install.html#fedora. But from your answer here, I realized I didn't tried the installer yet (i added the repo manually in /etc/yum.repo.d/), so I picked it up a few minutes ago and it worked just fine. I suppose the difference lies in the 'anonymous access' thingy ^^ ? Anyway thanks for your fast answer and your help, nuvola seems great ^^
