### ISSUE TITLE
Google Play Music rendering errors on new install only

### ISSUE THREAD

**Issue by Celti** [tiliado/nuvolaplayer#235]
On a new install (that is, no configuration or cache remaining from any previous version) of the latest versions of all involved packages (on Arch: `diorite-git 0.2.0.r20.g885d3e6-2` `nuvolaplayer-git 3.0.0.r38.g4d5feb9-1` `nuvola-app-google-play-git 5.14.r0.gf873e82-1`) I'm left with rendering errors for Google Play Music with All Access.

The debug log is here: [google_play_music_debug_log.txt](https://github.com/tiliado/nuvolaplayer/files/277474/google_play_music_debug_log.txt)

A screenshot of the Welcome screen in NuvolaPlayer: ![2016-05-23 05:36:21.png](https://cloud.githubusercontent.com/assets/4999146/15471091/0be07132-20a9-11e6-86c4-152691714fa4.png)
A screenshot of the sign-in screen in NuvolaPlayer: ![2016-05-23 05:36:29](https://cloud.githubusercontent.com/assets/4999146/15471092/0be1855e-20a9-11e6-9e78-f62fdd675332.png)
A screenshot of the main Music screen in NuvolaPlayer: ![2016-05-23 05:37:00](https://cloud.githubusercontent.com/assets/4999146/15471094/0be5ab3e-20a9-11e6-8847-cd6273b63932.png)

Finally, it looks like the error-causing content is the Google “app switcher” and G+ notifications widgets in the toolbar, judging by the icon in the error content and their visibility in Google Play Music on Chromium: ![2016-05-23 05:38:22](https://cloud.githubusercontent.com/assets/4999146/15471093/0be21000-20a9-11e6-8a5b-6a5ad6279b6c.png)

**Comment by fenryxo** [comment]
Hello @Celti. Thanks for taking the time to report this issue.

> Arch: diorite-git 0.2.0.r20.g885d3e6-2 nuvolaplayer-git 3.0.0.r38.g4d5feb9-1 nuvola-app-google-play-git 5.14.r0.gf873e82-1

These versions are old. Could you upgrade to Diorite 0.2.1 and Nuvola Player 3.0.2 and check whether the issue persists?

**Comment by Celti** [comment]
Diorite and NuvolaPlayer are the latest revisions you have on GitHub. The format for those package versions is: `<latest git tag>.r<number of revisions since tag>.g<HEAD commit hash>-<PKGBUILD revision>` — those are the latest commits for everything except nuvola-app-google-play-git, which obviously I didn't rebuild as I thought I did. Fixing now, will let you know how it goes.

**Comment by Celti** [comment]
And the problem persists identically with the latest revision of nuvola-app-google-play-music: screenshots identical, new log at 
[google_play_music_debug_log.txt](https://github.com/tiliado/nuvolaplayer/files/277597/google_play_music_debug_log.txt)

**Comment by fenryxo** [comment]
> The format for those package versions is: `<latest git tag>.r<number of revisions since tag>.g<HEAD commit hash>-<PKGBUILD revision>`

Oh, is it possible to make the packages have proper version numbers (Diorite 0.3.0 and Nuvola 3.1.0)?

**Comment by Celti** [comment]
If the version number of git releases is particularly important, I have a counter-question: perhaps there should be git tags indicating that? If you tagged master with, say, 0.3-dev and 3.1-dev, the automatic versioning the Arch PKGBUILDs use would pick that up, *plus* it would make it more obvious to anyone looking at the repository as to what version master is working towards (i.e., progressing towards 0.3.0 and 3.1.0).

**Comment by fenryxo** [comment]
Ok, I've created tags tiliado/nuvolaplayer@3.1.0 tiliado/diorite@0.3.0. There is no need for `-dev` suffix as the stable releases will be 3.2.0 and 0.4.0.

**Comment by Celti** [comment]
Perfect! I'll iron out the PKGBUILDs I have in the AUR — rather, I already have them ironed out locally. I'll push them once I'm finished with my current project, which is a build automation system for Nuvola Player packages for Arch Linux, plus an associated package repository.

**Comment by fenryxo** [comment]
There are two syntax errors and a few warning that may cause the incorrect rendering. No idea why it happends in Nuvola and not in Chrome.

```
Runner: https://play.google.com/music/listen:32:
 CONSOLE ERROR SyntaxError: Unexpected identifier 'html'
Runner: https://play-music.gstatic.com/fe/eeed7e9b2e3f4962b5be7d21031f27d0/sj_srcs.js:22187:13:
 CONSOLE WARN This file is deprecated. Please use iron-flex-layout/iron-flex-layout-classes.html, and one of the specific dom-modules instead
https://play-music.gstatic.com/fe/eeed7e9b2e3f4962b5be7d21031f27d0/sj_srcs.js:22188:13:
 CONSOLE WARN This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
Runner: https://play.google.com/music/listen?utm_medium=signed_out_warm_welcome&welcome=0:29:
 CONSOLE ERROR SyntaxError: Unexpected token '<'
https://play-music.gstatic.com/fe/eeed7e9b2e3f4962b5be7d21031f27d0/sj_srcs.js:22188:13:
 CONSOLE WARN This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
```

**Comment by Celti** [comment]
Well, if there's any other info or testing I can provide, let me know!

**Comment by fenryxo** [comment]
Is the issue reproducible in WebKitGTK+ MiniBrowser (a part of WebKitGTK+, but may not be built by your distribution) or GNOME Web browser (Epiphany)?

**Comment by fenryxo** [comment]
Hello. I'm closing this issue as I haven't received any response to my request for more information I posted on August 12th, 2016. If the issue still persists, feel free to add missing information and reopen this ticket.
