### ISSUE TITLE
Add Wayland support

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#240]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Support running under Wayland natively.

## Details from the reporter

Nuvola Player currently requires Xorg for complete functionality. These features are X-dependent and don't work under Wayland
- ~~Flash plugin~~ no longer supported
- Global keyboard shortcuts
- Legacy tray icon
- ~~Detection of window managers to enable client side decorations~~ no longer used
- ~~Chromium Embedded Framework~~ - Nuvola will be ported to QtWebEngine.

**Comment by fenryxo** [comment]
:heart: **A [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this feature.** As a result, the ticket has been moved from the "postponed" queue to the "ready" queue and the "patron" label has been attached.

**Comment by fenryxo** [comment]
Detection of window managers to enable client side decorations no longer uses X11 in flatpak builds.

**Comment by fenryxo** [comment]
[CEF on Wayland](https://blog.kov.eti.br/2017/12/cef-on-wayland/)

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
