### ISSUE TITLE
Amazon player asks for Flash player when one already exists

### ISSUE THREAD

**Issue by hexmode** [tiliado/nuvolaplayer#244]
I have successfully installed and the pepperflash-nonfree (for Chromium or Epiphany) and the pipelight's Wine wrapper for flash (for Firefox and Epiphany) so that I have recent flash versions working.

I've verified this by playing in the browser from https://amazonmusic.com/.

However when I install nuvoplayer3-amazon-cloud-player (5.1-2-jessie), I'm told that I need an updated flash plugin.

**Comment by fenryxo** [comment]
Hello @hexmode. Thanks for taking the time to report your issue. I need more information to investigate it further:

* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output).
* A screenshot of the error message asking for a Flash upgrade.
* A screenshot of the Format Support Dialog's Web Plugins tab (App Menu → Format support).

**Comment by fenryxo** [comment]
Hello @hexmode. I'm closing this issue as I haven't received any response to my request for more information I posted on July 29th, 2016. If the issue still persists, feel free to add missing information and reopen this ticket.
