### ISSUE TITLE
Nuvolaplayer is deleting and recreating .desktop file on every launch

### ISSUE THREAD

**Issue by CrazyLemon** [tiliado/nuvolaplayer#248]
So currently nuvolaplayer deletes and recreates nuvolaplayer3-soundcloud.desktop file. 
So lets say i wanna set an env before launching the nuvolaplayer because of #245 i currently can't do it because every single time you open nuvolaplayer  deletes/rewrites/recreates the file making it impossible to make any changes to it. 
You can easily check that by 
`ls -l ~/.local/share/applications/nuvolaplayer3-soundcloud.desktop` after every launch

Ubuntu 16.04 64bit
Unity desktop
Nuvola Player 3 3.0.3
Revision 8e3fd1301c4f055128063cce690165e832429265
WebKitGTK 2.12.2
libsoup 2.52.2
##

**Comment by fenryxo** [comment]
Hello @CrazyLemon. You can make your changes to the desktop file and then mark it as read-only using a prefered file manager or `chmod a-w`.

I'll keep this ticket open as Nuvola should stop overwriting desktop files as soon as all scripts are updated to the current icon set rules (#242).

**Comment by fenryxo** [comment]
Web App scripts should provide desktop file #263

**Comment by fenryxo** [comment]
Nuvola 3.1 no longer creates desktop files and removes ones that have been already created. Each web app script now provides its own desktop file in /usr/share/applications.

**Comment by fenryxo** [comment]
The same now applies also to Nuvola 3.0.5. In case somebody wants to modify desktop files, copy the original one from /usr/share/applications to ~/.local/share/applications. Make sure the filename (e.g. `eu.tiliado.NuvolaAppGooglePlayMusic.desktop`) is preserved.

Note: Previous desktop files (`~/.local/share/applications/nuvolaplayer3-*.desktop`) are now deleted on start-up.
