### ISSUE TITLE
Dark Mode for Web Pages

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#249]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add an option to show pages in dark mode.

## Details from reporter

Feedback form a Patron:

> Nuvola Player works pretty well but I would like to have a dark mode, similar to the [Chrome Deluminate plugin](https://github.com/abstiles/deluminate), for example. Even a basic colour invert would be helpful.

:heart: **One [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this feature.** Internal info: [(1)](https://tiliado.eu/admin/tiliado_funding/patron/54/).
##

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
