### ISSUE TITLE
Player fails to find any instance of Flash

### ISSUE THREAD

**Issue by benmacleod** [tiliado/nuvolaplayer#250]
Ubuntu 16.04.1 LTS, x86_64, Unity desktop
Nuvola Player R 3.1.0+201608141426.c7e45b4, development version provided by Tiliado repositories
WebKitGTK 2.12.2
libsoup 2.52.2

I open the Google Player window and it pops up a dialog with the message "Missing Flash Player. You need the latest Adobe Flash Player to listen to music." No music will play. I have an instance of Flash on my system which is detected by Google Play Music when used from Firefox or Google Chrome.

Debug output: https://gist.github.com/benmacleod/1d080a0a6e72cb56c3289a3a0d09a54d

**Comment by fenryxo** [comment]
Hello @benmacleod. Thanks for taking the time to report this issue. I need more information to investigate it further.

1. Is the issue always reproducible?
2. Does the issue occur also in Nuvola Player 3.0.3?
3. Does the issue occur also in the [WebKitGtk MiniBrowser](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#webkitgtk-minibrowser)?

**Comment by benmacleod** [comment]
Hey @fenryxo, sorry to take so long to get back to you.

1. Yes, the issue always occurs
2. Yes, it occurred in the previous 3.0 version which I had installed (don't recall the precise version). Would you like me to uninstall 3.1 and install a particular version, just to be sure?
3. No, it doesn't happen in the Minibrowser, which plays music just fine

**Comment by benmacleod** [comment]
@fenyrxo also note that it has happened since I elected not to show Flash warnings at startup in this dialog. There is now no way for me to see the dialog in the Google Play Music plugin, but I can see it fine in the BandCamp plugin, and BandCamp plays just fine.
![screenshot from 2016-09-08 11-07-26](https://cloud.githubusercontent.com/assets/157501/18333719/dcf4cdb2-75b4-11e6-9b88-9cd62a4b45b3.png)

**Comment by fenryxo** [comment]
> also note that it has happened since I elected not to show Flash warnings at startup in this dialog.
> There is now no way for me to see the dialog in the Google Play Music plugin

Could you open the dialog from the Gear menu → Format support → Web Plugins and check whether you didn't toggle "Load web plugins" off accidentally?

![Gear meni → Format Support](http://tiliado.github.io/nuvolaplayer/documentation/images/3.0/unity/unity_gear_menu_format_support.png)

**Comment by benmacleod** [comment]
We're getting close here :) I'm missing those options from my gear menu.
![screenshot from 2016-09-13 11-09-35](https://cloud.githubusercontent.com/assets/157501/18458221/bd94e000-79a2-11e6-887d-dd0cf60b866e.png)

**Comment by fenryxo** [comment]
Oh, I assumed you were running Unity with the global menu but the log shows that there is no global menu (`DesktopShell.vala:96: Shell: compiz ... menubar 0`). However, there should be an appmenu (`DesktopShell.vala:96: Shell: compiz ... appmenu 1`). The appmenu shows the entries which are not present in the gear menu. What is your desktop environment? Is there the appmenu?

**Comment by benmacleod** [comment]
Ahhh, so the appmenus on Ubuntu 16.04 Unity are all the HUD type ones activated by the left ALT key and typing. I thought they had disappeared altogether. I was able to switch on loading Flash plugins using the appmenu, as per your instructions. Thanks for your help!

**Comment by fenryxo** [comment]
I'm still concerned about your unusual Unity configuration. Could you answer my questions at tiliado/diorite#7? Thanks.
