### ISSUE TITLE
Add option to show track notifications delayed

### ISSUE THREAD

**Issue by CrazySky2121** [tiliado/nuvolaplayer#251]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add an option to show track change notification delayed.

## Details from reporter

Please add setting to adjust the notification duration of the name song.

I think duration can be in seconds. For example, if duration = 10 sec, notification showing 10 seconds after song started.
##

**Comment by fenryxo** [comment]
Hello @october21. Thanks for your feature request. I've added it to [the wishlist](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3Awishlist+sort%3Acreated-asc). I'd love to start hacking on it as soon as possible, but the project funding is scarce. Would you be willing to fund development of this feature?

**Comment by fenryxo** [comment]
This feature request has been moved to [the "postponed" queue](https://github.com/tiliado/nuvolaplayer/issues?q=is%3Aopen+label%3Apostponed+sort%3Acreated-asc) as the [project funding](https://tiliado.eu/nuvolaplayer/funding/) is scarce and no [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this particular feature.

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
