### ISSUE TITLE
MPRIS does not work again

### ISSUE THREAD

**Issue by regisz** [tiliado/nuvolaplayer#253]
For about a week the MPRIS has not worked again :(. And the app closes if I click on the window "close" button (earlier the app ran in the background in this case),.

Note: MPRIS did not work perfect earlier, the reload button had to been clicked 2-5 times for the working.

By the way the WebKitGTK crashed many times :(.

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

$ unity --version
unity 7.4.0

$ uname -m
x86_64

$ nuvolaplayer3 --version
Nuvola Player R 3.1.0+201609282019.58b9d1d
Revision 58b9d1d9ad3518fb1bf30e79dc006e9a6f4a2a8f
WebKitGTK 2.12.5
libsoup 2.52.2

$ apt-cache policy nuvolaplayer3
nuvolaplayer3:
  Telepítve: 3.1.0~201609282019.58b9d1d-0+1~xenial
  Jelölt:    3.1.0~201609282019.58b9d1d-0+1~xenial
  Verziótáblázat:
 *** 3.1.0~201609282019.58b9d1d-0+1~xenial 500
        500 https://tiliado.eu/nuvolaplayer/repository/deb xenial/devel amd64 Packages
        100 /var/lib/dpkg/status

**Comment by fenryxo** [comment]
Hello @regisz. Thanks for taking the time to report this issue. There is a lot of work under the hood to allow remote control from Pebble/Android apps so a bug may appear from time to time. I've just finished another bug squashing session and I'm going to build new packages tomorrow.

**Comment by fenryxo** [comment]
Hello @regisz. Does the issue still persist in the today's build?

**Comment by regisz** [comment]
cool, the service works in the last version :) And the close button too! Thx a lot!

$ nuvolaplayer3 --version
Nuvola Player R 3.1.0+201609301259.7a4fe9f
Revision 7a4fe9f33c2b4907abbde9597e7936717537a903
Diorite 0.3.0+201610011335.50d6664
WebKitGTK 2.12.5
libsoup 2.52.2
