### ISSUE TITLE
crashed with SIGSENV in g_type_check_instance_is_fundamentally_a()

### ISSUE THREAD

**Issue by regisz** [tiliado/nuvolaplayer#254]
I only use the player with Spotify and suddenly it crahsed.

>  #0  0x00007f5bee4cd7ed in g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #1  0x00007f5bee4ad9ae in g_object_ref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #2  0x00007f5bee98878d in _g_object_ref0 (self=0x1d92ba0) at src/nuvolakit-runner/components/mediakeys/MediaKeyServer.c:124
>  No locals.
>  #3  nuvola_media_keys_server_on_media_key_pressed (key=0x1d92d50 "Play", self=0x1be9120) at src/nuvolakit-runner/components/mediakeys/MediaKeyServer.c:373
>          _tmp3_ = 0x0
>          app_runner = 0x0
>          app_runner_collection = <optimized out>
>          app_runner_it = 0x1b58080
>          _tmp1_ = <optimized out>
>          _tmp32_ = 0
>          handled = 0
>          _tmp2_ = <optimized out>
>          _inner_error_ = 0x0
>          head = <optimized out>
>          _tmp0_ = <optimized out>
>  #4  _nuvola_media_keys_server_on_media_key_pressed_nuvola_media_keys_interface_media_key_pressed (_sender=<optimized out>, key=0x1d92d50 "Play", self=0x1be9120) at src/nuvolakit-runner/components/mediakeys/MediaKeyServer.c:134
>  No locals.
>  #5  0x00007f5bee4a8fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #6  0x00007f5bee4bafc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #7  0x00007f5bee4c3d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #8  0x00007f5bee4c4555 in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #9  0x00007f5bee4a8fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #10 0x00007f5bee4bafc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #11 0x00007f5bee4c3d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #12 0x00007f5bee4c4555 in g_signal_emit_by_name () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #13 0x00007f5bee98979b in _dbus_handle_nuvola_gnome_media_keys_media_player_key_pressed (parameters=<optimized out>, self=0x1dbddd0) at src/nuvolakit-runner/components/mediakeys/MediaKeys.c:775
>          app = 0x1af4f30 "nuvolaplayer3"
>          key = 0x1da9ca0 "Play"
>          _tmp1_ = 0x7f5bc800b350
>          _arguments_iter = {x = {31086176, 2, 1, 0, 31171984, 31086176, 27437328, 3579507750, 140032810770895, 140032813761805, 1, 140032813626150, 0, 72197626851559329, 29554960, 29554960}}
>          _tmp0_ = <optimized out>
>  #14 nuvola_gnome_media_keys_proxy_g_signal (proxy=0x1dbddd0, sender_name=<optimized out>, signal_name=<optimized out>, parameters=<optimized out>) at src/nuvolakit-runner/components/mediakeys/MediaKeys.c:783
>  No locals.
>  #15 0x00007f5be726fe40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
>  No symbol table info available.
>  #16 0x00007f5be726f8ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
>  No symbol table info available.
>  #17 0x00007f5bee4a97c9 in g_cclosure_marshal_generic () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #18 0x00007f5bee4a8fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #19 0x00007f5bee4bb56e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #20 0x00007f5bee4c3d5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #21 0x00007f5bee4c408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  No symbol table info available.
>  #22 0x00007f5bedee10fc in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
>  No symbol table info available.
>  #23 0x00007f5beded0964 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
>  No symbol table info available.
>  #24 0x00007f5bee1d205a in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
>  No symbol table info available.
>  #25 0x00007f5bee1d2400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
>  No symbol table info available.
>  #26 0x00007f5bee1d24ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
>  No symbol table info available.
>  #27 0x00007f5bedeadcdd in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
>  No symbol table info available.
>  #28 0x0000000000401f96 in nuvola_main (args=0x7ffc25b70f38, args_length1=1) at src/master/master.c:650
>          result = 0
>          _tmp13_ = <optimized out>
>          local_only_args = 1
>          log = <optimized out>
>          _tmp30_ = <optimized out>
>          _tmp36_ = <optimized out>
>          _tmp40_ = <optimized out>
>          _tmp41_ = <optimized out>
>          webkit_version = <optimized out>
>          _tmp44_ = <optimized out>
>          _tmp45_ = <optimized out>
>          _tmp46_ = <optimized out>
>          _tmp47_ = <optimized out>
>          _tmp48_ = <optimized out>
>          _tmp49_ = <optimized out>
>          storage = 0x1a00200
>          _tmp52_ = <optimized out>
>          _tmp53_ = 0x0
>          _tmp54_ = 0x1a00200
>          _tmp55_ = 0x1a00200
>          web_apps_storage = 0x1a28af0
>          _tmp56_ = 0x1a00200
>          _tmp57_ = 0x1a28af0
>          web_app_reg = 0x1a144e0
>          _tmp58_ = <optimized out>
>          _tmp59_ = <optimized out>
>          exec_cmd = 0x0
>          _tmp75_ = <optimized out>
>          exec_cmd_length1 = 0
>          _exec_cmd_size_ = 4
>          gdb_server = 0x0
>          _tmp76_ = <optimized out>
>          _tmp77_ = 0x0
>          _tmp78_ = 0x0
>          _tmp84_ = <optimized out>
>          _tmp84__length1 = <optimized out>
>          _tmp85_ = <optimized out>
>          _tmp86_ = <optimized out>
>          controller = 0x1a3a200
>          _tmp92_ = 0x1a00200
>          _tmp93_ = 0x1a144e0
>          _tmp94_ = <optimized out>
>          _tmp94__length1 = <optimized out>
>          _tmp95_ = 0x0
>          _tmp95__length1 = <optimized out>
>          _tmp96_ = <optimized out>
>          _tmp97_ = 0x1a3a200
>          _tmp98_ = 0x1a3a200
>          _tmp99_ = <optimized out>
>          _tmp99__length1 = 1
>          __tmp99__size_ = <optimized out>
>          _tmp100_ = <optimized out>
>          controller_args = 0x1a376d0
>          _tmp112_ = <optimized out>
>          _tmp112__length1 = 1
>          controller_args_length1 = 1
>          _controller_args_size_ = 1
>          _result_ = 0
>          _tmp122_ = 0x1a3a200
>          _tmp123_ = <optimized out>
>          _tmp123__length1 = <optimized out>
>          _tmp124_ = 0
>          _tmp125_ = 0x0
>          _tmp126_ = 0
>          _tmp127_ = 0
>          _inner_error_ = 0x0
>  #29 0x00007f5beae8f830 in __libc_start_main (main=0x401770 <main>, argc=3, argv=0x7ffc25b70f38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc25b70f28) at ../csu/libc-start.c:291
>          result = <optimized out>
>          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 7622568837347220259, 4200320, 140720941240112, 0, 0, -7624446736170542301, -7530272937363170525}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x3, 0x401770 <main>}, data = {prev = 0x0, cleanup = 0x0, canceltype = 3}}}
>          not_first_call = <optimized out>
>  #30 0x00000000004017a9 in _start ()
>  No symbol table info available.
> StacktraceAddressSignature: /usr/bin/nuvolaplayer3:11:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+347ed:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+149ae:/usr/lib/libnuvolaplayer3-runner.so+8578d:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+ffa5:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+21fc1:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+2ad5c:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+2b555:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+ffa5:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+21fc1:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+2ad5c:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+2b555:/usr/lib/libnuvolaplayer3-runner.so+8679b:/usr/lib/x86_64-linux-gnu/libffi.so.6.0.4+5e40:/usr/lib/x86_64-linux-gnu/libffi.so.6.0.4+58ab:/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.1+107c9
> StacktraceTop:
>  g_type_check_instance_is_fundamentally_a () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  g_object_ref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
>  _g_object_ref0 (self=0x1d92ba0) at src/nuvolakit-runner/components/mediakeys/MediaKeyServer.c:124
>  nuvola_media_keys_server_on_media_key_pressed (key=0x1d92d50 "Play", self=0x1be9120) at src/nuvolakit-runner/components/mediakeys/MediaKeyServer.c:373
>  _nuvola_media_keys_server_on_media_key_pressed_nuvola_media_keys_interface_media_key_pressed (_sender=<optimized out>, key=0x1d92d50 "Play", self=0x1be9120) at src/nuvolakit-runner/components/mediakeys/MediaKeyServer.c:134
> Tags: xenial third-party-packages
> 

See whole backtrace in the attachment.

**Comment by regisz** [comment]
[_usr_bin_nuvolaplayer3.1000.zip](https://github.com/tiliado/nuvolaplayer/files/502803/_usr_bin_nuvolaplayer3.1000.zip)

**Comment by fenryxo** [comment]
Hello @regisz. Thanks for taking the time to report this issue. There is a lot of work under the hood to allow remote control from Pebble/Android apps so a bug may appear from time to time. I've just finished another bug squashing session and I'm going to build new packages tomorrow.

**Comment by fenryxo** [comment]
Hello @regisz. Does the issue still persist in the today's build?

**Comment by regisz** [comment]
Today I has started to use the player with spotify (now last version; 3.1.0+201609301259.7a4fe9f), and this bug has not occurred yet. The exact reproduction is not known, sorry.

**Comment by fenryxo** [comment]
Ok, feel free to reopen this ticket if the issue appears again.

**Comment by regisz** [comment]
ok
