### ISSUE TITLE
WebKitPluginProcess2 crashed with SIGSEGV in start_thread()

### ISSUE THREAD

**Issue by regisz** [tiliado/nuvolaplayer#255]
I do not know exactly why, but sometimes WebKit crashes.

Here is the backtrace: [_usr_lib_x86_64-linux-gnu_webkit2gtk-4.0_WebKitPluginProcess2.1000.zip](https://github.com/tiliado/nuvolaplayer/files/506109/_usr_lib_x86_64-linux-gnu_webkit2gtk-4.0_WebKitPluginProcess2.1000.zip)

> $ nuvolaplayer3 --version
> Nuvola Player R 3.1.0+201609301259.7a4fe9f
> Revision 7a4fe9f33c2b4907abbde9597e7936717537a903
> Diorite 0.3.0+201610011335.50d6664
> WebKitGTK 2.12.5
> libsoup 2.52.2
> 
> $ apt-cache policy nuvolaplayer3
> nuvolaplayer3:
>   Telepítve: 3.1.0~201609301259.7a4fe9f-0+1~xenial
>   Jelölt:    3.1.0~201609301259.7a4fe9f-0+1~xenial
>   Verziótáblázat:
>  *** 3.1.0~201609301259.7a4fe9f-0+1~xenial 500
>         500 https://tiliado.eu/nuvolaplayer/repository/deb xenial/devel amd64 Packages
>         100 /var/lib/dpkg/status
> 
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.1 LTS
> Release:        16.04
> Codename:       xenial
> 
> $ unity --version
> unity 7.4.0
> 
> $ uname -m
> x86_64

**Comment by regisz** [comment]
another core dump: [_usr_lib_x86_64-linux-gnu_webkit2gtk-4.0_WebKitPluginProcess2_2.1000.zip](https://github.com/tiliado/nuvolaplayer/files/518919/_usr_lib_x86_64-linux-gnu_webkit2gtk-4.0_WebKitPluginProcess2_2.1000.zip)

**Comment by fenryxo** [comment]
Hello @regisz. It looks as a out-of-memory condition. Does your system have enough memory?

> SegvAnalysis:
 Segfault happened at: 0x7f8cf28e36ee:	cmpb   $0x0,0x2110(%rdx)
 PC (0x7f8cf28e36ee) ok
 source "$0x0" ok
 destination "0x2110(%rdx)" (0x34db2e85e110) not located in a known VMA region (needed writable region)!
 Stack memory exhausted (SP below stack segment)

**Comment by regisz** [comment]
sometimes google chrome eats my memory :(, but swap is enough

**Comment by fenryxo** [comment]
Well, it seems that's not enough for the flash plugin not to crash. Anyway, I'm closing this ticket as I cannot do anything but recommend increasing RAM. You may push this issue upstream to the WebKitGTK+ bug tracker though as the crash is in the WebKitPluginProcess2.

**Comment by regisz** [comment]
ok
unfortunately I can not increase the memory, now it is 8 GB, (and swap too).

**Comment by regisz** [comment]
I got the next message my bug report: https://bugs.webkit.org/show_bug.cgi?id=163485#c2
What do you think?

**Comment by fenryxo** [comment]
If you have installed the latest release of the Flash plug-in, then the only option is to pray for its stability. Alternatively, you can switch to a music service that doesn't require Flash.

**Comment by regisz** [comment]
:)
