### ISSUE TITLE
app can not reload (spotify) in case of network-interface change

### ISSUE THREAD

**Issue by regisz** [tiliado/nuvolaplayer#256]
I use VPN, but not always. If the nuvolaplayer is running and I (de)activate my vpn connection then the app can not continue the playing. I have to click on the reload button to continue the playing.

> $ nuvolaplayer3 --version
> Nuvola Player R 3.1.0+201609301259.7a4fe9f
> Revision 7a4fe9f33c2b4907abbde9597e7936717537a903
> Diorite 0.3.0+201610011335.50d6664
> WebKitGTK 2.12.5
> libsoup 2.52.2
> 
> $ apt-cache policy nuvolaplayer3
> nuvolaplayer3:
>   Telepítve: 3.1.0~201609301259.7a4fe9f-0+1~xenial
>   Jelölt:    3.1.0~201609301259.7a4fe9f-0+1~xenial
>   Verziótáblázat:
>  *** 3.1.0~201609301259.7a4fe9f-0+1~xenial 500
>         500 https://tiliado.eu/nuvolaplayer/repository/deb xenial/devel amd64 Packages
>         100 /var/lib/dpkg/status
> 
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.1 LTS
> Release:        16.04
> Codename:       xenial
> 
> $ unity --version
> unity 7.4.0
> 
> $ uname -m
> x86_64

**Comment by fenryxo** [comment]
Hello @regisz. Thanks for taking the time to report your issue. I need more information to investigate it further. Is the issue reproducible in the [WebKitGTK MiniBrowser](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#webkitgtk-minibrowser)?

**Comment by regisz** [comment]
Yes, I connected the player site of spotify (https://play.spotify.com), I started a track, and after I turn off my VPN connection, after I try to use anything on the page, but I could not do (error message was printed, see below). When I reload the player page, then everything worked again.

The next error message was printed:
> Failed to open VDPAU backend libvdpau_va_gl.so: nem nyitható meg a megosztott objektumfájl: Nincs ilyen fájl vagy könyvtár

In English:
> Failed to open VDPAU backend libvdpau_va_gl.so: can not open the shared object-file: No such file or directory

**Comment by fenryxo** [comment]
I believe this is an upstream issue, which cannot be fixed in Nuvola Player, and I'm closing this ticket for that reason. You may forward this bug report to the WebKitGTK bug tracker at https://goo.gl/TcsBMf though.

**Comment by regisz** [comment]
ok, thx!
