### ISSUE TITLE
apprunner crashed with SIGABRT in g_assertion_message()

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#257]
@regisz commented on [Mon Oct 03 2016](https://github.com/tiliado/nuvolaplayer.project/issues/41)

The app crashed maybe by low memory. I started the app in command line with the next command:
> $ nuvolaplayer3 -L /tmp/nuvolaplayer.log

Log: [nuvolaplayer.zip](https://github.com/tiliado/nuvolaplayer.project/files/505788/nuvolaplayer.zip)

I paused the playing, but after some seconds the playing continued, and I could not stop with any possibilities the playing. After I used CTRL-C to abort the app. Core was made [_usr_lib_nuvolaplayer3_apprunner.1000.zip](https://github.com/tiliado/nuvolaplayer.project/files/505781/_usr_lib_nuvolaplayer3_apprunner.1000.zip).

> $ nuvolaplayer3 --version
> Nuvola Player R 3.1.0+201609301259.7a4fe9f
> Revision 7a4fe9f33c2b4907abbde9597e7936717537a903
> Diorite 0.3.0+201610011335.50d6664
> WebKitGTK 2.12.5
> libsoup 2.52.2
> 
> $ apt-cache policy nuvolaplayer3
> nuvolaplayer3:
>   Telepítve: 3.1.0~201609301259.7a4fe9f-0+1~xenial
>   Jelölt:    3.1.0~201609301259.7a4fe9f-0+1~xenial
>   Verziótáblázat:
>  *** 3.1.0~201609301259.7a4fe9f-0+1~xenial 500
>         500 https://tiliado.eu/nuvolaplayer/repository/deb xenial/devel amd64 Packages
>         100 /var/lib/dpkg/status
> 
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.1 LTS
> Release:        16.04
> Codename:       xenial
> 
> $ unity --version
> unity 7.4.0
> 
> $ uname -m
> x86_64

---

@regisz commented on [Mon Oct 03 2016](https://github.com/tiliado/nuvolaplayer.project/issues/41#issuecomment-251053201)

Sorry the place for this issue. Can you move this into the right repository?

**Comment by regisz** [comment]
A new core dump: [_usr_bin_nuvolaplayer3.1000__12.10.2016.zip](https://github.com/tiliado/nuvolaplayer/files/525505/_usr_bin_nuvolaplayer3.1000__12.10.2016.zip)

**Comment by regisz** [comment]
A new core dump: [_usr_lib_nuvolaplayer3_apprunner.1000__12.10.2016.zip](https://github.com/tiliado/nuvolaplayer/files/525515/_usr_lib_nuvolaplayer3_apprunner.1000__12.10.2016.zip)

**Comment by fenryxo** [comment]
The issue has been fixed in the [Diorite master](https://github.com/tiliado/diorite) git branch. The fix will be published with the next rebuilt of packages of the [Nuvola Player 3.1 Rolling Releases](https://tiliado.github.io/nuvolaplayer/documentation/3.1/install.html). Thanks for making Nuvola Player better by filing bug reports.

**Comment by regisz** [comment]
cool :).
Thx your work!
