### ISSUE TITLE
nuvolaplayer3 crashed with SIGABRT in g_assertion_message()

### ISSUE THREAD

**Issue by regisz** [tiliado/nuvolaplayer#258]
The application did not respond any interaction (I had stopped the VPN before this situation), and I could stop the app used CTRL-C in command line.

The core dump: [_usr_bin_nuvolaplayer3.1000__12.10.2016.zip](https://github.com/tiliado/nuvolaplayer/files/525534/_usr_bin_nuvolaplayer3.1000__12.10.2016.zip)

The log: [nuvolaplayer__12.10.2016.zip](https://github.com/tiliado/nuvolaplayer/files/525540/nuvolaplayer__12.10.2016.zip)

> $ nuvolaplayer3 --version
> Nuvola Player R 3.1.0+201610021256.d392566
> Revision d392566f2d60e130cc52a872b89eb91798cd3d82
> Diorite 0.3.0+201610021222.2b2e526
> WebKitGTK 2.12.5
> libsoup 2.52.2
> 
> $ apt-cache policy nuvolaplayer3
> nuvolaplayer3:
>   Telepítve: 3.1.0~201610021256.d392566-0+1~xenial
>   Jelölt:    3.1.0~201610021256.d392566-0+1~xenial
>   Verziótáblázat:
>  *** 3.1.0~201610021256.d392566-0+1~xenial 500
>         500 https://tiliado.eu/nuvolaplayer/repository/deb xenial/devel amd64 Packages
>         100 /var/lib/dpkg/status
> 
> $ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.1 LTS
> Release:        16.04
> Codename:       xenial
> 
> $ unity --version
> unity 7.4.0
> 
> $ uname -m
> x86_64

**Comment by fenryxo** [comment]
It's the same Diorite bug as in #257
