### ISSUE TITLE
Shortcut Keys Not Working Under Linux Mint 18 (Cinnamon)

### ISSUE THREAD

**Issue by Kor0j** [tiliado/nuvolaplayer#259]
Mostly a non-issue for me, but the hardware keys for play/pause, prev and next cannot be assigned as global shortcuts for Nuvola, and do not work in the main window when assigned to regular shortcuts. Not sure if something is hijacking them, but works well otherwise, right-clicking the icon in the tray continues to work as intended. Running Linux Mint 18 Cinnamon on x86_64 on Linux Kernel 4.7.5.

**Comment by fenryxo** [comment]
Hello @Kor0j. Thanks for taking the time to report your issue. I need more information to investigate it further:

* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output) while you are setting the hardware keys for play/pause as global shortcuts.
* Does the hardware keys for play/pause work in other players, e.g. Rhytmbox?

**Comment by fenryxo** [comment]
Hello @Kor0j. I'm closing this issue as I haven't received any response to my request for more information I posted on October 22, 2016. If the issue still persists, feel free to add missing information and reopen this ticket.
