### ISSUE TITLE
"Oh no! Flash Player isn't running!"

### ISSUE THREAD

**Issue by Augustin82** [tiliado/nuvolaplayer#262]
Hi all,

I'm using Nuvola Player 3 on Ubuntu 16.04 with GNOME 3.18.

After updating my system, Deezer will no longer work: when I click "play" on a song, a pop-up shows saying "Oh no, Flash Player isn't running" (see at the bottom).
I have reinstalled NP3. Flash is enabled in the options. Googling the pop-up's title returns no hit.

Any idea what's going on?

Thank you very much!

![oh_no](https://cloud.githubusercontent.com/assets/2370810/19681738/ee64bc2c-9aaa-11e6-8f6a-9383a8f63f65.png)
##

**Comment by fenryxo** [comment]
Hello @Augustin82. Thanks for taking the time to report your issue. I need more information as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)to investigate it further:

* Which [version of Nuvola player](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#your-nuvola-player-instance) do you use?
* Could you provide the debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output).
* Is the issue reproducible in the [WebKitGTK MiniBrowser](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#webkitgtk-minibrowser)?
* A screenshot of the Format Support Dialog's Web Plugins tab (App Menu → Format support).

**Comment by Augustin82** [comment]
Hi @fenryxo. Thanks for answering and sorry for my initial lack of precision and delay in answering. I'll try to remedy the former as soon as possible ;)

**Comment by Augustin82** [comment]
@fenryxo again, apologies for not sticking to (actually, not even reading ^^) the guidelines.

There you go:

> Which version of Nuvola player do you use?

Nuvola Player 3 3.0.4
Revision bb4fdef51d50a620d739687eec9eb67dd6033da5
WebKitGTK 2.12.5
libsoup 2.52.2
Deezer 2.4
Installed using the Ubuntu repos, I think.

> Could you provide the debugging output from a terminal as specified in the Bug Reporting Guidelines.

https://gist.github.com/Augustin82/176185d06d5b83d5b7be51726b06c47d

> Is the issue reproducible in the WebKitGTK MiniBrowser?

When I go to deezer.com, log in, and try to play something, I have the same error message appearing as the one I've provided in my initial report.

> A screenshot of the Format Support Dialog's Web Plugins tab (App Menu → Format support).

![formatsupport](https://cloud.githubusercontent.com/assets/2370810/19958477/d47ad58e-a19f-11e6-9bb0-386be62a835b.png)

I'm using **Ubuntu 16.04**, **x86_64** architecture, with **GNOME 3.18.5**.

Many thanks for your help!

**Comment by Augustin82** [comment]
OK, using the message I got from the MiniBrowser, I found this issue: https://github.com/tiliado/nuvolaplayer/issues/241

I tried following the instructions, but at the end of the `sudo update-pepperflashplugin-nonfree --install` command, it gave me this error:

```
2016-11-03 17:09:34 (1,90 MB/s) - ‘/tmp/pepperflashplugin-nonfree.1QjBviukjA/google-chrome-stable_54.0.2840.90-1_amd64.deb’ saved [45750028/45750028]

mv: cannot stat 'unpackchrome/opt/google/chrome/PepperFlash/libpepflashplayer.so': No such file or directory
```

I'm going to investigate further.

**Comment by Augustin82** [comment]
This led to this issue: https://bugs.launchpad.net/ubuntu/+source/pepperflashplugin-nonfree/+bug/1632870

One of the answers (https://bugs.launchpad.net/ubuntu/+source/pepperflashplugin-nonfree/+bug/1632870/comments/27) suggested adding this PPA: https://launchpad.net/~jonathonf/+archive/ubuntu/pepperflashplugin-nonfree

I did, updated/upgraded (got an error about a file not found, but just went with it), and it apparently correctly set the flashplugin.

I started Deezer and it worked fine.

So, it seems it's a problem with the fact that Chrome 54 no longer bundles flash.

I'm closing this, but it might be worth keeping somewhere because I4m unlikely to be the only one with that issue, if it's indeed Chrome 54 that caused the problem =)
