### ISSUE TITLE
Google Play Music player does not launch

### ISSUE THREAD

**Issue by pszi1ard** [tiliado/nuvolaplayer#264]
Starting the main application on the command line from where I click on "Google Play Music" I get the following output, but the player does not start:
```
$ nuvolaplayer3 --verbose
Master: [INFO     Nuvola] WebAppRegistry.vala:89: Using web app Google Play Music, version 5.17, data dir /usr/share/nuvolaplayer3/web_apps/google_play_music
Runner: Failed to register: Timeout was reached
Runner: Runner: Runner: 
```
The "Runner:" printout can appear anywhere between 2-50 times :)

```
$ nuvolaplayer3 --version 
Nuvola Player 3 3.0.4
Revision bb4fdef51d50a620d739687eec9eb67dd6033da5
WebKitGTK 2.8.5
libsoup 2.44.2
```
Stable version install from Ubuntu tiliado repos.

System info: Ubuntu 14.04 x86_64

**Comment by fenryxo** [comment]
Hellp @pszi1ard. Thanks for taking the time to report this issue. Does it also happen if you log out & in? It look as if there were a blocked Nuvola Player instance.

**Comment by pszi1ard** [comment]
Thanks for the quick feedback. You're right, there was a hanging "apprunner" process. After killing that, the Google Player app started.

It might be useful to put in more verbose feedback on the command line and possibly give some feedback to the user on the GUI too. Otherwise, consider the issue solved, feel free to close.

**Comment by fenryxo** [comment]
Well, the app registration procedure is handled by GTK+ itself so there is no way to  make it more verbose.

**Comment by pszi1ard** [comment]
I see. However, if we assume that the issue I bumped into is not a corner case (and given how stable the webkit browser is, I'm not sure it is), not being able to tell the user that their app is stuck/hanging, is still a relevant usability issue of nuvolaplayer itself, isn't it? Does the main application exit as soon as it tell GTK+ to start the app? Couldn't it check that the app has actually started?
