### ISSUE TITLE
Today google music has a new interface

### ISSUE THREAD

**Issue by KruyKaze** [tiliado/nuvolaplayer#271]
And that broke notifications, hotkeys , playback after closing window etc...
Thanks

**Comment by fenryxo** [comment]
Hello @KruyKaze. Thanks for letting me know about this change.

**Comment by fenryxo** [comment]
Hello @KruyKaze. Could you post a screenshot ? I still have the old interface.

**Comment by KruyKaze** [comment]
Sure! 
![screenshot from 2016-11-18 23-40-58](https://cloud.githubusercontent.com/assets/70369/20453629/bfc5cad6-ade8-11e6-83f5-659ed87b338d.png)

**Comment by fenryxo** [comment]
Nice. Unfortunately, I cannot fix the script until I get the new interface too.

**Comment by KruyKaze** [comment]
This new interface is somewhat tied to location history. Which might not be
available / legal in your country.
Is there anything we can do about that?
Thanks

**Comment by fenryxo** [comment]
It would be awesome if the Google Play Music script got a new maintainer, ideally with the All Access/Unlimited subscription and living in USA.

**Comment by KruyKaze** [comment]
It turns out it's being rolled out globally according to this :
https://blog.google/products/google-play/introducing-the-new-google-play-music/

**Comment by KruyKaze** [comment]
Any updates on this? I really miss Nuvola 😢

**Comment by fenryxo** [comment]
I'm going to look at it on Saturday.

**Comment by fenryxo** [comment]
Hello @KruyKaze. Unfortunately, I still have the old interface. Do you have the Google Play Music Unlimited subscription? The new interface may be available only or subscribers.

**Comment by KruyKaze** [comment]
No I have the free one only.
thanks.

**Comment by KruyKaze** [comment]
Yesterday I noticed an update for the google music plugin for Nuvola. Even-though it hasn't been touched on github since Dec 3rd. So I updated and now it's working with the new interface. nuvolaplayer3ctl works as well. So I'm very happy.
Thanks!

**Comment by fenryxo** [comment]
There hasn't been any change in the Nuvola's script.  Google Play Music has probably changed its internals back. Anyway, happy listening.
