### ISSUE TITLE
Nuvola Player repository issues (404)

### ISSUE THREAD

**Issue by CrazyLemon** [tiliado/nuvolaplayer#276]
So i just got notified about a deezer and siriusxm update. I press update and there was an issue.
These files are not accessible/available.
 ```
Err:2https://tiliado.eu/nuvolaplayer/repository/deb yakkety/stable amd64 nuvolaplayer3-deezer amd64 2.5-1~yakkety
  404  NOT FOUND
Err:2 https://tiliado.eu/nuvolaplayer/repository/deb yakkety/stable amd64 nuvolaplayer3-siriusxm amd64 1.3-1~yakkety
  404  NOT FOUND
E: Not available https://tiliado.eu/nuvolaplayer/repository/deb/pool/stable/n/nuvolaplayer3-deezer/nuvolaplayer3-deezer_2.5-1~yakkety_amd64.deb  404  NOT FOUND
E: Not available https://tiliado.eu/nuvolaplayer/repository/deb/pool/stable/n/nuvolaplayer3-siriusxm/nuvolaplayer3-siriusxm_1.3-1~yakkety_amd64.deb  404  NOT FOUND

```
If i go to 
https://tiliado.eu/nuvolaplayer/repository/deb/pool/stable/n/ and pick a folder files are locked down. 
So perrmissions issue?

**Comment by fenryxo** [comment]
Hello @CrazyLemon. Thanks for reporting this issue. It seems that I accidentally disabled the Ubuntu 16.10 Yakkety Yak repository when I added the Fedora 25 repository. It should be fixed now.
