### ISSUE TITLE
Amazon music/Spotify stops/crashes playback on Ubuntu 16.04 using Gnome-Shell

### ISSUE THREAD

**Issue by semidark** [tiliado/nuvolaplayer#278]
the latest stable Release 3.0.4 stops playing Sound on Ubuntu 16.04 under Gnome-shell.

This happens every time I...

- Adjust the volume (Volume Popup is rendered)
- Close a window (not the Nuvola one of course)

Using Amazon in the Chrome Browser does not show this faulty behavior.
I thought it would have something to do with the Composite Window Manager and the effects that Gnome Shell renderes. So I uninstalled my NVIDIA Driver and tried it without it. Stops Playback. Updated to the latest Stable NVIDIA Driver release and it still stops playback.

After the Playback crashes i have to restart the whole player.

So at the moment the player is useless for me.

I will try to gather more information on this issue and post it here.

**Comment by semidark** [comment]
```
$ nuvolaplayer3 -V
Nuvola Player 3 3.0.4
Revision bb4fdef51d50a620d739687eec9eb67dd6033da5
WebKitGTK 2.12.5
libsoup 2.52.2

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

$ gnome-shell --version
GNOME Shell 3.18.5

$ nvidia-smi
Thu Dec 22 13:16:01 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960     Off  | 0000:01:00.0      On |                  N/A |
| 30%   37C    P8    10W / 120W |    186MiB /  1988MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1484    G   /usr/lib/xorg/Xorg                             114MiB |
|    0      4437    G   /usr/bin/gnome-shell                            69MiB |
+-----------------------------------------------------------------------------+
```

**Comment by pyriand3r** [comment]
same issue here... when adjusting volumen replay stops / sound is muted. A restart of the app helps but is no solution of course. Happens in spotify and amazon, haven't tried other plugins so far.

Here is a log output. it contains starting nuvola -> starting spotify -> starting a song -> adjusting volume. As soon as i adjust the volume the console errors are starting and won't stop until closing nuvola

```
Worker: [DEBUG    Nuvola] WebExtension.vala:220: Page 1 created for (null)
Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded about:loading
Runner: [WARNING  Nuvola] FormatSupportCheck.vala:158: Too many Flash plugins have been found: 2
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Worker: [DEBUG    Nuvola] WebExtension.vala:130: Window object cleared for 'https://play.spotify.com/user/avaloncmp/playlist/4AQf6MsiZbVuw2YKivwDYe'
Worker: [DEBUG    Nuvola] WebExtension.vala:140: Init frame: https://play.spotify.com/user/avaloncmp/playlist/4AQf6MsiZbVuw2YKivwDYe, 0x27c2470, 0x26537a0, 0x7f650cd380e0
Vector smash protection is enabled.
Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded https://play.spotify.com/user/avaloncmp/playlist/4AQf6MsiZbVuw2YKivwDYe
Vector smash protection is enabled.
Runner: 
(nuvolaplayer3-spotify:12784): Gtk-WARNING **: Allocating size to GtkSocket 0x7ff8d0002600 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Runner: libva info: VA-API version 0.39.4
Runner: libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
Runner: libva info: va_openDriver() returns -1
Runner: https://connect.facebook.net/en_US/fbevents.js:9:1718: CONSOLE WARN Facebook Pixel Warning: Multiple different pixels were detected on this page
Runner: https://play.spotify.edgekey.net/client/d5588ad/js/spotify.web.client.js:419:443: CONSOLE LOG Connecting to wss://lon2-linkap-a3560.ap.spotify.com:443
Runner: https://play.spotify.edgekey.net/client/d5588ad/js/spotify.web.client.js:419:443: CONSOLE INFO [AppLoader] Using only bundled apps
Runner: https://play.spotify.edgekey.net/client/d5588ad/js/spotify.web.client.js:419:443: CONSOLE WARN [FB] error
Runner: https://play.spotify.edgekey.net/apps/browse/7.1.6/main.js:11943:37: CONSOLE WARN The page at https://play.spotify.com/browse was allowed to display insecure content from http://b.scorecardresearch.com/p?c1=2&c2=15654041&c7=http%3A%2F%2Fwww.spotify-desktop.com&cv=2.0&cj=1.

Runner: CONSOLE WARN The page at https://play.spotify.com/user/avaloncmp/playlist/4AQf6MsiZbVuw2YKivwDYe was allowed to display insecure content from http://b.scorecardresearch.com/p2?c1=2&c2=15654041&c7=http%3A%2F%2Fwww.spotify-desktop.com&cv=2.0&cj=1.

Runner: https://play.spotify.com/apps/browse/7.1.6/?id=browse&cb=10&locale=en&spd-api=1.36.1:9:216: CONSOLE ERROR SyntaxError: Unexpected token '<'
Runner: https://play.spotify.com/apps/browse/7.1.6/?id=browse&cb=10&locale=en&spd-api=1.36.1:1:7: CONSOLE ERROR ReferenceError: Can't find variable: osdlfm
Runner: about:srcdoc:14: CONSOLE ERROR SyntaxError: Unexpected token '<'
Runner: about:srcdoc:15:23886: CONSOLE ERROR ReferenceError: Can't find variable: osdlfm
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
Runner: https://d3jfuiz4ixupna.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
^C%   
```

**Comment by fenryxo** [comment]
Hello @semidark & @pyriand3r. Thanks for taking the time to report this issue. I need more information to investigate it further:

@semidark

* Is the issue reproducible with the GNOME Web browser (also known as Epiphany)?
* Could you provide debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output)?
* If you run commands `ulimit -c unlimited; nuvolaplayer3 -D` in a terminal, does a file called `core` (possibly with a suffix/extension) appear when the issue occurs?

@pyriand3r 

* Is the issue reproducible with the GNOME Web browser (also known as Epiphany)?
* Do you also use Ubuntu GNOME 16.04 and Nuvola Player 3.0.4?
* If you run commands `ulimit -c unlimited; nuvolaplayer3 -D` in a terminal, does a file called `core` (possibly with a suffix/extension) appear when the issue occurs?

**Comment by pyriand3r** [comment]
Hi,

1. 
The issue is reproducible with Epiphany: I have tested both Spotify Web Player and Amazon Music. Both behave similar to Nuvola on playback. In Spotify changing the volume seems to crash the whole web player. Not even the music stops but also the interface crashes: Track seems to stop (playback counter stops) but play button indicates it is playing), changing the song changes the text of current playing song but playback counter doesn't change. The amazon player is not crashing like that but stops playback too, play counter stops and when changing the song it won't get a connection (loading...)

2.
i am using Arch Linux and Nuvola Player 5.2.

3.
 No, nothing with `core` in it appeared in my log/terminal

4.
Interessting thing maybe: Both Epiphany and Nuvola complained about flash not being installed after logging in to Amazon music. (Normally Nuvola complains about too many flash versions installed (lib vs. lib64)). After reloading the page playback works until changing volume)

**Comment by fenryxo** [comment]
Thanks @pyriand3r.

* Thee is no such version as Nuvola Player 5.2. What does `nuvolaplayer3 --version` show?
* Do you use GNOME Shell?
* Which Flash plugin do you use and how did you install Flash it?
* When the issue occurs, is the WebKitPluginProcess2 still alive?
* Which graphic card do you have? Does it support accelerated compositing and libva?
* Have you ever seen the `libva info: va_getDriverName() returns 0; Trying to open /usr/lib/dri/i965_drv_video.so;  va_openDriver() returns -1` error message before? Have you tried installing a package containing the /usr/lib/dri/i965_drv_video.so file?

**Comment by pyriand3r** [comment]
1. naah, sorry. Amazon Cloud Player Plugin version was 5.2. Sorry for that.
```
Nuvola Player 3 3.0.4
Revision fuzzy
WebKitGTK 2.14.2
libsoup 2.56.0
```
2. Yes i use GNOME Shell 3.22
3. I use the standard flash plugin, installed it via pacman : `extra/flashplugin 24.0.0.186-1`  
Nuvola says it is `Shockwave Flash 24.0 r0` so it matches the installed package
4. No, it crashes when the issue occurs
5. Intel Graphics HD 5200 / dunno if it supports accelerated compositing and libva
6. Never seen that error before and i haven't tried to install such a package (at least not intentionally)  
`find` couldn't find that file on my system neither.

**Comment by fenryxo** [comment]
Well, it seems that the Flash plugin simply crashes, which is not that surprising. Looking at the libva error, it may be possible that the Flash plugin tries to initialize accelerated compositing with the libva library and it fails because a driver isn't installed. The driver should be in the [libva-intel-driver](https://www.archlinux.org/packages/extra/i686/libva-intel-driver/files/) package. Could you install it and check whether the issue still perists?

**Comment by pyriand3r** [comment]
Hi, sorry that it took so long. I have installed the libva-intel-driver but the issue is still there. But the flash error is gone now. Music still stops on volume change but the console is not flooded with flash errors any more...

**Comment by fenryxo** [comment]
Does the WebKitPluginProcess2 stay alive now? Could you post a new debug output? Is the issue still reproducible in Epiphany too? (I'm sorry that I ask so many questions with seemingly obvious answers, but there is no place for making assumptions in the debugging process or an important detail may be left unnoticed.)

**Comment by pyriand3r** [comment]
Happy new year!!!

1. The WebKitPluginProcess2 still dies
2. New Debug-Output: https://gist.github.com/pyriand3r/3a6616a374c097e0e3dddffce2b2500f
3. Epiphany still has the same issue

**Comment by alanvbs** [comment]
Hi. I believe that I just posted a similar issue on the nuvola-spotify issue page.
I got this message when running the nuvola player with the option -D

```
Runner: https://xxxxxxxxxxx.cloudfront.net/sdk/spotify.sdk.5.9.6-enc-cf3c98c.min.js:9:4822: CONSOLE ERROR TypeError: _flashObject.getSWF().sp_playerState is not a function. (In '_flashObject.getSWF().sp_playerState(id)', '_flashObject.getSWF().sp_playerState' is undefined)
```
I am using fedora 25 (GNOME Shell 3.22.2) and this message also appears on the terminal:
```
Vector smash protection is enabled.
```
Regarding possible video driver issues I use the bumblebee. However it appears that the nuvola player can correct inicialize the de libva. Since the following message appears:

```
Runner: libva info: VA-API version 0.39.4
Runner: libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
Runner: libva info: Found init function __vaDriverInit_0_39
Runner: libva info: va_openDriver() returns 0
```

I also tested the webpage play.spotify.com  using the epiphany browser it works without any issues.

**Comment by fenryxo** [comment]
Thanks @pyriand3r.

> The WebKitPluginProcess2 still dies

 Is there any "core" file after the WebKitPluginProcess2 crash?

> New Debug-Output

Do you remember in which position of the log the issue occurred? After the line 92 `Runner: libva info: va_openDriver() returns 0`? Or maybe after the line 87?

> I use the standard flash plugin, installed it via pacman : extra/flashplugin 24.0.0.186-1

The Flash plugin 24 is a major update. Did you use Nuvola Player in the past with an older version of the Flash plugin? If yes, did the same issue occurred?

**Comment by fenryxo** [comment]
Hello @alanvbs. I need more info.

* Could you provide debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output)?
* If you run commands `ulimit -c unlimited; nuvolaplayer3 -D` in a terminal, does a file called `core` (possibly with a suffix/extension) appear when the issue occurs?
* When the issue occurs, is the WebKitPluginProcess2 still alive?
* Do you also use the Flash plugin 24.0.0.186?

**Comment by pyriand3r** [comment]
Hi,

> Is there any "core" file after the WebKitPluginProcess2 crash?

If you mean, that ther is a WebKit Core Process in the process list, no, and there is no debug output containing anything with core. In fact, the process now fails silently. It appears in the log after the `Media player notify: artwork-location` part and there is no new log entry when crashing. (My log posted is the log until the crash happens. It is at the end of the file and there was no more log except for shutting down the app normally).

> Did you use Nuvola Player in the past with an older version of the Flash plugin? If yes, did the same issue occurred?

Yes i did and i never had this error before. So it seems to be connected to this flash version maybe... I will try to install and use an older one to confirm that.

**Comment by alanvbs** [comment]
Hi @fenryxo . Actually a core file is generated. But I have had to change the location of this file (`sudo sysctl -w kernel.core_pattern=core` will generate the file on the current folder).I had just installed the latest flash player to use with the nuvola player, the version is  24.0.0.186. The process that you mentioned when I interact with the interface (for instance changing the volume or closing to the tray) is killed.

The GDB output of the core file is (A debug version of the program is available?):
```
gdb nuvolaplayer3 -c core.28751
GNU gdb (GDB) Fedora 7.12-29.fc25
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nuvolaplayer3...Reading symbols from /usr/lib/debug/usr/bin/nuvolaplayer3.debug...done.
done.

warning: core file may not match specified executable file.
[New LWP 28751]
[New LWP 28779]
[New LWP 28781]
[New LWP 28984]
[New LWP 28753]
[New LWP 28774]
[New LWP 29010]
[New LWP 28780]
[New LWP 28782]
[New LWP 28785]
[New LWP 28783]
[New LWP 29008]
[New LWP 28754]
Core was generated by `/usr/libexec/webkit2gtk-4.0/WebKitPluginProcess2 37 /usr/lib64/mozilla/plugins/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f76ea5fe412 in ?? ()
[Current thread is 1 (LWP 28751)]
(gdb) bt f
#0  0x00007f76ea5fe412 in ?? ()
No symbol table info available.
#1  0x00007f773d78eac1 in ?? ()
No symbol table info available.
#2  0x000055b608813000 in ?? ()
No symbol table info available.
#3  0x000055b608813000 in ?? ()
No symbol table info available.
#4  0x000055b6088de110 in ?? ()
No symbol table info available.
#5  0x00007ffc062e85d0 in ?? ()
No symbol table info available.
#6  0x000055b60880b000 in ?? ()
No symbol table info available.
#7  0x000055b608813000 in ?? ()
No symbol table info available.
#8  0x00000000000000d4 in ?? ()
No symbol table info available.
#9  0x00007f773d79036d in ?? ()
No symbol table info available.
#10 0x000055b60880f000 in ?? ()
No symbol table info available.
#11 0x000055b6087fe560 in ?? ()
No symbol table info available.
#12 0x000055b6088e5d30 in ?? ()
No symbol table info available.
#13 0x000055b60880f000 in ?? ()
No symbol table info available.
#14 0x000055b60880b000 in ?? ()
No symbol table info available.
#15 0x00007f7700000000 in ?? ()
No symbol table info available.
#16 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by fenryxo** [comment]
Well, all evidence suggest that there is a bug in the Flash plugin 24.0.0.186. I'll [create a bug report at Adobe](https://tracker.adobe.com/) but I'm not sure when I get to it. Meanwhile, you can use older Flash plugin 11 (but with all his security vulnerabilities).

Also, Amazon Cloud Player seems to play fine without the Flash plugin in Nuvola Player 3.1. Nuvola
will complain about missing Flash plugin but you can disable this check (the app menu → Format support → Web Plugins). I haven't tested the Prime Music subscription though

**Comment by hurricanehrndz** [comment]
Can confirm an issue.
https://github.com/tiliado/nuvola-app-deezer/issues/8

**Comment by semidark** [comment]
Hello fenryxo,

the "flash plugin format support workaround" you suggested works for me.
No more Crashes and no more ugly flash support needed for my Amazon Music Playback.

Thnx. Keep up the good work.

semidark

**Comment by semidark** [comment]
Hi fenryxo,

using the suggested disable flash workaround only works for some tracks. Music I bought plays fine. Music I want to Stream from Prime or Music unlimited gives me an Error saying "Flash not detected
Flash must be installed and enabled to stream Amazon Music. You can install Flash from..."

greetz semidark

**Comment by fenryxo** [comment]
Oh, Flash is needed because of DRM I suppose :-(

**Comment by joetjen** [comment]
FYI: As I have the same problem, I came across this link (https://howto-ubuntunew.blogspot.de/2016/11/how-to-install-adobe-flash-player-24.html) which I did on my Ubuntu 16.10 system. So far the beta plugin seems to work better than the one installed by default.

**Comment by craigchambers** [comment]
joetjen's suggestion fixed the issue for me on Mint 18.

**Comment by fenryxo** [comment]
For those who have access to Nuvola Player 3.1 builds: There have been a few fixes recently that might have a positive effect on this issue. Could anybody check it with the latest stable Flash plugin (not beta nor 11.x)? The fixes are going to be backported to Nuvola 3.0 later this month.

**Comment by fenryxo** [comment]
[Nuvola Player 3.0.5 and Diorite 0.2.2 has been released.](https://medium.com/nuvola-news/nuvola-player-3-0-5-and-diorite-0-2-2-released-c170dfb53130) Does the issue still occur?

**Comment by hurricanehrndz** [comment]
Yes still does.

**Comment by hurricanehrndz** [comment]
Seems to be fixed.

**Comment by fenryxo** [comment]
Hello @hurricanehrndz. Thanks for your feedback. I'm closing this issue then but feel free to reopen it when it reappears.
