### ISSUE TITLE
Sync likes/rating across services

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#284]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add an option to synchronize track rating/likes across services.

## Details from reporter

From https://groups.google.com/d/msg/nuvola-player-devel/EE7nXqr6ybA/2MxTWYpBAAAJ
> It would be awesome to have a local database created from songs and playlists from all services with the ability to sync playlists and song likes.
> For example:
> I love to discover new music using "radio / station" style streaming services while working & studying, and I would like to be able to "like" or "rate" a song (including, using the HTTP remote control software), and in turn, when I launch a paid service like amazon music, the songs that I rate high or "like" would be added to my library of songs with complete automation from the database created.

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
