### ISSUE TITLE
Disable HTTP Remote Control if Network Manager is not available

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#286]
From the maintainer of FreeBSD ports

> By the way, I've seen that 3.1 requires NetworkManager. Is that a hard
> dependency? We don't have that on FreeBSD... :/

If any user of the FreeBSD port is interested in the HTTP Remote Control, they can provide patches to substitute the required Network Manager functionality.

> Network Manager is currently a hard dependency for the HTTP Remote Control feature. It is used to get human-friendly names of network interfaces (instead of eth0 etc) and corresponding IP addresses.

**Comment by xzhavilla** [comment]
I might work on that, one day.

**Comment by scotte** [comment]
A dependency on networkmanager is a bad idea - it would certainly mean no more nuvolaplayer for me, running on Debian with i3wm.

**Comment by fenryxo** [comment]
No need to worry. Network Manager is an optional run-time dependency and is used only by the HTTP Remote Control feature. Nuvola can still be installed on systems without Network Manager and all other features do work without it.

The HTTP Remote Control feature now shows info when Network Manager is not available. If a Nuvola Premium+ customer expresses interest in making this feature work without NM, I'll look at it.

**Comment by scotte** [comment]
Thanks for clarifying that it only affects the one feature - that's important and I missed it. Thank you!
