### ISSUE TITLE
Segmentation fault with KDE Plasma 5.9/OpenSUSE

### ISSUE THREAD

**Issue by DJViking** [tiliado/nuvolaplayer#296]
djviking@mintaka:~> nuvolaplayer3
Segmentation fault (core dumped)

djviking@mintaka:~> cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.2"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.2"
PRETTY_NAME="openSUSE Leap 42.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

djviking@mintaka:~> nuvolaplayer3 --debug  
Master: [DEBUG    Nuvola] master.vala:111: Compositing mode disabled because of WebKitGTK < 2.13.4
Master: [DEBUG      Gtk] Connecting to session manager
Master: [DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: kwin (null), CSD off
Master: [DEBUG    Nuvola] config.vala:174: Json Error: Failed to open file '/home/djviking/.config/nuvolaplayer3/master/config.json': No such file or directory
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_test 48 not found.
Segmentation fault (core dumped)

djviking@mintaka:~> gdb --args nuvolaplayer3 -D                                                                                            
GNU gdb (GDB; openSUSE Leap 42.2) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nuvolaplayer3...Reading symbols from /usr/lib/debug/usr/bin/nuvolaplayer3.debug...done.
done.
(gdb) bt
No stack.
(gdb) quit

djviking@mintaka:~> gdb --args nuvolaplayer3 -D
GNU gdb (GDB; openSUSE Leap 42.2) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nuvolaplayer3...Reading symbols from /usr/lib/debug/usr/bin/nuvolaplayer3.debug...done.
done.
(gdb) run
Starting program: /usr/bin/nuvolaplayer3 -D
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-3.7.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe378f700 (LWP 28640)]
Master: [DEBUG    Nuvola] master.vala:111: Compositing mode disabled because of WebKitGTK < 2.13.4
[New Thread 0x7fffe278f700 (LWP 28641)]
[New Thread 0x7fffe1f8e700 (LWP 28642)]
[New Thread 0x7fffe092b700 (LWP 28643)]
Master: [DEBUG      Gtk] Connecting to session manager
Master: [DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: kwin (null), CSD off
Master: [DEBUG    Nuvola] config.vala:174: Json Error: Failed to open file '/home/djviking/.config/nuvolaplayer3/master/config.json': No such file or directory
Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_test 48 not found.
[New Thread 0x7fff92dff700 (LWP 28644)]
[New Thread 0x7fff925fe700 (LWP 28645)]
[New Thread 0x7fff91dfd700 (LWP 28646)]
Detaching after fork from child process 28647.
Detaching after fork from child process 28649.
[New Thread 0x7fff913fa700 (LWP 28652)]

Thread 1 "nuvolaplayer3" received signal SIGSEGV, Segmentation fault.
0x00007ffff2173cc4 in ?? () from /usr/lib64/libdioritegtk-0.2.so
Missing separate debuginfos, use: zypper install diorite-debuginfo-0.2.0-1.4.x86_64 fontconfig-debuginfo-2.11.1-2.2.x86_64 gdk-pixbuf-loader-rsvg-debuginfo-2.40.15-8.1.x86_64 glibc-locale-debuginfo-2.22-3.7.x86_64 gvfs-debuginfo-1.28.3-2.2.x86_64 krb5-debuginfo-1.15-203.1.x86_64 libX11-6-debuginfo-1.6.3-7.1.x86_64 libXau6-debuginfo-1.0.8-7.4.x86_64 libXcomposite1-debuginfo-0.4.4-11.3.x86_64 libXcursor1-debuginfo-1.1.14-7.3.x86_64 libXdamage1-debuginfo-1.1.4-10.3.x86_64 libXext6-debuginfo-1.3.3-4.19.x86_64 libXfixes3-debuginfo-5.0.1-8.1.x86_64 libXi6-debuginfo-1.7.5-4.1.x86_64 libXinerama1-debuginfo-1.1.3-6.3.x86_64 libXrandr2-debuginfo-1.5.0-5.1.x86_64 libXrender1-debuginfo-0.9.9-4.1.x86_64 libarchive13-debuginfo-3.1.2-16.1.x86_64 libatk-1_0-0-debuginfo-2.20.0-1.5.x86_64 libatk-bridge-2_0-0-debuginfo-2.20.1-2.2.x86_64 libatspi0-debuginfo-2.20.2-4.2.x86_64 libattr1-debuginfo-2.4.47-6.57.x86_64 libbz2-1-debuginfo-1.0.6-32.53.x86_64 libcairo-gobject2-debuginfo-1.15.2-4.2.x86_64 libcairo2-debuginfo-1.15.2-4.2.x86_64 libcanberra-gtk3-0-debuginfo-0.30-12.2.x86_64 libcanberra-gtk3-module-debuginfo-0.30-12.2.x86_64 libcanberra0-debuginfo-0.30-12.2.x86_64 libcom_err2-debuginfo-1.42.11-11.4.x86_64 libcroco-0_6-3-debuginfo-0.6.11-2.2.x86_64 libdatrie1-debuginfo-0.2.4-20.5.x86_64 libdbus-1-3-debuginfo-1.8.22-1.1.x86_64 libenchant1-debuginfo-1.6.0-24.5.x86_64 libepoxy0-debuginfo-1.3.1-5.4.x86_64 libexpat1-debuginfo-2.1.0-17.9.x86_64 libffi4-debuginfo-5.3.1+r233831-7.1.x86_64 libfreetype6-debuginfo-2.6.3-1.2.x86_64 libgcc_s1-debuginfo-5.3.1+r233831-7.1.x86_64 libgcrypt20-debuginfo-1.6.1-33.1.x86_64 libgdk_pixbuf-2_0-0-debuginfo-2.34.0-5.1.x86_64 libgio-2_0-0-debuginfo-2.48.2-1.10.x86_64 libglib-2_0-0-debuginfo-2.48.2-1.10.x86_64 libgmodule-2_0-0-debuginfo-2.48.2-1.10.x86_64 libgobject-2_0-0-debuginfo-2.48.2-1.10.x86_64 libgpg-error0-debuginfo-1.13-4.19.x86_64 libgraphite2-3-debuginfo-1.3.1-3.6.x86_64 libgstapp-1_0-0-debuginfo-1.8.3-3.1.x86_64 libgstaudio-1_0-0-debuginfo-1.8.3-3.1.x86_64 libgstfft-1_0-0-debuginfo-1.8.3-3.1.x86_64 libgstpbutils-1_0-0-debuginfo-1.8.3-3.1.x86_64 libgstreamer-1_0-0-debuginfo-1.8.3-1.8.x86_64 libgsttag-1_0-0-debuginfo-1.8.3-3.1.x86_64 libgstvideo-1_0-0-debuginfo-1.8.3-3.1.x86_64 libgtk-3-0-debuginfo-3.20.9-1.2.x86_64 libharfbuzz-icu0-debuginfo-1.3.0-1.2.x86_64 libharfbuzz0-debuginfo-1.3.0-1.2.x86_64 libhyphen0-debuginfo-2.8.8-7.1.x86_64 libicu52_1-debuginfo-52.1-11.5.x86_64 libjavascriptcoregtk-4_0-18-debuginfo-2.12.5-1.6.x86_64 libjpeg8-debuginfo-8.0.2-33.1.x86_64 libjson-glib-1_0-0-debuginfo-1.2.2-1.2.x86_64 libkeyutils1-debuginfo-1.5.9-5.18.x86_64 libltdl7-debuginfo-2.4.2-17.54.x86_64 liblzma5-debuginfo-5.2.2-1.11.x86_64 libnotify4-debuginfo-0.7.6-6.5.x86_64 libogg0-debuginfo-1.3.0-4.3.x86_64 libopenssl1_0_0-debuginfo-1.0.2j-2.2.x86_64 liborc-0_4-0-debuginfo-0.4.24-7.6.x86_64 libpango-1_0-0-debuginfo-1.40.1-1.5.x86_64 libpcre1-debuginfo-8.39-6.1.x86_64 libpixman-1-0-debuginfo-0.34.0-2.2.x86_64 libpng16-16-debuginfo-1.6.8-8.1.x86_64 librsvg-2-2-debuginfo-2.40.15-8.1.x86_64 libsecret-1-0-debuginfo-0.18.5-2.2.x86_64 libselinux1-debuginfo-2.5-2.12.x86_64 libsoup-2_4-1-debuginfo-2.54.1-1.5.x86_64 libsqlite3-0-debuginfo-3.8.10.2-7.9.x86_64 libstdc++6-debuginfo-5.3.1+r233831-7.1.x86_64 libthai0-debuginfo-0.1.25-1.2.x86_64 libvorbis0-debuginfo-1.3.3-4.18.x86_64 libvorbisfile3-debuginfo-1.3.3-4.18.x86_64 libwayland-client0-debuginfo-1.9.0-2.5.x86_64 libwayland-server0-debuginfo-1.9.0-2.5.x86_64 libwebkit2gtk-4_0-37-debuginfo-2.12.5-1.6.x86_64 libwebp5-debuginfo-0.4.3-7.4.x86_64 libxcb-render0-debuginfo-1.11.1-2.25.x86_64 libxcb-shm0-debuginfo-1.11.1-2.25.x86_64 libxcb1-debuginfo-1.11.1-2.25.x86_64 libxml2-2-debuginfo-2.9.4-3.1.x86_64 libxslt1-debuginfo-1.1.28-9.5.x86_64 libz1-debuginfo-1.2.8-10.1.x86_64
(gdb) bt
#0  0x00007ffff2173cc4 in  () at /usr/lib64/libdioritegtk-0.2.so
#1  0x00007ffff76ba908 in g_closure_invoke () at /usr/lib64/libgobject-2.0.so.0
#2  0x00007ffff76cbb37 in  () at /usr/lib64/libgobject-2.0.so.0
#3  0x00007ffff76d42a8 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#4  0x00007ffff76d4592 in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#5  0x00007ffff391a16c in gtk_widget_realize () at /usr/lib64/libgtk-3.so.0
#6  0x00007ffff391a458 in gtk_widget_map () at /usr/lib64/libgtk-3.so.0
#7  0x00007ffff3791010 in  () at /usr/lib64/libgtk-3.so.0
#8  0x00007ffff3715d8f in  () at /usr/lib64/libgtk-3.so.0
#9  0x00007ffff76baaaf in  () at /usr/lib64/libgobject-2.0.so.0
#10 0x00007ffff76d3918 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#11 0x00007ffff76d4592 in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#12 0x00007ffff391a3fc in gtk_widget_map () at /usr/lib64/libgtk-3.so.0
#13 0x00007ffff3715d8f in  () at /usr/lib64/libgtk-3.so.0
#14 0x00007ffff76baaaf in  () at /usr/lib64/libgobject-2.0.so.0
#15 0x00007ffff76d3918 in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#16 0x00007ffff76d4592 in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#17 0x00007ffff391a3fc in gtk_widget_map () at /usr/lib64/libgtk-3.so.0
#18 0x00007ffff38522e2 in  () at /usr/lib64/libgtk-3.so.0
#19 0x00007ffff3715d8f in  () at /usr/lib64/libgtk-3.so.0
#20 0x00007ffff3852421 in  () at /usr/lib64/libgtk-3.so.0
#21 0x00007ffff76baaaf in  () at /usr/lib64/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---q 
Quit
(gdb) quit
A debugging session is active.

        Inferior 1 [process 28636] will be killed.

Quit anyway? (y or n) y

djviking@mintaka:~> uname -a
Linux mintaka 4.4.36-8-default #1 SMP Fri Dec 9 16:18:38 UTC 2016 (3ec5648) x86_64 x86_64 x86_64 GNU/Linux

sverre@mintaka:/usr> nuvolaplayer3 --version       
Nuvola Player 3 3.0.4
Revision fuzzy
WebKitGTK 2.12.5
libsoup 2.54.1
From repository: http://download.opensuse.org/repositories/multimedia:/apps/openSUSE_Leap_42.2

Tried some other variations of starting nuvolaplayer
djviking@mintaka:~> nuvolaplayer3 --app-id=spotify
Got a window up telling me it cannot find the application spotify. Don't know if it is the right app-id as I cannot list available ids. See attached screenshot for this:
![screenshot_20170211_210851](https://cloud.githubusercontent.com/assets/3070076/22857100/f738edc4-f09e-11e6-9770-c26e87f4b32b.png)

**Comment by fenryxo** [comment]
Hello @DJViking. Thaks for taking the time to report this issue.
> Thread 1 "nuvolaplayer3" received signal SIGSEGV, Segmentation fault.
> 0x00007ffff2173cc4 in ?? () from /usr/lib64/libdioritegtk-0.2.so

> http://download.opensuse.org/repositories/multimedia:/apps/openSUSE_Leap_42.2/x86_64/
> ...
> diorite-0.2.0-1.4.x86_64.rpm  

This crash was fixed in Diorite 0.2.1 more than a year ago. Please talk to the maintainer of the diorite package to upgrade it.

> nuvolaplayer3 --app-id=spotify
> Got a window up telling me it cannot find the application spotify. 

The id is correct. Spotify script is probably not installed. Look at the /usr/share/nuvolaplayer3/web_apps directory.

> Don't know if it is the right app-id as I cannot list available ids.

A parameter to list apps would be helpful, indeed. Re-ticketed as #297

FYI, Nuvola will officially support OpenSUSE in the next stable release 4.0, which is going to be available only as [cross-distribution Flatpak packages](https://github.com/tiliado/nuvolaplayer/wiki/Flatpaks).
