### ISSUE TITLE
Amazon Cloud Player Won't Autoplay Next Song

### ISSUE THREAD

**Issue by mshirley** [tiliado/nuvolaplayer#299]
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

Nuvola Player 3 3.0.4
Revision bb4fdef51d50a620d739687eec9eb67dd6033da5
WebKitGTK 2.8.5
libsoup 2.44.2

When starting a playlist or a station from Amazon, the player does not advance to the next song in the playlist or station.  It just stops.  Play resumes when I hit next.

    Master: [DEBUG    Nuvola] master.vala:111: Compositing mode disabled because of WebKitGTK < 2.13.4
    Master: [DEBUG      Gtk] Connecting to session manager
    Master: [DEBUG    DioriteGtk] DesktopShell.vala:96: Shell: gnome shell 3.10.4, CSD 1, appmenu 1, menubar 0
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.5
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.18
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Groove at /usr/share/nuvolaplayer3/web_apps/groove, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 3.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SiriusXM at /usr/share/nuvolaplayer3/web_apps/siriusxm, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SoundCloud at /usr/share/nuvolaplayer3/web_apps/soundcloud, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.4
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app YouTube at /usr/share/nuvolaplayer3/web_apps/youtube, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
    Master: [DEBUG    Nuvola] WebApp.vala:209: Theme icon nuvolaplayer3_test 48 not found.
    Master: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Amazon Cloud Player at /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player, version 5.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app 8tracks at /usr/share/nuvolaplayer3/web_apps/8tracks, version 5.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.5
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.18
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Groove at /usr/share/nuvolaplayer3/web_apps/groove, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Logitech Media Server at /usr/share/nuvolaplayer3/web_apps/logitech_media_server, version 2.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 3.2
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Plex Music at /usr/share/nuvolaplayer3/web_apps/plex, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SiriusXM at /usr/share/nuvolaplayer3/web_apps/siriusxm, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app SoundCloud at /usr/share/nuvolaplayer3/web_apps/soundcloud, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app TuneIn at /usr/share/nuvolaplayer3/web_apps/tunein, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Yandex Music at /usr/share/nuvolaplayer3/web_apps/yandex_music, version 1.4
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app YouTube at /usr/share/nuvolaplayer3/web_apps/youtube, version 1.3
    Master: [DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
    Master: [INFO     Nuvola] WebAppRegistry.vala:89: Using web app Amazon Cloud Player, version 5.3, data dir /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player
    Master: [DEBUG    Nuvola] MasterController.vala:463: Launch app runner for 'amazon_cloud_player': /usr/lib/nuvolaplayer3/apprunner -D -a /usr/share/nuvolaplayer3/web_apps/amazon_cloud_player
    Runner: [DEBUG      Gtk] Connecting to session manager
    Runner: [DEBUG    DioriteGtk] DesktopShell.vala:96: Shell: gnome shell 3.10.4, CSD 1, appmenu 1, menubar 0
    Runner: [DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
    Master: [DEBUG    Nuvola] MasterController.vala:287: Connected to runner server for 'amazon_cloud_player'.
    Runner: [DEBUG    Nuvola] Connection.vala:132: Network Proxy: system settings
    Runner: [DEBUG    Nuvola] WebEngine.vala:73: Nuvola WebKit Extension directory: /usr/lib/nuvolaplayer3
    Runner: [DEBUG    Nuvola] Notifications.vala:175: Notifications: persistence true, actions true, icons true
    Master: [DEBUG    Nuvola] MediaKeys.vala:101: GNOME settings daemon appeared: org.gnome.SettingsDaemon, :1.11
    Runner: [DEBUG    Nuvola] AppRunnerController.vala:449: Component tray_icon (Tray Icon) enabled
    Runner: [DEBUG    Nuvola] AppRunnerController.vala:449: Component unity_launcher (Unity Laucher) enabled
    Runner: [DEBUG    Nuvola] AppRunnerController.vala:449: Component notifications (Notifications) enabled
    Runner: [DEBUG    Nuvola] AppRunnerController.vala:449: Component mediakeys (Media keys) enabled
    Runner: [DEBUG    Nuvola] AppRunnerController.vala:449: Component scrobbler (Audio Scrobbler Services) not enabled
    Runner: [DEBUG    Nuvola] AppRunnerController.vala:449: Component mpris (MPRIS 2) enabled
    Runner: [DEBUG    Nuvola] AppRunnerController.vala:449: Component lyrics (Lyrics) enabled
    Runner: [DEBUG    Nuvola] AppRunnerController.vala:449: Component developer (Developer's tools) enabled
    Runner: [DEBUG    Nuvola] MPRISProvider.vala:73: Bus acquired: org.mpris.MediaPlayer2.NuvolaAppAmazonCloudPlayer, registering objects
    Runner: [DEBUG    Nuvola] MPRISProvider.vala:90: Bus name acquired: org.mpris.MediaPlayer2.NuvolaAppAmazonCloudPlayer
    Worker: [DEBUG    Nuvola] WebExtension.vala:220: Page 1 created for (null)
    Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded about:loading
    Runner: [DEBUG    Nuvola] WebEngine.vala:496: Navigation, current window: uri = https://music.amazon.com/recently/played?do=play&stationKey=A2CQU7NWJ892R6, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
    Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Trying to play /usr/share/nuvolaplayer3/audio/audiotest.mp3.
    Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from NULL to READY.
    Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from READY to PAUSED.
    Runner: [DEBUG    Nuvola] FormatSupport.vala:103: Pipeline state changed from PAUSED to PLAYING.
    Runner: [DEBUG    Nuvola] FormatSupport.vala:103: End of stream for file /usr/share/nuvolaplayer3/audio/audiotest.mp3.
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: iTunes Application Detector (enabled, not flash) at /usr/lib/mozilla/plugins/librhythmbox-itms-detection-plugin.so: This plug-in detects the presence of iTunes when opening iTunes Store URLs in a web page with Firefox.
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: VLC Multimedia Plugin (compatible Videos 3.10.1) (enabled, not flash) at /usr/lib/mozilla/plugins/libtotem-cone-plugin.so: The <a href="http://www.gnome.org/">Videos</a> 3.10.1 plugin handles video and audio streams.
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Windows Media Player Plug-in 10 (compatible; Videos) (enabled, not flash) at /usr/lib/mozilla/plugins/libtotem-gmp-plugin.so: The <a href="http://www.gnome.org/">Videos</a> 3.10.1 plugin handles video and audio streams.
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Google Talk Plugin Video Renderer (enablRunner: ed, not flash) at /usr/lib/mozilla/plugins/libnpo1d.so: Version: 5.41.3.0
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: DivX® Web Player (enabled, not flash) at /usr/lib/mozilla/plugins/libtotem-mully-plugin.so: DivX Web Player version 1.4.0.233
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Gnome Shell Integration (enabled, not flash) at /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so: This plugin provides integration with Gnome Shell for live extension enabling and disabling. It can be used only by extensions.gnome.org
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: QuickTime Plug-in 7.6.6 (enabled, not flash) at /usr/lib/mozilla/plugins/libtotem-narrowspace-plugin.so: The <a href="http://www.gnome.org/">Videos</a> 3.10.1 plugin handles video and audio streams.
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Shockwave Flash (enabled, flash) at /usr/lib/mozillaRunner: /plugins/libflashplayer.so: Shockwave Flash 11.1 r102
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Google Talk Plugin (enabled, not flash) at /usr/lib/mozilla/plugins/libnpgoogletalk.so: Version: 5.41.3.0
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Java(TM) Plug-in 11.121.2 (enabled, not flash) at /usr/lib/mozilla/plugins/libjavaplugin.so: Next Generation Java Plug-in 11.121.2 for Mozilla browsers
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Google Talk Plugin Video Renderer (enabled, not flash) at /usr/lib/firefox/plugins/libnpo1d.so: Version: 5.41.3.0
    Runner: [DEBUG    Nuvola] FormatSupportCheck.vala:145: Nuvola.WebPlugin: Google Talk Plugin (enabled, not flash) at /usr/lib/firefox/plugins/libnpgoogletalk.so: Version: 5.41.3.0
    Runner: [DEBUG    Nuvola] WebAppWindow.vala:170: Sidebar position: 1096
    Worker: [DEBUG    Nuvola] WebExtension.vala:130: Window object cleared for 'https://music.amazon.com/recently/played?do=play&stationKey=A2CQU7NWJ892R6'
    Worker: [DEBUG    Nuvola] WebExtension.vala:140: Init frame: https://music.amazon.com/recently/played?do=play&stationKey=A2CQU7NWJ892R6, 0x11fc6d0, 0xfd1470, 0x7fbaec09f4b0
    Runner: [WARNING  Nuvola] TiliadoAccount.vala:68: Failed to fetch project 'nuvolaplayer': Tiliado account session seems to be expired.
    Runner: [INFO     Nuvola] AppRunnerController.vala:236: Logged in as  ()
    Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded https://music.amazon.com/recently/played?do=play&stationKey=A2CQU7NWJ892R6
    Runner:
    (WebKitPluginProcess2:32000): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
    Runner: https://images-na.ssl-images-amazon.com/images/G/01/digital/music/player/web/assets/201718183840895/digitalMusicWebPlayer._CB535376405_.js:2:23302: CONSOLE WARN rxstores not found
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-pause
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-stop
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-play
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-go-previous
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-go-next
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: https://images-na.ssl-images-amazon.com/images/G/01/digital/music/player/web/assets/201718058408/cloudPlayerWeb_en_US._CB535313622_.js:6:2254: CONSOLE WARN Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-pause
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: can-stop
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: https://images-na.ssl-images-amazon.com/images/G/01/digital/music/player/web/assets/201718183840895/digitalMusicWebPlayer._CB535376405_.js:2:23302: CONSOLE WARN Prop trackMeta of TrackSourceLink is not type object-required
    Runner: [DEBUG    Nuvola] LyricsProvider.vala:103: Fetcher: NuvolaLyricsFetcherCache
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] LyricsProvider.vala:115: Fetch error: Song Down In A Hole (Album Version) was not found in cache
    Runner: [DEBUG    Nuvola] LyricsProvider.vala:103: Fetcher: NuvolaAZLyricsFetcher
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] LyricsProvider.vala:115: Fetch error: Song Down In A Hole (Album Version) was not found on AZ Lyrics
    Runner: [DEBUG    Nuvola] LyricsProvider.vala:103: Fetcher: NuvolaLyricsFetcherCache
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location
    Runner: [DEBUG    Nuvola] LyricsProvider.vala:115: Fetch error: Song No Rain was not found in cache
    Runner: [DEBUG    Nuvola] LyricsProvider.vala:103: Fetcher: NuvolaAZLyricsFetcher
    Runner: [DEBUG    Nuvola] DeveloperSidebar.vala:158: Media player notify: artwork-location

**Comment by fenryxo** [comment]
Hello @mshirley. Thanks for taking the time to report this issue. I need more information to investigate it further. Is it reproducible also in the WebKitGtk MiniBrowser? Run `/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser  https://music.amazon.com/` or `/usr/lib/i386-linux-gnu/webkit2gtk-4.0/MiniBrowser  https://music.amazon.com/` in the terminal.

**Comment by mshirley** [comment]
Confirmed it does still occur using the webkit minibrowser.  

Clicked "Stations", clicked "Top EDM", first song played, got to the end of the song and a new song did not play.  Song in the title bar is the song that played, time is at 0:00.

GLib errors occur before the end of the song.

``` 
$ /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser https://music.amazon.com/
(WebKitPluginProcess2:17138): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(WebKitPluginProcess2:17138): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

Using gnome 3.

```
$ gnome-session --version
gnome-session 3.9.90
```

**Comment by fenryxo** [comment]
Thanks @mshirley. Could you try a more recent WebKitGTK 2.12.2 from my PPA? https://launchpad.net/~nuvola-player-builders/+archive/ubuntu/webkit

That PPA is now unmaintained but still better than WebKit 2.8.5. In the long term, I recommend upgrading to Ubuntu 16.04 LTS as I'm going to drop support for Ubuntu 14.04 very soon.

**Comment by fenryxo** [comment]
Hello @mshirley. I'm closing this issue as I haven't received any response to my request for more information I posted on February 22nd, 2017. If the issue still persists, feel free to add missing information to reopen this ticket.
