### ISSUE TITLE
Service request: Yandex.Music

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#31]
From [Launchpad bug #1027989](https://bugs.launchpad.net/nuvola-player/+bug/1027989) by Gadjet:

Homepage: http://music.yandex.ru/

Note to self: It's in Russian. We need an user who speaks Russian to provide feedback during development.

:heart: [One Nuvola Patron](https://tiliado.eu/accounts/group/3/) is interested in this issue (note 14).

**Comment by sergey-podunov** [comment]
What kind of feedback do you need?

**Comment by fenryxo** [comment]
Hi Sergey. Once I finish the first version, I will need a feedback whether everything works as expected. For example, I could mismatch album name with track name without noticing.

**Comment by petRUShka** [comment]
Do you still need help from Russian-speaker?

**Comment by fenryxo** [comment]
Hi @petRUShka. Not now, but I will need a feedback when when I create an initial version of the integration script.

**Comment by fenryxo** [comment]
I need a reliable proxy server or VPN in Russia, Ukraine, Belarus, or Kazakhstan to proceed further. Any volunteer?

> По требованию правообладателей музыку на сервисе можно слушать только пользователям
из России, Украины, Беларуси и Казахстана.

> Due to copyright, only users from Russia, Ukraine, Belarus, and Kazakhstan
can listen to music on this service.

**Comment by petRUShka** [comment]
You can try VPN Gate. It should be free and there are russian servers: http://www.vpngate.net/en/

Or any of these services with free trial:
1. https://shadeyouvpn.com/ (24 hours free trial)
2. http://hideme.ru/vpn/ (24 hours free trial)
3. https://zenvpn.net/ru/vpn-locations/russia/ (free trial).

14.08.2015, 23:41, "Jiří Janoušek" <notifications@github.com>:
> I need a reliable proxy server or VPN in Russia, Ukraine, Belarus, or Kazakhstan to proceed further. Any volunteer?
>
>> По требованию правообладателей музыку на сервисе можно слушать только пользователям
>> из России, Украины, Беларуси и Казахстана.
>>
>> Due to copyright, only users from Russia, Ukraine, Belarus, and Kazakhstan
>> can listen to music on this service.
>
> —
> Reply to this email directly or view it on GitHub.

-- 
Максим.

**Comment by fenryxo** [comment]
Great, VPN Gate works. [Script is available for dowload](https://github.com/tiliado/nuvola-app-yandex-music/releases/tag/1.0). Will make packages later (tomorrow?).

**Comment by fenryxo** [comment]
Packages uploaded.

**Comment by petRUShka** [comment]
Could you please point where you uploaded package?

**Comment by fenryxo** [comment]
https://tiliado.eu/nuvolaplayer/repository/
