### ISSUE TITLE
Gnome 3 performance problem

### ISSUE THREAD

**Issue by librucha** [tiliado/nuvolaplayer#317]
I'm using Nuvoal player 3 Google play Music v. 5.18 and under gnome on Fedora 25 x64 and I have some performance problems.

![image](https://cloud.githubusercontent.com/assets/1335068/24755297/e28663ce-1ad9-11e7-80b7-998db0be7856.png)

Process 31648 takes 5 and half core until music is playing. During pause is everything normal.
On same computer under Cinnamon desktop is everything normal.

```
$ nuvolaplayer3 -a google_play_music -V
Nuvola Player 3 3.0.7
Revision b0fb0023f3c4699c4f79189082eae9b81f6230b1
WebKitGTK 2.16.0
libsoup 2.56.0
```

When google play music is running from normal chrome browser, everything is going normal.

```
$ google-chrome --version
Google Chrome 57.0.2987.133
```
![image](https://cloud.githubusercontent.com/assets/1335068/24755353/2b44616a-1ada-11e7-8a0b-3099eeabe84a.png)

Do you have any idea what can be wrong?

Thanks.

**Comment by fenryxo** [comment]
Hello @librucha. Thanks for taking the time to report this issue. I need more information to investigate it further.

* The debugging output from a terminal as specified in the [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines#debugging-output).
* Which GTK theme do you use? If it is not Adwaita, is the issue reproducible with Adwaita?

**Comment by librucha** [comment]
Hi.
Debug output is [here](https://gist.github.com/librucha/d7a4453549db1b9e500c6c689eb56b7e#file-output-txt).
Im using GTK theme **Arc-Dark** whis was preinstalled in my Gnome

**Comment by fenryxo** [comment]
Thanks @librucha. Is the issue reproducible if you switch to the Adwaita GTK+ theme?

**Comment by librucha** [comment]
Yes it is. Under default GTK+ theme Adwaita was behaviour same. [Here](https://gist.github.com/librucha/78e094b11ea592b22e50c5b748b7b1dc#file-output-under-adwaita-txt) is output. But interesting moment was when I clicked on close button. Performance was back to perfect and application was running on background without UI. One problem is, application have to be closed from terminal by killing process.

**Comment by fenryxo** [comment]
It looks as an issue with a graphics driver similar to #260.

> `Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory`

Could you install a package containing the `libvdpau_nvidia.so` library to be sure this error is not relevant?

**Comment by librucha** [comment]
It is interesting because I'm using Fedora included nouveau driver.
```
Installed Packages
Name        : xorg-x11-drv-nouveau
Arch        : x86_64
Epoch       : 1
Version     : 1.0.13
Release     : 1.fc25
Size        : 213 k
Repo        : @System
From repo   : fedora
Summary     : Xorg X11 nouveau video driver for NVIDIA graphics chipsets
URL         : http://www.x.org
License     : MIT
Description : X.Org X11 nouveau video driver.
```

**Comment by fenryxo** [comment]
That's a driver for X11. I don't claim to be an expert but I think VDPAU needs another set of drivers. I don't remember what's Fedora's command for "tell me which package contains libvdpau_nvidia.so". Could you find it out?

**Comment by librucha** [comment]
I tried change everything, but nothing worked.
In final I returned back to Cinnamon desktop on CentOS and now I'm using different software for playing Google Music on my desktop.

Thank you for your time.

**Comment by fenryxo** [comment]
That's a pity. It would be great to solve this issue for other users. Hopefully somebody else experiencing the same issue will report in someday.

**Comment by librucha** [comment]
OK I will try it on my new Centos GNOME. But I think problem was in my Nvidia driver, because I used kernel 4.10 and this one is not supported by Nvidia.
