### ISSUE TITLE
Arc themes for Flatpak distribution

### ISSUE THREAD

**Issue by excieve** [tiliado/nuvolaplayer#318]
Please consider adding support for [Arc theme](https://github.com/horst3180/Arc-theme) family for the Flatpak distribution. It's fairly popular among GNOME users. Thank you!

**Comment by fenryxo** [comment]
Hello @excieve. Thanks for your suggestion :-)

**Comment by fenryxo** [comment]
The preferences dialog currently crashes with the Arc theme. Need to find out why.

**Comment by fenryxo** [comment]
It should be fixed now. All three Arc theme variants are available. Could you check it, @excieve?

**Comment by fenryxo** [comment]
To update flatpaks, run `flatpak update` as sudo/root or you can use GNOME Software (3.22+). I should put this info somewhere.

**Comment by excieve** [comment]
Works great, thank you!
