### ISSUE TITLE
Service Request: Jamendo

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#32]
From [Launchpad bug #1031344](https://bugs.launchpad.net/nuvola-player/+bug/1031344) by makilakixki:

Jamendo home page: http://www.jamendo.com/

There are some patches for Nuvola Player 2 in the old bug report.
##

**Comment by forteller** [comment]
I'd like to add my voice to this. Jamendo is a service strictly for Creative Commons licensed music, and so a great thing for a Free Software Linux program like Nuvola to support :)

**Comment by fenryxo** [comment]
https://github.com/tiliado/nuvola-app-jamendo

**Comment by fenryxo** [comment]
Released with Nuvola 4.15.0, [more info](https://medium.com/nuvola-news/nuvola-4-15-released-ccf2e02e6d4e).
