### ISSUE TITLE
Flatpak installation on Arch can't start Google Play Music directly

### ISSUE THREAD

**Issue by Cybolic** [tiliado/nuvolaplayer#320]
I also posted this on the mailing list.

After installing Nuvola and the Google Play Music app I get the following error: 

```
$ flatpak run eu.tiliado.NuvolaAppGooglePlayMusic 
Runner: [WARNING Δ080509us Nuvola] AppRunnerController.vala:210: Master server error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name eu.tiliado.Nuvola was not provided by any .service files 
Runner: [WARNING Δ043420us Nuvola] Traits.vala:54: No requirements specified. 'Feature[flash] Codec[mp3]' used by default but that may change in the future. 
pure virtual method called 
terminate called without an active exception 
```

For reference, I installed everything as follows: 

```
sudo flatpak install --from https://nuvola.tiliado.eu/eu.tiliado.Nuvola.flatpakref 
sudo flatpak install --from https://nuvola.tiliado.eu/eu.tiliado.NuvolaAppGooglePlayMusic.flatpakref 
```

For what it's worth, the Nuvola application itself starts without issue but doesn't list the Google Play Music app.

## UPDATE since the mailing list post

Running `flatpak run eu.tiliado.Nuvola` in one terminal and `flatpak run eu.tiliado.NuvolaAppGooglePlayMusic` in another starts the Google Play Music app without issue.

## Version info
```
$ flatpak run eu.tiliado.Nuvola --version
Nuvola Apps 3.1.2+11.g03a5635
Revision 11.g03a5635
Diorite 0.3.3+3.g0c70498
WebKitGTK 2.16.1
libsoup 2.56.0
```

**Comment by fenryxo** [comment]
Hello @Cybolic. Thanks for taking the time to report this issue. Have you rebooted your system after the installation of flatpak?

**Comment by Cybolic** [comment]
Hello @fenryxo. Yes, I rebooted after initially installing flatpack (using `yaourt flatpak`), but not since.

**Comment by fenryxo** [comment]
There seems to be an issue with DBus activation of Flatpak apps on your system. Could you close all instances of Nuvola and then run `d-feet` and look at the Session Bus tab whether there is `eu.tiliado.Nuvola` dbus service with `activatable: yes`?

**Comment by Cybolic** [comment]
I had to install d-feet, but no, there's no such service under Session Bus (or System Bus for that matter).

**Comment by fenryxo** [comment]
What do `echo $XDG_DATA_DIRS` print on your system?

**Comment by Cybolic** [comment]
```
$ echo $XDG_DATA_DIRS
/home/cybolic/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
```
Looks correct to me :/

```
$ ls .local/share/flatpak/exports/share/dbus-1/services/
eu.tiliado.NuvolaAppGooglePlayMusic.data.service  eu.tiliado.NuvolaAppGooglePlayMusic.service  eu.tiliado.Nuvola.service
```
(I removed the Nuvola flatpak packages and reinstalled them with --user to see if it would help, hence the dir above - it didn't make any change)

**Comment by fenryxo** [comment]
The $XDG_DATA_DIRS looks correct. Could you install it once again as a system-wide flatpak (remove it with `--user` first) and reboot again?

**Comment by fenryxo** [comment]
If it doesn't help, I'd look at dbus session config files whether there is anything suspicious.

* /usr/share/dbus-1/session.conf
* /etc/dbus-1/session.d
* /etc/dbus-1/session-local.conf

**Comment by Cybolic** [comment]
That did indeed fix it. I suppose the installation instruction should be to reboot after installing the Nuvola base program or probably org.gnome.Platform.
Thanks for your help!

**Comment by fenryxo** [comment]
Well, during my testing, it was enough to reboot only after installation of flatpak to adjust the $XDG_DATA_DIRS variable. But I'll check that again.
