### ISSUE TITLE
Can't run Deezer flatpak in Debian Stretch

### ISSUE THREAD

**Issue by wheldrake** [tiliado/nuvolaplayer#325]
I can't run the lastest flatpak Debian Stretch. I run KDE with Flash installed and working. I can also use 3.1 debs without problem. This is the error I get:

Runner: [WARNING Δ148795us Nuvola] AppRunnerController.vala:210: Master server error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'eu.tiliado.Nuvola' on object at path /eu/tiliado/Nuvola
Runner: [WARNING Δ130486us Nuvola] Traits.vala:54: No requirements specified. 'Feature[flash] Codec[mp3]' used by default but that may change in the future.

**Comment by fenryxo** [comment]
Hello @wheldrake. That's interesting. I use the Deezer flatpak in Debian Stretch every day. It's the most tested one. I'll look at it when I arrive home.

**Comment by wheldrake** [comment]
I just installed RC3 yesterday night, installed kde-plasma-desktop on it with Phonon GStreamer backend. And that's all. So it is pretty vanilla.

**Comment by fenryxo** [comment]
Have you removed the deb-packaged Nuvola completely? It looks as if the Nuvola Runtime was installed (there would be "eu.tiliado.Nuvola is not provided by any .service files" error otherwise), but it doesn't contain the eu.tiliado.Nuvola interface, which is available only in flatpak builds but not in other builds.

**Comment by wheldrake** [comment]
I haven't even installed it. I only installed it after I couldn't get flatpak to work.

I will try in a new user after removing debs. Maybe there was some leftovers from my old disto that caused a problem. I'm using my /home without a format. I tried to clean but might have missed something. I will report back in 1 hour or so.

**Comment by wheldrake** [comment]
A new error with the new user:

Runner: [WARNING Δ397484us Nuvola] AppRunnerController.vala:210: Master server error: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._diorite_5ferror_2dquark.Code6: Nuvola refused connection.

**Comment by fenryxo** [comment]
That's better. Have Nuvola's window (not Deezer's) appeared?

**Comment by wheldrake** [comment]
Nuvola's windows appears, then detaches itself from the terminal. Nuvola windows works, I can open settings, authenticate, but I cannot start Deezer.

**Comment by fenryxo** [comment]
Could you post a screenshot of the window when you are authenticated and Deezer is selected in the selector? There should be an info bar with version etc.

**Comment by wheldrake** [comment]
Here: http://i.hizliresim.com/kbR0BW.png

**Comment by fenryxo** [comment]
It is necessary to obtain a complete debuging output then. Close all Nuvola windows and then run
`flatpak run eu.tiliado.Nuvola//stable --debug` in the first terminal windows, then `flatpak run eu.tiliado.NuvolaAppDeezer//stable --debug` in the second one and attach the logs as text files here..

**Comment by fenryxo** [comment]
I take it back. I have found a bug. Building fixed version right now.

**Comment by fenryxo** [comment]
Could you run `flatpak update` and try again?

**Comment by wheldrake** [comment]
Yes, works perfectly now. Thank you!

**Comment by fenryxo** [comment]
You're welcome. Happy listening and thanks for reporting this issue and your patience 👍
