### ISSUE TITLE
nuvolaplayer keeps to create other copy of the .desktop file in ~/.local/share/applications

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvolaplayer#328]
It seems that the nuvola apps, although packaged into RPM and providing their own .desktop files, nuvolaplayer keeps to create other copy of the .desktop file in ~/.local/share/applications/, is there any way how to control this behavior?

bugzillla ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1441828#c3

**Comment by fenryxo** [comment]
Nuvola doesn't create desktop files any more since c521e11
