### ISSUE TITLE
DNS Failure with DNSMasq

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#329]
@MetricMike commented on [Thu Apr 27 2017](https://github.com/tiliado/tiliado-repositories/issues/21)

Running the Spotify app gives me `Error resolving 'play.spotify.com': Temporary failure in name resolution` and a dialog error titled "Integration error" with `Failed to inject JavaScript API. Function 'Nuvola.core.emit' failed. file:///app/share/nuvolaplayer3/web_apps/spotify/integrate.js:99: SecurityError: The operation is insecure. The application might not function properly.`

The two changes I made which I think led to this were installing dnsmasq (directs *.dev to 127.0.0.1) and disabling DNSStubListener on systemd-resovlerd. I believe this has the consequence of forcing DNS lookups through DNSMasq, but I'm not 100%.

Using the official Spotify client or the web player through Chrome work fine. 

Any ideas? 

---

`flatpak list`
```
eu.tiliado.Nuvola/x86_64/stable           system,current
eu.tiliado.NuvolaAppSpotify/x86_64/stable system,current
org.gnome.Platform.Locale/x86_64/3.22     system,runtime
org.gnome.Platform/x86_64/3.22            system,runtime
```
`flatpak info eu.tiliado.NuvolaAppSpotify`
```
app/eu.tiliado.NuvolaAppSpotify/x86_64/stable nuvola c91cf23a8d3beffdf30f43fb333c7b6c7f20ef234395ac8d1a7edb1154a5945c 223.0 MB
```
`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```
`uname -r`
```
4.10.0-20-generic
```

**Comment by fenryxo** [comment]
Hello @MetricMike. Thanks for taking the time to report this issue. What the following commands say?

```
flatpak run --command=bash eu.tiliado.NuvolaAppSpotify//stable
cat /etc/resolv.conf
```

Is that the same as if you run `cat /etc/resolv.conf` outside flatpak?

**Comment by MetricMike** [comment]
Yep both return:

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.1
```

**Comment by fenryxo** [comment]
Thanks @MetricMike. I'm going to add a DNS lookup tool to the Nuvola flatpaks to investigate this issue further.

**Comment by fenryxo** [comment]
I've added `drill` to the Nuvola CDK flatpak. Could you run following commands:

* `flatpak remote-list` to find out the name of Nuvola's remote, e.g. `eu.tiliado.Nuvola-origin`.
* `sudo flatpak install eu.tiliado.Nuvola-origin eu.tiliado.NuvolaCdk//stable` to install Nuvola CDK
* `flatpak run --command=bash eu.tiliado.NuvolaCdk//stable` to launch Nuvola CDK and then
* `drill google.com`
* `drill play.spotify.com`

**Comment by MetricMike** [comment]
both `drill google.com` and `drill play.spotify.com` return:
`Error: error sending query: Could not send or receive, because of network error`

But then I found https://github.com/flatpak/flatpak/wiki/Sandbox#the-current-flatpak-sandbox, which led me to:
```bash
bash-4.3$ ls -lah /etc/resolv.conf 
lrwxrwxrwx 1 weigle@DCCC.LAN domain users@DCCC.LAN 29 May  2 14:26 /etc/resolv.conf -> /run/host/monitor/resolv.conf
bash-4.3$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.0.1
```
Which clears this up for me - 127.0.0.1 is a valid nameserver on my host (DNSMasq is listening on that address), but not inside flatpak (no local DNS server). I think this is a flatpak issue (or a bad DNSMasq configuration on my part), so I think you can probably close this?

**Comment by fenryxo** [comment]
[Could you report this issue to Flatpak](https://github.com/flatpak/flatpak/issues/new) and post here a reference?

**Comment by fenryxo** [comment]
Closing in favour of flatpak/flatpak#759
