### ISSUE TITLE
Remove packages for old distributions

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#333]
They do no good.

**Comment by fenryxo** [comment]
DEB and RPM repos purged, docs need to be updated.

**Comment by SvenDub** [comment]
Is Debian Jessie no longer supported? I can't find it in the repository anymore.

**Comment by fenryxo** [comment]
Hello @SvenDub. [Debian Jessie is still supported in the Nuvola 3.1.x series](https://nuvola.tiliado.eu/#!nuvola!debian!jessie). Support in 3.0.x series has been dropped because these builds use system WebKitGTK library, which is very old in Debian Jessie. WebKitGTK+ 2.6.2 is full of security vulnerabilities and bugs that make some web pages not to work properly. I cannot support that.

**Comment by SvenDub** [comment]
I see, that makes sense.

Thanks for the reply!

**Comment by fenryxo** [comment]
Announced: [Nuvola Drops Support for Old Distributions](https://medium.com/nuvola-news/nuvola-drops-support-for-old-distributions-c73b39b741eb)
