### ISSUE TITLE
questions about different files in the source code

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvolaplayer#334]
we are working on packaging nuvolaplayer for Fedora and have a few questions for that.

* Bundled engine.io library?
  - It seems engine.io library is bundled by nuvolaplayer. Is it required for
    something?

* What is the purpose of %{_datadir}/nuvolaplayer3/web_apps/test
  - Is the content of the directory used somewhere?

* What is the purpose of %{_datadir}/nuvolaplayer3/audio
  - Is the .mp3 file used somewhere for something?

**Comment by fenryxo** [comment]
> Bundled engine.io library? It seems engine.io library is bundled by nuvolaplayer. Is it required for        something?

Engine.io is not a bundled library in the meaning as a copy of an independent library. It just hasn't been separated into and independent library yet. Engineio is used in some experimental features which are not built by default yet but that may change in the future.

> What is the purpose of %{_datadir}/nuvolaplayer3/web_apps/test. Is the content of the directory used somewhere?

This is a test service to test various features of Nuvola (`nuvola -D -a test`). It may be helpful when you need provide your users with support. It might go to devel subpackage though.

> What is the purpose of %{_datadir}/nuvolaplayer3/audio. Is the .mp3 file used somewhere for something?

The mp3 file is used to check that gstreamer can play mp3 files.

**Comment by martinkg** [comment]
> > * What is the purpose of %{_datadir}/nuvolaplayer3/audio
> >   - Is the .mp3 fie used somewhere for something?
> > 
> The mp3 file is used to check that gstreamer can play mp3 files.

How to do that? Is this available somewhere in UI? Is this available somewhere to end user? I'd suggest to not ship the file unless it proves we are missing it for something ...

**Comment by fenryxo** [comment]
> How to do that? 

It is done on Nuvola's start-up automatically.

> Is this available somewhere in UI? Is this available somewhere to end user?

Yes, in the Format support dialog.

> I'd suggest to not ship the file unless it proves we are missing it for something ...

Hm, I should check the code to find out how Nuvola behaves in that case and make sure it won't crash.

**Comment by fenryxo** [comment]
> Hm, I should check the code to find out how Nuvola behaves in that case and make sure it won't crash.

It doesn't crash but format support check doesn't work then.

**Comment by fenryxo** [comment]
> It doesn't crash but format support check doesn't work then.

Nuvola now aborts when the mp3 file is not available rather then running with errors in the background.

**Comment by martinkg** [comment]
> Bundled engine.io library? It seems engine.io library is bundled by nuvolaplayer. Is it required
> for something?

>> Engine.io is not a bundled library in the meaning as a copy of an independent library. It just hasn't >> >> been separated into and independent library yet. Engineio is used in some experimental features >> >> which are not built by default yet but that may change in the future.

Frankly, I am not very satisfied with upstream response, since this [2]
commit clearly links engine.io.js file from different upstream repository.
Moreover, the .js file is in two copies currently in the source code ...

[2] https://github.com/tiliado/nuvolaplayer/commit/56171f4d021d65adebf1ae234ba3218a2ba9ad11

**Comment by fenryxo** [comment]
I see. I thought you talked about libengineio-soup - the Vala port of engineio. It didn't occur to me there is also engine.io.js. That could be unbundled.  However, I have no idea what is the typical filesystem location for JavaScript libraries. Let's continue at #341.

**Comment by voxik** [comment]
>> It doesn't crash but format support check doesn't work then.
>
> Nuvola now aborts when the mp3 file is not available rather then running with errors in the background.

Just FTR, the behavior of 3.1.3 was a bit strange. I was testing this with the "test" plugin and when I completely removed the .mp3 file, the plugin just started without any questions. Once I had the file in place, Nuvola started to complain about missing mp3 gstreamer plugin. Once I installed it (BTW there is now gstreamer1-plugin-mpg123 officially available F25+, so you probably want to recommend this in documentation) it complained about missing flash. I did not tried further but not sure if Nuvola should skips the checks when the mp3 file is missing.

**Comment by fenryxo** [comment]
>  I was testing this with the "test" plugin and when I completely removed the .mp3 file, the plugin just started without any questions.

But with errors in the background. This is a bug and it has been fixed in master. The code just assumed that Nuvola was installed correctly.

> Once I had the file in place, Nuvola started to complain about missing mp3 gstreamer plugin. 

That's correct behaviour.

> Once I installed it [...] it complained about missing flash.

That's correct behaviour.

> there is now gstreamer1-plugin-mpg123 officially available F25+, so you probably want to recommend this in documentation

Nuvola 3.1 doesn't have any distro-specific documentation on format support ([downstream is supposed to do that](https://github.com/tiliado/nuvolaplayer/wiki/Web-App-Requirements)), but I'll update docs for Nuvola 3.0 (#343).
