### ISSUE TITLE
rpmlint reports: W: shared-lib-calls-exit /usr/lib64/libnuvolaplayer3-runner.so exit@GLIBC_2.2.5

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvolaplayer#340]
rpmlint -i -v /home/martin/rpmbuild/RPMS/x86_64/nuvolaplayer-3.1.3-4.fc25.x86_64.rpm

nuvolaplayer.x86_64: W: shared-lib-calls-exit /usr/lib64/libnuvolaplayer3-runner.so exit@GLIBC_2.2.5
This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.

**Comment by fenryxo** [comment]
libnuvolaplayer3-runner.so contains the main application logic, so it ok to call exit(). Anyway, it does so only as a last resort when WebKitWebProcess hangs.
