### ISSUE TITLE
Add local database of played tracks/videos

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#346]
[Andrew Stubbs wrote](https://groups.google.com/d/msg/nuvola-player-devel/aoZkOegzUiw/cp9C8n7RAwAJ):

> This isn't interesting for music sites, nor for sites like YouTube that already track what you watch, but it might be nice if Nuvola could track which videos/podcasts/etc have been watched or listened to, and store that data locally (although, a Gpodder integration might be a nice stretch goal).
>
> Have there been any thoughts or plans about this already? I did have a specific site in mind, but I'm just asking, for now.

Follow-up:

> I was asking if there were any existing plans. It sounds like the answer is "no". :-)

> Either of those options would be fine. Some players might make it possible to record the last-known playback location, in other cases it might be possible to differentiate between playback stopping on its own vs. stopping following user input. If Nuvola were to provide the database API then support for both might be nice.

> Given the regular JS local storage capabilities, it ought to be possible for the integration script to do whatever it chooses, but a unified Nuvola approach might be better (or might be pointless).

> I was thinking it might be nice to overlay an icon on the thumbnail links to watched/unwatched pages, as recognised by URL. There doesn't have to be super-complicated detection to make that work.

**Comment by fenryxo** [comment]
Hello @a-m-s. What Nuvola JavaScript API would you wish to have implemented for your needs?

**Comment by a-m-s** [comment]
Initially, I was thinking of having a simple mapping from a URL to a true/false state. The integration script would then lookup each link in a playlist page (for example), and inject some sort of "played" overlay symbol on the links marked "true" in the database. Absence of a URL in the database would be the same as "false". When a particular podcast's URL is visited, and playback is detected, the integration script would set the mapping to "true".

A more advanced implementation might well record the playback position, and use that to support resume.

As far as the API is concerned, all that is really needed is a means to record arbitrary data (a string, perhaps), using a unique string as the key (which may, or may not be derived from a URL).

So far, all this can be done using using the browser's built in local storage mechanism. The point of a Nuvola database might be to support cross device syncing (via Dropbox, say), or maybe to have some kind of plugin-independent playback history list. These extra features are the only reason to impose any particular database schema.

I propose something like this:

Schema:
   String ID    (unique)
   String URL
   String Name
   Time Length  
   Time LastKnownPosition
   Boolean Played

API:
   state lookup_db (ID)
      Returns one of PLAYED, UNPLAYED, PARTIAL, NEW, where it's new if it's not in the database yet,
      and considered partial according to playback position and possibly user settings.
   create_db (ID, URL, name, length)
      Create a new entry for an as-yet-unplayed entry. It will not be NEW next time it is seen.
   set_db_played (ID, state, position)
      Update an existing entry with updated tracking info.

The ID might typically be the same as the URL, but not all sites have a unique page per podcast, track, etc. so the integration script may need to find some other identifier to use. Nuvola itself might want to present the URL as a link (now or in future), so it's useful to have it identifiable (although, in the case of a non-unique URL, I'm not sure how it helps the user find the specific item again).

Of course, given the new playback position reporting feature, and the fact that Nuvola already knows the URL and track name, it's possible that Nuvola could fill in the database automatically, even for plugins not using the API.

Finally, it might be useful if Nuvola provided standard overlay graphics for displaying state in pages. This might help keep the tool more cohesive and allow the plugins to remain lean.

**Comment by a-m-s** [comment]
Hmm, perhaps also add a "custom" string field to the database schema so that plugins can store JSON or something that Nuvola doesn't need to understand.

**Comment by fenryxo** [comment]
I propose following API based on your feedback:

**TrackInfo**
* id: integer, primary key, not null, autoincrement [internal property for Nuvola]
* key: string, unique index, null [for scripts which other properties are not suitable for]
* url: string, unique index, null [for your use case]
* title: string, null [title + artist will be used by Deezer]
* artist: string, null
* album: string, null
* length: integer [usec], not null, default 0
* last_position: integer [usec], not null, default 0
* farthest_position: integer [usec], not null, default 0
* played: bool, not null, default false
* rating: double, not null, default 0.0 [for #284]
* custom: string [JSON], null

**TrackDatabase.lookupRecords(params)**
* params object contains key-value pairs to look for, e.g. `{url: "http://..."}`, `{title: "Happy Day", artist: "Happy Band"}` or `{key: "whatever"}`.
* returns array of matching TrackInfo objects (the array can be empty)

**TrackDatabase.getRecord(params)**
* Similar to lookupRecords but returns a single record if there is only one match, `null` if there is no match or throws error if there are more than one matches.

> create_db (ID, URL, name, length) Create a new entry for an as-yet-unplayed entry. It will not be NEW next time it is seen.
> set_db_played (ID, state, position) Update an existing entry with updated tracking info.

This should be done automatically by **MediaPlayer.setTrackInfo**. It just needs to be extended to support `key`, `url`, `played` and `custom`. If `played` or `custom` are `null/undefined`, these properties are unchanged in db.

> state lookup_db (ID) Returns one of PLAYED, UNPLAYED, PARTIAL, NEW, where it's new if it's not in the database yet, and considered partial according to playback position and possibly user settings.

This should be implemented by individual scripts as a wrapper around TrackDatabase.getRecord(params) first. Once it settles a bit, it can be moved to Nuvola Runtime.

>  Nuvola already knows the URL

Nuvola doesn't know the URL of a track. It knows the URL of currently loaded page but doesn't make any assumptions whether it is track/album/artist/whatever URL. URL must be explicitly set by **MediaPlayer.setTrackInfo**.

**Comment by a-m-s** [comment]
Looks good. Maybe it should also record which plugin each record is associated with?

**Comment by fenryxo** [comment]
> Maybe it should also record which plugin each record is associated with?

That's a good idea.

Since database queries will involve two IPC calls (web worker process → app runner process → master process), the database API must be asynchronous. I need to study how [Promises](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) work for that.

**Comment by fenryxo** [comment]
Well, async JavaScript might lead to the callback hell unless async & await are used. These features are available in Safari 10.1 but the latest stable WebKitGTK contains WebKit of Safari 10.0. I'll look at the development branch of WebKitGTK to check the situation there. The next stable GNOME release 3.26 is scheduled for September 13 and a new stable WebKitGTK series should be available as well by that time.

**Comment by fenryxo** [comment]
>  I'll look at the development branch of WebKitGTK to check the situation there. 

WebKitGTK 2.17.5 supports `async/await`.

**Comment by fenryxo** [comment]
Closing in favor of #414.
