### ISSUE TITLE
Flashplayer not recognized

### ISSUE THREAD

**Issue by Scolari** [tiliado/nuvolaplayer#347]
Master: [INFO     Nuvola] WebAppRegistry.vala:89: Using web app Spotify, version 2.2, data dir /usr/local/share/nuvolaplayer3/web_apps/spotify
Worker: [DEBUG    Nuvola] WebExtension.vala:220: Page 1 created for (null)
Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded about:loading
Runner: [INFO     Nuvola] config.vala:260: Config saved to /home/scolari/.config/nuvolaplayer3/apps_data/spotify/config.json
Worker: [DEBUG    Nuvola] WebExtension.vala:130: Window object cleared for 'https://play.spotify.com/browse'
Worker: [DEBUG    Nuvola] WebExtension.vala:140: Init frame: https://play.spotify.com/browse, 0x81802a670, 0x81802a790, 0x80ad2f4b0
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [CRITICAL  Json] json_node_get_parent: assertion 'JSON_NODE_IS_VALID (node)' failed
Runner: [CRITICAL  Json] Application will not function properly.
Runner: [CRITICAL  GLib] g_ptr_array_remove_index: assertion 'index_ < rarray->len' failed
Runner: [CRITICAL  GLib] Application will not function properly.
Runner: [INFO     Nuvola] AppRunnerController.vala:236: Logged in as  ()
Runner: Gtk-Message: Failed to load module "canberra-gtk-module"
Worker: [DEBUG    Nuvola] WebExtension.vala:291: Document loaded https://play.spotify.com/browse
Runner: Gtk-Message: Failed to load module "canberra-gtk-module"
Runner: https://www.googleadservices.com/pagead/conversion.js:2:772: CONSOLE ERROR Blocked a frame with origin "https://4721227.fls.doubleclick.net" from accessing a frame with origin "https://play.spotify.com". Protocols, domains, and ports must match.
Runner: https://www.googleadservices.com/pagead/conversion.js:3:443: CONSOLE ERROR Blocked a frame with origin "https://4721227.fls.doubleclick.net" from accessing a frame with origin "https://play.spotify.com". Protocols, domains, and ports must match.
Runner: *** NSPlugin Wrapper *** ERROR: NPP_WriteReady() invoke: Broken pipe
*** NSPlugin Wrapper *** WARNING:(/wrkdirs/usr/ports/www/nspluginwrapper/work/nspluginwrapper-1.4.4/src/npw-wrapper.c:2705):invoke_NPP_Write: assertion failed: (rpc_method_invoke_possible(plugin->connection))
Runner: *** NSPlugin Wrapper *** WARNING:(/wrkdirs/usr/ports/www/nspluginwrapper/work/nspluginwrapper-1.4.4/src/npw-wrapper.c:2550):invoke_NPP_DestroyStream: assertion failed: (rpc_method_invoke_possible(plugin->connection))

**Comment by fenryxo** [comment]
Hello @Scolari. Thanks for reporting the issue. It seems there is a crash in nspluginwrapper.

```
*** NSPlugin Wrapper *** ERROR: NPP_WriteReady() invoke: Broken pipe
*** NSPlugin Wrapper *** WARNING:(/wrkdirs/usr/ports/www/nspluginwrapper/work/nspluginwrapper-1.4.4/src/npw-wrapper.c:2705):invoke_NPP_Write: assertion failed: (rpc_method_invoke_possible(plugin->connection))
*** NSPlugin Wrapper *** WARNING:(/wrkdirs/usr/ports/www/nspluginwrapper/work/nspluginwrapper-1.4.4/src/npw-wrapper.c:2550):invoke_NPP_DestroyStream: assertion failed: (rpc_method_invoke_possible(plugin->connection))
```

For this reason, I believe there is nothing to do about that in Nuvola. I can only recommend not using nspluginwrapper but  [Adobe Flash plugin with NP API](https://get.adobe.com/flashplayer/).
