### ISSUE TITLE
 Service Request: Songza

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#36]
From [Launchpad bug #1048347](https://bugs.launchpad.net/nuvola-player/+bug/1048347) by Bennett Kanuka:

Please add support for Songza (songza.com)

There are patches for Nuvola Player 2 in the old bug tracker.
##

**Comment by dericke** [comment]
I think this can be closed, as Songza was acquired by Google and merged into Play Music.

**Comment by fenryxo** [comment]
Ok, thanks for info 👍
