### ISSUE TITLE
Add listening history panel

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#414]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Track all listened to tracks across services and show them in listening history.

## Details from reporter

As in MellowPlayer ([source](https://www.omgubuntu.co.uk/2017/08/mellowplayer-cloud-music-app-qt?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+d0od+(OMG!+Ubuntu!))):
![mellowplayer-recent-history-panel](https://user-images.githubusercontent.com/853706/36857456-e20e1570-1d78-11e8-811e-55ee044bb949.jpg)

Some implementation details were discussed in #346.

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
