### ISSUE TITLE
Deezer eats a lot of memory

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#467]
* Demo Player app consumes 39 MB and it doesn't rise up at all.
* Deezer starts with 46 MB (that's ok) and keeps rising up (800 MB overnight).
* Is it a bug in Nuvola (but not reproducible with the demo app)? Or in Chromium Embedded Framework?
* How about other scripts?

**Comment by fenryxo** [comment]
After one hour: Deezer +130 MB, Spotify +10 MB.

**Comment by fenryxo** [comment]
> How about other scripts?

Spotify is ok.
