### ISSUE TITLE
Improve developer documentation

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#474]
* Explain how to get the active version of Nuvola SDK/ADK/CDK.
  - SDK: `nuvolasdk --version`
  - ADK: `nuvolaruntime --version`
  - CDK: `run-service --version`
* Explain that the latest installed flatpak might not be the one which is actually running.
  - If you are in a Bash session of Nuvola ADK and you update the ADK flatpak, the old flatpak is still in use until all its instances exit. (This way, it won't happen that a running flatpaked app crashes because its data files have suddenly changed because of a pending update.)
* Document the current release process:
  * Always update the changelog, but don't touch version numbers in `metadata.in.json`.
  * If you wish to have a code review, create a pull request to the master branch.
  * If you don't need a code review, commit  directly to the master branch.
  * Whatever is in the master branch is included in the next rebuild of Flatpaks.
  * Once for a while, I make a new X.Y.0 release of Nuvola and all components for third-party packagers. That's when the `version_minor` field gets updated.
* Port developer docs to the new webgen
  - Include the current Nuvola ADK wiki page
  - Include the current Nuvola CDK wiki page

**Comment by fenryxo** [comment]
* Changelogs: If there are any unreleased changes, the toplevel list of changes should not have any heading. Rationale: The future release date is unknown and the next version may also be different (e.g., 1.7 → 2.0 instead of 1.7 → 1.8).

```
Changelog
=========

* Require Nuvola 4.13.
* Integrate repeat state.

1.7 -  September 21st, 2018
-----------------------------------

* Integrate volume management.
* Adjust to the changes of web UI.
```
