### ISSUE TITLE
LIRC Control Support

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#49]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Control Nuvola with a remote infrared controller.

## Details from reporter

From Launchpad bug by Bobby Graese:

Support for using LIRC to control Nuvola. Currently, this can be done using some hackery by making LIRC emit key strokes via a third party program, but it would be awesome if this support was built right in to Nuvola itself. This would make Nuvola useful in, for example, HTPC applications, where a keyboard often isn't available.

[1] LIRC homepage http://www.lirc.org/
[2] How to write LIRC client http://www.lirc.org/html/technical.html#applications
[3] Learn how to control everyone's favourite XMMS with a TV remote http://www.lirc.org/Remote%20Control%20XMMS.pdf

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
