### ISSUE TITLE
Inhibit screensaver when music/video is playing

### ISSUE THREAD

**Issue by Mykolajchik** [tiliado/nuvolaplayer#503]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add an option to inhibit a screensaver when music/video is playing.

## Details from reporter

User story: When using YouTube Music and YouTube, the screensaver is turned on in these apps. It's not convenient.

**Comment by fenryxo** [comment]
Hello @Mykolajchik, thanks for your feature request.

Note to self: Draw inspiration from [SimpleScan](https://gitlab.gnome.org/GNOME/simple-scan/commit/ac2f26557e26a2180276724c60864cfa125ac876).

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
