### ISSUE TITLE
Full-screen mode

### ISSUE THREAD

**Issue by murtezayesil** [tiliado/nuvolaplayer#514]
I have an issue with everything that doesn't have to be on screen but takes space anyway. I have 1366x768 resolution screen and title-bar + toolbar + GNOME bar on the top take around 15% of the screen together.

**A clear and concise description of what you want to happen. What are the benefits and drawbacks?**

I want F11 keyboard event (aka click) to toggle full screen just like in web browsers.
Drawbacks:
 1. toolbar won't be accessible while in full-screen. Solution: toolbar menu appears when ALT was clicked just like in Vivaldi browser.

**Describe alternatives you've considered:**

App starts full-screen and switched to windowed mode when F11 clicked

**Add any other context or screenshots about the feature request here.**

Before (Windowed mode)
![Screenshot from 2019-04-29 00-08-41](https://user-images.githubusercontent.com/24689015/56868345-08702180-6a13-11e9-9bf1-0b7b3db1591f.png)
After (Full Screen - I actually launched Yandex Music on Vivaldi to show that)
![Screenshot from 2019-04-29 00-13-58](https://user-images.githubusercontent.com/24689015/56868394-c2678d80-6a13-11e9-9de1-a8d27791f050.png)

**Comment by fenryxo** [comment]
Hello @murtezayesil. Thanks for your feature request. Adding F11 to toggle fullscreen mode is a good idea. Meanwhile, there are two ways to get more space:

- You can join the title bat and toolbar: Menu → Preferences → Appearance tweaks → toggle off Use system window decorations.
- You can collapse the toolbar: Menu → untick Show toolbar.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.

**Comment by murtezayesil** [comment]
Don't worry about it. Sad to see this project going away. I wish you success in life and in your future endeavors.

Last Questions:
Will the last compiled binaries be available after 2022?
Will source code stay on GitHub as archived for future reference?
I read your post on medium but it doesn't really explain what will happen to source code after 31st December 2022.

**Comment by jiri-janousek** [comment]
All Nuvola Player source code repositories will stay archived on GitHub.

The Flatpak repository is likely to go down unless somebody else offers to host it elsewhere. That is to be decided in November 2022. Users who purchased a lifetime license on Gumroad will receive a snapshot of the whole flatpak repository.
