### ISSUE TITLE
Support for Netflix 

### ISSUE THREAD

**Issue by ghost** [tiliado/nuvolaplayer#518]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature request

Add support for Netflix with resource-optimized playback.

## Details from reporter

Hello!

Could you add a webapp for Netflix please?

They do an excellent job ;)

**Comment by fenryxo** [comment]
Hello @CristhianEcheverry, thanks for your suggestion but you really don't want Netflix in Nuvola. Video playback needs a lot of resources so it must be as optimized as possible. Nuvola will always provide a worse experience than Google Chrome. I cannot guarantee accelerated video decoding and fullscreen mode in Nuvola is buggy.

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by Strykar** [comment]
This might be cool if it could integrate https://github.com/truedread/netflix-1080p

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
