### ISSUE TITLE
Time issue on SiriusXM app

### ISSUE THREAD

**Issue by Shak7** [tiliado/nuvolaplayer#532]
Hi,

I'm using the SiriusXM app with Nuvola and I was wondering if it is possible to adjust the time or change the time zone somewhere because the time near the "play/skip" controls of the app is always an hour behind. It does not make any problems whatsoever, it's just 1 hour behind..

Thank you, Nuvola is great and easy to use, I love using it!

**Comment by fenryxo** [comment]
Hello @Shak7. Thanks for reporting the issue. I'm going to look at it at the weekend.

**Comment by fenryxo** [comment]
I was sick during the weekend but I hope to look at it this week.

**Comment by Shak7** [comment]
Thank you, hope you feel better!

**Comment by fenryxo** [comment]
I'm afraid I cannot reproduce the issue. The time is usually correct for me (at 5:40 p.m.):

![image](https://user-images.githubusercontent.com/853706/61580725-4ca42700-ab15-11e9-902d-e39c84d78bc5.png)

It is sometimes *completely* wrong but consistent with what other web browsers (Chrome and Firefox) show:

![image](https://user-images.githubusercontent.com/853706/61580730-57f75280-ab15-11e9-8ae2-271babc6242a.png)

**Comment by fenryxo** [comment]
Are both values (start & end) one hour behind for you?

**Comment by Shak7** [comment]
Yes, both values are one hour behind and values were always right when I tried other browser.

Thanks for the follow up!
