### ISSUE TITLE
Android client to control Nuvola Player remotely

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#54]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Introduce an Android client to control Nuvola Player remotely over Bluetooth or network.

## Details from reporter

From [Launchpad bug #1254434](https://bugs.launchpad.net/nuvola-player/+bug/1254434) by reremi59@hotmail.fr:

Is it possible to set up a service for remote control for android Google Music? It would serve to wander through the various music / radio, add to the queue, pause or play the next song. In summary as a service "spotcommander" for "spotify"

https://code.google.com/p/spotcommander/

:exclamation:  This issue depends on #19 

* [Universal Android Music Player Sample](https://github.com/googlesamples/android-UniversalMusicPlayer)
* https://www.binpress.com/tutorial/using-android-media-style-notifications-with-media-session-controls/165
* http://www.tutorialsface.com/2015/08/android-custom-notification-tutorial/
* http://stackoverflow.com/questions/34487872/media-player-controls-in-notification

Android Wear
-----------------

Android Wear automatically builds media notifications with play controls when you register a [RemoteControlClient][1] or its Android 5.0 replacement, [MediaSession][2], using the transport flags you provide to determine which buttons to show and how responses get sent to your app. ([Source](http://stackoverflow.com/questions/27122675/how-to-get-the-music-player-buttons-on-android-wear-like-google-play-music))

  [1]: http://developer.android.com/reference/android/media/RemoteControlClient.html
  [2]: http://developer.android.com/reference/android/media/session/MediaSession.html

**Comment by KruyKaze** [comment]
This would be great if it had android wear support where you could pause , skip , thumbs up/down.

**Comment by fenryxo** [comment]
> This would be great if it had android wear support where you could pause , skip , thumbs up/down.

Unfortunately, I don't have any Android Wear device to test this on.

**Comment by KruyKaze** [comment]
I think the android sdk does this automatically. All you have to do is
enable wear support via a checkmark.
Thanks

**Comment by fenryxo** [comment]
You're right: http://stackoverflow.com/a/27143556/991303

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by pedrofleck** [comment]
Is this really necessary? I mean, it is kinda complex to build an Android app from the scratch and you can do it with existing apps like KDE-connect (and I'm pretty sure there are other apps that can do it out there).

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
