### ISSUE TITLE
Feature: Add Airsonic support

### ISSUE THREAD

**Issue by eharris** [tiliado/nuvolaplayer#545]
Airsonic is a free fork of Subsonic (which had a support request in #57) but likely has diverged enough to warrant its own support.

As noted in the original ticket here (https://bugs.launchpad.net/nuvola-player/+bug/1325741), since Airsonic (and other Subsonic derivatives) already have an API, a web-based interface is not really necessary, but for reasons of convenience and having all your music services accessible from the same player, it would be nice to have a web-based integration for Airsonic in Nuvola.

---

* [Homepage](https://airsonic.github.io/)
* [Stand-alone WAR installation](https://airsonic.github.io/docs/install/war-standalone/)

**Comment by fenryxo** [comment]
Hello @eharris. Thanks for your feature request.

**Comment by johnmurrayvi** [comment]
I would also appreciate Airsonic support. It's been my de facto media player after GPM shutdown. This is an old issue, so I wanted to say that there is still desire for this, in case it's at risk of being closed like #57.
Thanks!

**Comment by fenryxo** [comment]
Hello @eharris & @johnmurrayvi, Airsonic integration has been added:

* [Flatpak package](https://nuvola.tiliado.eu/app/airsonic/)
* [Source code](https://github.com/tiliado/nuvola-app-airsonic)
