### ISSUE TITLE
Add Google/Chrome Cast compatibility

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#55]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add support for Google/Chrome Cast to cast audio/video to Google/Chrome Cast compatible devices.

## Details from reporter

From [Launchpad bug #1296890](https://bugs.launchpad.net/nuvola-player/+bug/1296890) by Jonas Frei:

For those who don't know Google Cast (Chromecast):
https://developers.google.com/cast/

In Google Music, there is the Lab feature, where you can cast your music on the TV showing a fireplace. It only works if opened with Chrome though. It would be cool if it also worked with Nuvola.

Even cooler would be, if casting would work, no matter which service you use, including a button in the toolbar or so. It could show the Album Art and the title of the song.

Attached you find an example of the cast button when using Chrome.
![screenshot from 2014-03-24 19_43_03](https://cloud.githubusercontent.com/assets/853706/5327816/d3830088-7d62-11e4-85b8-e293174a84ea.png)

Also mentioned by @arcresu (Nuvola Patron).

:heart: **Four [Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/) are interested in this feature.** Internal info: [(1)](https://tiliado.eu/admin/tiliado_funding/patron/5/) [(2)](https://tiliado.eu/admin/tiliado_funding/patron/67/) [(3)](https://tiliado.eu/admin/tiliado_funding/patron/76/). GitHub: @arcresu @brianredbeard @ejdan @DavidBM

Related articles:

* ['Cast to TV' Lets You Stream Media From Ubuntu to Chromecast - OMG! Ubuntu!](https://www.omgubuntu.co.uk/2019/01/chromecast-tv-gnome-shell-extension)
* [How Chromecast works: HTML5, WebRTC, and the technology behind casting](https://www.androidauthority.com/html5-and-webrtc-the-technology-behind-chromecast-248968/)
* [CEF Deplhi - Send to Chromecast](https://www.briskbard.com/forum/viewtopic.php?t=38)
* [Add support for Screen Sharing to CEF - PR](https://bitbucket.org/chromiumembedded/cef/pull-requests/98/add-support-for-screen-sharing-to-cef/diff)
* https://github.com/GPMDP/electron-chromecast

**Comment by freijon** [comment]
There is a new app which looks very promising to accomplish this feature request:
https://github.com/masmu/pulseaudio-dlna --> adds a new audio sink which automatically connects to a nearby Chromecast/DLNA/UPNP device and streams the output to the device. With Pulseaudio Volume Control I manually set 'freshwrapper' to use the new Chromecast sink. Works like a charm. Maybe a more integrated solution is now possible?

**Comment by fenryxo** [comment]
Hello. Thanks for your idea. I successfully installed [python-zeroconf](https://packages.debian.org/stretch/all/python-zeroconf/download) and [pulseaudio-dlna](https://packages.debian.org/stretch/all/pulseaudio-dlna/download) on my Debian Jessie system. However, I've failed turning my phone into a DLNA/uPnP renderer for testing. I'll try again later.

**Comment by fenryxo** [comment]
TODO: Try [YouMap Chromecast Receiver for Android](http://forum.xda-developers.com/android-tv/chromecast/app-youmap-chromecast-receiver-android-t3161851) or [Cast Receiver app for Android](http://forum.xda-developers.com/android-tv/chromecast/app-cast-receiver-app-android-t2900726)

**Comment by fenryxo** [comment]
:heart: Another [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this feature.

**Comment by fenryxo** [comment]
+1 from tiliado/nuvola-app-google-play-music#20

**Comment by fenryxo** [comment]
There is an app called mkchromecast: [How to Send Your Linux Desktop Audio to a Chromecast](http://www.omgubuntu.co.uk/2016/08/cast-ubuntu-desktop-audio-chromecast)

**Comment by fenryxo** [comment]
:heart: Another [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this feature.

**Comment by fenryxo** [comment]
:heart: Another [Nuvola Patron](https://tiliado.eu/nuvolaplayer/funding/) is interested in this feature.

**Comment by fenryxo** [comment]
This feature should be one of those to work on when the ongoing transition to Flatpaks is complete.

**Comment by JulienAramino** [comment]
+1

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by boognish-rising** [comment]
The absence of this feature is the only reason that I'm not currently a paying Nuvola patron. I discovered Nuvola a few months ago and while I love it as a tightly integrated, native Linux option for SiriusXM, YouTube and YouTube music (these are the services I subscribe to so they're the most relevant to me but I certainly appreciate the development time/effort that goes into all of the many other players as well), I am quite heavily invested in Google Home/Nest devices and speakers so casting support is a must. For some reason, I've failed to get mkchromecast working on any of my Linux machines so unless I'm listening on my headphones, I have to forgo the Nuvola player options for browser based alternatives with casting ability. It seems like I won't be able to vote when the time comes as a user of free Nuvola services so I wanted to chime in here while I have the ability to do so. Regardless of what's to come, I do appreciate all of the excellent work you devs have put into Nuvola, it really is something special. Here's hoping that this issue lands somewhere among the prioritized requests so that I become a paid patron sometime in the not too distant future.  -cheers

**Comment by fenryxo** [comment]
Hello @boognish-rising. You don't have to be a Patron to vote. You can [purchase a one-year license for $3.99](https://gumroad.com/l/nuvola-pwyw) (the equivalent of one Skinny Peppermint Mocha (tall) at Starbucks). That's $0.33 a month.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
