### ISSUE TITLE
Provide Emby support

### ISSUE THREAD

**Issue by cgrima** [tiliado/nuvolaplayer#551]
[Emby](https://emby.media/) is another personal media streaming service, much like Plex. Would be great for Nuvola to provide an app to connect to the Music on an emby server.

**Comment by fenryxo** [comment]
Hello @cgrima. Thanks for your feature request.

**Comment by fenryxo** [comment]
Integration is ready. [Flatpak package](https://nuvola.tiliado.eu/app/emby/) and [source code](https://github.com/tiliado/nuvola-app-emby) have been published.
