### ISSUE TITLE
Add an option for minimum font size

### ISSUE THREAD

**Issue by elielmeira** [tiliado/nuvolaplayer#553]
Hey!
Great Job with Nuvola! Congratulations!

I think would great if we can resize the letter font.
When I zoon out to get a small window player the font size get too small.

Regards
Eliel.

----

- Use `Cef.BrowserSettings.minimum_font_size`

**Comment by fenryxo** [comment]
Hello @elielmeira. Thanks for your feature request. I think it should be possible to specify minimum font size.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
