### ISSUE TITLE
Bandcamp: Last.fm scrobble only works in the album's page

### ISSUE THREAD

**Issue by anarrestee** [tiliado/nuvolaplayer#559]
### Basic information

- Your Linux distribution and its version: elementary OS 5.0 Juno - based in Ubuntu 18.04.2 LTS || Linux 4.15.0-64-generic || GTK 3.22.30

- Your desktop environment:  pantheon

 - Nuvola Runtime version: 4.16.21 (21-gce55552)
  
 - The web app you use and its version: Bandcamp

### Describe the bug

... the only way to get tracks scrobbled to last.fm is to play them in the album page.

**Steps to reproduce the behavior**

1. Go to 'Home'
2. Click on any post that has embedded music
3. Play any song and then look for the scrobble in last.fm 
4. Alternatively go to "Collection" and play from the collection and search for the scrobble

**Expected behavior**
To get scrobbles no matter where you are playing tracks on Bandcamp
...

**Debugging log**

When trying to start debug from terminal with command "flatpak run eu.tiliado.NuvolaAppBandcamp --d"
I get: «Failed to load module "pantheon-filechooser-module"»

Attach the debug log here: ...

**Additional context**

The best playback experience is in the collection, using the Media Buttons, but there tracks are not scrobbled, and it's a shame if only going to the album page gets tracks scrobbled. 
-- This does not happen, curiously, with the Mixcloud app, which scrobbles correctly from the homepage, when you are using the Media Buttons, with no need to go to the radio page.

**Comment by fenryxo** [comment]
Hello @anarrestee. Thanks for reporting the issue. Bandcamp is the most complex streaming website I've ever seen. There are multiple sources of music playback, so it's hard to figure out which one is currently playing and where to find the corresponding metadata.

Could you help me with debugging?

1. Enable Developer's tools from Preferences.
2. Show Developer sidebar.
3. For each playback source affected by this issue, take a screenshot of the web view and developer sidebar, then highlight the playback source in the screenshot (e.g. with a red rectangle).
4. Attach the screenshots here.

**Comment by fenryxo** [comment]
Closing as there was no response from the reporter.
