### ISSUE TITLE
Mini player view

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#56]
Posted by Steffen Coenen on Google+: Recently I had an idea about implementing an mini player view for Nuvola consisting out of track information, playing controls and the cover art in a small window without showing the big websites. Do you think something like this could be possible without causing to much efforts. At least the things displayed would be more or less the same as in the new developer bar.﻿

![mockup](https://cloud.githubusercontent.com/assets/853706/5327821/1805f166-7d63-11e4-8318-19cc9378df4d.png)
##

**Comment by fenryxo** [comment]
* toggle repeat/shuffle.
* progress bar
* visible on all workspaces (remember in settings)
* always on top (remember in settings)

**Comment by fenryxo** [comment]
- Button to open the mini player: multimedia-player-symbolic
- Restore the player: view-restore-symbolic
- Pin to all desktops: view-pin-symbolic
- Keep above: go-top-symbolic

**Comment by fenryxo** [comment]
It could also show lyrics.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
