### ISSUE TITLE
Pretzel.rocks support

### ISSUE THREAD

**Issue by ian70203** [tiliado/nuvolaplayer#562]
Hi, I'm grizzogor and I would like to have Nuvola support the Pretzel music streaming service for live streaming. 

While the Pretzel web app that they provide works well on Windows and macOS, they do not have a Linux version of their software available. They do have a web portal, but it removes file output and global media controls.

You can implement the web app into the Nuvola runtime, and add some media control support in there.

There was an old repo on GitHub that ported the Electron app over to Linux, but has since been deleted and unsupported.

**Comment by fenryxo** [comment]
Hello @ian70203. Thanks for your feature request.

**Comment by fenryxo** [comment]
The way the Preztel web app is written makes it difficult to integrate with Nuvola. Help from somebody more experienced with JavaScript and react JS is needed.

**Comment by ask-compu** [comment]
what about the community project on the snap store? https://snapcraft.io/pretzeldesktop could this be integrated as an official app?

**Comment by fenryxo** [comment]
There is a new version of Pretzel:  https://play.pretzel.rocks

**Comment by fenryxo** [comment]
Now available: [Flatpak package](https://nuvola.tiliado.eu/app/pretzel/), [source code](https://github.com/tiliado/nuvola-app-pretzel).
