### ISSUE TITLE
Favorite Song if not in favorites, Deezer

### ISSUE THREAD

**Issue by Gnabe** [tiliado/nuvolaplayer#570]
Hey
Could you add a feature to the Deezer App, that checks whether the song you are trying to favorite is in your liked songs already? 
And if possible add a hotkey to dislike the song, which hits the heart if the song is liked.
It would be great to just smash Like/Dislike without accidentally removing/adding songs, cus you forgot you added them before.
Also, the like only works when songtexts are available. It seems like it just presses the third button on the right?

Appreciate your work
Gnabe

**Comment by fenryxo** [comment]
Hello @Gnabe, thanks for your feature request :-)

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
