### ISSUE TITLE
Lyrics from LyricWiki

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#58]
From [Launchpad bug #1327114](https://bugs.launchpad.net/nuvola-player/+bug/1327114) by Antonio Roberts:

The current lyrics plugin fetches content from A-Z lyrics. For my music collection it is missing a lot of lyrics. Lyricwiki, in my opinion, has a more robust collection of lyrics http://lyrics.wikia.com/Lyrics_Wiki
##

**Comment by fenryxo** [comment]
Unfortunately, the Lyrics wiki has been shut down :-(

**Comment by fenryxo** [comment]
It might be possible to use wayback machine:

* http://lyrics.wikia.com/Billy_Talent:Surrender
* https://web.archive.org/web/20190901002918/http://lyrics.wikia.com/wiki/Billy_Talent:Surrender

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
