### ISSUE TITLE
Port to QtWebEngine

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#583]
Nuvola currently uses [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/) as the web engine. There are numerous issues with that:

- There are no releases, no release notes, only supported branches.
- It doesn't work well with Nuvola/GTK 3 without custom patches.
- It is unlikely I manage to make it work with GTK 4.
- I haven't managed to make Nuvola work with CEF > 75.
- No wayland support.
- I can't write accented words in Spanish tiliado/nuvolaruntime#535
- Spell check for different languages than US English tiliado/nuvolaruntime#537
- etc.

We could port Nuvola to use QtWebEngine.

- It's an official Qt project.
- It is widely used and better supported than CEF.
- Documentation is great.
- Media codecs and Widevine is supported.

However, Nuvola is written in Vala, which cannot be used to write Qt apps. 

Two ways how to solve it:

1. Nuvola remains written in Vala/GTK. QtWebEngine uses offscreen rendering in a separate process via [QQuickRenderControl](https://doc.qt.io/qt-5/qquickrendercontrol.html)
2. Nuvola rewritten to Python/Qt.

What not to forget:

* Persist session cookies #567
* Widevine plugin
* MP3 and other proprietary formats
* HTML5 audio test
* HiDPI displays
* Error Pages
* Pop-up windows

**Comment by fenryxo** [comment]
Hello @sk8darr, @K4S1, @sebawild, @dhitchcock. It might happen that Nuvola in order to support Google services, Nuvola will have to be rewritten from scratch. It might take a while.

Which Nuvola features do you currently use the most?

**Comment by sebawild** [comment]
I'm using mostly the Google Calendar webapp (scandalously, there is no desktop/offline app that works nearly as smoothly with synced calendars as Google Calendar ...).

I occasionally used the Gmail webapp, but by far not as important for me.

**Comment by K4S1** [comment]
> Hello @sk8darr, @K4S1, @sebawild, @dhitchcock. It might happen that in order to support Google services, Nuvola will have to be rewritten from scratch. It might take a while.
> 
> Which Nuvola features do you currently use the most?

I just downloaded the YoutubeMusic for the first time, to test the desktop app, vs. Browser resource drain. to see if this performed a bit better on my PC.

**Comment by sebawild** [comment]
I can add that the memory footprint for Google Calendar is significantly better compared to running Chromium on my side.

**Comment by sk8darr** [comment]
> Hello @sk8darr, @K4S1, @sebawild, @dhitchcock. It might happen that in order to support Google services, Nuvola will have to be rewritten from scratch. It might take a while.
> 
> Which Nuvola features do you currently use the most?

Hello,
I'm using mostly the YouTubeMusic webapp.

**Comment by dhitchcock** [comment]
Apps I use Google Play Music, supposedly someday they'll force me to switch to Youtube Music.  I also use Pocketcasts.

Actual FEATURES of the app, the features I appreciate the most are multimedia hotkeys and the theme switcher.  The lyrics is a nice perk, but not deal breaking.  I will say I mush prefer GTK applications and I was more attracted to this program because of it's better GTK integrated look as opposed to say GPMDP.  If it were done in Qt, I would be disappointed, but I don't understand the difficulties it causes you.  If that's what needs to be done, so be it.

**Comment by fenryxo** [comment]
I did some research yesterday and it could be possible to embed QtWebEngine into the current GTK app via offscreen rendering.

**Comment by fenryxo** [comment]
Two key components for the QtWebWengine port of Nuvola have been published. Plenty of work ahead but it looks promising :-)

* [Wayland Embedded View Framework Server](https://github.com/tiliado/wayland-embedded-view-server) written in **Vala + GTK** will be used in the main Nuvola process. It acts as an embedded Wayland compositor.
* [Wayland Embedded View Framework Client](https://github.com/tiliado/wayland-embedded-view-client) written in **Python + QT** will run **QtWebEngine** in a separate process. It acts as a Wayland client.

![nuvola_website_embedded](https://user-images.githubusercontent.com/853706/97323555-36852a80-1871-11eb-83ff-bac1d9516352.png)

**Comment by pedrofleck** [comment]
Is there any issue with using WebKitGTK? I'll probably stop using Nuvola if it drop GTK. 😞

**Comment by fenryxo** [comment]
> Is there any issue with using WebKitGTK?

WebKitGTK is not a competitive web engine with regard to multimedia playback. We switched from it for this reason.

> I'll probably stop using Nuvola if it drop GTK.

Nuvola won't drop GTK. QtWebEngine will be used for rendering in the background and the result embedded in Nuvola's GTK interface.

**Comment by fenryxo** [comment]
[DodoWebEngine for Nuvola Player](https://github.com/tiliado/dodo-web-engine) also resolves #728 - Nuvola not supporting HiFi quality in Deezer.

![image](https://user-images.githubusercontent.com/853706/116807653-a338f480-ab34-11eb-845b-7e58fbe377f3.png)

**Comment by fenryxo** [comment]
I'm still struggling to allocate enough time to finish the porting. However, I currently have 30 vacation days at my disposal and don't plan much traveling this year because of the covid situation. That means I could invest 20-25 days into the effort! :+1:

**Comment by azertyalex** [comment]
QtWebengine uses a very old chromium. Isn't this a problem?

**Comment by fenryxo** [comment]
* The latest official QtWebEngine 5.15.5  contains Chrome 87.0.4280.144 ([ref](https://code.qt.io/cgit/qt/qtwebengine.git/tree/tools/scripts/version_resolver.py?h=5.15.5#n41)). 
* The latest KDE's QtWebEngine 5.15.5  contains Chrome 90.0.4430.228 ([ref](https://invent.kde.org/qt/qt/qtwebengine/-/blob/dev/tools/scripts/version_resolver.py#L41)).
* The official QtWebEngine 6.2 contains Chrome 90.0.4430.228 ([ref](https://code.qt.io/cgit/qt/qtwebengine.git/tree/tools/scripts/version_resolver.py?h=6.2#n41)).
* The latest Chrome version is 92.0.4515.131.

QtWebEngine is typically two 2 versions behind the latest Chrome, which should be ok.

**Comment by jiri-janousek** [comment]
I apologize for failing terribly to make this port happen :-(

I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
