### ISSUE TITLE
iHeart Radio

### ISSUE THREAD

**Issue by kstephens98** [tiliado/nuvolaplayer#589]
Please consider adding support for iHeart radio.

https://www.iheart.com/podcast/

**Comment by fenryxo** [comment]
Hello @kstephens98. Thanks for your feature request.

**Comment by fenryxo** [comment]
Now available: [Flatpak package](https://nuvola.tiliado.eu/app/iheart_radio/), [source code](https://github.com/tiliado/nuvola-app-iheart-radio).
