### ISSUE TITLE
Audio normalization

### ISSUE THREAD

**Issue by doktoil-makresh** [tiliado/nuvolaplayer#590]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add an option to enable audio normalization - to make the audio volume level of different tracks consistent.

## Details from reporter

**Is your feature request related to a problem? Please describe:**

Some tracks have different audio level, so sometimes you have to rush on audio level button to lower it, and to raise it

**Describe the solution you'd like:**

As in most players, I would like to have an audio normalization feature

**Additional context:**

Available in most audio players, as genuine Amazon Music app

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
