### ISSUE TITLE
Stop play

### ISSUE THREAD

**Issue by Alain-Andja** [tiliado/nuvolaplayer#592]
### Basic information

- Your Linux distribution and its version: ubuntu 18.04.4 LTS
   

- Your desktop environment: GNOME
   

 - Nuvola Runtime version: x86_64

   

 - The web app you use and its version: DEEZER
   

### Describe the bug

1 - I play a sound and few minute it's stop playing. try to replay and happen nothing else.

**Steps to reproduce the behavior**

1. Go to 'Playlist'
2. Click on 'play '
3. I don't Scroll
4. I don't See error message just I retry to click on play and nothing

**Expected behavior**

...

**Debugging log**

Attach the debug log here: [Debug_Deezer.txt](https://github.com/tiliado/nuvolaruntime/files/4283873/Debug_Deezer.txt)

**Screenshots**

Attach screenshots here: ...

**Additional context**

...

**Comment by fenryxo** [comment]
Hello @Alain-Andja. Thanks for reporting the issue. Unfortunately, I cannot reproduce it on my machine, which can make it impossible to fix it.
