### ISSUE TITLE
Improve the icons

### ISSUE THREAD

**Issue by veljkho** [tiliado/nuvolaplayer#596]
Hi,

I like your work and I will definitely donate! I'd like to suggest something:

Please try to improve the icons design. Make it little bit smaller, cuter, high quality resolution. Current design is not that nice to me.. I believe you didn't want to focus on this in the past, but it's time to improve it, specially when Ubuntu is becoming more nicer. I'm working with Ubuntu 19.10, I hope I was clear enough. Thank you!

**Comment by fenryxo** [comment]
Hello @veljkho. Are you referring to the icons of individual services? Nuvola 5 will merge all streaming services back to a single application *Nuvola Player* with a single icon, so the issue will disappear.

**Comment by veljkho** [comment]
Hi @fenryxo ,
Yes, for Deezer, TuneIn.. separate services, they have those light blue icons.
That sounds great about Nuvola 5. Can't wait to try it. Thanks.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
