### ISSUE TITLE
Can't sign in when 2FA is enabled on my account

### ISSUE THREAD

**Issue by dericke** [tiliado/nuvolaplayer#600]
I have 2FA enabled on my Google account. It would appear that the Nuvola runtime does not support U2F keys, which is my primary second factor. This would be OK, since I have several authentication methods set up on my account, but the "Try another way" button does nothing. I also can't set up an application-specific password for Nuvola in my Google account, because Google thinks that Nuvola should be able to handle 2FA and refuses to bypass it.

![google_nuvola_2fa](https://user-images.githubusercontent.com/3587185/78323320-4d0b1380-7526-11ea-8889-3a77e597cfed.png)

**Comment by fenryxo** [comment]
The issue was moved to https://github.com/tiliado/nuvolaruntime/issues/600 (what a nice number though!).

**Comment by dericke** [comment]
Oops, I should've read the bug reporting guidelines in the first place. Sorry!

# System info:
Ubuntu 19.10 x86_64
Default GNOME Shell

[nuvola eu.tiliado.txt](https://github.com/tiliado/nuvolaruntime/files/4466644/nuvola.eu.tiliado.txt)
[NuvolaAppGoogle.txt](https://github.com/tiliado/nuvolaruntime/files/4466645/NuvolaAppGoogle.txt)

**Comment by fenryxo** [comment]
Is your Nuvola installation brand new? If not, could you remove all data and try again?

```
rm -rf ~/.var/app/eu.tiliado.NuvolaAppGooglePlayMusic/
```

**Comment by dericke** [comment]
@fenryxo sorry for the delay, I tried to remove my user data and it didn't make a difference. However, I did try temporarily removing the U2F from my Google account, which made Google default to phone prompt-based 2FA, and was able to sign in that way without issue. So it would appear that the problem is specific to U2F as the primary second factor.

**Comment by fenryxo** [comment]
It worked for me with U2F as the primary second factor. Anyway, Nuvola will switch the web rendering engine, so it is unlikely I'll address the issue with the current backend. I'll keep this issue open to test it with the new backend when it's ready. Thanks for your bug report :-)

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
