### ISSUE TITLE
I experience higher CPU usage using TuneIn and Deezer

### ISSUE THREAD

**Issue by veljkho** [tiliado/nuvolaplayer#601]
Hi team,

I am experiencing very high CPU usage when I use your apps like TuneIn and Deezer (im not using anything else atm). It is not immediatelly, but from time to tim lets say in about 10-15 min it will be 80-90% of cpu usage.. and the process is called "ValacefSubproce" and when I kill it, one of your apps either Deezer or TuneIn ends.. so I believe it comes from your apps.

However, please see the attachment below. This ValacefSubproce process is causing very high cpu usage and when I kill it your apps ends along with the cpu usage, so no additional steps to tell you, it is just simple, using the apps TuneIn or Deezer.. normally left in background to play and doing nothing else except open Opera browser, Bluemail client, Slack.

I have Ubuntu 19.10, 8 core AMD processor, 16GB of RAM.
I tried with:  flatpak update --system; flatpak update --user

[![2020-04-07-14-18.png](https://i.postimg.cc/vmWwMSjt/2020-04-07-14-18.png)](https://postimg.cc/t1CMND9s)

**Comment by veljkho** [comment]
False alarm, this is not proper view to see cpu usage.. this should be 9% actually, I'm new to Ubuntu sorry.

**Comment by fenryxo** [comment]
Actually, 90% as shown in top is still pretty high. Nuvola shouldn't use a whole single core.

**Comment by fenryxo** [comment]
I mean it shouldn't use a whole single core constantly. My CPU utilization is below 20% (of a single core) with occasional spikes to 70%.

**Comment by veljkho** [comment]
I think the problem may be more related to TuneIn app, specially when there's very good audio quality of some radio.. for now its like constant of 35-45% of a single core for TuneIn, listening to 1.FM - A List 80s radio.
