### ISSUE TITLE
Youtube-dl Integration for Bandcamp

### ISSUE THREAD

**Issue by ghost** [tiliado/nuvolaplayer#613]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add feature to download favorite albums from Bandcamp for offline usage.

## Details from reporter

**Is your feature request related to a problem? Please describe:**
No. 
A clear and concise description of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like:**
I would like integration for youtube-dl to download your favourite albums to listen to them offline. While the tool youtube-dl has youtube in the name it also works in bandcamp so don't worry. 
A clear and concise description of what you want to happen. What are the benefits and drawbacks?
I would like a right-click feature that puts the link on bandcamp into youtube-dl and downloads it. I would like a option to include the metadata and the thumbnail.

**Describe alternatives you've considered:**
There are alternative solutions, like using bandcamp-dl which is basically a similar script to youtube-dl but just more optimized for bandcamp rather than youtube. You can find that in the AUR and maybe in some debian repos too.

**Additional context:**

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
