### ISSUE TITLE
Internal Audio Output Selector

### ISSUE THREAD

**Issue by Originalme** [tiliado/nuvolaplayer#618]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

This feature adds an option to select an audio output device for Nuvola Player. The selection will be remembered when you launch Nuvola again unless the device is unplugged.

## Details from reporter

I would love an option to set a default audio device in the application.

Currently, I have to swap this in pulse every time I start nuvola, and since it shows up as Chromium it affects my other chrome pages. I would love to have a localized setting directly in the application.

**Comment by fenryxo** [comment]
Hello @Originalme, thanks for your feature request. I've been thinking about something similar a while ago. Priority for the year 2020 is #583. Then I could add new features.

**Comment by Originalme** [comment]
Sounds good. That other request seems like a much higher priority, and quite a bit of a lift. Thank you for responding to this request in the meantime.

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
