### ISSUE TITLE
Picture-in-Picture mode for videos

### ISSUE THREAD

**Issue by friendlybigyan** [tiliado/nuvolaplayer#629]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Picture-in-Picture mode allows you to pop videos out of their webpage into a floating, always on top, window so you can watch while continuing to work in other apps. You can move the Picture-in-Picture window around the screen and resize it to your liking.

## Details from reporter

This is a feature I really wanted.

Recently, i got quite fond of Vivaldi as a browser, specially, its feature called "picture in picture" which is basically allowing the video to be a separate window. This makes playing music on YouTube very clean and appealing. I wish this feature gets added in Nuvola's YouTube too.

**Comment by fenryxo** [comment]
Hello @friendlybigyan, thanks for your idea :-)

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
