### ISSUE TITLE
Add support for Google Podcasts

### ISSUE THREAD

**Issue by aia832003** [tiliado/nuvolaplayer#633]
I know it's not as popular as some others, but is becoming the default on many Android phones. I'd love to see podcasts.google.com added to the services available.

**Comment by fenryxo** [comment]
Hello @aia832003. Thanks for your tip. I'd rather avoid adding any Google services until #583 is done. Google sites are quite hostile to other clients than Google Chrome.

**Comment by aia832003** [comment]
Thanks for the update!

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
