### ISSUE TITLE
Introduce Quality Assurance Assistants

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#635]
Nuvola provides integration of 32 streaming services. Since I don't have time to test them all, we need assistance from the community.

Benefits for the assistants:

1. The warm feeling that you help improve the quality of service integration.
2. Nuvola license for free.
3. Upon your approval, we may list your name in release announcements or in Nuvola's about dialog

Requirements:
* Active use of a particular service with access to most features.
  * If some features are available only to registered users, the assistant has to be registered at the service.
  * If some features are available only to paying customers, the assistant has to purchase the service.
  * If some features are available only at a higher pricing tier, the assistant should purchase the higher tier.
* Regular service check-ups according to Quality Assurance Scenarios - probably twice a month.
* Ability to copy error messages from built-in web developer tools. No investigation of the messages is required.
* All issues reported to Nuvola's issues tracker on GitHub.

Quality Assurance Scenario example
* Service: Spotify
* Terms:
  * Developer sidebar - Open Nuvola preferences and enable *Developer's tools*. The select *Developer* panel in Nuvola's sidebar.
  * Developer sidebar - Switch to Developer sidebar and click button *Open Dev Tools*. Switch to the tab *Console* in the newly opened window.
* Scenario 1: User not logged in
  * User can log in by all means.
  * ...
* Scenario 2: User logged in
  * User can log out.
  * User can play a track.
  * When music is playing:
    * The developer console shows no errors except for the already known ones.
    * The **Album art** image at the top of the developer sidebar is correct.
    * The **Song** field in the developer sidebar is correct.
    * The **Artist** field in the developer sidebar is correct.
    * The **Album** field in the developer sidebar is `(null)`.
    * The **Playback state** field in the developer sidebar is `playing`.
    * The **Toggle play/pause** button in the developer sidebar is enabled and pauses the music without any error in the developer console.
    * The **Play** button in the developer sidebar is disabled.
    * The **Pause** button in the developer sidebar is enabled and pauses the music without any error in the developer console.
    * ... 
  * When music is paused:
    * The **Toggle play/pause** button in the developer sidebar is active and resumes music playback without any error in the developer console.
    * ... 
* ...

**Comment by halcyon22** [comment]
I can help with Amazon Music.

**Comment by fenryxo** [comment]
Hello @halcyon22, thanks for your interest. Do you have a paid Amazon Music account?

**Comment by halcyon22** [comment]
> Hello @halcyon22, thanks for your interest. Do you have a paid Amazon Music account?

Yes I do.

**Comment by fenryxo** [comment]
Could you send me your e-mail address to supoort@tiliado.eu to receive a free Nuvola license? Or you can write it here if you aren't afraid of spam bots.

**Comment by fenryxo** [comment]
I've just sent the license key :mailbox:
