### ISSUE TITLE
Lyrics stopped in Tidal

### ISSUE THREAD

**Issue by ssreddy555** [tiliado/nuvolaplayer#643]
I have been using Nuvola runtime app for Tidal.

The lyrics were appearing till yesterday but today they are not being fetched.

What could be the reason?

Please suggest a fix.

Thank you.

**Comment by fenryxo** [comment]
Hello @ssreddy555, could you provide a debugging log? Thanks.

```
 flatpak run eu.tiliado.NuvolaAppTidal -D
```

**Comment by fenryxo** [comment]
Closing as no log has been provided.
