### ISSUE TITLE
Add Pomodoro functionality

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#650]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

[Pomodoro Technique](https://en.wikipedia.org/wiki/Pomodoro_Technique) is a time management method developed by Francesco Cirillo in the late 1980s. The technique uses a timer to break down work into intervals, traditionally 25 minutes in length, separated by short breaks.

The Pomodoro feature adds two modes:
* **Music playing during work intervals:** When a work interval starts, music playback is resumed. When a break starts, music playback is paused. This mode could be used with *deep focus* playlists to focus during work intervals and silence to recover during breaks.
Start music playback when working.
* **Music playing during breaks:** When a break interval starts, music playback is resumed. When a working interval starts, music playback is paused. This mode could be used with *refreshing* playlists to recover during breaks.

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.
