### ISSUE TITLE
Add option to launch Nuvola Player hidden/minimized waiting in the background

### ISSUE THREAD

**Issue by Juanrk96** [tiliado/nuvolaplayer#652]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

## Feature description

Add two new options:

* **Start Nuvola Player hidden**: When Nuvola starts, its main window remains hidden and it isn't visible in a task bar. Nuvola is then waiting in the background.

* **Start Nuvola Player minimized**: When Nuvola starts, its main window remains hidden but it's visible in a task bar. Nuvola is then waiting in the background.

You can display the window with following actions:

  1. Launch Nuvola again - the already running instance is activated and its window is shown.
  2. Activate the window from a tray icon.
  3. Activate the window via MPRIS aplet. 

## Details from the reporter

**Is your feature request related to a problem? Please describe:**

Is not a problem, but would be cool if, as a user, could find an option to auto-start the apps on tray

**Describe the solution you'd like:**

When starting linux some apps start automatically, but all windowed (or almost all) in my case the important ones that I have are Firefox, Sublime, Blender, Discord and the Spotify on Nuvola. I know that all nuvola apps can minimize on tray instead of closing them and because of that detail I rather use this version instead of the Spotify's official. But something that the Spotify's oficcial doesn't have is when someone starts the app (doesn't matter if you click on it or launch it self on system boot) always shows the window and then manually you have to minimize it to tray (Windows) or just minimize it (Linux). I think that would be very cool if as users we could set on the preferences if we want to start windowed or automatically minimize it to tray

The only drawback that I see is that some user would forget the configuration and (beacuse they don't see the Spotify's window) they'll try to open it more than once

**Comment by fenryxo** [comment]
Hello @Juanrk96, thanks for your feature request :-)

**Comment by fenryxo** [comment]
Nuvola shows two windows on startup: The about dialog with the progress of initialization and the main window. It would be quite complicated to add "Launch on tray" feature now, so it'll wait until the progress of initialization is moved somewhere else in Nuvola 5.

**Comment by fenryxo** [comment]
📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
