### ISSUE TITLE
Audible (Amazon audiobooks) script request

### ISSUE THREAD

**Issue by andrewazores** [tiliado/nuvolaplayer#655]
**Describe the solution you'd like:**

A Nuvola script for Audible audiobooks playback. https://www.audible.com

**Additional context:**

This seems like a very similar use case to podcast listening, so I think it fits with Nuvola's streaming audio goals. The Audible web player is pretty sad, but having it in Nuvola with MPRIS etc. might perk it up a little.

**Comment by fenryxo** [comment]
Hello @andrewazores. Thanks for your script request :-)

**Comment by fenryxo** [comment]
Integration is ready. [Flatpak package](https://nuvola.tiliado.eu/app/audible/) and [source code](https://github.com/tiliado/nuvola-app-audible) have been published.
