### ISSUE TITLE
DI.FM: current settings are not saved 

### ISSUE THREAD

**Issue by mzuther** [tiliado/nuvolaplayer#658]
### Basic information

- Your Linux distribution and its version: Linux Mint 20
- Your desktop environment: i3wm (https://i3wm.org/)
 - Nuvola Runtime version: 4.17.25
 - The web app you use and its version: DI.FM script 1.0.2

### Describe the bug
1. Start DI.FM script
2. Accept the warning about version mismatch (the problem occurred with the former version, too)
3. Click on a radio station or playlist to start playing
4. Change volume to 50%
5. Quit DI.FM script using the Hamburger menu
6. Re-start DI.FM script, either directly or after re-starting your PC
7. Tthe DI.FM script defaults to a default playlist (Future House in my case) and to a volume of approx. 80%

**Expected behavior**

The DI.FM script should remember current settings such as currently played item or radio station and volume.

I have checked the browser-based web app using Firefox and it showed the same problem. But when I allowed storing cookies for http://di.fm and https://di.fm, the problem vanished and my settings were restored correctly.

**Debugging log**

[runtime.log](https://github.com/tiliado/nuvolaruntime/files/5422257/runtime.log)
[difm_1st.log](https://github.com/tiliado/nuvolaruntime/files/5422259/difm_1st.log)
[difm_2nd.log](https://github.com/tiliado/nuvolaruntime/files/5422260/difm_2nd.log)

Thanks! :)

**Comment by fenryxo** [comment]
Hello @mzuther, thanks for your bug report :-)

**Comment by fenryxo** [comment]
> I have checked the browser-based web app using Firefox and it showed the same problem. But when I allowed storing cookies for http://di.fm and https://di.fm, the problem vanished and my settings were restored correctly.

Could you elaborate more on what exactly did you do to allow storing cookies?

**Comment by mzuther** [comment]
Of course. Open section "Privacy & Security" in Firefox's preferences and enable "Delete cookies and site data when Firefox is closed". I have used this setting for so long now that I do not notice it anymore – sorry...

In case you have not used this setting before, you should use a new [profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US#firefox:linux:fx82), otherwise all your logins and site data will be deleted whenever you close Firefox!

Now do this:

1. Open https://www.di.fm/ in Firefox and log in
1. Click on a radio station or playlist to start playing
1. Change volume to 50%
1. Log out of DI.FM and close Firefox
1. Open https://www.di.fm/ in Firefox and log in
1. DI.FM uses to a default playlist and volume

Go to Firefox's preferences again and click on "Manage Exceptions" (right next to "Delete cookies and site data when Firefox is closed"). Enter "di.fm" in the text field, click on "Allow" and "Save Changes". This will allow cookies and site data to be stored for both http://di.fm and https://di.fm.

Now, repeat the steps in the list above. In the last step, DI.FM should now "remember" your settings.

Can you reproduce this?

**Comment by fenryxo** [comment]
Thanks, I'll look at it next month.

**Comment by fenryxo** [comment]
I'm afraid I haven't managed to look at it during Nuvola 4.19 release cycle.

**Comment by mzuther** [comment]
Never mind, I appreciate that you thought about it... :smile:

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
