### ISSUE TITLE
Support input method

### ISSUE THREAD

**Issue by xcffl** [tiliado/nuvolaplayer#662]
**Is your feature request related to a problem? Please describe:**

When searching (e.g. in Spotify) in CJK languages, it's not possible to input keywords directly in Nuvola apps so far.

**Describe the solution you'd like:**

Probably it's related to CEF. Some disscussions are made in https://bitbucket.org/chromiumembedded/cef/issues/1813/cef-does-not-work-with-imes-on-linux.
But cef is deprecated by nuvola now. Hopefully QtWebEngine supports IME natively.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by fenryxo** [comment]
Hello @xcffl, indeed, I'll look at it once QtWebEngine port is complete.

**Comment by fenryxo** [comment]
This will be fixed in the QtWebWengine port of Nuvola in #583. The work-in-progress components [Wayland Embedded View Framework Server](https://github.com/tiliado/wayland-embedded-view-server) and [Wayland Embedded View Framework Client](https://github.com/tiliado/wayland-embedded-view-client) use the basic GTK+ 3 IM context to support dead keys (`´` + `a` = `á`, etc.), but more work must be done to support CJK languages.

**Comment by xcffl** [comment]
I think I'll need some time to get familiar with how to integrate IM context. I suppose https://developer.gnome.org/gtk3/stable/GtkIMContext.html isn't sufficient. Do you know any materials that might enlight me?

**Comment by oppilate** [comment]
Probably the solution can be found at https://bugs.chromium.org/p/chromium/issues/detail?id=791920. Will check later

**Comment by fenryxo** [comment]
I don't know whether GtkIMContext is sufficient or not. I haven't explored inputting CJK languages in detail yet.

**Comment by xcffl** [comment]
Well, but is the Client ready to use (as a demo)? If not, please remind me if it's usable and I'll figure out. Thanks.

**Comment by fenryxo** [comment]
> Well, but is the Client ready to use (as a demo)? If not, please remind me if it's usable and I'll figure out. Thanks.

Not yet.

**Comment by xcffl** [comment]
Sorry there's a typo. I mean when it's usable, please remind me, because to my understanding QtWebEngine natively supports IME. But perhaps it's not the case, as it's embedded through a server.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
