### ISSUE TITLE
Make scripts pass with Standard JS code style 16.0.1

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#674]
## Progress

- [x] [8tracks](https://github.com/tiliado/nuvola-app-8tracks) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-8tracks/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-8tracks/tree/master)
- [x] [amazon-cloud-player](https://github.com/tiliado/nuvola-app-amazon-cloud-player) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-amazon-cloud-player/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-amazon-cloud-player/tree/master)
- [x] [apple-music](https://github.com/tiliado/nuvola-app-apple-music) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-apple-music/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-apple-music/tree/master)
- [x] [bandcamp](https://github.com/tiliado/nuvola-app-bandcamp) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-bandcamp/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-bandcamp/tree/master)
- [x] [bbc-iplayer](https://github.com/tiliado/nuvola-app-bbc-iplayer) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-bbc-iplayer/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-bbc-iplayer/tree/master)
- [x] [brain-fm](https://github.com/tiliado/nuvola-app-brain-fm) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-brain-fm/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-brain-fm/tree/master)
- [x] [deezer](https://github.com/tiliado/nuvola-app-deezer) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-deezer/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-deezer/tree/master)
- [x] [difm](https://github.com/tiliado/nuvola-app-difm) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-difm/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-difm/tree/master)
- [x] [focus-at-will](https://github.com/tiliado/nuvola-app-focus-at-will) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-focus-at-will/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-focus-at-will/tree/master)
- [x] [gaana](https://github.com/tiliado/nuvola-app-gaana) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-gaana/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-gaana/tree/master)
- [x] [google-calendar](https://github.com/tiliado/nuvola-app-google-calendar) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-google-calendar/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-google-calendar/tree/master)
- [x] [google-play-music](https://github.com/tiliado/nuvola-app-google-play-music) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-google-play-music/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-google-play-music/tree/master)
- [x] [google-keep](https://github.com/tiliado/nuvola-app-google-keep) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-google-keep/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-google-keep/tree/master) fails for a different reason
- [x] [idagio](https://github.com/tiliado/nuvola-app-idagio) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-idagio/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-idagio/tree/master)
- [x] [ivoox](https://github.com/tiliado/nuvola-app-ivoox) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-ivoox/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-ivoox/tree/master)
- [x] [jamendo](https://github.com/tiliado/nuvola-app-jamendo) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-jamendo/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-jamendo/tree/master)
- [x] [jango](https://github.com/tiliado/nuvola-app-jango) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-jango/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-jango/tree/master)
- [x] [jupiter-broadcasting](https://github.com/tiliado/nuvola-app-jupiter-broadcasting) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-jupiter-broadcasting/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-jupiter-broadcasting/tree/master)
- [x] [kexp](https://github.com/tiliado/nuvola-app-kexp) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-kexp/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-kexp/tree/master)
- [x] [mentorfm](https://github.com/tiliado/nuvola-app-mentorfm) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-mentorfm/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-mentorfm/tree/master)
- [x] [mixcloud](https://github.com/tiliado/nuvola-app-mixcloud) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-mixcloud/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-mixcloud/tree/master) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-mixcloud/tree/test.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-mixcloud/tree/test)
- [x] [npr-one](https://github.com/tiliado/nuvola-app-npr-one) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-npr-one/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-npr-one/tree/master)
- [x] [owncloud-music](https://github.com/tiliado/nuvola-app-owncloud-music) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-owncloud-music/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-owncloud-music/tree/master)
- [x] [pandora](https://github.com/tiliado/nuvola-app-pandora) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-pandora/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-pandora/tree/master)
- [x] [plex](https://github.com/tiliado/nuvola-app-plex) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-plex/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-plex/tree/master)
- [x] [pocket-casts](https://github.com/tiliado/nuvola-app-pocket-casts) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-pocket-casts/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-pocket-casts/tree/master)
- [x] [primephonic](https://github.com/tiliado/nuvola-app-primephonic) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-primephonic/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-primephonic/tree/master)
- [x] [qobuz](https://github.com/tiliado/nuvola-app-qobuz) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-qobuz/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-qobuz/tree/master)
- [x] [siriusxm](https://github.com/tiliado/nuvola-app-siriusxm) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-siriusxm/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-siriusxm/tree/master)
- [x] [soundcloud](https://github.com/tiliado/nuvola-app-soundcloud) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-soundcloud/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-soundcloud/tree/master)
- [x] [spotify](https://github.com/tiliado/nuvola-app-spotify) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-spotify/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-spotify/tree/master)
- [x] [tidal](https://github.com/tiliado/nuvola-app-tidal) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-tidal/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-tidal/tree/master)
- [x] [tunein](https://github.com/tiliado/nuvola-app-tunein) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-tunein/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-tunein/tree/master)
- [x] [yandex-music](https://github.com/tiliado/nuvola-app-yandex-music) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-yandex-music/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-yandex-music/tree/master)
- [x] [youtube](https://github.com/tiliado/nuvola-app-youtube) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-youtube/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-youtube/tree/master)
- [x] [youtube-music](https://github.com/tiliado/nuvola-app-youtube-music) [![CircleCI](https://circleci.com/gh/tiliado/nuvola-app-youtube-music/tree/master.svg?style=svg)](https://circleci.com/gh/tiliado/nuvola-app-youtube-music/tree/master)

## Procedure

1. `flatpak install nuvola eu.tiliado.NuvolaAdk//master`
2. `alias nuvola-adk-master="flatpak run --filesystem=~/projects/nuvola-apps eu.tiliado.NuvolaAdk//master"`
3. `nuvola-adk-master`
4. `standard --version` → `16.0.1`
5. `standard --fix` → this should fix most errors
6. `standard` → if there are any errors left, you need to fix them manually
7. Verify changes and push

**Comment by fenryxo** [comment]
Hello @ams, @d-r-q and @Romunix. I've updated the master branch of Nuvola ADK with Standard JS code style checker 16.0.1. Could you look at your scripts and fix new errors? `standard --fix` should fix most errors. If you need any help, add a comment here. Thanks :-)

**Comment by fenryxo** [comment]
You can also look at fixes applied to my scripts.

**Comment by ams** [comment]
> ams

I think you mean a different person, I have nothing to do with this project.

**Comment by d-r-q** [comment]
Hi, @fenryxo 
I will look it later this week

**Comment by fenryxo** [comment]
> > ams
> 
> I think you mean a different person, I have nothing to do with this project.

Yes, you're right. @a-m-s is the correct person. Sorry for the noise.

**Comment by fenryxo** [comment]
Hello, @a-m-s, any chance you could manage to port your scripts before 2020-11-28? :-)

**Comment by fenryxo** [comment]
Hello, @a-m-s, any chance you could manage to port your scripts before 2020-12-27? :-)

**Comment by fenryxo** [comment]
All green.
