### ISSUE TITLE
after Change volume in Keyboard Shortcuts I had lost sound in tunein

### ISSUE THREAD

**Issue by pagurets** [tiliado/nuvolaplayer#676]

**Comment by fenryxo** [comment]
Hello @pagurets. Could you precisely describe the steps to reproduce the issue and attach a debug log while performing the steps? Thanks.

```
flatpak run eu.tiliado.NuvolaAppTunein -D
```

**Comment by pagurets** [comment]
flatpak run eu.tiliado.NuvolaAppTunein -D
Runner: [DEBUG Δ141003us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Runner: [DEBUG Δ002682us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Runner: [DEBUG Δ000241us  GLib] setenv()/putenv() are not thread-safe and should not be used after threads are created
Runner: [DEBUG Δ192294us  GLib] unsetenv() is not thread-safe and should not be used after threads are created
Runner: [DEBUG Δ258529us Nuvola] AboutDialog.vala:54: Nuvola Apps 4.18.0 (0-g0624419)
Runner: [DEBUG Δ000027us Nuvola] AboutDialog.vala:56: TuneIn script 1.4.3 (3-ga8230a6)
Runner: [DEBUG Δ000013us Nuvola] AboutDialog.vala:60: Diorite 4.18.0
Runner: [DEBUG Δ014190us Nuvola] AboutDialog.vala:62: Chromium 75.0.3770.100
Runner: [DEBUG Δ000037us Nuvola] AboutDialog.vala:63: ValaCEF 75.3770.15
Runner: [DEBUG Δ032993us  GLib] unsetenv() is not thread-safe and should not be used after threads are created
Runner: [DEBUG Δ020449us DioriteGtk] DesktopShell.vala:254: Shell: mutter (muffin) (null), CSD 0, appmenu 0, menubar 0
Runner: [DEBUG Δ000473us  GLib] setenv()/putenv() are not thread-safe and should not be used after threads are created
Runner: [DEBUG Δ100435us Nuvola] Connection.vala:124: Network Proxy: system settings
Runner: [DEBUG Δ070731us GLib-GIO] _g_io_module_get_default: Found default implementation portal (GProxyResolverPortal) for ‘gio-proxy-resolver’
Runner: [DEBUG Δ04s469757us Nuvola] AppRunnerController.vala:115: Scale factor: 1
Runner: [DEBUG Δ004099us DioriteGtk] Application.vala:255: XFCE session vanished: org.xfce.SessionManager
Runner: [DEBUG Δ078575us CefGtk] WidevinePlugin.vala:15: Widevine path: /home/pps/.var/app/eu.tiliado.NuvolaAppTunein/data/nuvolaruntime/apps_data/tunein/widevine
Your system is broken: dlsym doesn't work! This has been reported to be caused by Nvidia's libGL. You should expect time related functions to misbehave. https://bugs.chromium.org/p/chromium/issues/detail?id=16800
Runner: [DEBUG Δ181362us GLib-GIO] _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
Runner: [INFO Δ217157us CefGtk] WidevinePlugin.vala:27: WidevinePlugin is available: 0 (null)
[1126/090829.205675:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process.
Runner: [WARNING Δ01s863774us Nuvola] StartupWindow.vala:146: tiliado-account-message: Features Tier: Free
Runner: [INFO Δ096211us Nuvola] CefEngine.vala:301: Partially implemented: register_ipc_handlers()
Runner: [INFO Δ000314us CefGtk] WebView.vala:75: CEF rendering mode: CEF_GTK_RENDERING_MODE_WINDOWED
Runner: [INFO Δ044200us CefGtk] Client.vala:106: get_life_span_handler
Runner: [DEBUG Δ045516us CefGtk] WebViewWindowed.vala:65: allocation 0,1+711,606 child_allocation 0,0+711,606
[1126/090830.344551:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
Runner: [INFO Δ090448us CefGtk] WebView.vala:114: Renderer #1 created.
Worker: [DEBUG Δ006538us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ000258us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Runner: [DEBUG Δ063610us Nuvola] CefEngine.vala:377: Init finished
Runner: [DEBUG Δ000487us Nuvola] WebWorker.vala:80: Cannot call ('Nuvola.actions.emit', <('ActionEnabledChanged', 'go-forward', false)>, false)
Runner: [DEBUG Δ000068us Nuvola] WebWorker.vala:80: Cannot call ('Nuvola.actions.emit', <('ActionEnabledChanged', 'go-back', false)>, false)
Runner: [DEBUG Δ004685us Nuvola] AppRunnerController.vala:692: Component tray_icon (Tray Icon) available=true, enabled=false
Runner: [DEBUG Δ000065us Nuvola] AppRunnerController.vala:692: Component audio_tweaks (Audio Tweaks) available=true, enabled=false
Runner: [DEBUG Δ000055us Nuvola] AppRunnerController.vala:692: Component unity_launcher (Extra Dock Actions) available=true, enabled=false
Runner: [DEBUG Δ000053us Nuvola] AppRunnerController.vala:692: Component notifications (Notifications) available=true, enabled=false
Runner: [DEBUG Δ000049us Nuvola] AppRunnerController.vala:692: Component mediakeys (Multimedia keys) available=true, enabled=false
Runner: [DEBUG Δ000045us Nuvola] AppRunnerController.vala:692: Component scrobbler (Audio Scrobbling) available=true, enabled=false
Runner: [DEBUG Δ000047us Nuvola] AppRunnerController.vala:692: Component mpris (Media Player DBus Interface) available=true, enabled=false
Runner: [DEBUG Δ000054us Nuvola] AppRunnerController.vala:692: Component httpremotecontrol (Remote control over HTTP (experimental)) available=true, enabled=false
Runner: [DEBUG Δ000050us Nuvola] AppRunnerController.vala:692: Component lyrics (Lyrics) available=true, enabled=false
Runner: [DEBUG Δ000043us Nuvola] AppRunnerController.vala:692: Component developer (Developer's tools) available=true, enabled=false
Worker: [DEBUG Δ188014us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ000039us CefGtk] RendererContext.vala:57: JS Context created 1
Runner: [DEBUG Δ792925us Nuvola] CefEngine.vala:163: App Runner Initialized
Runner: [DEBUG Δ000275us Nuvola] CefEngine.vala:167: App Runner Ready
Runner: [DEBUG Δ013589us Nuvola] CefEngine.vala:380: Web Worker Ready
Runner: [DEBUG Δ000399us Nuvola] WebAppWindow.vala:179: Sidebar position: 478
Runner: [DEBUG Δ077310us Nuvola] CefEngine.vala:580: Navigation: new window: false → false, uri: 'https://tunein.com/radio/Christian-Life-Radio-s112984/' → 'https://tunein.com/radio/Christian-Life-Radio-s112984/', approved: true, frame: (null), type: TT_EXPLICIT, user gesture: true
Runner: [DEBUG Δ001428us Nuvola] CefEngine.vala:487: Load started
Runner: [DEBUG Δ008726us Nuvola] CefEngine.vala:487: Load started
Runner: [INFO Δ658392us Nuvola] config.vala:223: Config saved to /home/pps/.var/app/eu.tiliado.NuvolaAppTunein/config/nuvolaruntime/apps_data/tunein/config.json
Worker: [DEBUG Δ009172us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ000328us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Runner: [DEBUG Δ02s321244us Nuvola] CefEngine.vala:380: Web Worker Ready
Worker: [DEBUG Δ012253us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ008714us CefGtk] RendererContext.vala:57: JS Context created 1
Runner: [DEBUG Δ020028us Nuvola] CefEngine.vala:487: Load started
Worker: [DEBUG Δ03s714955us Nuvola] CefRendererExtension.vala:145: Lost JS context
Worker: [INFO Δ000336us CefGtk] RendererContext.vala:64: JS Context released: 1
Runner: [INFO Δ016362us CefGtk] WebView.vala:114: Renderer #1 created.
Runner: [DEBUG Δ004863us DioriteGlib] DuplexChannel.vala:502: Channel (2) has been closed.
Runner: [DEBUG Δ000095us DioriteGlib] DuplexChannel.vala:328: The channel has already been closed
Runner: [INFO Δ402854us Nuvola] config.vala:223: Config saved to /home/pps/.var/app/eu.tiliado.NuvolaAppTunein/config/nuvolaruntime/apps_data/tunein/config.json
[1126/090834.977936:WARNING:keyring_util_linux.cc(77)] Could not load libgnome-keyring.so.0: libgnome-keyring.so.0: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
Runner: [INFO Δ03s099383us CefGtk] WebView.vala:106: Console: https://cdn-web.tunein.com/assets/js/vendor.2f740aa5c49675e889bc.js:25: '' is not defined in translations.
Runner: [CRITICAL Δ093438us GLib-GIO] g_simple_action_set_state: assertion 'value != NULL' failed
Runner: [CRITICAL Δ000032us GLib-GIO] Application will not function properly.
Runner: [INFO Δ481261us CefGtk] WebView.vala:106: Console: https://cdn-web.tunein.com/assets/js/vendor.2f740aa5c49675e889bc.js:25: '' is not defined in translations.
Runner: [INFO Δ405265us CefGtk] WebView.vala:106: Console: https://cdn-web.tunein.com/assets/js/vendor.2f740aa5c49675e889bc.js:25: Error: apstag has already loaded - preventing duplicate load
Runner: [INFO Δ02s356126us CefGtk] WebView.vala:106: Console: https://tunein.com/radio/Christian-Life-Radio-s112984/:0: Mixed Content: The page at 'https://tunein.com/radio/Christian-Life-Radio-s112984/' was loaded over HTTPS, but requested an insecure audio file 'http://ice64.securenetsystems.net/CLR1MP3'. This content should also be served over HTTPS.
[1126/070841.853704:ERROR:bus.cc(554)] Failed to get the ownership of org.mpris.MediaPlayer2.chromium.instance2: org.freedesktop.DBus.Error.ServiceUnknown

**Comment by pagurets** [comment]
I remove config from /home/pps/.var/app/eu.tiliado.NuvolaAppTunein/. After this sound return to app. Troble is desided. Thanks!
