### ISSUE TITLE
Spotify: I can't use the widget on the notification section

### ISSUE THREAD

**Issue by rpayanm** [tiliado/nuvolaplayer#677]
The next/prev/play/pause no longer works.

![image](https://user-images.githubusercontent.com/6087454/100453549-e381db80-3099-11eb-8987-0007109ed4ea.png)

**Comment by fenryxo** [comment]
Hello @rpayanm, thanks for your bug report.

**Comment by fenryxo** [comment]
Playback actions are fixed in Spotify script 3.3.0.

**Comment by rpayanm** [comment]
Thanks, It works now!
