### ISSUE TITLE
Let paying users vote for features

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#678]
## Reason

There are plenty of feature requests in Nuvola's issue tracker on GitHub. However, some of them are really old and we don't know whether they are still relevant. We would also like to find out which features are most wanted. That's why we selected most feature requests for voting by users. 

## Phases

1. **January 2021 - April 2021 Preparation of feature requests for voting.** You can [review and improve existing feature requests labeled voting](https://github.com/tiliado/nuvolaplayer/labels/voting) to make them more appealing for other users or [create a new feature request](https://github.com/tiliado/nuvolaplayer/issues/new?template=feature-request.md).
  2. **May 2021 - December 2021 - Voting on feature requests.** Survey started with Nuvola Player 4.22 on May 9th, 2021.
3. **January 2022 - Evaluation of voting.**

### Feature Selected

📌 **Hello there! This feature request has been selected to be voted for by Nuvola users.**

Anyone can update its description to make it more appealing before the voting starts in February 2021.

* 👍 Successful feature requests will be prioritized during Nuvola development.  
* 👎 Unsuccessful feature requests will be closed.
* 👉 Follow ticket #678 for more details and to provide feedback on the voting process.

**Comment by rama-2402** [comment]
Add "AdBlocker" for Youtube, Youtube Music.

**Comment by fenryxo** [comment]
> Add "AdBlocker" for Youtube, Youtube Music.

Hello @rama-2402. That's covered in Support Chrome extensions #412. Once Chrome extensions are supported, you can install any adblocker you wish to.

**Comment by fenryxo** [comment]
Voting should start mid-February.

**Comment by fenryxo** [comment]
The voting is not yet ready as there were issues with Nuvola CI and a few bugs to fix.

**Comment by kowalk** [comment]
Please add support for Tidal "Master" streaming quality - now it's only possible to listen in HIFI quality:
![Screenshot from 2021-02-22 16-15-58](https://user-images.githubusercontent.com/2781079/108727965-6267a280-7529-11eb-8a1c-d9f133f5c9b4.png)

**Comment by fenryxo** [comment]
> Please add support for Tidal "Master" streaming quality - now it's only possible to listen in HIFI quality:
> ![Screenshot from 2021-02-22 16-15-58](https://user-images.githubusercontent.com/2781079/108727965-6267a280-7529-11eb-8a1c-d9f133f5c9b4.png)

Hello @kowalk. We currently support whatever is supported in Chrome and I'm afraid we don't have development resources to go beyond that.

**Comment by kowalk** [comment]
@fenryxo sorry to hear, but thanks for the answer. Cheers!

**Comment by fenryxo** [comment]
* Survey is not yet finished. I've been developing a new [Survey app](https://gitlab.com/tiliado/survey) with Django.
* New dates:
  * May 2021 - November 202: voting in the survey
  * December 2021: evaluation of the results

**Comment by fenryxo** [comment]
The survey has started with Nuvola Player 4.22 on May 9th, 2021.
