### ISSUE TITLE
Docs: Service Integrations Tutorial `integrate.js` line numbers do not match

### ISSUE THREAD

**Issue by strugee** [tiliado/nuvolaplayer#680]
On https://tiliado.github.io/nuvolaplayer/development/apps/tutorial.html#integration-script, the line-by-line explanation of what the script does at some point stops matching the actual script. I believe lines 31 through 84 are all off by one. `Lines 27-28 and 86` should instead be `Lines 27 and 83` since line 28 is blank and line 86 does not exist.

**Comment by fenryxo** [comment]
Fixed, thanks :-)

**Comment by strugee** [comment]
👍 sure! Thanks for maintaining Nuvola :-)
