### ISSUE TITLE
Consider renaming the "Web Worker" process to e.g. "Web Runner"

### ISSUE THREAD

**Issue by strugee** [tiliado/nuvolaplayer#681]
I'm going through the docs to create a new service and stumbled when I first read this term since it's also a [web platform thing](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API). I figured out pretty fast that they weren't the same, but it might be worth renaming to avoid the ambiguity.

**Comment by fenryxo** [comment]
Hello @strugee. Thanks for your suggestion. There is also the `InitWebWorker` signal so it must be renamed with care. Unlikely to happen anytime soon though.

**Comment by strugee** [comment]
No worries! If you don't want to do this for technical/backwards compatibility reasons feel free to close - I just figured I would raise it just in case since in my experience it can be kind of hard to spot this kind of problem when you're already deep into a codebase instead of being brand new.

**Comment by fenryxo** [comment]
Web Runner is a much better name.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
