### ISSUE TITLE
Nuvola Player doesn't recognize bandcamp tracks.

### ISSUE THREAD

**Issue by tetsuo76** [tiliado/nuvolaplayer#689]
Controls (Next song, Previous Song etc) don't work either. I am using Fedora 33 Workstation. Here is a screenshot:

![Screenshot-20201209194859-1364x906](https://user-images.githubusercontent.com/5783637/101667232-c1079f00-3a57-11eb-9efb-6bb7d2191ca9.png)

Nuvola Player version: 4.19.0 (0-gd583d07)
Bandcamp script version: 2.3.3 (3-g3d75a1d)

**Comment by fenryxo** [comment]
🐛 The bug has been fixed in **Bandcamp script version 2.3.4** (4-g9766db5). It's already available in [📦 the Nuvola Player flatpak repository](https://nuvola.tiliado.eu/app/bandcamp/) (both stable and development branches). Thanks for reporting the issue :+1:

**Comment by tetsuo76** [comment]
It's working perfectly. Many thanks!
