### ISSUE TITLE
Does it supports cahce?

### ISSUE THREAD

**Issue by fahad-irshad** [tiliado/nuvolaplayer#690]
Does it support cache for spotify? as you know spotify saves cache of music in storage to use it later, would love to have that and are there any .deb builds available?

**Comment by fenryxo** [comment]
Hello @fahad-irshad.

Spotify web player does cache played tracks, but I'm not sure how many tracks are cached.

Nuvola project doesn't and won't provide any official deb builds as we don't have enough resources to create and maintain them. There might be community deb builds, but I'm not aware of any right now.
