### ISSUE TITLE
Lyrics database

### ISSUE THREAD

**Issue by ConnyTheNerd** [tiliado/nuvolaplayer#692]
Hi developers and thank you for that great work!

What I would like to know - where or from which databases are the lyrics fetched? I often encounter songs which are international famous oldies and there is no lyrics available which I find a bit peculiar. Is there a way to determine the source (perhaps even more sources would be nice) of the lyrics database?

**Comment by fenryxo** [comment]
Hello @ConnyTheNerd. We fetch lyrics from http://www.azlyrics.com/ and https://gecimi.com/. It is possible to add another source though.

**Comment by ConnyTheNerd** [comment]
Hi @fenryxo,

that sounds good! But I assume it is not me who can add an additional source - but you the developers?
Or is there a way I could do that myself?

**Comment by fenryxo** [comment]
Yes, only developers can do that because the way the lyrics are extracted from the databases is always different.

**Comment by fenryxo** [comment]
Do you have in mind any source we could add? I know Lyrics Wiki, but it's been shut down :-(

**Comment by ConnyTheNerd** [comment]
Well, LetsSingIt.com, QuickLyrics and Musixmatch and/or lyrics finder from gnome extension for example? What would also be nice is
if I could choose myself ... Since for example "German" texts can only seldom be found.

And thank you again for your attention and efforts!

**Comment by fenryxo** [comment]
I've created tickets #698 #699 #700. Which lyrics finder gnome extension do you have in mind?

**Comment by ConnyTheNerd** [comment]
Here is the URL:
http://github.com/TheWeirdDev/lyrics-finder-gnome-ext
So actually to which database this is referring to I could not detect.

**Comment by fenryxo** [comment]
I've created #701 for that. That's all from this ticket I guess.
