### ISSUE TITLE
Amazon Music HD Music Playback

### ISSUE THREAD

**Issue by davidrhoderick** [tiliado/nuvolaplayer#693]
**Please describe in detail what you would like to solve with the proposed feature:**

Since I pay for HD service, I would love the ability to stream HD music from Amazon etc.  I realize this may not be completely possible via Nuvola but this is literally the top item on my wishlist for this software.  I pay for the HD service and use it well on my phone but on the Nuvola app, it isn't an option and I get a constant reminder that I should download the app to experience HD, which I can't do because I use Linux.

**Do you have an idea how it could be solved and how it should look like?**

If a user has an HD subscription, it should automatically be selected on load.  Additionally, an option could be present in the settings to allow switching between SD and HD streaming services.

**Describe alternatives you've considered:**

I can't use a native application for Linux for Amazon HD streaming services because it doesn't exist.  I could use my phone to stream but since I'm on a laptop, it seems superfluous.  Spotify has a native app so I sometimes use that instead of Amazon.

**Additional context:**

If you could at least remove the notification regarding downloading a native app from the Amazon music streamer, that would at least put this issue out of mind and not constantly remind me that I'm not using my streaming service to fullest extent.

**Comment by fenryxo** [comment]
Hello @davidrhoderick. @a-m-s could know something about it. I think that Tidal can offer "HiFi" music in Nuvola with Widevine, but I'm not sure about Amazon Music.

**Comment by davidrhoderick** [comment]
@fenryxo apologies but I accidentally closed this issue so the automation moved it into "In Progress".

**Comment by a-m-s** [comment]
https://www.amazon.co.uk/gp/help/customer/display.html?nodeId=G8X4YJYLED87FSH2
HD music is not supported by the web player, and therefore not by Nuvola.

Sorry.
