### ISSUE TITLE
gapless playback

### ISSUE THREAD

**Issue by mambostep** [tiliado/nuvolaplayer#694]
I looked for an application for playback the amazon music outside of a browser on linux. The supply isn't huge ... The nuvola player is very good.

Because I often want  to listen concept albums so I need an app that is able to play gapless all tracks. I'm under impression that the nuvola player can do it but only sometimes. Is it only by hazard or a feature that I can configure? The amazon music player app on my android smartphone is able to do this but android is not the OS on my PC ...

Thx in advance

**Comment by fenryxo** [comment]
Hello @mambostep. I don't think there is anything I can do about it in Nuvola as the Amazon web app itself is in charge of streaming and music playback, not Nuvola. Maybe @a-m-s could find a trick to force Amazon Music to play gapless?

**Comment by mambostep** [comment]
No problem but only an idea. Maybe the android app and the Windows app (I checked it just now) use a buffer to compensate the pause between tracks. With a suggestion of irony: the android app does it everytime. So I think it's not a feature of Amazon streaming by service but a palliation by the apps. Attention: without the option to switch it OFF if it's convenient or not !

So - it's your chance to be better then Amazon ... ;-)

**Comment by a-m-s** [comment]
I don't know of a way to do this. There may be some hack that could work (perhaps by duplicating the <audio> tag and fiddling the volume controls and play speed?), but it would be extremely fragile and liable to break Nuvola completely whenever Amazon makes a minor change. And it would screw up the lyric matching etc.

Basically, we'd have to rework the whole Amazon web player by live-patching the HTML and possibly the minified javascript too.

**Comment by fenryxo** [comment]
Indeed, Amazon web app itself is in charge of playback so it's up to them to implement gapless playback.
