### ISSUE TITLE
Can I Integrate Nuvola with Cinnamon's "Launch Player" Menu?

### ISSUE THREAD

**Issue by mfreeman72** [tiliado/nuvolaplayer#695]
I'm not sure if this is a bug report, a feature request, or just a question...

I'm running Nuvola on Cinnamon on Linux Mint 20.1. While it can integrate well with the player controls and cover art display in the sound applet, none of the Nuvola players are showing up in the "Launch Player" menu in the sound applet. Is there a way to get Nuvola to do this? All of my other audio and video player applications show up. Just not Nuvola's players.

In the image I'm attaching, you can see all my installed players, except for any of the installed Nuvola players (the "Spotify" entry is the official Spotify application, not Nuvola's).

![Launch_Player_Menu](https://user-images.githubusercontent.com/7842664/104639550-6536c400-565c-11eb-93af-2813788615ba.png)

**Comment by fenryxo** [comment]
Hello @mfreeman72. Nuvola players show in **Linux Mint 20**. I'm not yet sure why not in **Linux Mint 20.1**.

**Comment by mfreeman72** [comment]
Strange. Everything seems to work fine with the Nuvola players except they aren't in the Launch Player menu, and can't be quit through the sound menu, either. I have to quit them through the Nuvola player's own quit option in its menu. I don't seem to have any problems getting other programs to appear in the Launch Player menu (and as a test, I just installed Clementine while writing this, which I've never installed on this specific machine, and it shows up in the Launch Player menu as soon as I run it). I've tried all the settings in Preferences in the Nuvola players. I'm very confused as to why Nuvola isn't working with it.

Could it be a Flatpak-related problem? I've never seen a Flatpak yet that fully integrates well with the system, and even things that are supposed to work sometimes need to be manually tweaked in some way to get it integrating like it should.

**Comment by fenryxo** [comment]
Created upstream issue: linuxmint/cinnamon#9866

**Comment by fenryxo** [comment]
> can't be quit through the sound menu, either. I have to quit them through the Nuvola player's own quit option in its menu.

That's a bug in Nuvola - #696

**Comment by mfreeman72** [comment]
Ok. You can ignore that comment, then. :)

**Comment by fenryxo** [comment]
Closing in favor of linuxmint/cinnamon#9866
