### ISSUE TITLE
Nuvola player don't work

### ISSUE THREAD

**Issue by maxxcan** [tiliado/nuvolaplayer#697]
The error on console is
Your system is broken: dlsym doesn't work! This has been reported to be caused by Nvidia's libGL

[0122/060333.129182:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process

**Comment by fenryxo** [comment]
Hello @maxxcan. Could you elaborate more on what do exactly you mean by "Nuvola player don't work"? Also please provide the full debugging output `flatpak run eu.tiliado.NuvolaAppXxx --debug`. Thanks.

**Comment by maxxcan** [comment]
Here: 

Runner: [DEBUG Δ013422us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Runner: [DEBUG Δ003807us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Runner: [DEBUG Δ000053us  GLib] setenv()/putenv() are not thread-safe and should not be used after threads are created
Runner: [DEBUG Δ052013us  GLib] unsetenv() is not thread-safe and should not be used after threads are created
Runner: [DEBUG Δ022571us Nuvola] AboutDialog.vala:54: Nuvola Player 4.20.0 (0-gd3f19e9)
Runner: [DEBUG Δ000041us Nuvola] AboutDialog.vala:56: Amazon Cloud Player script 5.11.1 (1-ga66d701)
Runner: [DEBUG Δ000032us Nuvola] AboutDialog.vala:60: Diorite 4.20.0
Runner: [DEBUG Δ000075us Nuvola] AboutDialog.vala:62: Chromium 75.0.3770.100
Runner: [DEBUG Δ000022us Nuvola] AboutDialog.vala:63: ValaCEF 75.3770.16
Runner: [DEBUG Δ021931us  GLib] unsetenv() is not thread-safe and should not be used after threads are created
Runner: [DEBUG Δ25s079110us DioriteGtk] DesktopShell.vala:254: Shell: bspwm (null), CSD 0, appmenu 0, menubar 0
Runner: [DEBUG Δ000525us  GLib] setenv()/putenv() are not thread-safe and should not be used after threads are created
Runner: [DEBUG Δ065486us Nuvola] config.vala:143: Json Error: Falló al abrir el archivo «/home/maxxcan/.var/app/eu.tiliado.NuvolaAppAmazonCloudPlayer/config/nuvolaruntime/apps_data/amazon_cloud_player/config.json»: No such file or directory
Runner: [DEBUG Δ047370us Nuvola] Connection.vala:124: Network Proxy: system settings
Runner: [DEBUG Δ25s308947us GLib-GIO] _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
Runner: [DEBUG Δ019939us GLib-GIO] _g_io_module_get_default: Found default implementation libproxy (GLibproxyResolver) for ‘gio-proxy-resolver’
Runner: [DEBUG Δ192907us GdkPixbuf] gdk_pixbuf_from_pixdata() called on:
Runner: [DEBUG Δ000038us GdkPixbuf] 	Encoding raw
Runner: [DEBUG Δ000016us GdkPixbuf] 	Dimensions: 14 x 14
Runner: [DEBUG Δ000014us GdkPixbuf] 	Rowstride: 56, Length: 808
Runner: [DEBUG Δ000014us GdkPixbuf] 	Copy pixels == false
Runner: [DEBUG Δ01s765126us Nuvola] AppRunnerController.vala:112: Scale factor: 1
Runner: [DEBUG Δ005035us DioriteGtk] Application.vala:255: XFCE session vanished: org.xfce.SessionManager
Runner: [DEBUG Δ072976us CefGtk] WidevinePlugin.vala:15: Widevine path: /home/maxxcan/.var/app/eu.tiliado.NuvolaAppAmazonCloudPlayer/data/nuvolaruntime/apps_data/amazon_cloud_player/widevine
Your system is broken: dlsym doesn't work! This has been reported to be caused by Nvidia's libGL. You should expect time related functions to misbehave. https://bugs.chromium.org/p/chromium/issues/detail?id=16800
Runner: [INFO Δ361839us CefGtk] WidevinePlugin.vala:27: WidevinePlugin is available: 0 (null)
[0124/093726.822036:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by fenryxo** [comment]
So, the output stops with the last line from your log and nothing else happens? No other output, no window is shown?

Also, what are your Linux distribution and the desktop environment?

**Comment by maxxcan** [comment]
The window is this
![image](https://user-images.githubusercontent.com/4959947/105632907-f9233f80-5e55-11eb-8eca-3ee3ca35756b.png)

I use Archlinux with bspwm and few days I hadn't any problems.

**Comment by fenryxo** [comment]
It seems to be a system issue. D-Bus activation of XDG desktop portals fails. I'll look at it once a spin up Arch Linux in GNOME Boxes.

**Comment by fenryxo** [comment]
I'm afraid I cannot reproduce your issue in my virtualized Arch Linux. I installed D-Feet (`pacman -Sy d-feet`) and used it to activate DBus service `org.freedesktop.portal.Desktop` without any issues. I can give you a few hints as to where to look and get help from other Arch Linux users.

The  `org.freedesktop.portal.Desktop` DBus service is defined here:

```
$ cat /usr/share/dbus-1/services/org.freedesktop.portal.Desktop.service
[D-BUS Service]
Name=org.freedesktop.portal.Desktop
Exec=/usr/lib/xdg-desktop-portal
SystemdService=xdg-desktop-portal.service
AssumedAppArmorLabel=unconfined
```

There is a corresponding systemd service:

```
$ systemctl --user status xdg-desktop-portal.service
\u25cf xdg-desktop-portal.service - Portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static)
     Active: active (running) since Sun 2021-01-24 21:01:58 CET; 2min 16s ago
   Main PID: 1586 (xdg-desktop-por)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal.service
             \u2514\u25001586 /usr/lib/xdg-desktop-portal

Jan 24 21:01:57 archlinux systemd[689]: Starting Portal service...
Jan 24 21:01:58 archlinux systemd[689]: Started Portal service.
```

If it fails to start automatically, you can try starting it manually:

```
$ /usr/lib/xdg-desktop-portal
```

**Comment by maxxcan** [comment]
ok I found the problem. 
I don't know exactly why but I starting the session with slim, but Nuvola only works if I start the session with lxdm, kdm or gdm. 

I'm very sorry to make you waste your time.

**Comment by fenryxo** [comment]
No problem. I'm glad you have managed to resolve the issue :-)
