### ISSUE TITLE
Nuvola scrobbles twice to last.fm

### ISSUE THREAD

**Issue by dd23** [tiliado/nuvolaplayer#70]
I just activated the scrobbling for last.fm which seems to work fine, except that sometimes Nuvola3 scrobbles tracks twice. 
I think it happens, when I pause a track and finish it later, but I wasn't able to verify if that is indeed the cause for the problem.

Anyway, it would be great if you could look into this.

**Comment by fenryxo** [comment]
Hi. Thanks for taking the time to report this issue. I've just fixed it in the master branch, will be available in the next rebuild of packages. Feel free to reopen this ticket if the issue persists.
