### ISSUE TITLE
Multi-App Media Control

### ISSUE THREAD

**Issue by andre-exads** [tiliado/nuvolaplayer#702]
**Please describe in detail what you would like to solve with the proposed feature:**

When you have multiple apps playing at the same time, say:
 - youtube playing white noises (rain on the window);
 - youtube-music playing songs;
Then you want to pause/play both apps at the same time with keyboard media keys, and most likely if you press the skip forward/backward you want only one app (the one playing songs) to get that command.

**Do you have an idea how it could be solved and how it should look like?**

Add advanced media key binding or something similar that consider multiple apps.

**Describe alternatives you've considered:**

Using the mouse to access the "notifications panel" had been the only way to achieve a similar control.

**Additional context:**

![image](https://user-images.githubusercontent.com/54406757/105844080-8c808000-5fd0-11eb-942a-bd1e9c0b1634.png)

**Comment by fenryxo** [comment]
Hello @andre-exads, thanks for your suggestion, but your idea seems too complex and I'm not going to implement it. You can, however, use [Nuvola's command line interface](https://nuvola.tiliado.eu/docs/4/command_line.html) to achieve your goal.

For example, you can create a script `toggle-play-all.sh` and assign a keyboard shortcut in GNOME Settings → Keyboard shortcuts.

```
#!/bin/bash
for app in $(flatpak run eu.tiliado.Nuvola api-master /nuvola/core/list_apps | jq -r '.[].id')
do flatpak run eu.tiliado.Nuvola -a $app action toggle-play
done
```

**Comment by andre-exads** [comment]
> Hello @andre-exads, thanks for your suggestion, but your idea seems too complex and I'm not going to implement it. You can, however, use [Nuvola's command line interface](https://nuvola.tiliado.eu/docs/4/command_line.html) to achieve your goal.
> 
> For example, you can create a script `toggle-play-all.sh` and assign a keyboard shortcut in GNOME Settings → Keyboard shortcuts.
> 
> ```
> #!/bin/bash
> for app in $(flatpak run eu.tiliado.Nuvola api-master /nuvola/core/list_apps | jq -r '.[].id')
> do flatpak run eu.tiliado.Nuvola -a $app action toggle-play
> done
> ```

Thanks a lot for the reply. That script will do the trick :+1:
