### ISSUE TITLE
Is Qobuz Supported at Hi-Res?

### ISSUE THREAD

**Issue by hurrricane478** [tiliado/nuvolaplayer#703]
Hello,
First of all, thanks for bringing Qobuz and Amazon Music to Linux outside of the web player, I really appreciate that. I was wondering if Qobuz was supported at beyond CD quality or is it supported at beyond that? Is Amazon Music HD supported at CD quality or better? 

Thanks in advance.

**Comment by fenryxo** [comment]
Hello @hurrricane478. @Romunix, the maintainer of the Qobuz script in Nuvola, might know the answer.

**Comment by hurrricane478** [comment]
Thank you very much, I hope you have a good day.

**Comment by fenryxo** [comment]
@Romunix will answer you here :-)

**Comment by hurrricane478** [comment]
Oh, sorry. Thanks again for the help.

**Comment by Romunix** [comment]
Hello,

Nuvola uses the Qobuz webplayer with system integration.

And the web player allows listening quality up to "Hi-Res 24-Bit / up to 192 kHz" so you can enjoy the best quality of qobuz.

I hope I have answered your question.

**Comment by hurrricane478** [comment]
Thank you very much, that answered my question.
