### ISSUE TITLE
command line a nd startup

### ISSUE THREAD

**Issue by jpberry** [tiliado/nuvolaplayer#706]
hello,
I'd like to start Nuvola automatically, using the standard "startup application" app. Nuvola is not in the list of proposed applications. To add it, I need a command line to start it up. What could that possibly be ?
Thanx
JP

**Comment by fenryxo** [comment]
Hello @jpberry. The command is:

```
flatpak run eu.tiliado.NuvolaAppSpotify
```

Replace `eu.tiliado.NuvolaAppSpotify` with the app you use from the list:

```
flatpak list --app --columns=name,application | grep eu.tiliado.NuvolaApp
```
