### ISSUE TITLE
Vapi patch directly in system ?

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [tiliado/nuvolaplayer#707]
https://github.com/tiliado/nuvolaplayer/blob/master/wscript#L611-L622

Is this actually patching the vapi files in user's system directly during build ?

Anyway I'm trying to package nuvolaplayer for Nixpkgs and I'm wondering if you could either give an option in the wscript to disable those patches or to support giving other vapi dirs.

**Comment by fenryxo** [comment]
Hello @SCOTT-HAMILTON, it doesn't patch system vapi files in-place, it creates a patched copy of some system vapi files as needed. I'll add `--no-vapi-patch` configure option.

**Comment by fenryxo** [comment]
Before considering packaging Nuvola, make sure you can package [Vala-CEF 75.3770](https://github.com/tiliado/valacef/tree/75.3770.x), which requires ancient patched [CEF 75.3770](https://github.com/tiliado/cef/tree/3770-valacef) (the latest Chrome version is 88). I'd recommend waiting for #583.

**Comment by SCOTT-HAMILTON** [comment]
Ok, you're right, I better wait for the QtWebEngine port.

**Comment by fenryxo** [comment]
Fixed in master branch.
