### ISSUE TITLE
chose country for  audible player

### ISSUE THREAD

**Issue by d7p** [tiliado/nuvolaplayer#708]
Hi 

Having installed the audible plugin I logged in to Audible and was told I don't have any books in my library. As I'v had an Audible subscription for may years I know that is not the case. After checking is seems that Nuvo Audible plugin goes to Audible.com and accounts/ libraries are not copied between countries.  I can not see a way to change the TLD (from .com to .co.uk etc) in the settings etc.

.com would be a good default but i would expect to change it in the settings somewhere.

Thanks for your work.

**Comment by fenryxo** [comment]
Hello @d7p, indeed, we need to add a selector of country variants.

**Comment by fenryxo** [comment]
What is the domain of your national variant?

**Comment by d7p** [comment]
HI 

UK. The TLD is co.uk 
I don't know how many other TLDs audible use but as they are part of amazon i suspect they is one for every country they operate in.

**Comment by fenryxo** [comment]
🍬 The feature was added to **Audible script version 1.0.1** (1-ge6895c3). It's already available in [📦 the Nuvola Player flatpak repository](https://nuvola.tiliado.eu/app/audible/) (both stable and development branches). Thanks for reporting the issue :+1:

**Comment by d7p** [comment]
Thanks
