### ISSUE TITLE
Scrobble also repeated song in Google Play

### ISSUE THREAD

**Issue by trakhov** [tiliado/nuvolaplayer#71]
**Steps to reproduce the problem**:
1. start playback of some song in Google Play Music
2. check the «repeat 1 song» button
3. make sure last.fm scrobbling is enabled
4. wait for 2 or 3 repeating cycles
5. open last.fm page

**Expected behaviour**: the list of recently played songs includes multiple repetitions of the chosen song.

**What goes wrong**: the list of recently played songs includes only one copy of the chosen song.

**Comment by fenryxo** [comment]
Hi @trakhov. Thanks for taking the time to report this issue. Nuvola Player currently memorizes the last scrobbled track and doesn't scrobble it again on purpose to prevent double scrobble issue #70. It is neccessary to find a way how to distinguish following two events:

1. User pauses and resumes playback of a single non-repeating track. => Don't scrobble again.
2. User repeats single track. => Scrobble the track again.

**Comment by dd23** [comment]
I think resetting the ``scrobbled`` status back to false, once a song is finished would solve this problem.

**Comment by fenryxo** [comment]
Nuvola Player currently does that. However, it uses a very simple assumption to detect when song finished: "If an artist or a song name changes, the previous song has finished." This approach obviously doesn't work with a single repeated song.

**Comment by fenryxo** [comment]
I'm closing this ticket as this feature would complicate code without a significant benefit.
