### ISSUE TITLE
Update logos for Deezer

### ISSUE THREAD

**Issue by nclm** [tiliado/nuvolaplayer#710]
In most places, Nuvola seems to use an older version of the Deezer logo and icon. It should be updated everywhere with the latest version of the logotype: https://deezerbrand.com/d/9wmMErzrRuiH/brand-elements#/brand-dna/logotype

Some files to update:
- https://github.com/tiliado/nuvolaplayer/blob/master/graphics/service-icons/deezer.orig.svg
- https://github.com/tiliado/nuvolaplayer/blob/master/graphics/service-icons/deezer.svg
- https://github.com/tiliado/nuvola-app-deezer/blob/master/src/icon.svg
- https://github.com/tiliado/nuvola-app-deezer/blob/master/src/icon-xs.svg
- https://github.com/tiliado/nuvola-app-deezer/blob/master/src/icon-sm.svg
- https://nuvola.tiliado.eu/static/apps/deezer.png

**Comment by fenryxo** [comment]
Hello @nclm, thanks for you tip :-)

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
