### ISSUE TITLE
Spotify Connect devices not listed

### ISSUE THREAD

**Issue by jcassee** [tiliado/nuvolaplayer#711]
### Basic information

- Your Linux distribution and its version: Ubuntu 20.04

- Your desktop environment: GNOME

- Nuvola Runtime version: 4.20.1 (1-g4a9ecde)

- The web app you use and its version: Spotify 3.3.0 (0-g0d7419d)

### Describe the bug

In the device list, my Spotify Connect devices do not appear. They do appear in the Spotify Linux client.

**Steps to reproduce the behavior**

1. Open the Nuvola Spotify app.
2. Open the "connect device" menu in the player area:  <img src="https://user-images.githubusercontent.com/20749/109484240-7b6bd880-7a80-11eb-8b84-6f4bf531c370.png" height="18">
3. Spotify Connect devices are not listed.

**Expected behavior**

To see Spotify Connect devices in the menu.

**Debugging log**

Attach the debug log here:
[nuvola-log.txt](https://github.com/tiliado/nuvolaplayer/files/6060846/nuvola-log.txt)
[nuvola-spotify-log.txt](https://github.com/tiliado/nuvolaplayer/files/6060848/nuvola-spotify-log.txt)

**Screenshots**

Attach screenshots here:

The device list in the Linux Spotify client:
<img src="https://user-images.githubusercontent.com/20749/109483457-8d00b080-7a7f-11eb-94b3-f75eff07ab43.png" width="200">

The device list in the Nuvola Spotify app:
<img src="https://user-images.githubusercontent.com/20749/109483530-a570cb00-7a7f-11eb-8268-873e5c9e6a70.png" width="200">

**Additional context**

...

**Comment by fenryxo** [comment]
Hello @jcassee, thanks for reporting the issue.

* Do the Spotify Connect devices appear in the web player  https://open.spotify.com ?
* Do you have Spotify Premium account and are you logged in with it in Nuvola? (Spotify support pages says that some Spotify Connect devices require Premium account.)

**Comment by jcassee** [comment]
Indeed, the web player did not show Connect devices. Their webpage on Connect suggests the web player should work fine.

<img src="https://user-images.githubusercontent.com/20749/109774579-cd3b6c80-7c00-11eb-9702-a7a37984c11c.png" height="160">


But I found this buried [in the support forum](https://community.spotify.com/t5/Spotify-Answers/What-is-Connect-and-how-can-I-use-it/ta-p/4964156):
> Currently to be able to control another device via the Connect feature on Desktop and the Web player, you'll need to start playing music from the device itself or have the Spotify app open first. Then you’ll get to see it in the Devices available list on your computer.

So there is the answer. Thanks for putting me on the right track. I'm closing this issue now.
