### ISSUE TITLE
No sounds from App

### ISSUE THREAD

**Issue by A1eph0** [tiliado/nuvolaplayer#712]
### Basic information

- Your Linux distribution and its version: Ubuntu 20.o4.2 LTS
   

- Your desktop environment: GNOME
   

 - Nuvola Runtime version: 4.20.1 (1-g4a9ecde)
   

 - The web app you use and its version: Amazon Cloud Player 5.11.1 (1-ga66d701)
   

### Describe the bug

...

**Steps to reproduce the behavior**

1. Press on Play button for any song
2. Music is shown (graphically by the player bar etc) to be playing, but there is no sound from the app at all.

**Expected behavior**

Sound is expected while playing.

**Debugging log**

Attach the debug log here: ...

**Screenshots**

Attach screenshots here: ...

**Additional context**

...
[NuvolaAppAmazonCloudPlayer_log.txt](https://github.com/tiliado/nuvolaplayer/files/6073543/NuvolaAppAmazonCloudPlayer_log.txt)
[Nuvola_log.txt](https://github.com/tiliado/nuvolaplayer/files/6073540/Nuvola_log.txt)

**Comment by fenryxo** [comment]
Hello @A1eph0. Thanks for reporting the issue. The log says that the headphones were connected. Does the issue persist also without headphones? If yes, could you install PulseAudio Volume Control app (`pavucontrol`) and check whether

1. Nuvola's audio stream is not muted.
2. Nuvola's audio stream has the correct output device set.
3. The bar in the red rectangle on the screenshot pulseswhen misic is pleying.

![image](https://user-images.githubusercontent.com/853706/110035703-45f31380-7d3c-11eb-9507-baa604fabd21.png)

**Comment by fenryxo** [comment]
Hello. There hasn't been any response for a month. Please add a comment if the issue has not been resolved yet.
