### ISSUE TITLE
Please add an app icon for Focus@Will

### ISSUE THREAD

**Issue by trustin** [tiliado/nuvolaplayer#713]
**Please describe in detail what you would like to solve with the proposed feature:**

Focus@Will app currently has a generic icon, which is hard to know it will launch Focus@Will.

**Do you have an idea how it could be solved and how it should look like?**

How about using something based on Focus@Will's logo?
See: https://i1.wp.com/blog.focusatwill.com/wp-content/uploads/2018/01/app-icon.png

**Describe alternatives you've considered:**

Maybe extract some assets from their official Linux app (Electron)?

**Comment by fenryxo** [comment]
Hello @trustin. Unfortunately, we currently don't have an icon designer on our team. We cannot simply take an arbitrary icon from the internet neither. It needs to have an open-source license.

**Comment by trustin** [comment]
Out of curiosity, does Spotify icon have an open-source license? :thinking:

**Comment by fenryxo** [comment]
Yes, the icon we use for the Spotify app was created for Nuvola by Alexander King and is licensed under BSD-2-Clause ([copyright info](https://github.com/tiliado/nuvola-app-spotify#copyright)).

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
