### ISSUE TITLE
Qobuz: support design v5.8.0-b021+

### ISSUE THREAD

**Issue by Romunix** [tiliado/nuvolaplayer#715]
Qobuz has updated this design.

The player integration does not work with the new design and needs to be updated.

The new JS version of Qobuz is : 5.8.0-b021

**Comment by fenryxo** [comment]
Hello @Romunix, are still working on this or have you already finished porting your script? Thanks :-)

**Comment by Romunix** [comment]
Hello @fenryxo, I finished porting the script and added a set of custom icons.

**Comment by fenryxo** [comment]
Great :-) I've published an updated Flatpak package.
