### ISSUE TITLE
Integration request for Anghami

### ISSUE THREAD

**Issue by akmalkady** [tiliado/nuvolaplayer#716]
Anghami is a popular music platform. Anghami in just google play has +50M downloads. 
https://www.anghami.com/

Could you please support it. 
Best,

**Comment by fenryxo** [comment]
Hello @akmalkady, thanks for your feature request :-)

**Comment by fenryxo** [comment]
Hello @akmalkady, Anghami integration has been added:

* [Installation instructions](https://nuvola.tiliado.eu/app/anghami/)
* [Source code](https://github.com/tiliado/nuvola-app-anghami)
