### ISSUE TITLE
Automatic configuration from Nuvola of Sample Format and Sample Rate in PulseAudio.

### ISSUE THREAD

**Issue by bordelaque** [tiliado/nuvolaplayer#717]
For Qobuz it would be fantastic.
Volumio gets there why not Nuvola

Thanks

Damien

**Comment by fenryxo** [comment]
Hello @bordelaque. I have no idea what exactly do you request and why it that needed. Could you elaborate more? Thanks.

**Comment by bordelaque** [comment]
Hello Jiri,

Today, when i listen music on my system, each tracks are differents !
Some tracks are 24bits, 192Khz, some tracks are 24bits, 96Khz, some track
are 24bits 48Khz, some tracks are 16bits, 44,1Khz, ......
For exemple: if I'm listening a track 16bits 44,1Khz. Before i need to
configure the File \\etc\pulse\daemon.conf with :
default-sample-format = s16le
default-sample-rate = 44100
and after I write in console : pulseaudio -k   pulseaudio -D
If the next track is 24bits 192Khz Before i need to change the
configuration of the file daemon.conf like this :
default-sample-format = s24le
default-sample-rate = 192000
and after I write in console : pulseaudio -k   pulseaudio -D

In fact, it's not easy....
If Nuvola would can configure automaticaly the file daemon.conf ....it
would be fantastic !!!
Perhaps ,there are others solutions....
Firefox make this option but only 44,1Khz and 48Khz 😥
Look in attachment, there are some photos.
Thank you for your work.

Best regards

Damien GRIMAUD



Le lun. 22 mars 2021 à 08:40, Jiří Janoušek ***@***.***> a
écrit :

**Comment by fenryxo** [comment]
Hello @bordelaque. Could you attach the photos via GitHub website? It cannot be done via e-mail

**Comment by bordelaque** [comment]
![20210322_221707](https://user-images.githubusercontent.com/69172767/112242482-3f293380-8c4c-11eb-8867-ede6a6103238.jpg)
![20210322_222644](https://user-images.githubusercontent.com/69172767/112242492-451f1480-8c4c-11eb-86a3-293006fbf1d8.jpg)
![20210322_222037](https://user-images.githubusercontent.com/69172767/112242504-49e3c880-8c4c-11eb-98c6-89be5c562d41.jpg)
![20210322_221936](https://user-images.githubusercontent.com/69172767/112242517-4fd9a980-8c4c-11eb-8777-7b85ca9898dd.jpg)
![20210322_221928](https://user-images.githubusercontent.com/69172767/112242523-536d3080-8c4c-11eb-9e06-0914cfcedbf6.jpg)

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
