### ISSUE TITLE
Do not activate microphone

### ISSUE THREAD

**Issue by snake3lake** [tiliado/nuvolaplayer#718]
I use [micro-camera-privacy](https://extensions.gnome.org/extension/2099/micro-camera-privacy/) to see if my camera or microphone are activated. Nuvola activates the microphone by default which isn't necessary.

I would like Nuvola not to activate the microphone.

Best regards,

**Comment by fenryxo** [comment]
Hello @snake3lake. I installed the extension but I cannot find any sign of microphone activation. No icon in the top right corner, no application shown in PulseAudio Volume Control's Recording tab. 

![image](https://user-images.githubusercontent.com/853706/112745984-6b2a1900-8fac-11eb-9027-ad6f5a945f74.png)

Could you provide more details?

* Which distribution and version do you use?
* Which streaming service do you use?

Thanks.

**Comment by fenryxo** [comment]
I'm closing this issue as there has not been any response from the reporter for a month, so I cannot investigate the issue further. If the problem still occurs, please provide me with the required information and I will look at it again. If you are unsure which information I need, you can ask me here.
