### ISSUE TITLE
Couldn't sign on Spotify and Primephonic using my google account

### ISSUE THREAD

**Issue by thicknee** [tiliado/nuvolaplayer#719]
Hi

I have just installed the last version of Nuvola Player and I tried to use the Spotify and Primephonic scripts.
I tried to login using my Google account, but I received the message:

Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

OS: Ubuntu Linux 20.04

I really appreciate some advice

Best

D

**Comment by fenryxo** [comment]
Hello @thicknee. Thanks for reporting the issue. I'll look at it.

**Comment by fenryxo** [comment]
Hello @thicknee, could you try with the latest stable flatpaks?

* Nuvola 4.20.2 (2-g9904d45) 
* Spotify script 3.3.4 (4-g0b9414b)
* Primephonic script 1.0.3 (3-g14b1e57)

**Comment by thicknee** [comment]
Hi @fenryxo 

Now it works

Thanks
