### ISSUE TITLE
Artist incorrect (Add Song Icon) in Spotify

### ISSUE THREAD

**Issue by hovancik** [tiliado/nuvolaplayer#723]
### Basic information

- Your Linux distribution and its version: Ubuntu 20.04
   

- Your desktop environment: KDE
   

 - Nuvola Runtime version: 4.21.0
 

 - The web app you use and its version: Spotify
   

### Describe the bug
Artist is incorrect in Spotify (in Desktop notification or when being scrolled). It is always "Add Song Icon". Song's title is fine. 

...

**Steps to reproduce the behavior**

1. Play song
2. Artist is "Add Song Icon"

**Expected behavior**

Title is correct
**Debugging log**

Attach the debug log here: ...

**Screenshots**

![image](https://user-images.githubusercontent.com/4745859/114359994-d3642780-9b74-11eb-93c7-03636728ae98.png)

**Additional context**

...

**Comment by fenryxo** [comment]
Hello @hovancik, good catch :-) The bug occurs only on the artist page. Could you check the latest flatpak with Spotify script 3.4.1 (1-g37d7d72)? Thanks.

**Comment by hovancik** [comment]
Great work @fenryxo , works now fine both in tooltips and in scrobller, thanks!
