### ISSUE TITLE
Nuvola player Gapless

### ISSUE THREAD

**Issue by farkiker** [tiliado/nuvolaplayer#724]
**Please describe in detail what you would like to solve with the proposed feature:**
Is it possible achieve  gapless  playback across the range of  services the the Nuvola player ?
Qobuz for example can't playback gapless  via Nuvola at present .

**Comment by fenryxo** [comment]
Hello @farkiker. Unfortunately, gapless playback cannot be enforced from Nuvola.  Nuvola provides streaming services with a  web engine to create and manage media streams, playback, buffering, etc. Nuvola doesn't control that.

I'm closing this issue as we cannot act on it. However, if you have any follow-up questions, feel free to ask.
