### ISSUE TITLE
Repeated notifications with Spotify

### ISSUE THREAD

**Issue by hovancik** [tiliado/nuvolaplayer#725]
### Basic information

- Your Linux distribution and its version: Ubuntu 20.04
   

- Your desktop environment: KDE
   

 - Nuvola Runtime version: 4.21.0 (0-g96d9bdb)
   

 - The web app you use and its version: Spotify 3.4.1 (1-g37d7d72)
   

### Describe the bug

Notification won't finish. It gets to about the 1/3rd of duration and then starts again and again
**Steps to reproduce the behavior**

Play song
Check notification

**Expected behavior**

Notification finishes

**Debugging log**

Attach the debug log here: 
```
Runner: [WARNING Δ246333us Nuvola] Notifications.vala:127: Unable to show notification: GDBus.Error:org.freedesktop.Notifications.Error.ExcessNotificationGeneration: Created too many similar notifications in quick succession
```

**Screenshots**

Attach screenshots here: 

![image](https://user-images.githubusercontent.com/4745859/114980979-91e1be00-9e8d-11eb-8dba-76123d399fed.png)

**Additional context**

Any other notifications of other apps work correctly.

**Comment by fenryxo** [comment]
Hell @hovancik. Thanks for your bug report :-)

**Comment by fenryxo** [comment]
Hello @hovancik, could you test the latest flatpak build with **Spotify script  3.4.2 (2-geff3f1a)**? Thanks :-)

**Comment by hovancik** [comment]
Looks good!
