### ISSUE TITLE
How do I use Google login for Deezer on Ubuntu Linux?

### ISSUE THREAD

**Issue by dcandis** [tiliado/nuvolaplayer#726]
Type your question here.
Installation and program start just fine. I previously used Tidal with no issues. However, when I created my Deezer account, I used Google SSO and I'm unable to do so with the Nuvola player. Is there a setting or trick to make this work?

Thanks in advance.

**Comment by fenryxo** [comment]
Hello @dcandis. Thanks for reporting your issue. Could you check whether it is resolved with the latest flatpak build with **Deezer script 3.4.1 (1-g77d1220)**? Thanks :-)

**Comment by dcandis** [comment]
Works perfectly! Thanks so much for the very fast response.
