### ISSUE TITLE
Deezer Client Needs to Support High Fidelity

### ISSUE THREAD

**Issue by dcandis** [tiliado/nuvolaplayer#728]
**Please describe in detail what you would like to solve with the proposed feature:**

I have the Hifi option for Deezer. However, that option doesn't show when using nuvola player. When I access Deezer using Vivaldi, the option appears. The same for any Chrome based browser.

Please fix.

Thank you.

**Comment by fenryxo** [comment]
Hello @dcandis, thanks for reporting your issue. I hope it gets resolved when Nuvola is ported to a new web engine (#583). I'll check it at the weekend.

**Comment by fenryxo** [comment]
Hello @dcandis, I've used Nuvola Player project funds to upgrade my account to Deezer HiFi. I can confirm your observation that HiFi quality is available in Vivaldi but not supported in Nuvola Player. 

I tested Deezer player with [DodoWebEngine](https://github.com/tiliado/dodo-web-engine) and **it supports HiFi** as shown in the picture below.

![image](https://user-images.githubusercontent.com/853706/116807653-a338f480-ab34-11eb-845b-7e58fbe377f3.png)

Unfortunately, DodoWebEngine is not yet ready to be used by Nuvola Player, so I don't have any solution for your problem in the short them. If you purchased Nuvola license and HiFi quality is critical for you, [you may ask for a refund](https://nuvola.tiliado.eu/terms/).

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
