### ISSUE TITLE
Apple music script won't play/show login

### ISSUE THREAD

**Issue by bill812** [tiliado/nuvolaplayer#730]
**Unfortunately, Apple Music is currently incompatible with Nuvola Player and there is no feasible workaround.** Per [our terms](https://nuvola.tiliado.eu/terms/), the service has been marked as deprecated and affected Nuvola Player users may ask for a refund of their Nuvola Player license. We plan to bring Apple Music back once #583 is resolved by the end of 2021.

Reason for the incompatibility: Apple Music website fails with `Uncaught SyntaxError: Unexpected token ?` because it requires a new version of JavaScript engine supporting `??` operator. The only way to fix the issue is upgrading the web engine, which will happen with #583 by the end of 2021.

---

Original report:

I'm new to nuvola player.  I installed the apple music script, not sure how to login to apple music so nothing is playing.   The screen populates but the play buttons do nothing when I click on browse and radio.  Nothing happens when I click on listen now.

Any tips? Im running ubuntu 21.04.

Here's what happens when I run from command line:

```
$ flatpak run eu.tiliado.NuvolaAppAppleMusic
Gtk-Message: 10:29:43.804: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:29:43.805: Failed to load module "canberra-gtk-module"
Your system is broken: dlsym doesn't work! This has been reported to be caused by Nvidia's libGL. You should expect time related functions to misbehave. https://bugs.chromium.org/p/chromium/issues/detail?id=16800
Runner: [WARNING Δ388932us Nuvola] StartupWindow.vala:146: tiliado-account-message: Features Tier: ★ Premium
Worker: [DEBUG Δ003555us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ000084us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Worker: [DEBUG Δ012829us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ000020us CefGtk] RendererContext.vala:57: JS Context created 1
Worker: [DEBUG Δ003521us  GVFS] org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

Worker: [DEBUG Δ000102us GLib-GIO] _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
Worker: [DEBUG Δ002617us Nuvola] CefRendererExtension.vala:137: Got JS context
Worker: [INFO Δ002606us CefGtk] RendererContext.vala:57: JS Context created 1
Worker: [DEBUG Δ135027us Nuvola] CefRendererExtension.vala:145: Lost JS context
Worker: [INFO Δ000019us CefGtk] RendererContext.vala:64: JS Context released: 1
```

**Comment by fenryxo** [comment]
Hello @bill812, thanks for reporting the issue.  Unfortunately, Apple Music has become incompatible with Nuvola Player. I've updated the issue description with the reason and our plan to bring Apple Music back. I'm sorry that we cannot provide any short-term fix to let you use Apple Music with Nuvola Player.

**Comment by bill812** [comment]
Got it, thank you.

**Comment by fenryxo** [comment]
Please keep the issue open until we fix it. Thanks :-)

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
