### ISSUE TITLE
Popular list broken in Spotify

### ISSUE THREAD

**Issue by davidrhoderick** [tiliado/nuvolaplayer#732]
### Basic information

- Your Linux distribution and its version: Pop!_OS 20.10
- Your desktop environment: GNOME 3.38.3
 - Nuvola Runtime version: 4.22.0
 - The web app you use and its version: Spotify 3.5.0

### Describe the bug

The "Popular" list for an artist is improperly displayed (too narrow) and is unusable.

**Steps to reproduce the behavior**

This happens on start-up so no steps are required except navigate to an artist.

**Expected behavior**

I used to be able to navigate to an artist and see everything displayed correctly.

**Debugging log**

Attach the debug log here: 
[nuvola-debug-broken-popular.txt](https://github.com/tiliado/nuvolaplayer/files/6464888/nuvola-debug-broken-popular.txt)
[nuvolaspotify-debug-broken-popular.txt](https://github.com/tiliado/nuvolaplayer/files/6464887/nuvolaspotify-debug-broken-popular.txt)

**Screenshots**

![image](https://user-images.githubusercontent.com/2300366/117947540-93799700-b310-11eb-983e-32a93958e49a.png)

**Comment by fenryxo** [comment]
Hello @davidrhoderick. Thanks for reporting your issue. Could you check whether the latest flatpak build with **Spotify script 3.5.1 (1-g94f683c)* fixes the problem? Thanks.

**Comment by davidrhoderick** [comment]
Yep looks good now!
