### ISSUE TITLE
I am not getting lyrics,though i have bought the premium version.

### ISSUE THREAD

**Issue by ssreddy555** [tiliado/nuvolaplayer#735]
Type your question here.

**Comment by fenryxo** [comment]
Hello @ssreddy555. Thanks for reporting your issue. I need more information to investigate it further. Could you [visit the Bug reporting guidelined](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#basic-information) and answer the questions below?


* What is the version of Nuvola on your system?
* What streaming service is affected and what is its version?
* Do you have [lyrics fetching](https://nuvola.tiliado.eu/docs/4/lyrics.html) enabled in preferences?
* Could you obtain a debugging log and attach it here as a file?

**Comment by ssreddy555** [comment]
OK, the streaming service is Tidal. I'm getting lyrics after updating both
Nuvola services & Tidal.

Thank you.

**Comment by fenryxo** [comment]
glad to help :-)
