### ISSUE TITLE
RadioTunes, Jazzradio, Classical Radio, Rockradio & Zen radio

### ISSUE THREAD

**Issue by kaosnews** [tiliado/nuvolaplayer#738]
**Please describe in detail what you would like to solve with the proposed feature:**

RadioTunes (DI.FM is part of this) also provides more dedicated stations like RadioTunes (https://www.radiotunes.com), https://www.jazzradio.com/ etc. Maybe an idea to add these also? 

**Do you have an idea how it could be solved and how it should look like?**

They work the same like DI.FM so make these availiable isn't that difficult maybe?

**Comment by fenryxo** [comment]
Hello @kaosnews, thanks for your idea :-)

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
