### ISSUE TITLE
Integration error: Error during call of Nuvola.browser._downloadDone failed

### ISSUE THREAD

**Issue by davidrhoderick** [tiliado/nuvolaplayer#739]
### Before creating a new bug report

We recommend these actions first:

- [x] Update Nuvola Player - run `flatpak update --system; flatpak update --user`
- [x] [Go through a list of recently updated issues](https://github.com/tiliado/nuvolaruntime/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- [x] [Read bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)

### Basic information

We often need some basic information - refer to [bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)
for help.

- Nuvola Player version: 4.22.0
- The streaming service you use and its version: Spotify version 3.5.1

### Describe the bug

Please describe the issue in great detail to help us understand what the problem is. You may include:

- This bug occurs on startup _and_ between songs.
- The bug doesn't prevent the songs from playing _but_ it does take focus away from current application _every_ time
- Obviously, this bug shouldn't be happening
- ![nuvola spotify app integration error](https://user-images.githubusercontent.com/2300366/119495325-976ed580-bd62-11eb-842a-935ca8e60b1b.png)
- The bug's text reads "Error during call of Nuvola.browser._downloadDone: Function 'Nuvola.browser._downloadDone' failed file:///app/share/nuvolaruntime/js/main.js:902: Uncaught Error: Refusing to convert undefined value.  Nuvola._callIpcMethodVoid('/nuvola/mediaplayer/set-track-info', info) The application might not function properly."
- The application was working perfectly fine an hour ago.

**Comment by davidrhoderick** [comment]
And just so you have my other OS info:
```
Distributor ID: Pop
Description:    Pop!_OS 20.10
Release:        20.10
Codename:       groovy
```

**Comment by fenryxo** [comment]
Hello @davidrhoderick. Thanks for reporting your issue. Could you check whether the latest flatpak build with **Spotify script 3.5.2 (2-gb8cdb39)** fixes the problem? Thanks.

**Comment by bradym** [comment]
Came here with the same issue and updating to `Spotify script 3.5.2 (2-gb8cdb39)` fixed the problem for me. Thanks!

**Comment by davidrhoderick** [comment]
Looks like that update fixed it, thanks a lot @fenryxo!
