### ISSUE TITLE
Last.fm feature disabled after temporary unavailability

### ISSUE THREAD

**Issue by wesQ3** [tiliado/nuvolaplayer#74]
When listening to Google Play Music and scrobbling to Last.fm, occasionally the message bar appears reporting an error with Last.fm and that the feature is disabled. These messages are output to the console:

    [Runner:WARNING  Nuvola] AudioScrobblerComponent.vala:210: Scrobbling failed for Last.fm (lastfm): 16: Error applying mutate to radb (for db 14301233 )
    [Runner:WARNING  DioriteGtk] application.vala:91: Last.fm Error. Failed to scrobble track. This functionality has been disabled

From [the Last.fm API error listing](http://www.last.fm/api/errorcodes), error 16 indicates "The service is temporarily unavailable, please try again." Perhaps the scrobbler should cache the request data and send it with the next scrobble request, or simply wait a bit and try the same request again.

To work around this currently, the user can toggle the "scrobble played tracks" switch under Preferences -> Components -> Audio Scrobbler Services menu.

I am currently on a build from 19 Jan 2015, e393fdbe5a52754440311fb7583e369539d4f899.

**Comment by fenryxo** [comment]
Thanks for taking the time to report this issue. I believe I've just fixed it in tiliado/nuvolaplayer@3395a11 and the fix will be available in the next rebuild. Feel free to reopen this ticket if the issue is not fixed.

*[My work on Nuvola Player is funded by Nuvola Patrons.](https://tiliado.eu/nuvolaplayer/funding/)*

**Comment by wesQ3** [comment]
Hi, thanks for the quick response. I'm running on a build from 3395a116b056e5bc29f5ba75c9dda8fefc075a65 with your fix and encountered this today:

    [Runner:DEBUG    Nuvola] LastfmCompatibleScrobbler.vala:186: lastfm scrobble: Genesis by Grimes, 1422387212
    [Runner:WARNING  Nuvola] LastfmCompatibleScrobbler.vala:267: 16: There was an internal error. Please retry your request.
    [Runner:WARNING  Nuvola] AudioScrobblerComponent.vala:210: Scrobbling failed for Last.fm (lastfm): Empty response from the server.
    [Runner:WARNING  DioriteGtk] application.vala:91: Last.fm Error. Failed to scrobble track. This functionality has been disabled

I know the fix is working in some cases because previously I saw it recover from an error 16 that would have disabled the scrobbling component otherwise: 

    [Runner:DEBUG    Nuvola] LastfmCompatibleScrobbler.vala:186: lastfm scrobble: Feeling Alright by Warpaint, 1422385159
    [Runner:WARNING  Nuvola] LastfmCompatibleScrobbler.vala:267: 16: Error applying mutate to radb (for db 14301233 )
    [Runner:DEBUG    Nuvola] LastfmCompatibleScrobbler.vala:161: lastfm update now playing: CC by Warpaint
I'll try to add in some more detailed scrobble error logging in my build to get some more details, but then I'll have to wait for lastfm to error again to see if I did it right. We'll see!

**Comment by fenryxo** [comment]
Please always post whole debug output unless you have better awareness of Nuvola Player code than me and are sure you haven't stripped any useful detail.

**Comment by wesQ3** [comment]
Sorry about that; rookie mistake. There didn't seem to be anything else in
the log except for navigation and developersidebar updates. Next time I
will post the full log.
