### ISSUE TITLE
Incorrect song is displayed in Gnome notifications area while using Nuvola with Amazon Music

### ISSUE THREAD

**Issue by angelomaragos** [tiliado/nuvolaplayer#740]
- Nuvola Player version: 4.22.0 
- The streaming service you use and its version: 5.12.0 

I'm running Ubuntu 20.04, Gnome/Wayland
### Describe the bug
Incorrect song is displayed in Gnome notifications area while using Nuvola with Amazon Music

Please describe the issue in great detail to help us understand what the problem is. You may include:
1.  Launch Amazon Cloud Player
2.  Play song from album that appears on home screen
3.  Click on the Home icon in the Nuvola Player window
4.   Select some other song
5.  Check Gnome notifications, incorrect song is displayed.  

As songs other songs continue to play...the same incorrect song is displayed in the notifications area.

I did not see this issue while using Youtube Music. 

[A screen shot showing the issue.](https://user-images.githubusercontent.com/853706/119956518-7647f800-bfa1-11eb-8966-02e1f80dd714.png)

**Comment by fenryxo** [comment]
Hello @angelomaragos, thanks for reporting your issue.

Hello @a-m-s, could you look at it, please? Thanks :-)

**Comment by a-m-s** [comment]
Sorry, I've been away, and I have a new computer so I'll have to set up my dev environment again.

**Comment by fenryxo** [comment]
Hello @a-m-s. It seems Amazon Music no longer works in Nuvola - see #744.

**Comment by a-m-s** [comment]
Yeah, I was planning to come back to this issue tomorrow, but it just got more challenging.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
