### ISSUE TITLE
Amazon Cloud Player 'Your Browser Not Supported' Error Upon Startup

### ISSUE THREAD

**Issue by Kandelai** [tiliado/nuvolaplayer#744]
**Unfortunately, Amazon Music is currently incompatible with Nuvola Player and there is no feasible workaround.** Per [our terms](https://nuvola.tiliado.eu/terms/), the service has been marked as deprecated and affected Nuvola Player users may ask for a refund of their Nuvola Player license. We plan to bring Amazon Music back once #583 is resolved by the end of 2021.

Reason for the incompatibility: Amazon Music website shows "Your browser not supported". The only way to fix the issue is upgrading the web engine, which will happen with #583 by the end of 2021.

---

Issue: Attaching photo of the browser not supported error I recently started receiving upon startup of Nuvolaplayer using the Amazon Cloud Player.  Updated Flatpak, issue remains.

Nuvolaplayer version: 4.22.0 (0-gcff8d27)

Amazon Cloud Player version: 5.12.0 (0-gc08a57d)

System Information:

Operating System: EndeavourOS
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.12.9-zen1-1-zen
OS Type: 64-bit
Graphics Platform: X11
Processors: 6 × Intel® Core™ i5-9600K CPU @ 3.70GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
![Screenshot_20210604_235006](https://user-images.githubusercontent.com/39681298/120883192-a0e11480-c590-11eb-8edc-879b65d2932b.jpg)

**Comment by fenryxo** [comment]
Hello @Kandelai, thanks for reporting your issue. Unfortunately, it seems Nuvola is no longer compatible with Amazon Music. I've updated the issue description with the reason and our plan to bring Amazon Music back. I'm sorry that we cannot provide any short-term fix to let you use Amazon Music with Nuvola Player. Per [our terms](https://nuvola.tiliado.eu/terms/), the service has been marked as deprecated and affected Nuvola Player users may ask for a refund of their Nuvola Player license.

**Comment by Kandelai** [comment]
Thank you for your quick response. Although unfortunate to hear, I understand the greater issues at hand. I will check back towards the end of 2021 to see where the project landed.

**Comment by a-m-s** [comment]
Can we not just change the user agent?

**Comment by domdfcoding** [comment]
I think there's more to their detection than just the user agent. If I follow the instructions in the docs [here](https://tiliado.github.io/nuvolaplayer/development/apps/tutorial.html#user-agent-quirks) and use the user agent from Chrome it still doesn't work.

**Comment by fenryxo** [comment]
> Can we not just change the user agent?

This is the first thing I tried. They seem to use proper browser features detection rather than dumb user agent parsing.

**Comment by jedatwork** [comment]
I'm not sure if this helps here, but I was able to bypass the agent check building an app with nativefier and passing firefox as the agent and including the `--widevine` flag.

**Comment by theli-ua** [comment]
fwiw even before it became blocked I started having multiple playback issues in amazon music with nuvola

**Comment by fenryxo** [comment]
> I'm not sure if this helps here, but I was able to bypass the agent check building an app with nativefier and passing firefox as the agent and including the `--widevine` flag.

Unfortunately, Firefox user agent doesn't work for Nuvola.

**Comment by gandalf239** [comment]
I was just able to successfully build an Electron-wrapped Amazon Music HD player on Pop OS 20.10 (Linux), using the following:



nativefier https://music.amazon.com/?ref_=dm_lnd_k ... rec_signin -p linux -a x64 --inject ./worker.js --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"   --widevine



Note: the worker.js file contains:



if ('serviceWorker' in navigator) {

caches.keys().then(function (cacheNames) {

cacheNames.forEach(function (cacheName) {

caches.delete(cacheName);

});

});

}



The --widevine flag downloads a Widevine-enabled version of Electron, which supplies the requisite DRM to enable playback.



Your mileage will of course vary. One must of course have nativefier, and its prerequisites (imagemagick, nodejs, etc), installed.

![DeepinScreenshot_select-area_20210820104839](https://user-images.githubusercontent.com/17886839/130273672-c88355e1-31bf-4067-a5dc-c2e1282c4408.png)!

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
