### ISSUE TITLE
Tidal - You have been blocked

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#745]
**Some users reported that Tidal stopped working and shows "You have been blocked". We haven't managed to identify the cause of the issue, so we cannot start working on a fix.** It is possible that Tidal will start working once Nuvola is ported to a new web engine by the end of 2021 (#583), but we cannot guarantee that.

Per [our terms](https://nuvola.tiliado.eu/terms/), affected Nuvola Player users may ask for a refund of their Nuvola Player license.

---

From #742 by @nanga

### Before creating a new bug report

We recommend these actions first:

- [ ] Update Nuvola Player - run `flatpak update --system; flatpak update --user`
- [ ] [Go through a list of recently updated issues](https://github.com/tiliado/nuvolaruntime/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- [ ] [Read bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)

### Basic information

We often need some basic information - refer to [bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)
for help.

- Nuvola Player version: ...
- The streaming service you use and its version: Tidal ...

### Describe the bug

Please describe the issue in great detail to help us understand what the problem is. You may include:

- Exact steps to trigger the issue.
- Wrong behavior.
- Expected behavior.
- Any additional information that you think could help us help you.

Never share your e-mail, password or license key.

![tidal blocked](https://user-images.githubusercontent.com/25297244/120700919-a3f0dd80-c488-11eb-86dd-3cbe3048e213.png)

**Comment by fenryxo** [comment]
Hello @nanga. Thanks for reporting your issue. I need more information to investigate it further. Could you [visit the Bug reporting guidelined](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#basic-information) and answer the questions below?

* What is the version of Nuvola and Tidal on your system?
* What Linux distribution do you use and what is its version?
* Could you obtain a debugging log and attach it here as a file?

**Comment by dameq1** [comment]
I also get this bug. At first, playing music was not possible because Nuvola has played 2 seconds of the track and later shows the tidal message "Something wrong" or similar and the sound stops. I tried to log out and log in but after logout, this error page showed up and no other action is possible to do. I did flatpack update and apt update then upgrade. My system is Ubuntu 18.04 LTS. Nuvola version as on the screenshot.
![image](https://user-images.githubusercontent.com/77672308/121601950-e5fcbf00-ca46-11eb-99c0-b43ef0386364.png)

**Comment by antaeusdk** [comment]
Same issue. Ubuntu 21.04.
![Screenshot from 2021-06-13 12-11-35](https://user-images.githubusercontent.com/2125190/121803174-9386f280-cc40-11eb-9b9a-fc1893ebb79b.png)

**Comment by fenryxo** [comment]
Hello, thanks for reporting your issue. I need more information to investigate it further. Could you [visit the Bug reporting guidelined](https://github.com/tiliado/nuvolaruntime/wiki/Bug-Reporting-Guidelines#basic-information) and answer the questions below?

* Could you obtain a debugging log and attach it here as a file?

**Comment by fenryxo** [comment]
Also, could you check whether the command below helps?

```
rm -rf ~/.var/app/eu.tiliado.NuvolaAppTidal/
```

**Comment by dameq1** [comment]
Logs:

[bug Nuvola service stdout.txt](https://github.com/tiliado/nuvolaplayer/files/6648120/bug.Nuvola.service.stdout.txt)
[bug NuvolaAppTidal stdout.txt](https://github.com/tiliado/nuvolaplayer/files/6648122/bug.NuvolaAppTidal.stdout.txt)

**Comment by fenryxo** [comment]
Thanks for the log. Could anybody explicitly say whether the command below helps or not at all?

```
rm -rf ~/.var/app/eu.tiliado.NuvolaAppTidal/
```

**Comment by dameq1** [comment]
Sorry, I forgot to add a comment for this. Unfortunately in my situation, it don't help.

**Comment by antaeusdk** [comment]
[debug.txt](https://github.com/tiliado/nuvolaplayer/files/6652767/debug.txt)
[nuvola.txt](https://github.com/tiliado/nuvolaplayer/files/6652768/nuvola.txt)

I have tried the rm -rf. Unfortunately, I still get the error.

**Comment by fenryxo** [comment]
Hello  @dameq1 &  @antaeusdk. Thanks for the logs.

Did you quit Nuvola before the data removal? If yes, could quit Nuvola and remove the data again, then attach a new log?

**Comment by dameq1** [comment]
Yes of course I quit before remo
[nuvolaTidal-debug-log.txt](https://github.com/tiliado/nuvolaplayer/files/6662152/nuvolaTidal-debug-log.txt)
ving and tried this a few times. Here you have a new log when the app is started just after data removing.

[nuvola-debug-log.txt](https://github.com/tiliado/nuvolaplayer/files/6662151/nuvola-debug-log.txt)
[nuvolaTidal-debug-log.txt](https://github.com/tiliado/nuvolaplayer/files/6662153/nuvolaTidal-debug-log.txt)

**Comment by ptillemans** [comment]
![image](https://user-images.githubusercontent.com/44337/122246893-381a6600-cec7-11eb-9b90-bab298e35be8.png)

same issue on fresh install on Arch. Primephonic and Qobuz work fine.

**Comment by fenryxo** [comment]
Unfortunately, I still have no idea about the cause of the problem. I can use Tidal without any issues and the provided logs don't show anything suspicious. I don't have a clue what is different between my machine or Tidal account and your machines and Tidal account.  I've updated the issue description. I'm sorry that I cannot provide any short-term solution to the problem.

Per [our terms](https://nuvola.tiliado.eu/terms/), affected Nuvola Player users may ask for a refund of their Nuvola Player license (the reference date for a partial refund is June 3, 2021).

**Comment by bovinespirit** [comment]
For anyone who encounters this I completely wiped the Nuvola flatpaks and deleted all the Nuvola data I could find and eventually was able to get Tidal up and running again.  Unfortunately I did not record exactly what I deleted but it looks like it included the `~/.var/app/eu.tiliado.NuvolaAppTidal/` directory mentioned above.  I had issues getting it to log in again but it came right in the end.

**Comment by muharrem-demir** [comment]
Please don't deprecate Tidal. It's the only way I could run Tidal on Linux (Manjaro). After removing everything and re-installing, it works flawlessly. I didn't have any issues since then.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
