### ISSUE TITLE
Spotify no longer plays the selected song/podcast as expected

### ISSUE THREAD

**Issue by lktaylor49** [tiliado/nuvolaplayer#748]
OS: Linux Mint 20.1 (stock 5.4.0-74-generic, x86_64
Environment: Cinnamon 4.8.6
Nuvola runtime: 4.22.0
Spotify script: 3.5.2

I've been using it daily for podcasts and music, then some time last week it started. I don't think I was tinkering with anything but who knows. To reproduce:
-- Start Spotify script as normal
-- Select a song/podcast from a playlist
-- Instead of playing what you selected, the application skips that item and exactly the next 5 items in the list (in order or random, depending on your choice. It still follows that.) and then plays exactly 9 seconds of the one it lands on and hangs. I can still interact with the application and redo the process, but at that 9 second mark it just stops playing. The application itself does not hang or become unresponsive.

[NuvolaSpotifyDebug.txt](https://github.com/tiliado/nuvolaplayer/files/6665310/NuvolaSpotifyDebug.txt)

**Comment by fenryxo** [comment]
Hello @lktaylor49. Thanks for reporting your issue. Unfortunately, I cannot reproduce it on my machine. Could you quit Nuvola, execute the command below and start Nuvola again? Let me know whether it helps.

```
mv ~/.var/app/eu.tiliado.NuvolaAppSpotify ~/.var/app/eu.tiliado.NuvolaAppSpotify-backup
```

**Comment by lktaylor49** [comment]
Yup, that did it. No bug here, thanks!
