### ISSUE TITLE
Amazon Cloud Player update?

### ISSUE THREAD

**Issue by jwt79** [tiliado/nuvolaplayer#749]
I've been sad to lose the use of the novolaplayer Amazon Cloud Player.  It seems to no longer be supported.  Are there any plans to update this application?  I really miss it!

Regards,
jwt

**Comment by jwt79** [comment]
Just found the thread regarding this issue.  My apologies.

**Comment by fenryxo** [comment]
Hello @jwt79, we track the issue in #744.
