### ISSUE TITLE
Scrobbling doesn't seem to work from YouTube Music

### ISSUE THREAD

**Issue by brylie** [tiliado/nuvolaplayer#750]
Scrobbling not working on Last.fm, ListenBrainz, or Libre.fm

### Basic information
- Nuvola Player version: 1.5.0 (0-gdb17f13)
- The streaming service you use and its version: YouTube Music

### Describe the bug
I just installed Nuvola Player 4.22.0 and YouTube Music script 1.5.0. When I configure the scrobbling services, new tracks are not automatically sent to those services.

Please describe the issue in great detail to help us understand what the problem is. You may include:

- install Nuvola Player and YouTube Music script
- subscribe to Pro
- enable scrobbling services

New tracks do not appear on Last.fm, ListenBrainz, or Libre.fm

I would expect scrobbling to just work without any further configuration.

![image](https://user-images.githubusercontent.com/17307/123782425-01d4e180-d8de-11eb-8605-98edbbabe547.png)

**Comment by brylie** [comment]
Also, the "Disconnect" button under Last.fm stays highlighted in blue, which may be a surface indicator of some underlying problem.

**Comment by fenryxo** [comment]
Hello @brylie.  Thanks for reporting your issue. Could you check whether the latest flatpak build with **YouTube Music script 1.5.1 (1-g7ae7cd9)** fixes the problem? Thanks.

**Comment by brylie** [comment]
Yeah that seems to have fixed the issue! :-) 
- [x] Last.fm
- [x] Libre.fm
- [x] MusicBrainz

**Comment by fenryxo** [comment]
Glad to hear that :-)
