### ISSUE TITLE
(Optionally) scrobble songs only near end

### ISSUE THREAD

**Issue by brylie** [tiliado/nuvolaplayer#751]
**Please describe in detail what you would like to solve with the proposed feature:**
Currently, Nuvola seems to scrobble a song as soon as playback begins.

This is a bit subtle, but Nuvola should only scrobble a song when the user has listened to most of the song. I.e. the song should be scrobbled near the end rather than at the beginning. This is because not all songs that play (e.g. on Spotify or YouTube Music) are enjoyed by the user.

**Do you have an idea how it could be solved and how it should look like?**

I think Last.fm just waits until a certain percent of the song has been played before scrobbling, e.g. by getting the song length and finding the time code for the desired percent of the song to be played (e.g. 80%).

**Describe alternatives you've considered:**

Well, perhaps a manual "scrobble this" button, but that would seem tedious. I'm not sure of an alternative implementation, but the "scrobble near end" could be an optional setting.

**Additional context:**

Scrobbling songs at the beginning means that the user listening profile is defined more by the streaming service recommendation algorithm than by the taste of the listener. Moving scrobbling to a later place in the song gives back control to the listener to determine which songs appear on their listening list, as well as follows conventions established by Last.fm (principle of least surprise).

**Comment by fenryxo** [comment]
Hello @brylie, thanks for creating your feature request.

Nuvola currently updates *now playing* when playback starts but *scrobbles* the track after 20 seconds of playback. When the feature was implemented, Nuvola didn't parse metadata about track position and length, so it was not possible to scroble according to the track playback percentage. However, most Nuvola integrations scripts already provide track position and length, so I could revisit the idea.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
