### ISSUE TITLE
Add new service for LivePhish

### ISSUE THREAD

**Issue by aybesea** [tiliado/nuvolaplayer#753]
LivePhish (http://livephish.com) is a music service showcasing the band Phish and their members. Is it possible that you can add service for it?

**Comment by fenryxo** [comment]
Hello @aybesea, thanks for your service request.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
