### ISSUE TITLE
Add new service for Live Music Archive

### ISSUE THREAD

**Issue by aybesea** [tiliado/nuvolaplayer#754]
Live Music Archive (https://archive.org/details/etree) is a part of the massive Archive.org project that houses a huge collection of live music, along with the facilities to download and play the content.

Is it possible that you could add service for the Live Music Archive at archive.org?

**Comment by fenryxo** [comment]
Hello @aybesea, thanks for your service request.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
