### ISSUE TITLE
Youtube Music songs are not being scroblled to last.fm

### ISSUE THREAD

**Issue by GuilhermeBarile** [tiliado/nuvolaplayer#756]
### Basic information

- System: Fedora 34
- Nuvola Player version: 4.22.0 (via flatpak), latest nuvola service is also enabled
- The streaming service you use and its version: YouTube Music (script version 1.5.0)

### Describe the bug

I just noticed no songs were being scrobbled to my last.fm account since march. 
I tried re-authenticating to last.fm and restarting the player and it still does not work
![image](https://user-images.githubusercontent.com/502178/126880763-b80db633-d9a5-4aa5-bedc-c0acb51c57ae.png)
![image](https://user-images.githubusercontent.com/502178/126880779-eda334ae-6643-41e5-bc5c-134b23f88824.png)

-
I enabled the developer tools and confirmed no requests were made to last.fm in the network tab.
Curiously, the developer sidebar always show the `Playback state` as  `paused`, even though a song is being played
 
![image](https://user-images.githubusercontent.com/502178/126880585-89b0a1f9-0e98-426d-9b17-9e7b6ef57ab3.png)

Please tell me if there's anything else I can do to debug this.

**Comment by fenryxo** [comment]
Hello @GuilhermeBarile. Thanks for reporting the issue. I'll look at it at the weekend.

**Comment by fenryxo** [comment]
Hello @GuilhermeBarile. Could you update the YouTube Music script to the latest version 1.5.1 (1-g7ae7cd9)?

**Comment by GuilhermeBarile** [comment]
Hey @fenryxo , it's working now, thanks a lot for the fix.

**Comment by GuilhermeBarile** [comment]
@fenryxo I noticed the songs start scrobbling right away when played, it would be nice to have a 30s delay (something to have in mind for a future release). Thanks again

**Comment by fenryxo** [comment]
Nuvola currently scrobbles after 20 seconds, see [this comment](https://github.com/tiliado/nuvolaplayer/issues/751#issuecomment-876533865) for details.
