### ISSUE TITLE
Nuvola 4.24

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#758]
* Target date: early November, 2021
* Previous was #731 on 2021-08-01.
* [Release announcement draft](https://medium.com/nuvola-news/nuvola-4-24-released-ad8b9bde7a7f)
* [Issue Board](https://github.com/orgs/tiliado/projects/8)

**Comment by d-r-q** [comment]
Hi @jiri-janousek 
Sad to hear it, your work is inspiring for me. I will support Yandex.Music until EoL.
