### ISSUE TITLE
Integration error when pressing "Seek forward" media key

### ISSUE THREAD

**Issue by MurzNN** [tiliado/nuvolaplayer#761]
### Basic information

We often need some basic information - refer to [bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)
for help.

- Nuvola Player version: 4.23.0 (0-g3ab9c9a)
- The streaming service you use and its version: Spotify script, 3.6.1 (1-g7ce77bc)

### Describe the bug

When I press the "Seek forward" media key on Linux, when NuvolaPlayer with Spotify plugin plays the song, I see the popup window with "Integration error". The text of error is not selectable, so I can't copy-paste it here without manual retyping, here is screenshoot:
![image](https://user-images.githubusercontent.com/336662/129199290-d6c470e3-c1d3-4fbd-b72a-6c86720d8192.png)

_P.S. Also will be good to make an error text selectable._

**Comment by fenryxo** [comment]
Hello @MurzNN. Thanks for reporting your issue. Could you check whether the latest flatpak build with **Spotify script 3.6.3 (3-g34910df)** fixes the problem for you? Thanks.

P.S. I've also created issue #762 to let users copy error messages.
