### ISSUE TITLE
Upgrade to org.gnome.Platform/x86_64/40

### ISSUE THREAD

**Issue by m-holt** [tiliado/nuvolaplayer#763]
Nuvola requires Gnome 3.38, which is no longer supported as of August 19th.

flatpak list --app --columns=application,runtime

Application ID                                               Runtime
eu.tiliado.Nuvola                                            org.gnome.Platform/x86_64/3.38

flatpak update

Looking for updates…
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.

**Comment by fenryxo** [comment]
Hello @m-holt, thanks for reporting the issue. I plan to skip GNOME 40 and upgrade to GNOME runtime 41 once it is available.

**Comment by jiri-janousek** [comment]
The release is delayed due to user support tasks.

**Comment by jiri-janousek** [comment]
ld in GNOME SDK 41 seems to be affected by [bug 28138](https://sourceware.org/bugzilla/show_bug.cgi?id=28138).

**Comment by jiri-janousek** [comment]
Upgraded to GNOME SDK 40.
