### ISSUE TITLE
Option to output sound to ALSA instead of pulseaudio

### ISSUE THREAD

**Issue by sbrian30s** [tiliado/nuvolaplayer#765]
For audiophiles who use Qobuz, that app has a direct sound output option such as WASAPI in Windows to improve the sound quality not allow the OS to interfere.  It's called bit-perfect.  In Linux, Audacious has the equivalent option to use the ALSA output.  I believe that ALSA was created to allow this maximum sound quality.  This is very important for audiophiles.  This bypasses the volume control, etc.

I don't know much about Linux and I have not figured out how I might do this with the Nuvola player.

As an example, Audacious settings have one for "Output plugin", so "ALSA Output" is what people use who want the best sound quality.  The ALSA Output settings then have the option for HW- direct control device with no conversions.  
Nearby, there is also a field to choose buffer size in ms.  100 ms is the minimum and this also improves sound quality if one's HW can keep up.  The buffer selection is also an option in the Qobuz program, I believe.

Please add an ALSA output option with direct HW so that we can have comparable sound quality to the original Qobuz program.  This is an important feature included in Qobuz, but missing here.  Example:
![image](https://user-images.githubusercontent.com/90791221/133483441-67d61bdc-ae3b-4736-98f7-ea37d915e9c1.png)

Indirectly related, and lower priority, would be the ability to adjust the buffer size time:
![image](https://user-images.githubusercontent.com/90791221/133483762-775eb249-ed89-4263-b223-ac0f3e3896c5.png)

My options are to keep using with this compromise, or cancel Qobuz again.

When doing serious listening at maximum sound quality, this output mode does not allow any system sounds to interfere, which is something that users should be aware of..  But for those of use for whom sound quality is the priority, this is an essential feature, which is why Qobuz (and Tidal, etc.) has it in their player.
In Windows, Foobar2000 is a common player that has the comparable option and is described as:
"Adds Windows Audio Session API exclusive mode output support, allowing bit-exact output and muting all other sounds. "

![image](https://user-images.githubusercontent.com/90791221/133485027-79ec0bf6-4468-4063-afb9-9c929afe2651.png)
Thanks

**Comment by fenryxo** [comment]
Hello @sbrian30s. Thanks for your feature request.

Nuvola Player uses Chromium for audio playback and I'm not sure whether it is possible to satisfy your requirements without patching Chromium code, which I'd like to avoid.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.

**Comment by sbrian30s** [comment]
Thanks for your email and consideration.  After trying Mint for 6 months, I
went back to Windows, I'm sorry to say.  I was unable to figure out how to
get bit-perfect audio after trying many things, including online advice in
opposite directions, it seemed.  Nuvola was not my only problem in this
area.
