### ISSUE TITLE
Support AdBlock

### ISSUE THREAD

**Issue by akmalkady** [tiliado/nuvolaplayer#767]
Is it possible to support google chrome plugins such as AdBlock? When I use YouTube music on my Chrome browser, I can listen without ads. However, when I use Nuvola player, I get ads.

Enabling AdBlock will be a great improvement to Nuvola player

**Comment by fenryxo** [comment]
Hello @akmalkady, Nuvola doesn't support Chrome extensions yet but we have #412 for that.
