### ISSUE TITLE
Unable to load summary from remote nuvola: Unacceptable TLS certificate

### ISSUE THREAD

**Issue by sduenasb** [tiliado/nuvolaplayer#768]
Hi. I can't find the Nuvola or qobuz app in the Genome Software app. I get this error when manually trying to install the repository

Unable to load summary from remote nuvola: Unacceptable TLS certificate

**Comment by fenryxo** [comment]
Hello @sduenasb, thanks for reporting your issue. Could you provide me with more details?

* You Linux distribution and its version.
* Exact command you executed and full terminal output.
