### ISSUE TITLE
SiriusXM app cannot start due to xdg desktop portal issues 

### ISSUE THREAD

**Issue by fkelbe** [tiliado/nuvolaplayer#771]
Fedrora 35 (beta) x86_64 XFCE
SiriusXM app worked fine on F34, but upgrade to F35 immediately resulted in script error when opening app.

XDG Desktop Portal                      Error
org.freedesktop.portal.Desktop does not support OpenURI method of org.freedesktop.portal.OpenURI interface.

![Screenshot_2021-10-27_10-13-30](https://user-images.githubusercontent.com/20757599/139105458-d2deb6f2-5481-4261-ab46-4ea05c8dfccf.png)

**Comment by jiri-janousek** [comment]
Hello @fkelbe. Could you install `xdg-desktop-portal-gnome`, reboot your machine and try again?

```
sudo dnf install xdg-desktop-portal-gnome
```

**Comment by archmunky** [comment]
I can confirm this also happens with Fedora 25 Cinnamon Spin. I installed xdg-desktop-portal  along with the gnome and gtk backends. Rebooted and that appears to have fixed it. Error was

`Runner: [WARNING Δ003370us Nuvola] StartupWindow.vala:146: xdg-desktop-portal-message: org.freedesktop.portal.Desktop does not support OpenURI method of org.freedesktop.portal.OpenURI interface.`

**Comment by jiri-janousek** [comment]
Glad to hear that. I'm not sure whether it is a bug in xdg-portal-gtk or not.
