### ISSUE TITLE
Unable to get player on Ubuntu Budgie 21.10

### ISSUE THREAD

**Issue by JCfreak1087** [tiliado/nuvolaplayer#772]
I'm trying to get the Nuvola player onto my computer, but when I'm trying to follow the instructions, I'm not able to get access to the player. When I try opening things up through the software, it will display a prompt that it failed to install because it isn't supported. I have flatpaks available to choose from, but I don't know how to actually get Nuvola though.

**Comment by jiri-janousek** [comment]
Hello @JCfreak1087. Thanks for reaching out. Ubuntu has really poor Flatpak experience with regard to graphical package manager. I'd suggest command-line tools instead:

```
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak remote-add --if-not-exists nuvola https://dl.tiliado.eu/flatpak/nuvola.flatpakrepo
flatpak update
flatpak install nuvola eu.tiliado.Nuvola
flatpak install nuvola eu.tiliado.NuvolaAppSpotify
```

Does it help?
