### ISSUE TITLE
Make it clear a Google product is required on the description page

### ISSUE THREAD

**Issue by Newar417** [tiliado/nuvolaplayer#773]
So a search how to install this took me here: https://nuvola.tiliado.eu/app/bandcamp/debian/

If I would have known that a Google product is required to run this app, I could have save me the time to install this. Please be clear and open about requirements.

**Comment by jiri-janousek** [comment]
Hello @Newar417, thanks for our suggestion.

**Comment by jiri-janousek** [comment]
I'm closing this ticket as [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022. I'm sorry that I haven't managed to resolve this ticket in time.
