### ISSUE TITLE
Exact version of Nvidia driver not available

### ISSUE THREAD

**Issue by abdaxz** [tiliado/nuvolaplayer#775]
### Before creating a new bug report

We recommend these actions first:

- [x] Update Nuvola Player - run `flatpak update --system; flatpak update --user`
- [x] [Go through a list of recently updated issues](https://github.com/tiliado/nuvolaruntime/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- [x] [Read bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)

### Basic information

We often need some basic information - refer to [bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)
for help.

- Nuvola Player version: 4.23.0 (0-g3ab9c9a)
- The streaming service you use and its version: YouTube Music 1.6.0 (0-gd8bd7f0)

### Describe the bug

When starting, the wrong Nvidia driver is found. When I try to update, it says I have 470.82.01 on my system, but in Nuvola only version nvidia-470-82-00 exist (for 470-82.x). Therefore, I cannot update the driver or start the player. I am using a freshly installed version of Kubuntu 21.10 on a Dell XPS 7590.

**Comment by jiri-janousek** [comment]
Hello @abdaxz. Thanks for reporting your issue. Unfortunately, Nvidia driver 470.82.01 doesn't seem available for download from nvidia website, so it cannot be included in [the org.freedesktop.Platform.GL.nvidia flatpak](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia). I recommend upgrading your system driver to version [470.86](https://www.nvidia.com/Download/driverResults.aspx/183575/en-us).

**Comment by abdaxz** [comment]
@jiri-janousek thanks a lot for the swift reply! Based on your reply, I had a look at it turns out that, for some reason, I wasn't using the default driver for Kubuntu. I actually downgraded to the recommended driver and now everything works nicely.
