### ISSUE TITLE
Adventures and problems packaging Nuvola Player and its components

### ISSUE THREAD

**Issue by FabioLolix** [tiliado/nuvolaplayer#778]
Hello Jiří, [various pkgbuilds exist on the AUR](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=nuvola+player&outdated=&SB=l&SO=d&PP=50&do_Search=Go) for compiling and packaging natively Nuvola Player and its components

The pkgbuilds have been neglected for a long time, I have adopted them some time ago and updated all core components; however of the several app/integrations scripts no one compile successfully since a while

I store my pkgbuilds here on github https://github.com/FabioLolix/PKGBUILD-AUR_fix/tree/master/zz_aur-fix-3/nuvola

It wasn't immediate to successfully compile and package [nuvolaruntime](https://github.com/FabioLolix/PKGBUILD-AUR_fix/blob/master/zz_aur-fix-3/nuvola/nuvolaruntime/PKGBUILD), for which I'm using the flags:
* --dummy-engine, since I don't know how to build CEF
* --no-vala-lint, since there isn't a pkgbuild for it (but I could make it)
*  --no-js-lint and --no-strict because it fails with these
* test are not performed (run-nuvolaruntime-tests) because fails too

I have tried to build integrations for bandcamp, jupiter broadcasting, youtube and youtubemusic, they fails with the same error:

```
echo "Name=eu.tiliado.WebRuntimeAppYoutube" >> eu.tiliado.WebRuntimeAppYoutube.service
chmod a+x nuvola-app-youtube
echo "Exec=nuvola-app-youtube --gapplication-service" >> eu.tiliado.WebRuntimeAppYoutube.service
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/nuvolasdk/__main__.py", line 5, in <module>
    sys.exit(nuvolasdk.run(".", sys.argv))
  File "/usr/lib/python3.9/site-packages/nuvolasdk/__init__.py", line 92, in run
    return nuvolasdk.addondata.run(wd, prog + " " + cmd, argv[2:]) or 0
  File "/usr/lib/python3.9/site-packages/nuvolasdk/addondata.py", line 49, in run
    xml = create_addon_data_xml(meta
, args.genuine)
  File "/usr/lib/python3.9/site-packages/nuvolasdk/addondata.py", line 61, in create_addon_data_xml
    tree.add("id", "nuvola-app-" + dashed_id)
  File "/usr/lib/python3.9/site-packages/nuvolasdk/xmltree.py", line 87, in add
    elm = self.start(_tag, _attrs)
TypeError: start() argument 2 must be dict, not None
make: *** [Makefile:32: nuvola-app-youtube.metainfo.xml] Error 1
make: *** Waiting for unfinished jobs....
```

[nuvola-app-youtube-git-2.3.r0.gdfaa8ed-1-x86_64-build.log](https://github.com/tiliado/nuvolaplayer/files/7698979/nuvola-app-youtube-git-2.3.r0.gdfaa8ed-1-x86_64-build.log)

[nuvola-app-youtube-music-git-1.6.r0.gd8bd7f0-1-x86_64-build.log](https://github.com/tiliado/nuvolaplayer/files/7698980/nuvola-app-youtube-music-git-1.6.r0.gd8bd7f0-1-x86_64-build.log)

**Comment by jiri-janousek** [comment]
Hello @FabioLolix, although it would be handy to have AUR builds, the Nuvola project focuses heavily on its flatpak builds and there are no spare resources to support third-party packagers in their brave efforts. Nuvola Player is a packaging nightmare and I'm afraid that never changes. Please don't waste your valuable time on it. I'm deeply sorry that I don't have better advice.

**Comment by FabioLolix** [comment]
> Please don't waste your valuable time on it.

I already have but I didn't mind much

> the Nuvola project focuses heavily on its flatpak builds and there are no spare resources to support third-party packagers in their brave efforts

I was 99% sure of this :)

I'll procede to ask for removal of AUR pkgbuilds, however I'll keep my personal pkgbuilds

***

For curiosity, the flatpak python version which is? If it is 3.8, when 3.9 arrive you could one of the problems mentioned above
