### ISSUE TITLE
[Deezer] Explicit tracks title prefixed with "E" when using full player

### ISSUE THREAD

**Issue by bartlibert** [tiliado/nuvolaplayer#779]
### Before creating a new bug report

We recommend these actions first:

- [x] Update Nuvola Player - run `flatpak update --system; flatpak update --user`
- [x] [Go through a list of recently updated issues](https://github.com/tiliado/nuvolaruntime/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- [x] [Read bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)

### Basic information

We often need some basic information - refer to [bug reporting guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines)
for help.

- Nuvola Player version: 4.23.0 (0-g3ab9c9a)
- Deezer script version: 3.5.2 (2-g6a0dc26)

### Describe the bug

When playing a track marked "explicit" and the "full player" is open in Deezer, the track title is prefixed with "E"
![image](https://user-images.githubusercontent.com/948770/145783623-fe734584-5f11-425c-832d-e422727d756f.png)

It's most likely taken from the "E" in the `explicit outline small` div:

![image](https://user-images.githubusercontent.com/948770/145783327-0fff5856-4a22-4fe2-9cda-d51177b858f7.png)

![image](https://user-images.githubusercontent.com/948770/145783519-6e6366ba-cfcb-4cee-b7f7-e0e0f8adf7e8.png)

The bottom player has the same "E" and class, but if that one is used, the title is correct:

![image](https://user-images.githubusercontent.com/948770/145783929-5b49d74e-ba62-44f9-9c3c-0450f3387467.png)

![image](https://user-images.githubusercontent.com/948770/145783894-b56acddd-f5e7-4876-9996-ea2c79deb156.png)

![image](https://user-images.githubusercontent.com/948770/145783847-d9faac0f-c1aa-41c3-845c-8f220290220f.png)

**Comment by jiri-janousek** [comment]
Fixed in Deezer script 3.5.3 (3-ge14d842). I apologize for the delay.
