### ISSUE TITLE
Spotify skipping songs

### ISSUE THREAD

**Issue by ConnyTheNerd** [tiliado/nuvolaplayer#780]
``Hi all,
updated a few minutes ago and then wanted to play Spotify. When in playlist pushing the play button it hops from one song to the next without starting it and at the 6th it's stopping and really starts playing. But also then it only plays 9 seconds and then - although the song seems to be played - there is no sound to be heard.
This is what my error log says: ERROR:power save blocker x11.cc(403) No response to Uninhibit request. I have not a clue what this means and what I can do. Would be nice if you could give me a hint.

**Comment by adrianlorenz** [comment]
Hi, I can't offer you much help in solving the problem, but I have the exact same problem in Ubunto Studio 20.04.3 and Xfce and Chromium...

**Comment by jiri-janousek** [comment]
Hello @ConnyTheNerd. Thanks for reporting the issue. Could you run the command below and try again? It will delete the cached Widevine plugin and download a new version. 

```
rm -rf ~/.var/app/eu.tiliado.NuvolaApp*/data/nuvolaruntime/apps_data/*/widevine
```

**Comment by audiophileuser** [comment]
Many thanks!
"rm -rf ~/.var/app/eu.tiliado.NuvolaApp*/data/nuvolaruntime/apps_data/*/widevine" works very well!
For me: The bug is solved.

**Comment by ConnyTheNerd** [comment]
Many thanks for your quick and perfect help - this also solves the issue for me.

And by the way - happy New Year!
