### ISSUE TITLE
Nuvola Deezer-Player freezes

### ISSUE THREAD

**Issue by audiophileuser** [tiliado/nuvolaplayer#782]
Nuvola Deezer player freezes. The player accepts neither mouse input nor keyboard input. No adaptation to changes in the size of the window. Window navigation works.
I hope you can help me with my problem. Many thanks in advance.....

My system: 
Ubuntu Studio:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
x86_64, XFCE
Nuvola Player - Genuine flatpak build
Version 4.24.0
Revision 0-g71e3555
Diorite 4.24.0
Chromium 75.0.3770.100
ValaCEF 75.3770.16
libsoup 2.72.0

[error debug 1.txt](https://github.com/tiliado/nuvolaplayer/files/7797762/error.debug.1.txt)
[error debug 2.txt](https://github.com/tiliado/nuvolaplayer/files/7797764/error.debug.2.txt)
.

**Comment by jiri-janousek** [comment]
Hello @audiophileuser.  Thanks for reporting the issue. Could you check whether Deezeer script 3.6.1 (1-gdafc045) fixes the problem?

**Comment by audiophileuser** [comment]
Hello @jiri-janousek, great und fast work - the script fixes the problem very well :-) Now I´m happy and can relax after work with deezer streaming.... thanks.......
