### ISSUE TITLE
Yandex Music player Install stop with error flag after update nvidia drivers to 510.47 on Arch

### ISSUE THREAD

**Issue by null-shiva** [tiliado/nuvolaplayer#784]
1. 'Graphics driver 'nvidia-510-47-03' for Flatpak has not been found on your system. Please consult documentation on graphics drivers to get help with installation.' - text
2. OS Info:
Archlinux
DE Plasma 5.23.5
X11
Kernel 5.16.4-zen1-1-zen

**Comment by jiri-janousek** [comment]
The documentation mentioned in the error message is here: https://github.com/tiliado/nuvolaplayer/wiki/Graphics-Drivers
