### ISSUE TITLE
HI-Res output for USB-DAC

### ISSUE THREAD

**Issue by micatske** [tiliado/nuvolaplayer#785]
**Please describe in detail what you would like to solve with the proposed feature:**

I think it would be nice to let the player have better control with USB-dac for hi-res streaming. Currently, through the app, it's limited to 44.1HZ, even though I have the hi-res streaming from Qobuz, it's can't output the 96hz files.

**Do you have an idea how it could be solved and how it should look like?**

Replace this example: Please add new settings "Run in background when the window is closed" with three options:
"Always"/"When music is playing (default)"/"Never".

**Describe alternatives you've considered:**

Write your text here...

**Additional context:**

**Comment by jiri-janousek** [comment]
Hello @micatske. Thanks for your suggestion but [Nuvola Player has discontinued active development](https://medium.com/nuvola-news/nuvola-player-project-enters-maintenance-mode-d9d0e78f87ea). We are going to provide only integration bug fixes on a best-effort basis until the final End-of-Life on December 31, 2022.
