### ISSUE TITLE
premium

### ISSUE THREAD

**Issue by parsa-ghasemi** [tiliado/nuvolaplayer#787]
Hi, if you add premium features, it would be great, of course, for those who bought a premium subscription
Features such as downloading songs and ...

**Comment by jiri-janousek** [comment]
Hello @parsa-ghasemi. I think there has been a misunderstanding. Indeed, Nuvola Player does not support song downloading as there was low demand for this feature. However, Nuvola Player does not advertise song downloading as a premium feature anywhere.
