### ISSUE TITLE
Cross Compatibility with Mac

### ISSUE THREAD

**Issue by SteVwonder** [tiliado/nuvolaplayer#79]
I noticed that there was some previous interest in getting nuvolaplayer 2 to run on a Mac. So I looked into compiling nuvolaplayer 3 on my Mac (10.10).  Most of the dependencies are available through macports.  Diorite compiles just fine with some modifications to the wscript and #if preprocessor directives.

I got stuck trying to satisfy the webkit2gtk-3.0 dependency.  It seems no one has gotten webkit2 support for the Mac's quartz backend, only webkit1.  (source: https://www.mail-archive.com/gtk-osx-users-list@gnome.org/msg00543.html)  So for now it seems we are stuck waiting on that.
##

**Comment by fenryxo** [comment]
Thanks for your research on Nuvola Player Mac port. There is same issue regarding Windows port - the second generation of WebKitGTK+ is no longer multiplatform and [the paid developers](http://www.igalia.com) focus only on Linux :-(

**Comment by fenryxo** [comment]
Hi @SteVwonder. MacPorts seem to have webkit-gtk 2.4.9 and there is an effort to build 2.11.2 ([source](https://lists.webkit.org/pipermail/webkit-gtk/2016-January/002495.html)). Can you confirm this? It the webkit2gtk-4.0 library also built?

**Comment by SteVwonder** [comment]
Oh!  Interesting.  I will look into this and get back to you this weekend.

**Comment by SteVwonder** [comment]
I looked around online, and that thread seems to be the only one showing progress towards building a newer version of webkitgtk.  Unfortunately, there hasn't been any activity on that thread since you posted 6 days ago.  Also, it seems like not that many people are interested in getting it cross-compiled.  They claim it's a real chore on anything that isn't Linux.  I'll keep my eyes open for any further progress.

**Comment by SteVwonder** [comment]
It seems they got 2.11.3 to build and added it to MacPorts: https://trac.macports.org/changeset/144610
It also looks like gtk4 dylibs are being made.  I'll look into this further.

**Comment by fenryxo** [comment]
Great! I should start adding #if LINUX ... #endif to the Diorite & Nuvola Player code base.

**Comment by fenryxo** [comment]
Hi @SteVwonder. Is there any progress with WebKitTK+ on Mac OS X? Are you still interested in porting NP to Mac?
