### ISSUE TITLE
Packages for Arch Linux [$25]

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#8]
Provide official Nuvola Player 3 packages and dependencies for Arch Linux. 

Note: There is [unofficial nuvolaplayer-git package in AUR](https://aur.archlinux.org/packages/nuvolaplayer-git/) (you have to [install web app scripts](https://github.com/tiliado/nuvolaplayer/wiki/Web-App-Scripts) manually though)

:heart: [One Nuvola Patron](https://tiliado.eu/accounts/group/3/) is interested in this issue
##

**Comment by jck** [comment]
I have created Archlinux packages: https://github.com/jck/pkgbuilds/tree/master/nuvola

Google play music works well after downloading and installing :D

**Comment by rosshadden** [comment]
:+1: @jck. It installs!

But I can't figure out how to use it after opening.  When I open it, it's just an empty app with a `+` button which opens a file browser.

![image](https://cloud.githubusercontent.com/assets/669012/6072506/89321936-ad70-11e4-8050-bb3c0fa3888e.png)

**Comment by jck** [comment]
@rosshadden You need to manually install services right now.
Clone https://github.com/tiliado/nuvola-app-google-play and 'make install'. It will install the service in ~/.local.

**Comment by rosshadden** [comment]
That worked (with Grooveshark, even), thanks!

**Comment by fenryxo** [comment]
@jck Thanks for your work. I'll announce your packages on Nuvola Player profiles in social networks today/tomorrow.

@rosshadden Please don't use this ticket to get support for the unofficial packages from AUR. Use comment section of the package instead. https://aur.archlinux.org/packages/nuvolaplayer-git/

**Comment by mpdeimos** [comment]
@jck I'm a bit biased whether the services should be part of the package?
@fenryxo How do you handle this for other distros?

**Comment by gaborbernat** [comment]
@jck for me the build fails (vala should be added as a dependency), then a compile failure if I install it manually

**Comment by fenryxo** [comment]
@gaborbernat Please report build errors of the package from AUR to the comment section of the package in AUR: https://aur.archlinux.org/packages/nuvolaplayer-git/

@mpdeimos Official [Nuvola Player 3 repository](https://tiliado.eu/nuvolaplayer/repository/) provides one package per web app script.

**Comment by fenryxo** [comment]
Is there still a need for binary packages from the Nuvola Player team? The AUR packages seem to have a good maintainer now (Celti), who actually reports build errors upstream to get them fixed.

**Comment by gaborbernat** [comment]
it's fine ;)

**Comment by StefanoWoerner** [comment]
Would be great to have a package that also installs all services. With the existing one, you have to manually install the scripts for the webapps.

**Comment by fenryxo** [comment]
You can contact current maintainers and ask them to create a meta package nuvolaplayer3-all-services that depends on individual web app packages. Debian/Ubuntu/Fedora packages also use this way.

**Comment by Celti** [comment]
For people who don't mind using NuvolaPlayer 3.1 rolling, I've created a [nuvola-apps-git](https://aur.archlinux.org/packages/nuvola-apps-git/) package that depends on all the integrations in the AUR that are currently properly packaged.

**Comment by rosshadden** [comment]
@Celti Awesome! I think you should make the specific apps recommended dependencies.  When using `nuvolaplayer-git`, the only app I had installed was the one I wanted (`nuvola-app-google-play-git`).

I'm actually getting some errors with `hunks` failing when trying to build, but I'll look into it and give a more concise report or see if I can fix it myself and post the fix when I get a chance.

Thanks!

**Comment by Celti** [comment]
Well, if you only want a specific app then just install that app! :o) I might make them all opt-deps of nuvolaplayer-git itself, though, now that you mention it. Helps with visibility and management.

The hunks errors are because the problems the patch was patching have been fixed upstream and I haven't uploaded the unpatched PKGBUILD yet. Gimme... ten minutes, now that I've finished filing a new bug report! :D

**Comment by Celti** [comment]
Alright! I've built a tool set that leverages [makepkg-template](https://www.archlinux.org/pacman/makepkg-template.1.html), [makechrootpkg](https://git.archlinux.org/devtools.git), and [repose](https://github.com/vodik/repose), tying them together in an [evil bash script and a set of build templates](https://repo.celti.name/nuvolaplayer/).

Together, they create an (unofficial, fully-signed) repository of Arch Linux packages for Nuvola Player and its integrations, both 3.0 and 3.1.

You can use it by importing my key:
```sh
pacman-key --recv-keys 123C3F8B058A707F86643316FA682BD8910CF4EA
pacman-key --lsign-key 123C3F8B058A707F86643316FA682BD8910CF4EA
```

...and adding the following to your pacman.conf:
```ini
[nuvolaplayer]
SigLevel = Required TrustedOnly
Server = https://repo.celti.name/archlinux/$repo/$arch
```

I will be updating the git packages at least weekly, and the stable packages hopefully within a day or so of them seeing updates. I have vague intentions of cronning the whole process but we'll see if it's burdensome enough to need that.

Enjoy!

**Comment by fenryxo** [comment]
Great wotk, @Celti. How about promoting your repository to the Official Nuvola Player Repository for Arch Linux?

**Comment by Celti** [comment]
@fenryxo Sure, I'd be fine with that! (I mean, really, I'd be lying if I said I wasn't secretly hoping for that. :smile:)

I'm doing a first unattended rebuild of the -git packages, so we'll see if my build script is up to snuff...

**Comment by fenryxo** [comment]
@Celti I've created a new repository [tiliado/nuvola-arch-packaging](https://github.com/tiliado/nuvola-arch-packaging). Could you mirror your repository https://git.celti.name/nuvola-arch-packaging.git there? This repository will be used to track issues and improvements of your packaging :-)

Following actions must be made before your package repository becomes official. You can discuss them here.

### Diorite library:
- [ ] The `diorite-git` (0.3.x) package must not provide the `diorite` (0.2.x) package as there is no API/ABI stability/compatibility guarantee
- [ ] The `diorite` (0.2.x) & diorite-git (0.3.x) packages should be installable parallelly

### Nuvola Player
- [ ] The `nuvolaplayer` package must depend on the `diorite` package (0.2.x), preferably on the latest bugfix release
- [ ] The `nuvolaplayer-git` package must depend on the `diorite-git` (0.3.x) package, strictly on the latest available revision as there is no guarantee of API/ABI stability. When the Diorite git master branch adds a new function, the Nuvola Player git master branch can immediately start using it and won't work with even a single commit older Diorite library.
- [ ] The `nuvolaplayer-git` package should build with `--enable-apps-alpha` configuration option, but the `nuvolaplayer` package must not as it is an experimental feature.
- [ ] The `nuvolaplayer-git` package should provide and conflict with the `nuvolaplayer` package.

### Web App Scripts
- [ ] The 8tracks script is complete (was wrongly marked as incomplete though)
- [ ] Music streaming web apps should depend on the `nuvolaplayer` package (also satisfied by the `nuvolaplayer-git` package.) Both stable and git releases of a particular script should work with `nuvolaplayer` and `nuvolaplayer-git` as well.
- [ ] The Google Calendar script and other experimental web apps should depend on the `nuvolaplayer-git` package as they are not guaranteed to be compatible with NP 3.0.
- [ ] Some web apps (e.g. ownCloud Music - see `api_major` & `api_minor` fields in `metadata.json`) require NP 3.1 and should depend on the `nuvolaplayer-git` package.

**Comment by Celti** [comment]
All declared changes should be fixed, and new packages built and published. I've also set up a mirror hook so that [tiliado/nuvola-arch-packaging](https://github.com/tiliado/nuvola-arch-packaging) is automatically updated.in sync with my repos.

**Comment by jck** [comment]
I don't use Nuvola anymore, but I've been using Archlinux for many years now.
I think I speak for most Arch users when I say that Arch users don't like adding additional repositories for packages(In fact many Arch users love the fact that they don't need to deal with PPA hell). The AUR is the right place for this package. If nuvola gets popular enough on the AUR, it will probably end up in community.

**Comment by mpdeimos** [comment]
Using arch for a few years as well and I favor AUR instead of custom
repositories as well (for security reasons and for more control). Actually
this was my first thought when I read this discussion.

**Comment by fenryxo** [comment]
I understand AUR may be perfect from user's point of view. However, from the upstream's point of view, the present situation in AUR is a mess.

* Nuvola-related packages have various version schemes.
* There are 7 maintainers so it may be difficult to coordinate packaging to achieve compatibility & consistency across the whole Nuvola package set.
* The maintainers differ in how they respond to user support requests and whether they report issues upstream.

I'm afraid it would be quite hard to achieve sufficient quality of AUR packages to make them official whereas it is possible with Celti's repository.

* Version schemes are consistent.
* There is a single maintainer who communicates with upstream perfectly, reports issues and even makes pull requests. Actually, he is now a member of upstream team.
* Packaging is consistent across the whole package set and follows upstream's recommendations (e.g. my previous comment).
* It will be far easier to coordinate changes and improvements of packaging as we agreed to use GitHub issues for this.

Arch Linux users will have two choices instead of one:

* Present state: Unofficial Nuvola Player packages in AUR - PKGBUILDs, the Arch way, better security and far more control, community supported
* New option: Official Nuvola Player repository for Arch Linux - binary packages, guaranteed consistency & compatibility across the whole package set, directly supported by upstream

**Comment by Celti** [comment]
Other new option, best of both worlds: Use the source repository available at [tiliado/nuvola-arch-packaging](https://github.com/tiliado/nuvola-arch-packaging). The same PKGBUILDs and templates as the official repository, with all the full control of the AUR.

**Comment by fenryxo** [comment]
@Celti I'll look at your packages during weekend.

**Comment by fenryxo** [comment]
It seems that the Celti's repository is out of the table due to various emergencies in his family. Is there any volunteer to continue his work?

**Comment by fenryxo** [comment]
In progress...

**Comment by fenryxo** [comment]
Hello Arch users,

The [Nuvola project now officially supports Arch Linux since Nuvola 3.1 Milestone 2 thanks to cross-distribution flatpak packages](https://medium.com/nuvola-news/nuvola-3-1-milestone-2-deprecates-deb-rpm-packages-in-favor-of-flatpaks-and-officially-supports-579534c3b75c). These are not meant to replace AUR builds but to provide an alternative way to install Nuvola for those users who are not, for whatever reason, satisfied with the Arch way of installation. I believe that [Flatpak builds of Nuvola are a huge step forward because Flatpak finally, after years of struggling, allows Nuvola project to pursue its goals](https://medium.com/nuvola-news/how-the-benefits-of-nuvola-flatpak-builds-outweigh-the-drawbacks-c2ea5fde867c).

Note that Nuvola 3.1 is currently available only to users with [Premium/Patron plan](https://tiliado.eu/nuvolaplayer/funding/) but this will change with the Nuvola 4.0 release later this year.

Best regards,

Jiri Janousek, Nuvola core developer
