### ISSUE TITLE
Debian nuvolaplayer3 package should suggest nuvolaplayer3-all-services, not depend on it

### ISSUE THREAD

**Issue by hackel** [tiliado/nuvolaplayer#81]
I think many users still only use Nuvola Player for Google Play Music.  We should not need to install all of the services if we only intend to use one.

**Comment by fenryxo** [comment]
Hi. Thanks for your feedback. I will change "depends" to "recommends" (but not "suggests") so you can uninstall other services you don't use.

**Comment by fenryxo** [comment]
Published.

**Comment by hackel** [comment]
Did this change get undone?  nuvolaplayer3 3.0.0~201507061356.c86a837-0+3~vivid is back to `Depends: nuvolaplayer3-all-services`

**Comment by fenryxo** [comment]
> Did this change get undone?

Yes, it did. See #107.
