### ISSUE TITLE
Spotify ads crank system volume up

### ISSUE THREAD

**Issue by ItzBlitz98** [tiliado/nuvolaplayer#84]
I seem to be encountering a weird bug where spotify ads will crank my system and the spotify ad playback stream to 100%. However the stream where the music is coming from spotify and any other streams will stay at the same volume.

This is fairly serious as it could probably cause ear damage to anyone wearing headphones that go to some silly volume. It was incredibly uncomfortable for me.

It seems to be happening on both Nuvola Player 2 and the latest commit of Nuvola Player 3.
I'm using Arch Linux with Gnome-shell.

**Comment by fenryxo** [comment]
Thanks for taking the time to report this issue. Note that Nuvola Player is not officially supported on Arch Linux, so my ability to help you with your issue may be limited. I need more information to investigate it further:

1. What volume is set in the Spotify web interface for the music stream?
2. What do you have set for the `flat-volumes` option of [PulseAudio's daemon.conf file](https://wiki.archlinux.org/index.php/PulseAudio/Configuration#daemon.conf)?

---

Jiří Janoušek, Nuvola Player Developer • *My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).*

**Comment by ItzBlitz98** [comment]
The volume for the spotify interface is 100%
The pulseaudio volume is normally around 30%

And flat-volume is commented out in my daemon.conf, Going to uncomment it and see how it goes.

Thanks for the help :+1:

**Comment by fenryxo** [comment]
Glad to help :-)
