### ISSUE TITLE
build dependencies for nuvolaplayer on fedora 21

### ISSUE THREAD

**Issue by martinkg** [tiliado/nuvolaplayer#87]
could you please add the package diorite to your tools/fedora21_bootstrap.sh
because it's needed to build nuvolaplayer on Fedora21 (on Fedora20 the package diorite isn't available).

**Comment by fenryxo** [comment]
The "tools/fedora21_bootstrap.sh" script is used to prepare build environment to build and debug the latest git master snapshots of both Diorite library and Nuvola Player 3 in a clean installation in VirtualBox, so it necessary not to have installed any diorite package that might conflict with the library installed from git snapshot.

Anyway, I'm quite shocked that the Diorite library is already in Fedora 21. It doesn't have stable API & ABI and can break anytime. Does Fedora have any quality standards? Although I appreciate the time you have spent on packaging work, I would recommend to remove the package as soon as possible and wait for stable release 0.2 (odd version number unstable, even version number stable). Moreover, the Diorite snapshot in Fedora 21 is too old and the latest Nuvola Player git master doesn't build with it at all.
