### ISSUE TITLE
Close to tray inconsistent behaviour

### ISSUE THREAD

**Issue by sasha-** [tiliado/nuvolaplayer#89]
**Type** bug • **Priority** low ([raise priority](https://tiliado.eu/nuvolaplayer/funding/#donate-wishlist)) • **Status** enqueued

Nuvola player 3 closes to tray when close button is pressed and music is playing. If nothing is playing player will completely exit when close button is clicked. I think more standard approach to this is always closing to tray and using "quit" menu option to exit the player completely.

Alternatively, clicking tray icon should show/hide main window regardless if there is anything playing.

**Comment by fenryxo** [comment]
Hello. Thanks for taking time to report this issue. The behaviour of Nuvola Player is actually pretty consistent as it doesn't have any "close to tray" functionality, but only "play in background on close" functionality, which is independent on the tray icon.

Nevertheless, I agree Nuvola Player should have "close to tray icon" functionality as it is expected to be present when tray icon is available.

---
Jiri Janousek, Nuvola Player Developer • My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/) • Issues and feature requests [supported with donations](https://tiliado.eu/nuvolaplayer/funding/#donate-wishlist) have always higher priority.

**Comment by fenryxo** [comment]
Fixed in git master & 3.0.x branches. Will be included in the next update of package repository. Thanks for your bug report :+1:
