### ISSUE TITLE
Can't bind media keys to nuvolaplayer

### ISSUE THREAD

**Issue by hashworks** [tiliado/nuvolaplayer#90]
When I try changing any keybindings to media keys nuvolaplayer just shows `Disabled` instead and switches to the key set before. This occoures on all of my Debian Jessie machines.

EDIT: I can set them locally, but they won't work. Setting them globally results in `Disabled`.
EDIT: When I set them manually they show up correctly but won't work.

I'm using the version in the ppa.

Google Music Example:
```
[Runner:INFO Nuvola] KeyBindingsDialog.vala:181: nuvola.global_keybindings.prev-song AudioPrev 
[Master:WARNING Nuvola] (src/nuvolakit-runner/components/keybindings/GlobalActionsKeyBinder.c:230):nuvola_global_actions_key_binder_real_set_keybinding: runtime check failed: (g_strcmp0 ((const gchar*) _tmp7_, _tmp8_) == 0)
```

Spotify Example:
```
[Runner:INFO     Nuvola] KeyBindingsDialog.vala:181: nuvola.global_keybindings.prev-song AudioPrev
[Master:DEBUG    Nuvola] XKeyGrabber.vala:98: Ungrabbed <Alt>p, count 0
```
(Alt-p was the key set before, get's set again)

Proof that the key works:
![proof of working key](http://i.imgur.com/GpdAqPZ.png)
(keycode 165 = XF86AudioPrev)

**Comment by fenryxo** [comment]
Hi. Thanks for taking the time to report this issue. I think Nuvola Player cannot set your keybinding, because the key has been already grabbed. That would also explain why the local keybinding doesn't work neither. To be sure, could you run Nuvola Player witn IPC logging turned on and copy here all lines that appear in the process of setting the keybinding?
```
DIORITE_LOG_MESSAGE_SERVER=yes nuvolaplayer3 -d
```

Multimedia keys like `AudioPrev` are often grabbed by GNOME/MATE/Unity/whatever Setting Daemon and Google Chrome/Chromium as well. Do you have anything like this running on your system? 

---

Jiri Janousek, Nuvola Player Developer • My work on Nuvola Player and user support are [funded by Nuvola Patrons](https://tiliado.eu/nuvolaplayer/funding/).

**Comment by hashworks** [comment]
Thanks @fenryxo, you're right! Google Chrome fetched the media keys, to be specific the Google Play Music extension. Removing the extension solved my problem, so I'll close this issue.

I think a help message in the keyboard shortcut window could provide this information? Or maybe one is able to detect the issue right away programmatically.

Requested logs:
Globally
```
[Runner:INFO     Nuvola] KeyBindingsDialog.vala:181: nuvola.global_keybindings.prev-song AudioPrev
[Master:DEBUG    DioriteGlib] ipcmessageserver.vala:142: Request 'ActionsKeyBinder.setKeybinding': ('prev-song', 'AudioPrev')
[Master:WARNING  Nuvola] (src/nuvolakit-runner/components/keybindings/GlobalActionsKeyBinder.c:230):nuvola_global_actions_key_binder_real_set_keybinding: runtime check failed: (g_strcmp0 ((const gchar*) _tmp7_, _tmp8_) == 0)
[Master:DEBUG    DioriteGlib] ipcmessageserver.vala:154: Response 'OK': false
```
Locally
```
Locally:
[Runner:INFO     Nuvola] KeyBindingsDialog.vala:152: nuvola.keybindings.prev-song AudioPrev
[Worker:DEBUG    DioriteGlib] ipcmessageserver.vala:142: Request 'call_function': ('Nuvola.config.emit', <('ConfigChanged', 'nuvola.keybindings.prev-song')>)
[Worker:DEBUG    DioriteGlib] ipcmessageserver.vala:154: Response 'OK': ('ConfigChanged', 'nuvola.keybindings.prev-song')
[Runner:INFO     Nuvola] config.vala:260: Config saved to /home/hashworks/.config/nuvolaplayer3/apps_data/google_play_music/config.json
```

**Comment by fenryxo** [comment]
```
[Master:DEBUG    DioriteGlib] ipcmessageserver.vala:142: Request 'ActionsKeyBinder.setKeybinding': ('prev-song', 'AudioPrev')
[Master:DEBUG    DioriteGlib] ipcmessageserver.vala:154: Response 'OK': false
```

Indeed, the response `false` means that global keybinding failed.

> I think a help message in the keyboard shortcut window could provide this information? Or maybe one is able to detect the issue right away programmatically.

Thanks for your idea. I've created a new ticket #93 for it ;-)
