### ISSUE TITLE
Examine HiDPI support in WebKit WebView

### ISSUE THREAD

**Issue by fenryxo** [tiliado/nuvolaplayer#92]
**Type** bug • **Priority** high (a request from Nuvola Patron) • **Status** enqueued

From an email from a Nuvola Patron:

> As far as features, getting hidpi modes enabled in the webkit view would be nice when I'm working on my laptop.  It renders at the correct physical size, but is "blurry" -- all the fonts and images are rendered at "standard" DPI and then scaled up.  In Firefox, the fonts are rendered "natively" at hidpi and the web page "knows" its on a high res screen and can load higher res images.  In my case this is for Google Play Music.  I imagine not all services may have the hidpi images, but the fonts should be independent of the individual service.

Notes:
*  [WebKitGtk should support HiDPI since release 2.6.0](https://bugs.webkit.org/show_bug.cgi?id=131347)
* Nuvola Player 3 is currently built with WebKitGtk 2.2 - 2.4 in Ubuntu/Debian and Fedora 20, but with  2.6 in Fedora 21 and Arch Linux
* Packages for Ubuntu and Debian should be switched to WebKitGtk 2.6 if it is available in a particular release.

**Comment by fastcat** [comment]
My system that experiences this is:
* Samsung Ativ 9 Plus, with 3200x1800 13" screen -- ~ 275 DPI I think, though the HiDpi scalling generally runs at 2x (192 DPI).
* Debian testing ("jessie")
* Gnome desktop environment (3.14.1)
* The nuvolaplayer3 package I have installed from the tiliado repositories depends on libwebkit2gtk-3.0-25, which is version 2.4.8-2 for me
* Also available in the same version of Debian is libwebkit2gtk-4.0-37, version 2.6.2+dfsg1-4

I can provide screenshots showing further details if that will help, and am happy to try test/debug builds.

**Comment by fenryxo** [comment]
Packages for Devian Jessie & Sid and Ubuntu Vivid are now built with libwebkit2gtk-4.0 2.6. Could you check whether it works as expected?

**Comment by fastcat** [comment]
When it first starts loading GPM, it uses the retina imagery (visible in the Google play logo in the top left), but by the time it starts loading the progress bar, it goes back to the "correct size but blurry" behavior.

**Comment by fenryxo** [comment]
That's interesting. Does it happen also in the webkit2gtk-4.0 MiniBrowser?

```
/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser
```

**Comment by fastcat** [comment]
Yes, exactly the same thing happens there.  Looks like this is a webkit(gtk) bug, and not a nuvolaplayer bug.

**Comment by fastcat** [comment]
Interestingly, http://arstechnica.com/ correctly detects the hidpi mode in the webkitgtk browser, so it looks like maybe this is a Google bug.

**Comment by fenryxo** [comment]
>  Looks like this is a webkit(gtk) bug, and not a nuvolaplayer bug.

Indeed, I've found two WebKitGtk bugs related to HiDPI:

* [ [GTK] WebKit2GTK+ isn't always HiDPI](https://bugs.webkit.org/show_bug.cgi?id=141782)
* [[GTK] Bump cairo version to support HiDPI](https://bugs.webkit.org/show_bug.cgi?id=133378)

I've posted a request for information to the first one and will follow it.

> Interestingly, http://arstechnica.com/ correctly detects the hidpi mode in the webkitgtk browser, so it looks like maybe this is a Google bug.

Could you add this information to the mentioned webkit bug or create a new bug report in the WebKitGtk bug tracker? Thanks!

I've added this issue to [the list of known upstream issues](https://github.com/tiliado/nuvola-app-google-play/wiki/Known-Issues) and closing it as I cannot fix it in Nuvola Player.

**Comment by fastcat** [comment]
I left notes on the first ticket.  Since I saw there some indications that enabling/disabling acceleration might have an effect, I tried toggling that in the mini browser settings, but that didn't help.  Looks like this may be an issue with webkitgtk needing to build with a newer version of cairo, possibly newer than is available in debian.

Thanks for your help :)

**Comment by fastcat** [comment]
FWIW, the google play music update on the HiDPI laptop is ... a total mess.  I doubt that's worth investigating until the issues with the UI are fixed at "normal" DPI though (#100).
