### ISSUE TITLE
Spotify web page crashes after logging in

### ISSUE THREAD

**Issue by Ralsa** [tiliado/nuvolaplayer#97]
In Debian Testing (Stretch) with Gnome 3.14.1

user@debian~$ nuvolaplayer3 -D
[Master:DEBUG      Gtk] Connecting to session manager
[Master:DEBUG    Nuvola] config.vala:174: Json Error: Falló al abrir el archivo «/home/user/.config/nuvolaplayer3/master/config.json»: No existe el fichero o el directorio
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Calendar at /usr/share/nuvolaplayer3/web_apps/google_calendar, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.1
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Rdio at /usr/share/nuvolaplayer3/web_apps/rdio, version 4.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app This is My Jam at /usr/share/nuvolaplayer3/web_apps/this_is_my_jam, version 2.0
[Master:WARNING    Gtk] Symbolic icon media-playback-start-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon list-add-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon list-remove-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:DEBUG    DioriteGtk] application.vala:228: XFCE session vanished: org.xfce.SessionManager
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Calendar at /usr/share/nuvolaplayer3/web_apps/google_calendar, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Bandcamp at /usr/share/nuvolaplayer3/web_apps/bandcamp, version 2.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Play Music at /usr/share/nuvolaplayer3/web_apps/google_play_music, version 5.1
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Jango at /usr/share/nuvolaplayer3/web_apps/jango, version 2.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app KEXP Live Stream at /usr/share/nuvolaplayer3/web_apps/kexp, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Mixcloud at /usr/share/nuvolaplayer3/web_apps/mixcloud, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Rdio at /usr/share/nuvolaplayer3/web_apps/rdio, version 4.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app This is My Jam at /usr/share/nuvolaplayer3/web_apps/this_is_my_jam, version 2.0
[Master:WARNING    Gtk] Symbolic icon window-close-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon media-playback-start-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon list-add-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon list-remove-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon window-close-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon media-playback-start-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon list-add-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon list-remove-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon window-close-symbolic-ltr of size 16 is in an icon theme directory of size 96
[Master:WARNING    Gtk] Symbolic icon media-playbac
![captura de pantalla de 2015-05-09 14 11 57](https://cloud.githubusercontent.com/assets/11486880/7550115/66f2e516-f655-11e4-9ea0-92f2863c3ee7.png)

**Comment by fenryxo** [comment]
Hello. I'll probably take a look at this issue in early June. Thanks for you patience.

**Comment by fenryxo** [comment]
Does this issue still occur with the latest beta?

**Comment by fenryxo** [comment]
No response for a month, closing.
