### ISSUE TITLE
Update of development builds

### ISSUE THREAD

**Issue by orschiro** [tiliado/nuvolaplayer#98]
Dear @fenryxo,

I installed the Tilado repositories on my eOS (based on Ubuntu 14.04) system. I added the development builds for Nuvola Player. I am wondering about the update process. Are the updates automatically provided by the repository or do I have to manually fetch the latest development code?

Thanks!

Robert

**Comment by fenryxo** [comment]
Hello @orschiro,

your package management system should automatically upgrade Nuvola Player package to its latest version from the devel repository when a new version is published.

**Comment by orschiro** [comment]
Thank you!
